var language={

"1. DYNAMICS" : "1. الديناميكيات (القوى المحركة) ",
"STRAIGHT LINE MOTION" : "الحركة في خط مستقيم ",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: المسافة (م , متر ) , t: الزمن (ث , ثانية ) , v: السرعة (م/ث) , v_a: السرعة المتوسطة ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "الحركة في خط مستقيم بتسارع ثابت ",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: التسارع (عجلة الحركة) , v_o: السرعة الابتدائية , v: السرعة عند زمن t ",
"DISTANCE FUNCTION" : "دالة المسافة ",
"x_o: initial distance from origin, x: distance at time t" : "x_o: المسافة الابتدائية من نقطة الأصل , x: المسافة عند زمن t ",
"UNIFORM CIRCULAR MOTION" : "الحركة الدائرية المنتظمة ",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: زاوية (تقدير (ت) دائري) , l: طول القوس , R: نصف قطر الدائرة , ω: السرعة الزاوية (ت.دائري/ث) , t: الزمن الذي استغرقه الجسم ليتحرك طول مقداره l ",
"CENTRIPETAL FORCE" : "قوة الجذب المركزي ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: التردد (هرتز) , T: زمن دورة واحدة (ث) , a: تسارع الجاذبية ، F: قوة الجاذبية (N , نيوتن) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "حركة دائرية بعجلة تسارع ثابتة ",
"γ: angular acceleration" : "γ: التسارع الزاوي",
"ACCELERATION" : "تسارع",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: تسارع مماسي , a_n: تسارع عمودي ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: تسريع ، P2: حركة دائرية منتظمة ، P3: تباطؤ",
"FREE FALLING FROM HEIGHT h" : "السقوط الحر من ارتفاع h ",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: تسارع الجاذبية ، v: السرعة عند زمن t ، s: المسافة عند زمن t ، v_h: السرعة عند ملامسة الأرض ، t_h: الزمن حتى ملامسة الأرض ",
"VERTICAL PROJECTILE MOTION" : "حركة المقذوفات الرأسية",
"h_max: maximum height, v_o: initial velocity" : "h_max: أقصى ارتفاع، v_o: السرعة الأولية",
"Motion equation and velocity equation" : "معادلة الحركة ومعادلة السرعة",
"ANGLED PROJECTILE MOTION" : "حركة المقذوفات الزاوية ",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x، v_y: السرعة. x,y : معادلة الحركة بواسطة t؛ H: أقصى ارتفاع, L: أقصى مسافة ",
"HORIZONTAL PROJECTILE MOTION" : "حركة القذيفة الأفقية ",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: الزمن عند الهبوط، v_h: السرعة عند الهبوط ",
"SLIDING MOTION ON AN INCLINED PLANE" : "الحركة الانزلاقية على سطح مائل ",
"μ: coefficient of friction" : "μ: معامل الاحتكاك",
"Fiction coefficient of some materials" : "معامل الاحتكاك لبعض المواد",
"2. FORCES" : "2. القوى ",
"ATTRACTIVE FORCE" : "قوة جاذبة ",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁، m₂: كتلة جسمين. r: المسافة بين جسمين. G: ثابت الجاذبية ",
"GRAVITATIONAL FORCE" : "قوة الجاذبية",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: كتلة الأرض، m: كتلة الجسم، R: نصف قطر الأرض، h: ارتفاع الجسم ",
"GRAVITATIONAL ACCELERATION" : "تسارع الجاذبية",
"At a height h above the nominal surface of the earth" : "على ارتفاع h فوق السطح الأسمى للأرض ",
"Near the sea level" : "بالقرب من مستوى سطح البحر",
"FORCE OF GRAVITY" : "قوة الجاذبية",
"Force of gravity on earth, a special case of Gravitational force" : "قوة الجاذبية على الأرض ، حالة خاصة من قوة الجاذبية",
"NEWTON'S FIRST LAW" : "قانون نيوتن الأول",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: القوى المؤثرة على الجسم ، v: سرعة الجسم ، a: تسارع الجسم ",
"NEWTON'S SECOND LAW" : "قانون نيوتن الثاني",
"m: object's mass (kg)" : "m: كتلة الجسم (كلجم) ",
"NEWTON'S THIRD LAW" : "قانون نيوتن الثالث",
"LINEAR ELASTICITY - HOOKE'S LAW" : "المرونة الخطية - قانون هوك",
"k: spring constant (N/m), x: displacement (m)" : "k: ثابت الزنبرك (م / نيوتن) ، x: الإزاحة (م) ",
"A mass suspended by a spring" : "كتلة معلقة بواسطة زنبرك ",
"FORCE OF FRICTION" : "قوة الاحتكاك",
"μ: coefficient of friction, N: normal force" : "μ: معامل الاحتكاك ، N: قوة عمودية ",
"3. STATICS" : "3. علم السكون",
"MOMENT OF A FORCE" : "عزم القوة ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: القوة المطبقة (نيوتن) ، d: ذراع العزم (المسافة العمودية من المحور إلى خط تأثير القوة) ",
"MOMENT APPLICATION" : "تطبيق العزم ",
"MOMENT OF INERTIA" : "عزم القصور الذاتي ",
"Rod of length l" : "قضيب طوله l ",
"Thin circular hoop/ Thin cylindrical shell" : "طوق دائري رقيق / قشرة رقيقة اسطوانية ",
"Solid disk/ Solid cylinder" : "قرص صلب / اسطوانة صلبة ",
"Solid ball" : "كرة صلبة ",
"Hollow sphere" : "كرة مجوفة",
"ANGULAR MOMENTUM" : "الزخم الزاوي",
"I: moment of inertia, ω: angular velocity" : "I: عزم القصور الذاتي ، ω: السرعة الزاوية ",
"PLANE MOTION OF A RIGID BODY" : "الحركة المستوية لجسم جامد ",
"γ: angular acceleration, M: moment of a force" : "γ: التسارع الزاوي، M: عزم القوة ",

"4. CONSERVATION LAWS" : " 4. قوانين البقاء",
"MOMENTUM OF FORCE" : "زخم القوة",
"LAW OF CONSERVATION OF MOMENTUM" : "قانون بقاء الزخم ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁، v₂: السرعات الأولية للأجسام 1 و 2؛ v₁،'v₂': السرعات النهائية للأجسام 1 و 2 ",
"PLASTIC COLLISION" : "تصادم غير مرن ",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': سرعة نظام من جسمين (m₁ + m₂) بعد التصادم ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "تصادم مرن في بعد واحد",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁، 'v₂': سرعات m₁ وm₂ بعد التصادم ",
"5. WORK AND ENERGY" : "5. الشغل والطاقة",
"WORK" : "الشغل ",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: الشغل المبذول بواسطة قوة (جول) ، F: قوة محركة لجسم لمسافة s ، α: الزاوية بين F واتجاه الحركة ",
"EXAMPLES" : "أمثلة ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: الشغل المبذول بواسطة الجاذبية ، h: التغير في الارتفاع ، W_ms: الشغل المبذول بواسطة قوة الاحتكاك ، W: الشغل المبذول بواسطة زنبرك ",
"POWER" : "القوة (الطاقة) ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: الطاقة (واط، W)، t :   زمن إجراء الشغل W (ث) ",
"KINETIC ENERGY" : "الطاقة الحركية",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "الطاقة الحركية لجسم هائل دوار ",
"WORK-ENERGY PRINCIPLE" : "مبدأ الشغل والطاقة ",
"v₁, v₂: speeds of object before and after the change" : "v₁، v₂: سرعات الجسم قبل وبعد التغيير ",
"POTENTIAL ENERGY" : "طاقة الوضع  ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: طاقة الوضع التثاقلية (جول) ، m: كتلة الجسم (كلجم) ",
"CONSERVATION OF MECHANICAL ENERGY" : "حفظ (بقاء) الطاقة الميكانيكية ",
"CONSERVATION OF ENERGY" : "بقاء الطاقة ",
"6. MECHANICS OF FLUIDS" : "6. ميكانيكا السوائل",
"DENSITY" : "كثافة",
"m: mass of a volume V" : "m: كتلة حجم V ",
"PRESSURE" : "الضغط",
"F: force applied on area of A" : "F: القوة المطبقة على مساحة A ",
"PRESSURE OF LIQUIDS" : "ضغط السوائل",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: الجاذبية النوعية ( متر مكعب / نيوتن)، p_o: ضغط الهواء على سطح خالي (متر مربع / نيوتن)، P: الضغط الناتج عن وزن السائل أعلاه , p_B: الضغط الكلي على عمق h ",
"PASCAL’S PRINCIPLE" : "مبدأ باسكال",
"p_s: pressure on the surface" : "p_s: الضغط على السطح",
"APPLICATION" : "تطبيق",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁، A₂: مساحة اسطوانة صغيرة وأخرى كبيرة ، F₁، F₂: القوى التصاعدية والمطبقة ",
"ARCHIMEDES’ PRINCIPLE" : "مبدأ أرخميدس ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: الجاذبية النوعية لسائل (متر مكعب / نيوتن)، V: حجم الجسم , F_b: قوة الطفو ",
"FLOW RATE" : "معدل التدفق ",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: مساحة المقطع العرضي (متر مربع)، v: سرعة التدفق (م / ث)، Q: معدل التدفق (ثانية / متر مكعب) ",

"1. ELECTROSTATICS" : "1. الكهرباء الساكنة",
"COULOMB’S LAW" : "قانون كولوم",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: قيمة الشحنات (C)، ε: السماحية النسبية (في الفراغ ε = 1)، r: المسافة بين الشحنات (م)",
"ELECTRIC FIELDS" : "الحقول الكهربائية",
"E: electric field strength (N/C)" : "E: شدة المجال الكهربائي (كولوم / نيوتن) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "مبدأ تراكب الحقول الكهربائية ",
"In case of 2 electric fields" : "في حالة مجالين كهربيين ",
"WORK OF ELECTRIC FORCE" : "شغل القوة الكهربائية ",
"ELECTRIC POTENTIAL DIFFERENCE" : "فرق الجهد الكهربائي",
"RELATION BETWEEN E AND U" : "العلاقة بين E و U",
"CAPACITANCE" : "مواسعة",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: السعة الكهربية (فاراد)، Q: إجمالي الشحنة الكهربائية (كولوم)، U: الجهد الكهربائي (فولت) ",
"CAPACITOR" : "مكثف",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: مساحة كل قطب كهربي لوحي (متر مربع) ، d: المسافة بين الأقطاب (م)، ε: السماحية النسبية (م / فاراد) ",
"CAPACITANCES IN SERIES" : "السعة الكهربية في التوصيل على التوالي ",
"CAPACITANCES IN PARALLEL" : "السعة الكهربية في التوصيل على التوازي  ",
"ELECTRIC FIELD ENERGY" : "طاقة الحقل الكهربائي ",
"ENERGY OF CAPACITOR" : "طاقة المكثف ",
"V=A.d: volume between two electrode plates" : "V = A.d: الحجم بين قطبين كهربائيين لوحيين ",
"2. DIRECT CURRENT" : "2. التيار المباشر",
"ELECTRIC CURRENT" : "التيار الكهربائي",
"I: current (A), q: charge (C), t: time" : "I: التيار (أمبير)، q: الشحنة (كولوم)، t: الزمن ",
"OHM’S LAW" : "قانون أوم",
"U: electric potential difference between the ends of the resistor R" : "U: فرق الجهد الكهربائي بين طرفي المقاومة R ",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "الشغل الناتج بواسطة تيار (قانون جول) ",
"ELECTRICAL POWER" : "الطاقة الكهربائية",
"RESISTANCE" : "مقاومة",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: المقاومية للمادة (أوم.متر)، l: طول (م)، A: مساحة مقطع عرضي (متر مربع) ",
"SERIES CIRCUITS" : "الدوائر المتوالية ",
"PARALLEL CIRCUITS" : "الدوائر المتوازية ",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "الشغل أو الطاقة الحرارية التي تنتجها المقاومة ",
"POWER CONSUMPTION OF A RESISTOR" : "استهلاك الطاقة لمقاومة ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "القوة الدافعة الكهربائية لمولد كهربائي ",
"W: work of force (J), q: charge (C)" : "W: شغل القوة (جول) ، q: شحنة (كولوم) ",
"GENERATORS IN SERIES" : "مولدات على التوالي ",
"r: internal resistance of the generator" : "r: المقاومة الداخلية للمولد ",
"GENERATORS IN PARALLEL" : "مولدات على التوازي ",
"GENERATORS IN SERIES-PARALLEL" : "مولدات على التوالي-التوازي ",
"WORK AND POWER OF GENERATOR" : "الشغل وطاقة المولد ",
"H: Efficiency of generator" : "H: كفاءة المولد ",
"3. MAGNETISM" : "3. المغناطيسية",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "التدفق المغناطيسي خلال سطح مفتوح S ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: قيمة الحقل المغناطيسي (T، تسلا)، α: الزاوية بين B و الخط العمودي على السطح S ",
"MAGNETIC FORCES ON MOVING CHARGES" : "القوى المغناطيسية على شحنات متحركة ",
"v: velocity of the charge (m/s)" : "v: سرعة الشحنة (ث / م) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "القوة على سلك حامل للتيار ",
"I: current (A), l: length of the wire (m)" : "I: التيار (أمبير) ، l: طول السلك (م) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "القوة بين سلكين متوازيين حاملين للتيار ",
"r: distance between two wires (m)" : "r: المسافة بين سلكين (م) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "المجال المغناطيسي لسلك طويل به تيار مشحون ",
"r: perpendicular distance from the center of the wire (m)" : "r: المسافة العمودية من مركز السلك (م) ",
"MAGNETIC FIELD OF A LOOP" : "المجال المغناطيسي لحلقة ",
"n: number of turns per unit length of solenoid (turns/m)" : "n: عدد اللفات لكل وحدة طولية من الملف اللولبي (م / لفات) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "القوة الدافعة الكهربائية المستحثة - قانون فاراداي",
"N: numbers of turns per loop (turns/m)" : "N: عدد اللفات لكل حلقة (م / لفات)  ",
"INDUCTANCE" : "المحاثة الكهربية ",
"ELECTRIC ENERGY" : "الطاقة الكهربائية",
"MAGNETIC ENERGY" : "الطاقة المغناطيسية",
"ELECTRIC-MAGNETIC ENERGY" : "الطاقة الكهربية-المغناطيسية ",
"4. ALTERNATING CURRENT" : "4. التيار المتردد",
"BASIC PARAMETERS" : "المعاملات الأساسية ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: التيار اللحظي (أمبير) ، I_o: التيار اللحظي الأقصى (أمبير) ، T: الزمن الدوري للموجة ، f: التردد ، λ: الطول  الموجي، c: سرعة الضوء ",
"EFFECTIVE CURRENT AND VOLTAGE" : "التيار والجهد الكهربي الفعال ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "قانون أوم للتيار المتردد AC يحتوي فقط على مقاومة R ",
"CONTAINING ONLY INDUCTOR L" : "يحتوي فقط على محث (أداة حث) L ",
"Z_L: inductive reactance" : "Z_L: مفاعلة حثية ",
"CONTAINING ONLY CAPACITOR C" : "تحتوي فقط على مكثف C ",
"Z_C: capacitive reactance" : "Z_C: مفاعلة سعوية ",
"CONTAINING R, L AND C IN A SERIES" : "تحتوي على R، L و C على التوالي ",
"Z: impedance" : "Z: مقاومة",
"PHASE ANGLE" : "زاوية الطور",
"POWER FACTOR" : "معامل القدرة ",
"REAL POWER" : "القدرة الحقيقية ",
"ELECTRICAL RESONANCE" : "الرنين الكهربائي",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "تغيير الجهد الكهربي بواسطة المحولات ",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁، N₂: عدد اللفات في الملف الابتدائي والملف الثانوي. U₁، U₂: الجهد الكهربي الابتدائي والثانوي . I₁، I₂: التيارات الأولية والثانوية ",

"1. GAS LAWS" : "1. قوانين الغازات ",
"KELVIN TEMPERATURE" : "درجة الحرارة كلفن",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: درجة الحرارة على مقياس كلفن ، t: درجة الحرارة على مقياس الدرجات المئوية ",
"EQUATION OF STATE" : "معادلة الحالة ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: الضغط (P، باسكال)، V: الحجم (متر مكعب)، n: عدد مولات الغاز (مول)، R: الثابت العالمي للغازات، T: درجة حرارة الغاز على مقياس كلفن (كلفن)، k: ثابت بولتزمان، N: عدد الجزيئات في الغاز",
"IDEAL GAS LAW" : "قانون الغاز المثالي",
"BOYLE’S LAW FOR PRESSURE" : "قانون بويل للضغط",
"If the temperature of the gas is constant" : "إذا كانت درجة حرارة الغاز ثابتة ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "قانون جاي لوساك للضغط ودرجة الحرارة ",
"If the volume on a gas is constant" : "إذا كان حجم الغاز ثابت ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: ضغط الغاز عند درجة حرارة t , p_o: الضغط عند 0 درجة مئوية، γ: العامل عند حجم ثابت",
"Example when t=0 Kelvin" : "مثال عند t = 0 كلفن ",
"CHARLES'S LAW OF VOLUMES" : "قانون شارل للحجوم ",
"If the pressure on a gas is constant" : "إذا كان الضغط على غاز ثابت ",
"2. CHANGES OF STATE AND SHAPE" : "2. تغييرات الحالة والشكل ",
"HEAT" : "حرارة",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: الحرارة المنبعثة، Q_r: الحرارة الواردة، m: كتلة الجسم الإجمالية (كلجم)، c: الحرارة النوعية (كلجم.كلفن / جول)، Δt: التغير في درجة الحرارة (كلفن) ",
"The specific heats of some materials" : "الحرارة النوعية لبعض المواد ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "الانصهار (تجميد أو تصلب) ",
"Heat of fusion of some materials" : "حرارة انصهار بعض المواد",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: كمية الحرارة (جول)، λ: حرارة الانصهار (كلجم / جول) m: الكتلة (كلجم)",
"VAPORIZATION" : "تبخير",
"L: heat of vaporization" : "L: حرارة التبخر",
"Heat of vaporization of some materials" : "حرارة التبخر لبعض المواد ",
"LINEAR EXPANSION" : "التمدد الخطي ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: الطول الأصلي (م)، α: معامل التمدد الطولي (كلفن⁻¹)، Δt: التغير في درجة الحرارة",
"VOLUME EXPANSION" : "تمدد حجمي ",
"AREA EXPANSION" : "تمدد مساحي ",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "تغير الكثافة (كثافة الكتلة الحجمية) ",
"D_o: original density (kg/m³)" : "D_o: الكثافة الأصلية (متر مكعب / كلجم) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "تغير قطر القطاع العرضي لجسم صلب ",
"3. THERMODYNAMICS" : "3. الديناميكا الحرارية",
"THE FIRST LAW OF THERMODYNAMICS" : "القانون الأول للديناميكا الحرارية",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU: التغير في الطاقة الداخلية، W: الشغل المبذول بواسطة النظام، Q: الحرارة المضافة إلى داخل أو خارج النظام ",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "تطبيق القانون الأول على قوانين الغاز المثالي ",
"- Volume is constant" : "- 'الحجم ثابت ",
"- Pressure is constant, W': work created by gas" : "- الضغط ثابت , W': الشغل الناتج بواسطة الغاز ",
"- Temperature is constant" : "- درجة الحرارة ثابتة",
"THE SECOND LAW OF THERMODYNAMICS" : "القانون الثاني للديناميكا الحرارية",
"- The efficiency of a cyclic heat engine" : "- 'كفاءة المحرك الحراري الدوار ",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': الشغل المبذول لكل دورة (جول) , Q₁: الحرارة الممتصة لكل دورة من درجة الحرارة الأعلى (جول) , Q₂’: الحرارة المنطلقة لكل دورة إلى درجة الحرارة الأقل (جول) ",
"- Maximum thermal efficiency" : "- الكفاءة الحرارية القصوى",
"T₁, T₂: higher and lower temperatures" : "T₁، T₂: درجات الحرارة الأعلى والأقل ",

"1. SIMPLE HARMONIC MOTION" : "1. الحركة التوافقية البسيطة ",
"SPRING" : "زنبرك (نابض) ",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: ثابت الزنبرك (م / نيوتن) , s: الإزاحة (م) , ω: السرعة الزاوية (ث / ت.دائري) , T: الزمن الدوري , m: كتلة الجسم , A: السعة ",
"SPRINGS IN SERIES" : "نوابض على التوالي ",
"k: spring constant of the system, T: period of the system" : "k: ثابت الزنبرك بالنظام , T: الزمن الدوري للنظام ",
"SPRINGS IN PARALLEL" : "نوابض على التوازي ",
"SIMPLE PENDULUM" : "البندول البسيط",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: السرعة الزاوية (ث / ت.دائري)، T: الزمن الدوري، α_o: زاوية عند السعة، A: السعة، l: طول البندول ",
"MOTION EQUATIONS" : "معادلات الحركة",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: الإزاحة، α: الزاوية، v: السرعة، T: القوة على القضيب ",
"ENERGY" : "طاقة",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: طاقة الوضع، E_k: الطاقة الحركية، E: الطاقة الميكانيكية ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "التغير في الفترة (الزمن الدوري) الذي أعقب التغير في درجة الحرارة ",
"α: coefficient of linear expansion of the rod" : "α: معامل التمدد الطولي للقضيب",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "تغيير الفترة الذي تلا التغيير في الارتفاع ",
"h: height of pendulum, R: Earth's radius" : "h: ارتفاع البندول، R: نصف قطر الأرض ",
"PENDULUM" : "رقاص الساعة",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: عزم القصور الذاتي، ω: السرعة الزاوية، m: كتلة العنقود، d: OG، T: الزمن الدوري",
"2. PERIODIC MOTION" : "2. الحركة الدورية",
"WAVELENGTH" : "الطول الموجي",
"FUNCTION OF WAVE AT SOME POINTS" : "دالة الموجة عند بعض النقاط ",
"WAVE INTERFERENCE" : "تداخل الموجات ",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁، S₂: 2 مصادر موجة لها نفس الطور; M: نقطة عشوائية ",
"3. SOUND WAVES" : "3. موجات الصوت",
"SOUND SPEED" : "سرعة الصوت",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (ث / م): سرعة الصوت في البيئة عند درجة حرارة t (مئوية) ",
"SOUND INTENSITY " : "شدة الصوت",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: الطاقة الصوتية (جول)، P: قوة الصوت (وات)، A: مساحة سطح الكرة (متر مربع)، t: الزمن (ث) ",
"SOUND INTENSITY LEVEL" : "مستوى شدة الصوت",
"I_o: the standard reference sound intensity" : "I_o: معيار شدة الصوت المرجعية",
"THE DOPPLER EFFECT" : "تأثير دوبلر",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: السرعة النسبية للمراقب؛ v_S: السرعة النسبية للمصدر؛ v: سرعة الصوت في هذا الوسط. f_S، f_O: تردد الصوت من المصدر والمراقب ",
"SOUND SPEED IN GASES" : "سرعة الصوت في الغازات",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: سرعة الصوت (م / ث)، R: الثابت العالمي للغازات، T: درجة الحرارة المطلقة (كلفن)، M: الكتلة الجزيئية للغاز (كلجم / مول)، γ: الثابت الأديباتي (عند درجة حرارة ثابتة)",
"Example in air" : "مثال في الهواء ",

"1. GEOMETRIC OPTICS" : "1. البصريات الهندسية",
"LAWS OF REFLECTION" : "قوانين الانعكاس",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: شعاع ساقط، IR: شعاع منعكس، i: زاوية السقوط، i': زاوية الانعكاس ",
"REFRACTIVE INDEX" : "معامل الانكسار",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: معامل الانكسار للوسط، v: سرعة الضوء في الوسط، c: سرعة الضوء في الفراغ (ث / م) ",
"LAW OF REFRACTION" : "قانون الانكسار",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: معامل الانكسار للوسط 1، n₂: معامل الانكسار للوسط 2، i: زاوية السقوط، r: زاوية الانكسار، n₂₁: معامل الانكسار المطلق ",
"If medium 1 is vacuum" : "إذا كان الوسط 1 فراغ ",
"TOTAL REFLECTION PHENOMENON" : "ظاهرة الانعكاس الكلي ",
"There is no refracted ray if" : "لايوجد شعاع منكسر إذا ",
"PRISM" : "موشور",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: زاوية الأوج (قمة)، D: زاوية الانحراف، i₁: زاوية السقوط، i₂: زاوية الشعاع المنبعث (الخارج) ",
"- Condition to have refractive ray" : "- 'شرط حدوث شعاع منكسر ",
"- When angle of incidence is minimum" : "- عندما تكون زاوية السقوط هي الأدنى ",
"THIN LENS" : "عدسة رقيقة",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: البعد البؤري (عدسة مجمعة f&gt; 0؛ عدسة مفرقة f&lt;0)، d: بعد الجسم عن مركز العدسة، d': بعد الصورة عن مركز العدسة ",
"MAGNIFICATION FACTOR" : "عامل التكبير",
"h_I: image height, h_O: object height" : "h_I: ارتفاع الصورة، h_O: ارتفاع الجسم ",
"POWER OF THE LENS" : "قوة العدسة",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: معامل الانكسار لمادة العدسة، R₁: نصف قطر انحناء سطح العدسة الأقرب إلى مصدر الضوء، R₂: نصف قطر انحناء سطح العدسة الأبعد عن مصدر الضوء ",
"2. QUANTUM OF LIGHT" : "2. كم (مقدار) من الضوء ",
"PHOTON ENERGY" : "طاقة الفوتون",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: ثابت بلانك، f: التردد (هرتز)، λ: الطول الموجي (م)، c: سرعة الضوء ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "شرط حدوث التأثير الكهروضوئي ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: طول موجة الضوء الساطع، λ_o: الحد الكهروضوئي، W: الشغل المنبعث (جول) ",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "معادلة آينشتاين حول التأثير الكهروضوئي",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: كتلة الالكترون الضوئي (كلجم)، v_o: السرعة القصوى للالكترون الضوئي (م / ث) ",

"1. THEORY OF RELATIVITY" : "1. نظرية النسبية",
"MASS–ENERGY EQUIVALENCE" : "تكافؤ المادة والطاقة",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: كتلة (كلجم)، E: طاقة الجسم (جول)، c: سرعة الضوء (ث / م) ",
"LENGTH CONTRACTION" : "الإنكماش الطولي ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: الطول الحقيقي للجسم، l: الطول الملاحظ بواسطة مراقب متحرك بسرعة v ",
"RELATIVISTIC MASS" : "الكتلة النسبية",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: كتلة السكون m: الكتلة النسبية للجسم عندما يتحرك بسرعة v ",
"TIME DILATION" : "تمدد الزمن",
"2. ATOMIC NUCLEUS" : "2. النواة الذرية",
"NUCLEAR MAKEUP" : "البنية النووية (تركيب النواة) ",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: عدد البروتونات، N: عدد النيوترونات، A: العدد الكتلي ",
"NUCLEAR REACTION" : "التفاعل النووي",
"- m&glt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: تفاعل نووي يطلق طاقة ",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: تفاعل نووي يمتص طاقة ",
"RADIOACTIVE DECAY" : "الاضمحلال الإشعاعي",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: الكمية الأولية للمادة النشطة، N: الكمية التي مازالت موجودة ولم تتحلل بعد مرور زمن t، ΔN: كمية المادة المتحللة، m_o: الكتلة الأولية، m: الكتلة المتبقية، λ: ثابت الاضمحلال، t: الزمن، T:فترة نصف العمر ",
"Half life of some elements" : "فترة نصف العمر لبعض العناصر ",
"AMOUNT OF RADIOACTIVITY" : "كمية النشاط الإشعاعي",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: القيمة الأولية للنشاط الإشعاعي، H: كمية النشاط الإشعاعي عند زمن t ",
"1. CONSTANTS" : "1. الثوابت",
"ALPHA PARTICLE MASS" : "كتلة جسيم ألفا ",
"ATOMIC MASS CONSTANT" : "ثابت الكتلة الذرية",
"ATOMIC UNIT OF ENERGY" : "الوحدة الذرية للطاقة ",
"ATOMIC UNIT OF FORCE" : "الوحدة الذرية للقوة ",
"ATOMIC UNIT OF LENGTH" : "الوحدة الذرية للطول ",
"ATOMIC UNIT OF MASS" : "الوحدة الذرية للكتلة ",
"AVOGADRO'S CONSTANT" : "ثابت أفوجادرو",
"BOHR RADIUS" : "نصف قطر بور ",
"BOLTZMANN CONSTANT" : "ثابت بولتزمان ",
"CLASSICAL ELECTRON RADIUS" : "نصف قطر الالكترون الكلاسيكي ",
"ELEMENTARY CHARGE" : "الشحنة الأولية ",
"EARTH MASS" : "كتلة الأرض",
"EARTH EQUATORIAL RADIUS" : "نصف قطر الأرض الاستوائي ",
"EARTH MEAN ORBITAL VELOCITY" : "متوسط السرعة المدارية للأرض ",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "السرعة الدورانية الزاوية للأرض ",
"FARADAY’S CONSTANT" : "ثابت فاراداي",
"GAS CONSTANT" : "ثابت الغازات",
"MOLAR MASS CONSTANT" : "ثابت الكتلة المولية",
"MOLAR VOLUME OF IDEAL GAS" : "الحجم المولي للغاز المثالي",
"NEUTRON MASS" : "كتلة النيوترون ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "ثابتة نيوتن للجاذبية",
"PLANCK’S CONSTANT" : "ثابت بلانك",
"PLANCK MASS" : "كتلة بلانك",
"PROTON MASS" : "كتلة البروتون ",
"PROTON-ELECTRON MASS RATIO" : "النسبة الكتلية بين البروتون والالكترون ",
"SPEED OF LIGHT IN VACUUM" : "سرعة الضوء في الفراغ",
"STANDARD ACCELERATION OF GRAVITY" : "التسارع القياسي للجاذبية ",
"STANDARD ATMOSPHERE" : "الجو القياسي ",
"STANDARD REFERENCE SOUND INTENSITY" : "شدة الصوت المرجعية القياسية ",
"STEFAN-BOLTZMANN CONSTANT" : "ثابت ستيفان-بولتزمان",
"2. GREEK ALPHABET" : "2. الأبجدية اليونانية",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: الحرف اليوناني، C2: الاسم، C3: ما يعادلها، C4: الصوت عندما يتم التحدث ",

"Mechanics" : "علم الميكانيكا ",
"Thermal physics" : "الفيزياء الحرارية",
"Optics" : "علم البصريات ",
"Theory of relativity" : "النظرية النسبية",

"FREE FALLING" : "السقوط الحر",
"VERTICAL PROJECTILE" : "قذيفة عمودية ",
"ANGLED PROJECTILE" : "قذيفة زاوية ",
"HORIZONTAL PROJECTILE" : "قذيفة أفقية ",
"SLIDING MOTION" : "حركة انزلاقية ",
"ATTRACTIVE FORCE" : "قوة جاذبة ",
"Hydraulic press" : "ضغط هيدروليكي ",
"PRESSURE" : "الضغط",
"LINEAR EXPANSION" : "التمدد الخطي ",
"VOLUME EXPANSION" : "تمدد حجمي ",
"SOUND SPEED" : "سرعة الصوت",
"REFRACTION" : "الانكسار",
"PRISM" : "موشور",
"LENS" : "عدسة",
"Length contraction" : "الإنكماش الطولي ",
"Time dilation" : "تمدد الزمن",
"RELATIVISTIC MASS" : "الكتلة النسبية",

"Height " : "ارتفاع",
"Time to touchdown " : "زمن الهبوط ",
"Touchdown velocity " : "سرعة الهبوط ",
"Initial velocity " : "السرعة الأولية",
"Maximum height " : "أقصى ارتفاع",
"Initial velocity " : "السرعة الأولية",
"Angle " : "زاوية",
"Maximum height " : "أقصى ارتفاع",
"Maximum distance " : "المسافة القصوى",
"Height " : "ارتفاع",
"Initial velocity " : "السرعة الأولية",
"Time to touchdown " : "زمن الهبوط ",
"Touchdown velocity " : "سرعة الهبوط ",
"Angle of tilted plane " : "زاوية إمالة المستوى ",
"Coefficient of friction " : "معامل الاحتكاك",
"Acceleration " : "تسارع",
"Mass " : "كتلة",
"Mass " : "كتلة",
"Distance " : "مسافة ",
"Attractive force " : "قوة جذب ",
"Area " : "مساحة ",
"Area " : "مساحة ",
"Force " : "قوة",
"Force" : "قوة",
"Force F₂ (or F₁)" : "قوة F₂ (أو F₁)",
"Temperature " : "درجة حرارة",
"Pressure at 0°C " : "الضغط عند 0 ° درجة مئوية ",
"Pressure " : "الضغط",
"Original length " : "الطول الأصلي ",
"Temperature change " : "التغير في درجة الحرارة",
"Coefficient of linear expansion " : "معامل التمدد الطولي",
"Change of length " : "تغير الطول ",
"Original volume " : "الحجم الأصلي ",
"Temperature change " : "التغير في درجة الحرارة",
"Coefficient of linear expansion " : "معامل التمدد الطولي",
"Change of volume " : "تغير الحجم ",
"Temperature " : "درجة حرارة",
"Sound speed " : "سرعة الصوت",
"Refractive index " : "معامل الانكسار",
"Refractive index " : "معامل الانكسار",
"Angle of incidence " : "زاوية السقوط",
"Angle of refraction " : "زاوية الانكسار",
"Angle (r or i) " : "زاوية (r أو i) ",
"Apex angle " : "زاوية القمة ",
"Angle of incident " : "زاوية السقوط ",
"Refractive index " : "معامل الانكسار",
"Angle of emergent ray " : "زاوية الشعاع الخارج ",
"Deviation angle " : "زاوية الانحراف",
"Focal length " : "البعد البؤري",
"Object distance " : "بعد الجسم ",
"Image distance " : "بعد الصورة ",
"Image (or object) distance" : "بعد الصورة (أو الجسم) ",
"Magnification factor " : "عامل التكبير",
"Speed " : "سرعة",
"Proper length " : "الطول الحقيقي ",
"Observed length " : "الطول المرصود ",
"Rest mass " : "كتلة السكون ",
"Relativistic mass " : "الكتلة النسبية",
"Proper time interval " : "الفاصل الزمني الحقيقي ",
"Observed time interval " : "الفاصل الزمني المرصود",
"Calculate" : "احسب ",
"Or input" : "أو المدخلات",
"Calculation Tools" : "أدوات الحساب",


	
};