var language={

"1. DYNAMICS" : "1.动力学 ",
"STRAIGHT LINE MOTION" : "直线运动 ",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s：距离（m），t：时间（s，秒），v：速度（m/s），v_a：平均速度 ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "匀变速直线运动 ",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a:加速度，v_o:初速度，v：t时刻的速度 ",
"DISTANCE FUNCTION" : "距离函数 ",
"x_o: initial distance from origin, x: distance at time t" : "x_o：初始距离，x：在时间t内的运动距离 ",
"UNIFORM CIRCULAR MOTION" : "匀速圆周运动 ",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ：角（弧度），l：弧长，R：圆的半径，ω：角速度（弧度/秒），t:通过弧长l所用的时间",
"CENTRIPETAL FORCE" : "向心力 ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f：频率（Hz），T：运动一周所需的时间，即周期（s），a：向心加速度，F：向心力（N，牛顿） ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "匀加速圆周运动 ",
"γ: angular acceleration" : "γ：角加速度 ",
"ACCELERATION" : "加速度",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t:切向加速度， a_n:法向加速度 ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1：加速，P2：匀速圆周运动，P3：减速 ",
"FREE FALLING FROM HEIGHT h" : "从高度h处自由下落",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g：重力加速度，v：t时刻的速度，s:t时刻时下落的距离，v_h:接触地面时的速度，t_h:下落的时间",
"VERTICAL PROJECTILE MOTION" : "竖直上抛运动",
"h_max: maximum height, v_o: initial velocity" : "h_max：物体向上运动的最大高度， v_o:初速度 ",
"Motion equation and velocity equation" : "运动方程和速度方程 ",
"ANGLED PROJECTILE MOTION" : "斜抛运动 ",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x，v_y：速度；x,y:关于时间t的运动方程；H：最大高度；L：最大距离 ",
"HORIZONTAL PROJECTILE MOTION" : "平抛运动 ",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h:落地所用时间， v_h:落地时速度 ",
"SLIDING MOTION ON AN INCLINED PLANE" : "在斜面上滑动 ",
"μ: coefficient of friction" : "μ：摩擦系数 ",
"Fiction coefficient of some materials" : "某些材料的摩擦系数 ",
"2. FORCES" : "2. 力 ",
"ATTRACTIVE FORCE" : "引力 ",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂:两物体的质量；r：两个物体之间的距离；G：万有引力常数 ",
"GRAVITATIONAL FORCE" : "万有引力 ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M：地球质量，m：物体的质量，R：地球半径，h：物体的高度",
"GRAVITATIONAL ACCELERATION" : "重力加速度 ",
"At a height h above the nominal surface of the earth" : "在地球表面上高度为h的地方",
"Near the sea level" : "贴近海平面",
"FORCE OF GRAVITY" : "重力 ",
"Force of gravity on earth, a special case of Gravitational force" : "重力，万有引力的一个特殊情况",
"NEWTON'S FIRST LAW" : "牛顿第一定律 ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F：作用在物体上的力（N），v：物体的速度，a：物体的加速度 ",
"NEWTON'S SECOND LAW" : "牛顿第二定律 ",
"m: object's mass (kg)" : "m：物体的质量（kg） ",
"NEWTON'S THIRD LAW" : "牛顿第三定律 ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "弹性力学 - 胡克定律 ",
"k: spring constant (N/m), x: displacement (m)" : "k:弹簧常数（N/m)，x：位移(m) ",
"A mass suspended by a spring" : "弹簧上悬挂物体",
"FORCE OF FRICTION" : "摩擦力 ",
"μ: coefficient of friction, N: normal force" : "μ：摩擦系数，N：法向力 ",
"3. STATICS" : "3. 静力学",
"MOMENT OF A FORCE" : "力矩 ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F：使用的力的大小（N)，d：力臂（从着力点到力的作用线的垂直距离)",
"MOMENT APPLICATION" : "重要应用 ",
"MOMENT OF INERTIA" : "转动惯量 ",
"Rod of length l" : "长度为l的杆 ",
"Thin circular hoop/ Thin cylindrical shell" : "薄圆环/薄圆柱环",
"Solid disk/ Solid cylinder" : "圆盘/圆柱体",
"Solid ball" : "实心球 ",
"Hollow sphere" : "球壳",
"ANGULAR MOMENTUM" : "角动量 ",
"I: moment of inertia, ω: angular velocity" : "I：转动惯量，ω：角速度 ",
"PLANE MOTION OF A RIGID BODY" : "刚体平面运动 ",
"γ: angular acceleration, M: moment of a force" : "γ：角加速度，M：瞬时力 ",

"4. CONSERVATION LAWS" : "4. 守恒定律 ",
"MOMENTUM OF FORCE" : "动量 ",
"LAW OF CONSERVATION OF MOMENTUM" : "动量守恒定律 ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁，v₂：物体1和2的初始速度；v₁'，v₂'：物体1和2的最终速度 ",
"PLASTIC COLLISION" : "完全非弹性弹性碰撞",
"v': velocity of the two body system (m₁+m₂) after impact" : "v'：碰撞之后的两体系统（m₁+m₂）的速度",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "一维完全弹性碰撞",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁'，v₂'：碰撞之后m₁和m₂的速度",
"5. WORK AND ENERGY" : "5. 功及能量",
"WORK" : "功 ",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W：力所做的功（J），F：移动物体距离S时所用的力，α：F和运动方向之间的夹角 ",
"EXAMPLES" : "示例 ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p：重力所做的功，h：高度的变化； W_ms：摩擦力做的功； W：弹簧所做的功 ",
"POWER" : "功率 ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P：功率（瓦特, W），t：做功的时间（s）",
"KINETIC ENERGY" : "动能 ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "旋转体的转动动能",
"WORK-ENERGY PRINCIPLE" : "功-能原理",
"v₁, v₂: speeds of object before and after the change" : "v₁，v₂：对象变化前后的速度 ",
"POTENTIAL ENERGY" : "势能 ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p：重力势能（J），m：物体质量（kg） ",
"CONSERVATION OF MECHANICAL ENERGY" : "机械能守恒 ",
"CONSERVATION OF ENERGY" : "能量守恒 ",
"6. MECHANICS OF FLUIDS" : "6. 流体力学 ",
"DENSITY" : "密度 ",
"m: mass of a volume V" : "m：体积为V的物体质量 ",
"PRESSURE" : "压力 ",
"F: force applied on area of A" : "F：对面积为A所施加的力",
"PRESSURE OF LIQUIDS" : "液体内的压强",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d：比重（N/m³），p_o：表面空气压强 (N/m²)，p：因为液体重力产生的压强，p_B:在深度h处的总压强",
"PASCAL’S PRINCIPLE" : "帕斯卡原理 ",
"p_s: pressure on the surface" : "p_s：表面压强",
"APPLICATION" : "应用 ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁，A₂：小活塞和大活塞的面积； F₁，F₂：对小活塞施加的力和大活塞收受到的向上的力量 ",
"ARCHIMEDES’ PRINCIPLE" : "阿基米德定律 ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d：液体比重（N/m³），V：物体体积，F_b：浮力 ",
"FLOW RATE" : "流量 ",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A：截面积（m²），v：流速（m/s），Q：流量（m³/s） ",

"1. ELECTROSTATICS" : "1. 静电 ",
"COULOMB’S LAW" : "库仑定律 ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q：电荷的大小（C），ε：介电常数（真空中ε=1），r：两个电荷之间的距离（m） ",
"ELECTRIC FIELDS" : "电场 ",
"E: electric field strength (N/C)" : "E：电场强度（N/C） ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "电场叠加原理 ",
"In case of 2 electric fields" : "两个电场的叠加的情形",
"WORK OF ELECTRIC FORCE" : "电场力的功",
"ELECTRIC POTENTIAL DIFFERENCE" : "电势差 ",
"RELATION BETWEEN E AND U" : "E和U的关系 ",
"CAPACITANCE" : "电容 ",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C：电容(F)，Q：总电荷(C)，U：电势(V)",
"CAPACITOR" : "电容 ",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A：电极板的面积（m²），d：电极之间的距离(m)，ε:介电常数（F/m） ",
"CAPACITANCES IN SERIES" : "电容的串联",
"CAPACITANCES IN PARALLEL" : "电容的并联",
"ELECTRIC FIELD ENERGY" : "电场能量 ",
"ENERGY OF CAPACITOR" : "电容器的能量 ",
"V=A.d: volume between two electrode plates" : "V=A.d:两个电极板之间的体积",
"2. DIRECT CURRENT" : "2.直流电 ",
"ELECTRIC CURRENT" : "电流 ",
"I: current (A), q: charge (C), t: time" : "I：电流（A），q：电荷（C），t：时间 ",
"OHM’S LAW" : "欧姆定律 ",
"U: electric potential difference between the ends of the resistor R" : "U：电阻R的两端之间的电势差 ",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "电流所做的功",
"ELECTRICAL POWER" : "电源",
"RESISTANCE" : "电阻",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ：材料的电阻率（Ωm）， l：长度（m），A：材料的横截面面积（m²） ",
"SERIES CIRCUITS" : "串联电路 ",
"PARALLEL CIRCUITS" : "并联电路 ",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "由电阻产生的功或热能 ",
"POWER CONSUMPTION OF A RESISTOR" : "一个电阻的能量消耗 ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "发电机的电动势 ",
"W: work of force (J), q: charge (C)" : "W：力所做的功（J），q：电荷（C） ",
"GENERATORS IN SERIES" : "发电机 ",
"r: internal resistance of the generator" : "r：在发电机的内阻 ",
"GENERATORS IN PARALLEL" : "发电机的并联",
"GENERATORS IN SERIES-PARALLEL" : "发电机的串并联",
"WORK AND POWER OF GENERATOR" : "发电机的功和功率 ",
"H: Efficiency of generator" : "H：发电机的效率 ",
"3. MAGNETISM" : "3.磁 ",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "通过非闭合曲面S的磁通量 ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B：磁场的大小（T，特斯拉）α：磁场和曲面S的法线之间的夹角 ",
"MAGNETIC FORCES ON MOVING CHARGES" : "运动电荷所受到的磁力",
"v: velocity of the charge (m/s)" : "v：电荷运动速度（m/s） ",
"FORCE ON A CURRENT-CARRYING WIRE" : "通电导线的受力",
"I: current (A), l: length of the wire (m)" : "I：电流（A），l：线长（m） ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "在两平行通电导线之间的力 ",
"r: distance between two wires (m)" : "r：两电线之间的距离(m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "长通电导线的磁场",
"r: perpendicular distance from the center of the wire (m)" : "r:距离导线中心的垂直距离(m)",
"MAGNETIC FIELD OF A LOOP" : "通电线圈的磁场",
"n: number of turns per unit length of solenoid (turns/m)" : "n:单位长度通电螺线管的匝数（匝/m）",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "感应电动势 - 法拉第定律 ",
"N: numbers of turns per loop (turns/m)" : "N:感应线圈的匝数；导线环绕物体的圈数（匝/m）",
"INDUCTANCE" : "电感 ",
"ELECTRIC ENERGY" : "电能 ",
"MAGNETIC ENERGY" : "磁能",
"ELECTRIC-MAGNETIC ENERGY" : "电磁能 ",
"4. ALTERNATING CURRENT" : "4.交流电 ",
"BASIC PARAMETERS" : "基本参数 ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i：瞬时电流（A），I_o：最大瞬时电流（A），T：周期波，f：频率，λ：波长，c：光速 ",
"EFFECTIVE CURRENT AND VOLTAGE" : "有效的电流和电压 ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "交流电流​​的欧姆定律只包含电阻R ",
"CONTAINING ONLY INDUCTOR L" : "只含有电感器L ",
"Z_L: inductive reactance" : "Z_L：感抗 ",
"CONTAINING ONLY CAPACITOR C" : "只含有电容C ",
"Z_C: capacitive reactance" : "Z_C：容抗 ",
"CONTAINING R, L AND C IN A SERIES" : "含R，L和C的串联 ",
"Z: impedance" : "Z：阻抗 ",
"PHASE ANGLE" : "相位角 ",
"POWER FACTOR" : "功率因数 ",
"REAL POWER" : "实际功率 ",
"ELECTRICAL RESONANCE" : "电气共振 ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "变压器改变电压",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁，N₂：初级线圈和次级线圈的匝数数目； U₁，U₂：初级和次级电压；I₁，I₂：初级和次级电流 ",

"1. GAS LAWS" : "1.气体定律 ",
"KELVIN TEMPERATURE" : "开尔文温度 ",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T：开氏温度，即为热力学温度，t：摄氏温度",
"EQUATION OF STATE" : "状态方程 ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p：压强（P，帕斯卡），V：体积（m³），n：气体（摩尔）的摩尔数，R：气体常数，T：气体的开尔文温度（K），k:玻尔兹曼常数，N：在气体中的分子数 ",
"IDEAL GAS LAW" : "理想气体定律 ",
"BOYLE’S LAW FOR PRESSURE" : "波义耳压强定律 ",
"If the temperature of the gas is constant" : "如果气体的温度是恒定的 ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "盖 - 吕萨克压力 - 温度定律 ",
"If the volume on a gas is constant" : "如果在气体的体积是恒定的 ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p：温度t的气体压强，p_o：在0摄氏度的压强，γ：当体积不变的因数 ",
"Example when t=0 Kelvin" : "例如当t=0 K时",
"CHARLES'S LAW OF VOLUMES" : "查尔斯体积定律 ",
"If the pressure on a gas is constant" : "如果在气体中的压强是恒定的 ",
"2. CHANGES OF STATE AND SHAPE" : "2.状态和形状的变化 ",
"HEAT" : "热 ",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e：热发射，Q_r：接收的热量，m：物体的总质量（kg)，c：比热（J/kg.K），Δt：温度变化（K） ",
"The specific heats of some materials" : "一些材料的比热 ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "熔化（冻结或凝固） ",
"Heat of fusion of some materials" : "一些材料的溶解热 ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q：热量（J），λ：熔解热（J/kg），m：质量（kg） ",
"VAPORIZATION" : "汽化 ",
"L: heat of vaporization" : "L：汽化热 ",
"Heat of vaporization of some materials" : "一些材料的汽化热 ",
"LINEAR EXPANSION" : "线膨胀 ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o：原来长度（m），α：线性膨胀系数（K⁻¹），Δt：温度变化",
"VOLUME EXPANSION" : "体积膨胀 ",
"AREA EXPANSION" : "面积扩大 ",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "密度改变（体积质量密度） ",
"D_o: original density (kg/m³)" : "D_o：原始密度（kg/m³） ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "改变固体的横截面的直径 ",
"3. THERMODYNAMICS" : "3.热力学 ",
"THE FIRST LAW OF THERMODYNAMICS" : "热力学第一定律 ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU：内能改变，W：由系统所做的功，Q：系统吸收或放出的热量",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "第一理想气体定律的应用 ",
"- Volume is constant" : "- 体积不变",
"- Pressure is constant, W': work created by gas" : "压力为常数，W'：由气体产生的功 ",
"- Temperature is constant" : "- 温度是恒定",
"THE SECOND LAW OF THERMODYNAMICS" : "热力学第二定律 ",
"- The efficiency of a cyclic heat engine" : "- 循环热机的效率",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W'：每循环做的功（J），Q₁：每次循环从温度较高的地方吸收的热量（J），Q₂'：每个循环向温度较低的地方排出的热量（J） ",
"- Maximum thermal efficiency" : "- 最大热效率",
"T₁, T₂: higher and lower temperatures" : "T₁，T₂：更高和更低的温度 ",

"1. SIMPLE HARMONIC MOTION" : "1.简谐运动 ",
"SPRING" : "弹簧",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k:弹簧常数（N/m），s:位移（m），ω：角速度（rad/s），T：周期，m：质量的物体，A：振幅 ",
"SPRINGS IN SERIES" : "弹簧系列 ",
"k: spring constant of the system, T: period of the system" : "k：系统的弹簧常数，T：系统周期 ",
"SPRINGS IN PARALLEL" : "弹簧的并联",
"SIMPLE PENDULUM" : "单摆 ",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω：角速度（rad/s），T：周期，α_o：角幅度，A：振幅，l：钟摆的长度 ",
"MOTION EQUATIONS" : "运动方程 ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s：位移，α：角，v：速度，T：杆上的力 ",
"ENERGY" : "能源 ",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p：势能，E_k：动能，E：机械能 ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "随温度的变化产生的周期变化",
"α: coefficient of linear expansion of the rod" : "α：杆的线性膨胀系数 ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "高度的变化改变产生的周期变化 ",
"h: height of pendulum, R: Earth's radius" : "h：摆的高度，R：地球的半径 ",
"PENDULUM" : "摆 ",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I：转动惯量，ω：角速度，m：摆的质量，d：OG，T：周期 ",
"2. PERIODIC MOTION" : "2.周期运动",
"WAVELENGTH" : "波长 ",
"FUNCTION OF WAVE AT SOME POINTS" : "某些点的波函数",
"WAVE INTERFERENCE" : "波的干涉",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁，S₂：两个波的起源点; M：随机点 ",
"3. SOUND WAVES" : "3.声波 ",
"SOUND SPEED" : "声速 ",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v（m/s）：在温度t（摄氏）的环境中的声速 ",
"SOUND INTENSITY " : "声音强度 ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E：声音能量（J），P：声功率（W），A：一个球体的表面面积（m²），t：时间（s） ",
"SOUND INTENSITY LEVEL" : "声强级 ",
"I_o: the standard reference sound intensity" : "I_o：标准参考声强 ",
"THE DOPPLER EFFECT" : "多普勒效应 ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O：观测者的相对运动速度；v_S：源的相对速度；v：在这种介质中的声速； f_S，f_O：声源和观察者的频率 ",
"SOUND SPEED IN GASES" : "在气体中的声速 ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v：声速(m/s)，R：普遍气体常数，T：绝对温度（K），M：气体分子质量(kg/mol)，γ：绝热常数",
"Example in air" : "例如在空气中 ",

"1. GEOMETRIC OPTICS" : "1，几何光学 ",
"LAWS OF REFLECTION" : "反射定律 ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI：入射光线，IR：反射光线，i：入射角，i'：反射角 ",
"REFRACTIVE INDEX" : "折射率",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n：第一个介质的折射率，v： 光在介质中的速度，c：光在真空的速度(m/s)",
"LAW OF REFRACTION" : "折射定律 ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁：介质1的折射率，n₂:介质2的折射率，i：入射角角度，r：折射角角度，n₂₁：绝对折射率",
"If medium 1 is vacuum" : "如果介质1是真空 ",
"TOTAL REFLECTION PHENOMENON" : "全反射现象 ",
"There is no refracted ray if" : "没有折射光线",
"PRISM" : "棱镜",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A：顶角，D：偏差角度，i₁：入射角，i₂：出射角",
"- Condition to have refractive ray" : "-有折射光线的条件",
"- When angle of incidence is minimum" : "-当入射角为最小",
"THIN LENS" : "薄透镜 ",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f：焦距（凸透镜f&gt;0;凹透镜f&lt;0），d:物距，d':像距.",
"MAGNIFICATION FACTOR" : "放大系数 ",
"h_I: image height, h_O: object height" : "h_I:像的高度，h_O:物的高度",
"POWER OF THE LENS" : "透镜的功率 ",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n:透镜的折射率，R₁:透镜表面距离光源最近处的曲率半径，R₂:透镜表面距离光源最远处的曲率半径",
"2. QUANTUM OF LIGHT" : "2.光量子 ",
"PHOTON ENERGY" : "光子能量 ",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h：普朗克常数，f：频率（HZ），λ：波长（m），c：光速 ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "条件有光电效应 ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ:光的波长，λ_o的：光电子的临界波长，W：金属的逸出功（J） ",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "光电效应的爱因斯坦方程",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m：光电子质量（kg），v_o：光电子的最大速度（m/s） ",

"1. THEORY OF RELATIVITY" : "1.相对论理论 ",
"MASS–ENERGY EQUIVALENCE" : "质能方程",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m:质量（kg），E:物体的能量（J），c:光速（m/s）",
"LENGTH CONTRACTION" : "长度收缩 ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o：物体的实际长度，l:以速度v运动的观察着看到的长度",
"RELATIVISTIC MASS" : "相对质量 ",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o：静止质量，m：物体以速度v运动时的相对质量 ",
"TIME DILATION" : "时间膨胀 ",
"2. ATOMIC NUCLEUS" : "2.原子核 ",
"NUCLEAR MAKEUP" : "原子核组成",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z：质子数，N：中子数，A：质量数 ",
"NUCLEAR REACTION" : "核反应 ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o:核反应释放能量",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o：核反应的吸收能量",
"RADIOACTIVE DECAY" : "放射性衰变 ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o：放射性物质的初始量，N：剩余没有衰变的物质的数量，ΔN:衰变物质的质量，m_o：初始质量，m：剩余质量，λ：衰变常数，t：时间，T：半衰期 ",
"Half life of some elements" : "一些元素的半衰期",
"AMOUNT OF RADIOACTIVITY" : "放射量 ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o：放射性初始数量，H：在时间t内的放射的量 ",
"1. CONSTANTS" : "1.常量 ",
"ALPHA PARTICLE MASS" : "阿尔法粒子的质量 ",
"ATOMIC MASS CONSTANT" : "原子质量常数",
"ATOMIC UNIT OF ENERGY" : "能量的原子单位 ",
"ATOMIC UNIT OF FORCE" : "力的原子单位 ",
"ATOMIC UNIT OF LENGTH" : "长度的原子单位 ",
"ATOMIC UNIT OF MASS" : "质量的原子单位 ",
"AVOGADRO'S CONSTANT" : "阿伏加德罗常数 ",
"BOHR RADIUS" : "玻尔半径 ",
"BOLTZMANN CONSTANT" : "玻尔兹曼常数 ",
"CLASSICAL ELECTRON RADIUS" : "经典电子半径 ",
"ELEMENTARY CHARGE" : "基本电荷 ",
"EARTH MASS" : "地球质量 ",
"EARTH EQUATORIAL RADIUS" : "地球赤道半径 ",
"EARTH MEAN ORBITAL VELOCITY" : "地球运动的轨道速度 ",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "地球自转角速度 ",
"FARADAY’S CONSTANT" : "法拉第常数 ",
"GAS CONSTANT" : "气体常数 ",
"MOLAR MASS CONSTANT" : "摩尔质量不变 ",
"MOLAR VOLUME OF IDEAL GAS" : "理想气体的摩尔体积 ",
"NEUTRON MASS" : "中子的质量 ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "万有引力常数 ",
"PLANCK’S CONSTANT" : "普朗克常数 ",
"PLANCK MASS" : "普朗克质量 ",
"PROTON MASS" : "质子质量 ",
"PROTON-ELECTRON MASS RATIO" : "质子 - 电子质量比 ",
"SPEED OF LIGHT IN VACUUM" : "光在真空中的速度 ",
"STANDARD ACCELERATION OF GRAVITY" : "标准重力加速度 ",
"STANDARD ATMOSPHERE" : "标准大气压 ",
"STANDARD REFERENCE SOUND INTENSITY" : "标准参考声音强度 ",
"STEFAN-BOLTZMANN CONSTANT" : "斯蒂芬 - 波尔兹曼常数 ",
"2. GREEK ALPHABET" : "2.希腊字母 ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1：希腊字母，C2：名称，C3：等价的，C4：发音 ",

"Mechanics" : "力学",
"Thermal physics" : "热学",
"Optics" : "光学 ",
"Theory of relativity" : "相对论 ",

"FREE FALLING" : "自由落体",
"VERTICAL PROJECTILE" : "竖直上抛",
"ANGLED PROJECTILE" : "斜抛 ",
"HORIZONTAL PROJECTILE" : "平抛 ",
"SLIDING MOTION" : "滑动 ",
"ATTRACTIVE FORCE" : "引力 ",
"Hydraulic press" : "液压机 ",
"PRESSURE" : "压力 ",
"LINEAR EXPANSION" : "线膨胀 ",
"VOLUME EXPANSION" : "体积膨胀 ",
"SOUND SPEED" : "声速 ",
"REFRACTION" : "折射 ",
"PRISM" : "棱镜",
"LENS" : "透镜",
"Length contraction" : "长度收缩 ",
"Time dilation" : "时间膨胀 ",
"RELATIVISTIC MASS" : "相对质量 ",

"Height " : "高度 ",
"Time to touchdown " : "落地时间",
"Touchdown velocity " : "落地时速度",
"Initial velocity " : "初始速度 ",
"Maximum height " : "最大高度 ",
"Initial velocity " : "初始速度 ",
"Angle " : "角 ",
"Maximum height " : "最大高度 ",
"Maximum distance " : "最大距离 ",
"Height " : "高度 ",
"Initial velocity " : "初始速度 ",
"Time to touchdown " : "落地时间",
"Touchdown velocity " : "落地时速度",
"Angle of titled plane " : "平面夹角 ",
"Coefficient of friction " : "摩擦系数 ",
"Acceleration " : "加速度",
"Mass " : "质量",
"Mass " : "质量",
"Distance " : "距离",
"Attractive force " : "引力",
"Area " : "面积",
"Area " : "面积",
"Force " : "力",
"Force" : "力 ",
"Force F₂ (or F₁)" : "力F₂（或F₁） ",
"Temperature " : "温度 ",
"Pressure at 0°C " : "在0℃时的压力 ",
"Pressure " : "压力 ",
"Original length " : "原始长度 ",
"Temperature change " : "温度变化 ",
"Coefficient of linear expansion " : "线性膨胀系数 ",
"Change of length " : "长度变化 ",
"Original volume " : "原始体积",
"Temperature change " : "温度变化 ",
"Coefficient of linear expansion " : "线性膨胀系数 ",
"Change of volume " : "变化量 ",
"Temperature " : "温度 ",
"Sound speed " : "声速 ",
"Refractive index " : "折射率 ",
"Refractive index " : "折射率 ",
"Angle of incidence " : "入射角 ",
"Angle of refraction " : "折射角 ",
"Angle (r or i) " : "角度（r或i） ",
"Apex angle " : "顶角 ",
"Angle of incident " : "入射角 ",
"Refractive index " : "折射率 ",
"Angle of emergent ray " : "出射光线的角度 ",
"Deviation angle " : "偏向角 ",
"Focal length " : "焦距 ",
"Object distance " : "物距 ",
"Image distance " : "像距 ",
"Image (or object) distance" : "像(或)物距",
"Magnification factor " : "放大系数 ",
"Speed " : "速度 ",
"Proper length " : "适当的长度 ",
"Observed length " : "观察到的长度 ",
"Rest mass " : "静止质量",
"Relativistic mass " : "相对论质量 ",
"Proper time interval " : "适当的时间间隔 ",
"Observed time interval " : "观测时间间隔",
"Calculate" : "0",
"Or input" : "0",
"Calculation Tools" : "计算工具",


	
};