var language={

"1. DYNAMICS" : "1. Динамика ",
"STRAIGHT LINE MOTION" : "Прямолинейное движение",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: путь (м), t: время (c, секунда), v: скорость (м/с), v_a: средняя скорость ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Постоянное ускорение Прямолинейное движение ",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: ускорение, v_o: начальная скорость, v: скорость в момент времени t ",
"DISTANCE FUNCTION" : "Закон движения",
"x_o: initial distance from origin, x: distance at time t" : "x_o: исходное расстояние (начальная координата) от начала отсчета, х: расстояние в момент времени t",
"UNIFORM CIRCULAR MOTION" : "Равномерное движение по окружности",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: угол (рад), l: длина дуги, R: радиус окружности, ω: угловая скорость (рад/с), t: время движения тела по дуге l",
"CENTRIPETAL FORCE" : "Центтростремительная сила",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: частота (Гц), T: период одиного оборота (c), a: центростремительное ускорение, F: центростремительная сила (H, Ньютон)",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Постоянное ускорение Круговое движение (Движение по окружности)",
"γ: angular acceleration" : "g: угловое ускорение",
"ACCELERATION" : "Ускорение ",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: тангенциальное ускорение, a_n: нормальное ускорение ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: ускорение, P2: равномерное круговое движение, P3: замедление ",
"FREE FALLING FROM HEIGHT h" : "Свободное падение с высоты h",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: гравитационное ускорение, v: скорость в момент времени t, s: расстояние через время t, v_h: скорость при касании земли, t_h: время до приземления ",
"VERTICAL PROJECTILE MOTION" : "Вертикальное движение снаряда ",
"h_max: maximum height, v_o: initial velocity" : "h_max: максимальная высота, v_o: начальная скорость ",
"Motion equation and velocity equation" : "Уравнения движения и уравнение скорости ",
"ANGLED PROJECTILE MOTION" : "Движение тела под углом к горизонту",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: скорость; х, у: уравнение движения по t; H: максимальная высота; L: максимальное расстояние ",
"HORIZONTAL PROJECTILE MOTION" : "Движение тела, брошенного горизонтально",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: время приземления, v_h: скорость приземления ",
"SLIDING MOTION ON AN INCLINED PLANE" : "Скольжение по наклонной плоскости ",
"μ: coefficient of friction" : "μ: коэффициент трения ",
"Fiction coefficient of some materials" : "Коэффициент трения некоторых материалов ",
"2. FORCES" : "2. Силы",
"ATTRACTIVE FORCE" : "Сила притяжения",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: массы 2 объектов; r: расстояние между 2 объектами; G: гравитационная постоянная ",
"GRAVITATIONAL FORCE" : "Гравитационная сила ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: масса Земли, m: масса объекта, R: радиус Земли, h: высота объекта ",
"GRAVITATIONAL ACCELERATION" : "Ускорение свободного падения ",
"At a height h above the nominal surface of the earth" : "На высоте h над уровнем земли ",
"Near the sea level" : "Вблизи уровня моря (у поверхности земли)",
"FORCE OF GRAVITY" : "Сила тяжести ",
"Force of gravity on earth, a special case of Gravitational force" : "Сила тяжести на Земле, это частный случай гравитационной силы",
"NEWTON'S FIRST LAW" : "Первый закон Ньютона ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: силы, действующие на тело, v: скорость тела, а: ускорение тела ",
"NEWTON'S SECOND LAW" : "Второй закон Ньютона ",
"m: object's mass (kg)" : "m: масса тела (кг) ",
"NEWTON'S THIRD LAW" : "Третий закон Ньютона ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Линейная упругость - закон Гука",
"k: spring constant (N/m), x: displacement (m)" : "k: постоянная пружины (Н/м), х: смещение (м) ",
"A mass suspended by a spring" : "Масса удерживаемая пружиной ",
"FORCE OF FRICTION" : "Сила трения ",
"μ: coefficient of friction, N: normal force" : "μ: коэффициент трения, N: нормальная сила (сила реакции опоры)  ",
"3. STATICS" : "3. Статика ",
"MOMENT OF A FORCE" : "Момент силы ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: приложенная сила (H), d: плечо силы (перпендикулярное расстояние от оси до линии действия силы) ",
"MOMENT APPLICATION" : "Применение Момента",
"MOMENT OF INERTIA" : "Момент инерции ",
"Rod of length l" : "Штанга длины l",
"Thin circular hoop/ Thin cylindrical shell" : "Тонкий круговой обруч/тонкой цилиндрической оболочки ",
"Solid disk/ Solid cylinder" : "Сплошной диск/Сплошной цилиндр ",
"Solid ball" : "Твердые мяч ",
"Hollow sphere" : "Полая сфера",
"ANGULAR MOMENTUM" : "Угловой момент ",
"I: moment of inertia, ω: angular velocity" : "I: момент инерции, ω: угловая скорость",
"PLANE MOTION OF A RIGID BODY" : "Плоского движения твердого тела ",
"γ: angular acceleration, M: moment of a force" : "γ: угловое ускорение, M: Момент силы ",

"4. CONSERVATION LAWS" : "4. Законы сохранения ",
"MOMENTUM OF FORCE" : "Импульс силы ",
"LAW OF CONSERVATION OF MOMENTUM" : "Закон сохранения импульса ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: начальные скорости тел 1 и 2; v₁', v₂': конечные скорости тел 1 и 2 ",
"PLASTIC COLLISION" : "Неупругие столкновения",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': скорость системы двух тел (m₁ + m₂) после удара ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Одномерное упругое столкновение ",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': скорости m₁ и m₂ после удара ",
"5. WORK AND ENERGY" : "5. Работа и энергия ",
"WORK" : "Работа ",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: работа, совершенная силой (J), F: сила смещающая объект на расстояние s, α: угол между F и направлением движения ",
"EXAMPLES" : "Примеры",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: работа под действием силы тяжести, h: изменение высоты; W_ms: работа силы трения в; W: работа пружины ",
"POWER" : "Мощность ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: мощность (Ватт, Вт), t: время совершения работы W (с)",
"KINETIC ENERGY" : "Кинетическая энергия ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Кинетическая энергия массивного вращающегося тела ",
"WORK-ENERGY PRINCIPLE" : "Принцип работы-энергии ",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: скорости объекта до и после изменения ",
"POTENTIAL ENERGY" : "Потенциальная энергия ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: гравитационная потенциальная энергия (Дж), m: масса тела (кг) ",
"CONSERVATION OF MECHANICAL ENERGY" : "Сохранение механической энергии ",
"CONSERVATION OF ENERGY" : "Сохранение энергии",
"6. MECHANICS OF FLUIDS" : "6. Механика жидкостей ",
"DENSITY" : "Плотность",
"m: mass of a volume V" : "m: масса объема V ",
"PRESSURE" : "Давление ",
"F: force applied on area of A" : "F: сила, приложенная к площади А",
"PRESSURE OF LIQUIDS" : "Давление жидкостей ",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: удельный вес (Н/м³), p_o: давление воздуха на свободной поверхности (Н/м²), p: давление, создаваемое весом жидкости сверху, p_B: общее давление на глубине h ",
"PASCAL’S PRINCIPLE" : "Принцип Паскаля ",
"p_s: pressure on the surface" : "p_s: давление на поверхность ",
"APPLICATION" : "Применение ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: площадь малого и большого цилиндров; F₁, F₂: приложенные силы",
"ARCHIMEDES’ PRINCIPLE" : "Принцип Архимеда ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: удельный вес жидкости (H/м³), V: объем тела, F_b: выталкивающая сила ",
"FLOW RATE" : "Скорость потока",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "А: Площадь поперечного сечения (м²), v: скорость течения (м/с), Q: скорость потока (м³/с) ",

"1. ELECTROSTATICS" : "1. Электростатика ",
"COULOMB’S LAW" : "Закон Кулона ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: величина зарядов (Кл), ε: относительная диэлектрическая проницаемость (в вакууме ε = 1), г: расстояние между зарядами (м) ",
"ELECTRIC FIELDS" : "Электрические поля ",
"E: electric field strength (N/C)" : "E: напряженность электрического поля (Н/Кл) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Принцип суперпозиции для электрических полей ",
"In case of 2 electric fields" : "Случай 2 электрических полей ",
"WORK OF ELECTRIC FORCE" : "Работа электрической силы ",
"ELECTRIC POTENTIAL DIFFERENCE" : "Разность электрических потенциалов ",
"RELATION BETWEEN E AND U" : "Связь между Е и U ",
"CAPACITANCE" : "Емкость ",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "С: емкость (Ф), Q: суммарный электрический заряд (Кл), U: электрический потенциал (В) ",
"CAPACITOR" : "Конденсатор ",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: площадь каждой электродной пластины (м²), d: расстояние между электродами (м), ε: относительная диэлектрическая проницаемость (Ф/м) ",
"CAPACITANCES IN SERIES" : "Конденсаторы в цепочке ",
"CAPACITANCES IN PARALLEL" : "Конденсаторы в параллели (Параллельной соединение конденсаторов)",
"ELECTRIC FIELD ENERGY" : "Энергияэлектрического поля ",
"ENERGY OF CAPACITOR" : "Энергия конденсатора ",
"V=A.d: volume between two electrode plates" : "V = A.d: объем между двумя плоскими электродами",
"2. DIRECT CURRENT" : "2. Постоянный ток",
"ELECTRIC CURRENT" : "Электрический ток ",
"I: current (A), q: charge (C), t: time" : "I: ток (А),q: заряд (Кл), t: время ",
"OHM’S LAW" : "Закон Ома ",
"U: electric potential difference between the ends of the resistor R" : "U: разность электрических потенциалов на концах резистора R",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Работа совершенная током (Закон Джоуля) ",
"ELECTRICAL POWER" : "Электрическая мощность ",
"RESISTANCE" : "Сопротивление ",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: сопротивление материала (Ом · м), l: длина (м), A: площадь поперечного сечения (м²) ",
"SERIES CIRCUITS" : "Последовательные схемы",
"PARALLEL CIRCUITS" : "Параллельные схемы",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Работа или тепловая энергия, выделенная на резистор ",
"POWER CONSUMPTION OF A RESISTOR" : "Потребляемая мощность резистора ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Электродвижущая сила электрического генератора",
"W: work of force (J), q: charge (C)" : "W: работа силы (Дж), q: заряд (Кл) ",
"GENERATORS IN SERIES" : "Генераторы в цепочке",
"r: internal resistance of the generator" : "r: внутреннее сопротивление генератора ",
"GENERATORS IN PARALLEL" : "Параллельное соединение генераторов",
"GENERATORS IN SERIES-PARALLEL" : "Смешанное соединение генераторов",
"WORK AND POWER OF GENERATOR" : "Работа и мощность генератора ",
"H: Efficiency of generator" : "H: Эффективность генератора ",
"3. MAGNETISM" : "3. Магнетизм",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Магнитный поток через открытую поверхность S ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: величина магнитного поля (Т, тесла), α: угол между B и нормалью к поверхности S",
"MAGNETIC FORCES ON MOVING CHARGES" : "Магнитныевоздействия на движущиеся заряды ",
"v: velocity of the charge (m/s)" : "v: скорость заряда (м/с) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "Сила действующая на проводник с током",
"I: current (A), l: length of the wire (m)" : "I: ток (А), l: длина провода (м) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Силы между 2 параллельными токоведущими проводами ",
"r: distance between two wires (m)" : "r: расстояние между двумя проводами (м) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Магнитное поле длинного токоведущего провода ",
"r: perpendicular distance from the center of the wire (m)" : "r: перпендикулярное расстояние от центра провода (м) ",
"MAGNETIC FIELD OF A LOOP" : "Магнитное поле витка",
"n: number of turns per unit length of solenoid (turns/m)" : "n: число витков на единицу длины соленоида (​​об/м) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Индуцированная электродвижущая сила - Закон Фарадея",
"N: numbers of turns per loop (turns/m)" : "N: количество витков для петли (об/м) ",
"INDUCTANCE" : "Индуктивность ",
"ELECTRIC ENERGY" : "Электрическая энергия ",
"MAGNETIC ENERGY" : "Магнитная энергия ",
"ELECTRIC-MAGNETIC ENERGY" : "Электромагнитная энергия ",
"4. ALTERNATING CURRENT" : "4. Переменный ток",
"BASIC PARAMETERS" : "Основные параметры ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: мгновенный ток (A), I_o: максимум мгновенного значения тока (А), T: период волны, f: частота, λ: длина волны, с: скорость света ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Эффективный ток и напряжение",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Закон Ома для переменного тока, в цепи , содержащей только сопротивление R",
"CONTAINING ONLY INDUCTOR L" : "Cодержащей только  индуктивность L ",
"Z_L: inductive reactance" : "Z_L: индуктивное сопротивление ",
"CONTAINING ONLY CAPACITOR C" : "Cодержащей только  емкость C",
"Z_C: capacitive reactance" : "Z_C: емкостное сопротивление ",
"CONTAINING R, L AND C IN A SERIES" : " Последовательная цепь содержащая R, L и C ",
"Z: impedance" : "Z: импеданс",
"PHASE ANGLE" : "Фазовый угол",
"POWER FACTOR" : "Коэффициент мощности",
"REAL POWER" : "Реальная мощность",
"ELECTRICAL RESONANCE" : "Электрический резонанс ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Изменение напряжения в трансформаторах ",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: число витков в первичной обмотке и вторичной обмотке; U₁, U₂: первичное и вторичное напряжения; I₁, I₂: первичные и вторичные токи ",

"1. GAS LAWS" : "1. Газовые Законы ",
"KELVIN TEMPERATURE" : "Температура Кельвина ",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "Т: температура по шкале Кельвина, t: температура по шкале Цельсия",
"EQUATION OF STATE" : "Уравнение состояния ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: давление (П, Паскаль), V: объем (м³), n: число молей газа (моль), R: универсальная газовая постоянная, Т: температура газа по шкале Кельвина (K), k: постоянная Больцмана, N: число молекул в газе ",
"IDEAL GAS LAW" : "Идеальн газовый закон ",
"BOYLE’S LAW FOR PRESSURE" : "Закон Бойля для давления ",
"If the temperature of the gas is constant" : "Если температура газа постоянна ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Закон Гей-Люссака Давление-Температра",
"If the volume on a gas is constant" : "Если объем газа постоянный ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: давление газа при температуре t, p_o: давление при 0 по Цельсию, γ: коэффициент, когда объем является постоянной (термический коэффициент давления)",
"Example when t=0 Kelvin" : "Пример, когда t=0 Кельвин",
"CHARLES'S LAW OF VOLUMES" : "Закон Чарльза для объемов ",
"If the pressure on a gas is constant" : "Если давление на газ постоянное ",
"2. CHANGES OF STATE AND SHAPE" : "2. Изменения состояния и формы ",
"HEAT" : "Тепло",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: испускаемое тепло, Q_r: поглощаемое тепло, m: общая масса объекта (кг), с: теплоемкость (Дж/кг.К), ∆t: изменение температуры (K) ",
"The specific heats of some materials" : "Теплоемкости некоторых материалов ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Сплавление (замораживание или затвердевание) ",
"Heat of fusion of some materials" : "Теплота плавления некоторых материалов ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: количество тепла (Дж), λ: теплота плавления (Дж/кг), m: масса (кг) ",
"VAPORIZATION" : "Испарение ",
"L: heat of vaporization" : "L: теплота парообразования ",
"Heat of vaporization of some materials" : "Теплотапарообразования некоторых материалов ",
"LINEAR EXPANSION" : "Линейное расширение ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: начальная длина (м), α: коэффициент линейного расширения (K⁻¹), ∆t: изменение температуры ",
"VOLUME EXPANSION" : "Увеличение объема",
"AREA EXPANSION" : "Увеличение площади",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Изменение плотности (объемная плотность) ",
"D_o: original density (kg/m³)" : "D_o: начальная плотность (кг/м³) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Изменение диаметра поперечного сечения твердого вещества ",
"3. THERMODYNAMICS" : "3. термодинамика ",
"THE FIRST LAW OF THERMODYNAMICS" : "Первый закон термодинамики ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "∆U: изменение внутренней энергии (Дж), W: работа совершенная системой (Дж), Q: тепло сообщенное системе или взятое из системы ",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Применение первого закона к идеальным газовым законам ",
"- Volume is constant" : "- Постоянный объем",
"- Pressure is constant, W': work created by gas" : "- Постоянное давление, W' работа совершенная газом",
"- Temperature is constant" : "- Постоянная температура",
"THE SECOND LAW OF THERMODYNAMICS" : "Второй закон термодинамики ",
"- The efficiency of a cyclic heat engine" : "- Коэффициент полезного действия циклического теплового двигателя",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': работа осуществляемая за цикл (J), Q₁: тепло, поглощенное за цикл от высокой температуры (J), Q₂': Отвод тепла за цикл к более низкой температуре (J) ",
"- Maximum thermal efficiency" : "- Максимальный коэффициент полезного действия ",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: более высокие и более низкие температуры ",

"1. SIMPLE HARMONIC MOTION" : "1. Простые гармонические колебания ",
"SPRING" : "Пружина",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: постоянная жесткости (Н/м), s: смещение (м), ω: угловая скорость (рад/с), T: период (c), m: масса тела, А: амплитуда (м)",
"SPRINGS IN SERIES" : "Пружины в цепочке ",
"k: spring constant of the system, T: period of the system" : "k: постоянная жесткости системы, T: период системы ",
"SPRINGS IN PARALLEL" : "Пружины (соединенные) параллельно ",
"SIMPLE PENDULUM" : "Математический маятник",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: угловая скорость (рад/с), Т: период (c), α_o: угол в амплитуде (рад), А: амплитуда (м), l: длина маятника (м)",
"MOTION EQUATIONS" : "Уравнения движения ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: смещение, α: угол, v: скорость, T: сила натяжения стержня ",
"ENERGY" : "Энергия",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: потенциальная энергия, E_k: кинетическая энергия, E: механическая энергия",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Изменение периода, следующего за изменением температуры ",
"α: coefficient of linear expansion of the rod" : "α: коэффициент линейного расширения стержня ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Изменение периода, следующего за изменением высоты ",
"h: height of pendulum, R: Earth's radius" : "h: высота маятника, R: радиус Земли ",
"PENDULUM" : "Физический маятник",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: момент инерции, ω: угловая скорость, m: масса боба, d: OG, T: период ",
"2. PERIODIC MOTION" : "2. Периодическое движение",
"WAVELENGTH" : "Длина волны ",
"FUNCTION OF WAVE AT SOME POINTS" : "Функция волны в некоторых точках ",
"WAVE INTERFERENCE" : "Волновая интерференция",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 источники волн, имеющие одинаковую фазу; М: случайная точка",
"3. SOUND WAVES" : "3. Звуковые волны ",
"SOUND SPEED" : "Скорость звука ",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (м/с): скорость звука в среде с температурой Т (по Цельсию) ",
"SOUND INTENSITY " : "интенсивность звука ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: звуковая энергия (Дж), P: звуковая мощность (Вт), A: площадь поверхности сферы (м²), t: время (c)",
"SOUND INTENSITY LEVEL" : "Уровень интенсивности звука ",
"I_o: the standard reference sound intensity" : "I_o: стандартный эталон интенсивности звука ",
"THE DOPPLER EFFECT" : "Эффект Доплера ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: относительная скорость наблюдателя; v_S: относительная скорость источника; v: скорость звука в этой среде; f_S, f_O: частота звука от источника и наблюдателя ",
"SOUND SPEED IN GASES" : "Скорость звука в газах ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: скорость звука (м/с), R: универсальная газовая постоянная, T: абсолютная температура (К), М: молекулярная масса газа (кг/моль), γ: адиабатическая константа",
"Example in air" : "Пример в воздухе ",

"1. GEOMETRIC OPTICS" : "1. Геометрическая оптика",
"LAWS OF REFLECTION" : "Законы отражения ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: падающий луч, IR: отраженный луч, i: угол падения, i': угол отражения ",
"REFRACTIVE INDEX" : "Показатель преломления ",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: показатель преломления среды, v: скорость света в среде, c: скорость света в вакууме (м/с) ",
"LAW OF REFRACTION" : "Закон преломления ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: показатель преломления среды 1, n₂: показатель преломления среды 2, i: угол падения, r: угол преломления, n₂₁: абсолютный показатель преломления ",
"If medium 1 is vacuum" : "Если среда 1 - вакуум",
"TOTAL REFLECTION PHENOMENON" : "Явление полного отражения ",
"There is no refracted ray if" : "Не существует преломленного луча, если",
"PRISM" : "Призма ",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: Угол при вершине, D: угол отклонения, i₁: угол падения, i₂: угол выходящего луча ",
"- Condition to have refractive ray" : "- Условие наличия преломленного луча",
"- When angle of incidence is minimum" : "- Когда угол падения минимальный",
"THIN LENS" : "Тонкие линзы",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: фокусное расстояние (собирающие линзы f&gt;0; рассеивающие линзы f&lt;0), d: расстояние до объекта от центра линзы, d': расстояние изображения от центра линзы ",
"MAGNIFICATION FACTOR" : "коэффициент увеличения",
"h_I: image height, h_O: object height" : "h_I: высота изображения, h_O: высота объекта ",
"POWER OF THE LENS" : "Сила линз",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: показатель преломления материала линз, R₁: радиус кривизны поверхности линзы ближайшей к источнику света, R₂: радиус кривизны поверхности линзы дальней от источника света ",
"2. QUANTUM OF LIGHT" : "2. Квант света ",
"PHOTON ENERGY" : "Энергия фотонов",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: постоянная Планка, f: частота (Гц), λ: длина волны (м), с: скорость света ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Условие наличия  фотоэлектрический эффект ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: длина волны излучаемого света, λ_o: фотоэлектрический предел (красная граница фотоэффекта), W: излучаемая работа (J) ",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Уравнение Эйнштейна о фотоэлектрическом эффекте",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: масса фотоэлектрона (кг), v_o: максимальная скорость фотоэлектрона (м/с) ",

"1. THEORY OF RELATIVITY" : "1. Теория относительности ",
"MASS–ENERGY EQUIVALENCE" : "Эквивалентности массы и энергии ",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: масса (кг), E: энергия тела (Дж), c: скорость света  (м/с) ",
"LENGTH CONTRACTION" : "Сокращение длины ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: реальная длина объекта, l: длина наблюдаемая наблюдателем, движущимся со скоростью V",
"RELATIVISTIC MASS" : "Релятивистская масса ",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: масса покоя, m: релятивистская масса тела, когда оно смещается со скоростью v ",
"TIME DILATION" : "Замедление времени ",
"2. ATOMIC NUCLEUS" : "2. Атомное ядро ",
"NUCLEAR MAKEUP" : "Состав ядра",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: число протонов, N: число нейтронов, А: массовое число ",
"NUCLEAR REACTION" : "Ядерная реакция ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: ядерная реакция высвобождает энергию",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: ядерная реакция поглощает энергию",
"RADIOACTIVE DECAY" : "Радиоактивный распад ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: начальное количество активного вещества, N: количество, что до сих пор остается и еще не распался за временя t, ΔN: количество распавшегося вещества, m_o: начальная масса, m: оставшаяся масса, λ: постоянная распада, t: время, Т: период полураспада ",
"Half life of some elements" : "Период полураспада  некоторых элементов ",
"AMOUNT OF RADIOACTIVITY" : "Количество радиоактивности ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: начальное количество радиоактивности, H: Количество радиоактивности в момент времени t ",
"1. CONSTANTS" : "1. константы ",
"ALPHA PARTICLE MASS" : "Масса альфа частицы ",
"ATOMIC MASS CONSTANT" : "Постоянная атомной массы",
"ATOMIC UNIT OF ENERGY" : "Атомная единица энергии ",
"ATOMIC UNIT OF FORCE" : "Атомная единица силы ",
"ATOMIC UNIT OF LENGTH" : "Атомная единица длины ",
"ATOMIC UNIT OF MASS" : "Атомная единица массы",
"AVOGADRO'S CONSTANT" : "Постоянная Авогадро ",
"BOHR RADIUS" : "Боровский радиус",
"BOLTZMANN CONSTANT" : "Постоянная Больцмана ",
"CLASSICAL ELECTRON RADIUS" : "Классический радиус электрона ",
"ELEMENTARY CHARGE" : "Элементарный заряд ",
"EARTH MASS" : "Масса Земли",
"EARTH EQUATORIAL RADIUS" : "Экваториальный радиус Земли",
"EARTH MEAN ORBITAL VELOCITY" : "Значение орбитальной скорости Земли",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Угловая скорость вращения Земли",
"FARADAY’S CONSTANT" : "Постоянная Фарадея ",
"GAS CONSTANT" : "Газовая постоянная ",
"MOLAR MASS CONSTANT" : "Постоянная молекулярной массы ",
"MOLAR VOLUME OF IDEAL GAS" : "Молярный объем идеального газа ",
"NEUTRON MASS" : "Масса нейтрона ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Гравитационная константа ",
"PLANCK’S CONSTANT" : "Постоянная Планка ",
"PLANCK MASS" : "Масса Планка ",
"PROTON MASS" : "Масса протона ",
"PROTON-ELECTRON MASS RATIO" : "Отношение масс протон-электрон ",
"SPEED OF LIGHT IN VACUUM" : "Скорость света в вакууме ",
"STANDARD ACCELERATION OF GRAVITY" : "Стандарт ускорения силы тяжести ",
"STANDARD ATMOSPHERE" : "Нормальное значение атмосферного давления",
"STANDARD REFERENCE SOUND INTENSITY" : "Стандартные показания интенсивности звука ",
"STEFAN-BOLTZMANN CONSTANT" : "Постоянная Стефана-Больцмана ",
"2. GREEK ALPHABET" : "2. Греческий алфавит ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: греческая буква, C2: Назваание, C3: Эквивалент, C4: Звук при произношении ",

"Mechanics" : "Механика",
"Thermal physics" : "Теплофизика",
"Optics" : "Оптика ",
"Theory of relativity" : "Теория относительности",

"FREE FALLING" : "Свободное падение ",
"VERTICAL PROJECTILE" : "Вертикальное метание",
"ANGLED PROJECTILE" : "Движение тела под углом к горизонту",
"HORIZONTAL PROJECTILE" : "Горизонтальное метание",
"SLIDING MOTION" : "Скользящее движение",
"ATTRACTIVE FORCE" : "Сила притяжения",
"Hydraulic press" : "Гидравлическое давление",
"PRESSURE" : "Давление ",
"LINEAR EXPANSION" : "Линейное расширение ",
"VOLUME EXPANSION" : "Увеличение объема",
"SOUND SPEED" : "Скорость звука ",
"REFRACTION" : "Преломление ",
"PRISM" : "Призма ",
"LENS" : "Линзы",
"Length contraction" : "Сокращение длины ",
"Time dilation" : "Замедление времени ",
"RELATIVISTIC MASS" : "Релятивистская масса ",

"Height " : "Высота",
"Time to touchdown " : "Время до приземления ",
"Touchdown velocity " : "Скорость приземления ",
"Initial velocity " : "Начальная скорость ",
"Maximum height " : "Максимальная высота ",
"Initial velocity " : "Начальная скорость ",
"Angle " : "Угол ",
"Maximum height " : "Максимальная высота ",
"Maximum distance " : "Максимальное расстояние ",
"Height " : "Высота",
"Initial velocity " : "Начальная скорость ",
"Time to touchdown " : "Время до приземления ",
"Touchdown velocity " : "Скорость приземления ",
"Angle of titled plane " : "Угол наклона плоскости ",
"Coefficient of friction " : "Коэффициент трения ",
"Acceleration " : "Ускорение ",
"Mass " : "Масса ",
"Mass " : "Масса ",
"Distance " : "Расстояние ",
"Attractive force " : "Сила притяжения",
"Area " : "Площадь ",
"Area " : "Площадь ",
"Force " : "Сила",
"Force" : "Сила",
"Force F₂ (or F₁)" : "Сила F₂ (или F₁) ",
"Temperature " : "Температура ",
"Pressure at 0°C " : "Давление при 0°C ",
"Pressure " : "Давление ",
"Original length " : "Исходная длина ",
"Temperature change " : "Изменение температуры ",
"Coefficient of linear expansion " : "Коэффициент линейного расширения ",
"Change of length " : "Изменение длины ",
"Original volume " : "Исходный объем ",
"Temperature change " : "Изменение температуры ",
"Coefficient of linear expansion " : "Коэффициент линейного расширения ",
"Change of volume " : "Изменение объема ",
"Temperature " : "Температура ",
"Sound speed " : "Скорость звука ",
"Refractive index " : "Показатель преломления ",
"Refractive index " : "Показатель преломления ",
"Angle of incidence " : "Угол падения ",
"Angle of refraction " : "Угол преломления ",
"Angle (r or i) " : "Угол (r или i) ",
"Apex angle " : "Угол при вершине",
"Angle of incident " : "Угол падения ",
"Refractive index " : "Показатель преломления ",
"Angle of emergent ray " : "Угол выходящего луча ",
"Deviation angle " : "Угол отклонения ",
"Focal length " : "Фокусное расстояние ",
"Object distance " : "Расстояние до предмета",
"Image distance " : "Расстояние до изображения",
"Image (or object) distance" : "Расстояние  до изображения (или предмета)",
"Magnification factor " : "Коэффициент увеличения ",
"Speed " : "Скорость ",
"Proper length " : "Правильное расстояние ",
"Observed length " : "Наблюдаемая длина ",
"Rest mass " : "Масса покоя ",
"Relativistic mass " : "Релятивистская масса ",
"Proper time interval " : "Действительный интервал времени ",
"Observed time interval " : "Наблюдаемый интервал времени ",
"Calculate" : "Рассчитать ",
"Or input" : "Или вход ",
"Calculation Tools" : "Инструменты для расчета",


};