var language={

	
"1. DYNAMICS" : "1.動力學",
"STRAIGHT LINE MOTION" : "直線運動",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s：距離（m），t：時間（s，秒），v：速度（m/s），v_a：平均速度",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "勻變速直線運動",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a:加速度，v_o:初速度，v：t時刻的速度",
"DISTANCE FUNCTION" : "距離函數",
"x_o: initial distance from origin, x: distance at time t" : "x_o：初始距離，x：在時間t內的運動距​​離",
"UNIFORM CIRCULAR MOTION" : "勻速圓周運動",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ：角（弧度），l：弧長，R：圓的半徑，ω：角速度（弧度/秒），t:通過弧長l所用的時間",
"CENTRIPETAL FORCE" : "向心力",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f：頻率（Hz），T：運動一周所需的時間，即周期（s），a：向心加速度，F：向心力（N，牛頓）",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "勻加速圓周運動",
"γ: angular acceleration" : "γ：角加速度",
"ACCELERATION" : "加速度",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t:切向加速度， a_n:法向加速度",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1：加速，P2：勻速圓周運動，P3：減速",
"FREE FALLING FROM HEIGHT h" : "從高度h處自由下落",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g：重力加速度，v：t時刻的速度，s:t時刻時下落的距離，v_h:接觸地面時的速度，t_h:下落的時間",
"VERTICAL PROJECTILE MOTION" : "豎直上拋運動",
"h_max: maximum height, v_o: initial velocity" : "h_max：物體向上運動的最大高度， v_o:初速度",
"Motion equation and velocity equation" : "運動方程和速度方程",
"ANGLED PROJECTILE MOTION" : "斜拋運動",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x，v_y：速度；x,y:關於時間t的運動方程；H：最大高度；L：最大距離",
"HORIZONTAL PROJECTILE MOTION" : "平拋運動",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h:落地所用時間， v_h:落地時速度",
"SLIDING MOTION ON AN INCLINED PLANE" : "在斜面上滑動",
"μ: coefficient of friction" : "μ：摩擦係數",
"Fiction coefficient of some materials" : "某些材料的摩擦係數",
"2. FORCES" : "2. 力",
"ATTRACTIVE FORCE" : "引力",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂:兩物體的質量；r：兩個物體之間的距離；G：萬有引力常數",
"GRAVITATIONAL FORCE" : "萬有引力",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M：地球質量，m：物體的質量，R：地球半徑，h：物體的高度",
"GRAVITATIONAL ACCELERATION" : "重力加速度",
"At a height h above the nominal surface of the earth" : "在地球表面上高度為h的地方",
"Near the sea level" : "貼近海平面",
"FORCE OF GRAVITY" : "重力",
"Force of gravity on earth, a special case of Gravitational force" : "重力，萬有引力的一個特殊情況",
"NEWTON'S FIRST LAW" : "牛頓第一定律",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F：作用在物體上的力（N），v：物體的速度，a：物體的加速度",
"NEWTON'S SECOND LAW" : "牛頓第二定律",
"m: object's mass (kg)" : "m：物體的質量（kg）",
"NEWTON'S THIRD LAW" : "牛頓第三定律",
"LINEAR ELASTICITY - HOOKE'S LAW" : "彈性力學 - 胡克定律",
"k: spring constant (N/m), x: displacement (m)" : "k:彈簧常數（N/m)，x：位移(m)",
"A mass suspended by a spring" : "彈簧上懸掛物體",
"FORCE OF FRICTION" : "摩擦力",
"μ: coefficient of friction, N: normal force" : "μ：摩擦係數，N：法向力",
"3. STATICS" : "3. 靜力學",
"MOMENT OF A FORCE" : "力矩",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F：使用的力的大小（N），d：力臂（從著力點到力的作用線的垂直距離)",
"MOMENT APPLICATION" : "重要應用",
"MOMENT OF INERTIA" : "轉動慣量",
"Rod of length l" : "長度為l的桿",
"Thin circular hoop/ Thin cylindrical shell" : "薄圓環/薄圓柱環",
"Solid disk/ Solid cylinder" : "圓盤/圓柱體",
"Solid ball" : "實心球",
"Hollow sphere" : "球殼",
"ANGULAR MOMENTUM" : "角動量",
"I: moment of inertia, ω: angular velocity" : "I：轉動慣量，ω：角速度",
"PLANE MOTION OF A RIGID BODY" : "剛體平面運動",
"γ: angular acceleration, M: moment of a force" : "γ：角加速度，M：瞬時力",

"4. CONSERVATION LAWS" : "4. 守恆定律",
"MOMENTUM OF FORCE" : "動量",
"LAW OF CONSERVATION OF MOMENTUM" : "動量守恆定律",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁，v₂：物體1和2的初始速度；v₁'，v₂'：物體1和2的最終速度",
"PLASTIC COLLISION" : "完全非彈性彈性碰撞",
"v': velocity of the two body system (m₁+m₂) after impact" : "v'：碰撞之後的兩體系統（m₁+m₂）的速度",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "一維完全彈性碰撞",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁'，v₂'：碰撞之後m₁和m₂的速度",
"5. WORK AND ENERGY" : "5. 功及能量",
"WORK" : "功",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W：力所做的功（J），F：移動物體距離S時所用的力，α：F和運動方向之間的夾角",
"EXAMPLES" : "示例",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p：重​​力所做的功，h：高度的變化； W_ms：摩擦力做的功； W：彈簧所做的功",
"POWER" : "功率",
"P: power (watt, W), t: time of conducting the work W (s)" : "P：功率（瓦特, W），t：做功的時間（s）",
"KINETIC ENERGY" : "動能",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "旋轉體的轉動動能",
"WORK-ENERGY PRINCIPLE" : "功-能原理",
"v₁, v₂: speeds of object before and after the change" : "v₁，v₂：對像變化前後的速度",
"POTENTIAL ENERGY" : "勢能",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p：重力勢能（J），m：物體質量（kg）",
"CONSERVATION OF MECHANICAL ENERGY" : "機械能守恆",
"CONSERVATION OF ENERGY" : "能量守恆",
"6. MECHANICS OF FLUIDS" : "6. 流體力學",
"DENSITY" : "密度",
"m: mass of a volume V" : "m：體積為V的物體質量",
"PRESSURE" : "壓力",
"F: force applied on area of A" : "F：對面積為A所施加的力",
"PRESSURE OF LIQUIDS" : "液體內的壓強",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d：比重（N/m³），p_o：表面空氣壓強(N/m²)，p：因為液體重力產生的壓強，p_B:在深度h處的總壓強",
"PASCAL’S PRINCIPLE" : "帕斯卡原理",
"p_s: pressure on the surface" : "p_s：表面壓強",
"APPLICATION" : "應用",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁，A₂：小活塞和大活塞的面積； F₁，F₂：對小活塞施加的力和大活塞收受到的向上的力量",
"ARCHIMEDES’ PRINCIPLE" : "阿基米德定律",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d：液體比重（N/m³），V：物體體積，F_b：浮力",
"FLOW RATE" : "流量",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A：截面積（m²），v：流速（m/s），Q：流量（m³/s）",

"1. ELECTROSTATICS" : "1. 靜電",
"COULOMB’S LAW" : "庫侖定律",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q：電荷的大小（C），ε：介電常數（真空中ε=1），r：兩個電荷之間的距離（m）",
"ELECTRIC FIELDS" : "電場",
"E: electric field strength (N/C)" : "E：電場強度（N/C）",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "電場疊加原理",
"In case of 2 electric fields" : "兩個電場的疊加的情形",
"WORK OF ELECTRIC FORCE" : "電場力的功",
"ELECTRIC POTENTIAL DIFFERENCE" : "電勢差",
"RELATION BETWEEN E AND U" : "E和U的關係",
"CAPACITANCE" : "電容",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C：電容(F)，Q：總電荷(C)，U：電勢(V)",
"CAPACITOR" : "電容",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A：電極板的面積（m²），d：電極之間的距離(m)，ε:介電常數（F/m）",
"CAPACITANCES IN SERIES" : "電容的串聯",
"CAPACITANCES IN PARALLEL" : "電容的並聯",
"ELECTRIC FIELD ENERGY" : "電場能量",
"ENERGY OF CAPACITOR" : "電容器的能量",
"V=A.d: volume between two electrode plates" : "V=A.d:兩個電極板之間的體積",
"2. DIRECT CURRENT" : "2.直流電",
"ELECTRIC CURRENT" : "電流",
"I: current (A), q: charge (C), t: time" : "I：電流（A），q：電荷（C），t：時間",
"OHM’S LAW" : "歐姆定律",
"U: electric potential difference between the ends of the resistor R" : "U：電阻R的兩端之間的電勢差",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "電流所做的功",
"ELECTRICAL POWER" : "電源",
"RESISTANCE" : "電阻",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ：材料的電阻率（Ωm）， l：長度（m），A：材料的橫截面面積（m²）",
"SERIES CIRCUITS" : "串聯電路",
"PARALLEL CIRCUITS" : "並聯電路",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "由電阻產生的功或熱能",
"POWER CONSUMPTION OF A RESISTOR" : "一個電阻的能量消耗",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "發電機的電動勢",
"W: work of force (J), q: charge (C)" : "W：力所做的功（J），q：電荷（C）",
"GENERATORS IN SERIES" : "發電機",
"r: internal resistance of the generator" : "r：在發電機的內阻",
"GENERATORS IN PARALLEL" : "發電機的並聯",
"GENERATORS IN SERIES-PARALLEL" : "發電機的串並聯",
"WORK AND POWER OF GENERATOR" : "發電機的功和功率",
"H: Efficiency of generator" : "H：發電機的效率",
"3. MAGNETISM" : "3.磁",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "通過非閉合曲面S的磁通量",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B：磁場的大小（T，特斯拉）α：磁場和曲面S的法線之間的夾角",
"MAGNETIC FORCES ON MOVING CHARGES" : "運動電荷所受到的磁力",
"v: velocity of the charge (m/s)" : "v：電荷運動速度（m/s）",
"FORCE ON A CURRENT-CARRYING WIRE" : "通電導線的受力",
"I: current (A), l: length of the wire (m)" : "I：電流（A）, l：線長（m）",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "在兩平行通電導線之間的力",
"r: distance between two wires (m)" : "r：兩電線之間的距離(m)",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "長通電導線的磁場",
"r: perpendicular distance from the center of the wire (m)" : "r:距離導線中心的垂直距離(m)",
"MAGNETIC FIELD OF A LOOP" : "通電線圈的磁場",
"n: number of turns per unit length of solenoid (turns/m)" : "n:單位長度通電螺線管的匝數（匝/m）",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "感應電動勢 - 法拉第定律",
"N: numbers of turns per loop (turns/m)" : "N:感應線圈的匝數；導線環繞物體的圈數（匝/m）",
"INDUCTANCE" : "電感",
"ELECTRIC ENERGY" : "電能",
"MAGNETIC ENERGY" : "磁能",
"ELECTRIC-MAGNETIC ENERGY" : "電磁能",
"4. ALTERNATING CURRENT" : "4.交流電",
"BASIC PARAMETERS" : "基本參數",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i：瞬時電流（A），I_o：最大瞬時電流（A），T：週期波，f：頻率，λ：波長，c：光速",
"EFFECTIVE CURRENT AND VOLTAGE" : "有效的電流和電壓",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "交流電流​​的歐姆定律只包含電阻R",
"CONTAINING ONLY INDUCTOR L" : "只含有電感器L",
"Z_L: inductive reactance" : "Z_L：感抗",
"CONTAINING ONLY CAPACITOR C" : "只含有電容C",
"Z_C: capacitive reactance" : "Z_C：容抗",
"CONTAINING R, L AND C IN A SERIES" : "含R，L和C的串聯",
"Z: impedance" : "Z：阻抗",
"PHASE ANGLE" : "相位角",
"POWER FACTOR" : "功率因數",
"REAL POWER" : "實際功率",
"ELECTRICAL RESONANCE" : "電氣共振",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "變壓器改變電壓",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁，N₂：初級線圈和次級線圈的匝數數目； U₁，U₂：初級和次級電壓；I₁，I₂：初級和次級電流",

"1. GAS LAWS" : "1.氣體定律",
"KELVIN TEMPERATURE" : "開爾文溫度",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T：開氏溫度，即為熱力學溫度，t：攝氏溫度",
"EQUATION OF STATE" : "狀態方程",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p：壓強（P，帕斯卡），V：體積（m³），n：氣體（摩爾）的摩爾數，R：氣體常數，T：氣體的開爾文溫度（K），k:玻爾茲曼常數，N ：在氣體中的分子數",
"IDEAL GAS LAW" : "理想氣體定律",
"BOYLE’S LAW FOR PRESSURE" : "波義耳壓強定律",
"If the temperature of the gas is constant" : "如果氣體的溫度是恆定的",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "蓋 - 呂薩克壓力 - 溫度定律",
"If the volume on a gas is constant" : "如果在氣體的體積是恆定的",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p：溫度t的氣體壓強，p_o：在0攝氏度的壓強，γ：當體積不變的因數",
"Example when t=0 Kelvin" : "例如當t=0 K時",
"CHARLES'S LAW OF VOLUMES" : "查爾斯體積定律",
"If the pressure on a gas is constant" : "如果在氣體中的壓強是恆定的",
"2. CHANGES OF STATE AND SHAPE" : "2.狀態和形狀的變化",
"HEAT" : "熱",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e：熱發射，Q_r：接收的熱量，m：物體的總質量（kg)，c：比熱（J/kg.K），Δt：溫度變化（K）",
"The specific heats of some materials" : "一些材料的比熱",
"FUSION (FREEZING OR SOLIDIFICATION)" : "熔化（凍結或凝固）",
"Heat of fusion of some materials" : "一些材料的溶解熱",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q：熱量（J），λ：熔解熱（J/kg），m：質量（kg）",
"VAPORIZATION" : "汽化",
"L: heat of vaporization" : "L：汽化熱",
"Heat of vaporization of some materials" : "一些材料的汽化熱",
"LINEAR EXPANSION" : "線膨脹",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o：原來長度（m），α：線性膨脹係數（K⁻¹），Δt：溫度變化",
"VOLUME EXPANSION" : "體積膨脹",
"AREA EXPANSION" : "面積擴大",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "密度改變（體積質量密度）",
"D_o: original density (kg/m³)" : "D_o：原始密度（kg/m³）",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "改變固體的橫截面的直徑",
"3. THERMODYNAMICS" : "3.熱力學",
"THE FIRST LAW OF THERMODYNAMICS" : "熱力學第一定律",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU：內能改變，W：由系統所做的功，Q：系統吸收或放出的熱量",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "第一理想氣體定律的應用",
"- Volume is constant" : "- 體積不變",
"- Pressure is constant, W': work created by gas" : "壓力為常數，W'：由氣體產生的功",
"- Temperature is constant" : "- 溫度是恆定",
"THE SECOND LAW OF THERMODYNAMICS" : "熱力學第二定律",
"- The efficiency of a cyclic heat engine" : "- 循環熱機的效率",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W'：每循環做的功（J），Q₁：每次循環從溫度較高的地方吸收的熱量（J），Q₂'：每個循環向溫度較低的地方排出的熱量（J）",
"- Maximum thermal efficiency" : "- 最大熱效率",
"T₁, T₂: higher and lower temperatures" : "T₁，T₂：更高和更低的溫度",

"1. SIMPLE HARMONIC MOTION" : "1.簡諧運動",
"SPRING" : "彈簧",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k:彈簧常數（N/m），s:位移（m），ω：角速度（rad/s），T：週期，m：質量的物體，A：振幅",
"SPRINGS IN SERIES" : "彈簧系列",
"k: spring constant of the system, T: period of the system" : "k：系統的彈簧常數，T：系統週期",
"SPRINGS IN PARALLEL" : "彈簧的並聯",
"SIMPLE PENDULUM" : "單擺",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω：角速度（rad/s），T：週期，α_o：角幅度，A：振幅，l：鐘擺的長度",
"MOTION EQUATIONS" : "運動方程",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s：位移，α：角，v：速度，T：桿上的力",
"ENERGY" : "能源",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p：勢能，E_k：動能，E：機械能",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "隨溫度的變化產生的周期變化",
"α: coefficient of linear expansion of the rod" : "α：桿的線性膨脹係數",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "高度的變化改變產生的周期變化",
"h: height of pendulum, R: Earth's radius" : "h：擺的高度，R：地球的半徑",
"PENDULUM" : "擺",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I：轉動慣量，ω：角速度，m：擺的質量，d：OG，T：週期",
"2. PERIODIC MOTION" : "2.週期運動",
"WAVELENGTH" : "波長",
"FUNCTION OF WAVE AT SOME POINTS" : "某些點的波函數",
"WAVE INTERFERENCE" : "波的干涉",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁，S₂：兩個波的起源點; M：隨機點",
"3. SOUND WAVES" : "3.聲波",
"SOUND SPEED" : "聲速",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v（m/s）：在溫度t（攝氏）的環境中的聲速",
"SOUND INTENSITY " : "聲音強度",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E：聲音能量（J），P：聲功率（W），A：一個球體的表面面積（m²），t：時間（s）",
"SOUND INTENSITY LEVEL" : "聲強級",
"I_o: the standard reference sound intensity" : "I_o：標準參考聲強",
"THE DOPPLER EFFECT" : "多普勒效應",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O：觀測者的相對運動速度；v_S：源的相對速度；v：在這種介質中的聲速； f_S，f_O：聲源和觀察者的頻率",
"SOUND SPEED IN GASES" : "在氣體中的聲速",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v：聲速(m/s)，R：普遍氣體常數，T：絕對溫度（K），M：氣體分子質量(kg/mol)，γ：絕熱常數",
"Example in air" : "例如在空氣中",

"1. GEOMETRIC OPTICS" : "1，幾何光學",
"LAWS OF REFLECTION" : "反射定律",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI：入射光線，IR：反射光線，i：入射角，i'：反射角",
"REFRACTIVE INDEX" : "折射率",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n：第一個介質的折射率，v： 光在介質中的速度，c：光在真空的速度(m/s)",
"LAW OF REFRACTION" : "折射定律",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁：介質1的折射率，n₂:介質2的折射率，i：入射角角度，r：折射角角度，n₂₁：絕對折射率",
"If medium 1 is vacuum" : "如果介質1是真空",
"TOTAL REFLECTION PHENOMENON" : "全反射現象",
"There is no refracted ray if" : "沒有折射光線",
"PRISM" : "棱鏡",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A：頂角，D：偏差角度，i₁：入射角，i₂：出射角",
"- Condition to have refractive ray" : "- 有折射光線的條件",
"- When angle of incidence is minimum" : "-  當入射角為最小",
"THIN LENS" : "薄透鏡",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f：焦距（凸透鏡f&gt;0;凹透鏡f&lt;0），d:物距，d':像距.",
"MAGNIFICATION FACTOR" : "放大係數",
"h_I: image height, h_O: object height" : "h_I:像的高度，h_O:物的高度",
"POWER OF THE LENS" : "透鏡的功率",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n:透鏡的折射率，R₁:透鏡表面距離光源最近處的曲率半徑，R₂:透鏡表面距離光源最遠處的曲率半徑",
"2. QUANTUM OF LIGHT" : "2.光量子",
"PHOTON ENERGY" : "光子能量",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h：普朗克常數，f：頻率（HZ），λ：波長（m），c：光速",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "條件有光電效應",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ:光的波長，λ_o的：光電子的臨界波長，W：金屬的逸出功（J）",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "光電效應的愛因斯坦方程",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m：光電子質量（kg），v_o：光電子的最大速度（m/s）",

"1. THEORY OF RELATIVITY" : "1.相對論理論",
"MASS–ENERGY EQUIVALENCE" : "質能方程",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m:質量（kg），E:物體的能量（J），c:光速（m/s） ",
"LENGTH CONTRACTION" : "長度收縮",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o：物體的實際長度，l:以速度v運動的觀察著看到的長度",
"RELATIVISTIC MASS" : "相對質量",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o：靜止質量，m：物體以速度v運動時的相對質量",
"TIME DILATION" : "時間膨脹",
"2. ATOMIC NUCLEUS" : "2.原子核",
"NUCLEAR MAKEUP" : "原子核組成",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z：質子數，N：中子數，A：質量數",
"NUCLEAR REACTION" : "核反應",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o:核反應釋放能量",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o：核反應的吸收能量",
"RADIOACTIVE DECAY" : "放射性衰變",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o：放射性物質的初始量，N：剩餘沒有衰變的物質的數量，ΔN:衰變物質的質量，m_o：初始質量，m：剩餘質量，λ：衰變常數，t：時間，T：半衰期",
"Half life of some elements" : "一些元素的半衰期",
"AMOUNT OF RADIOACTIVITY" : "放射量",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o：放射性初始數量，H：在時間t內的放射的量",
"1. CONSTANTS" : "1.常量",
"ALPHA PARTICLE MASS" : "阿爾法粒子的質量",
"ATOMIC MASS CONSTANT" : "原子質量常數",
"ATOMIC UNIT OF ENERGY" : "能量的原子單位",
"ATOMIC UNIT OF FORCE" : "力的原子單位",
"ATOMIC UNIT OF LENGTH" : "長度的原子單位",
"ATOMIC UNIT OF MASS" : "質量的原子單位",
"AVOGADRO'S CONSTANT" : "阿伏加德羅常數",
"BOHR RADIUS" : "玻爾半徑",
"BOLTZMANN CONSTANT" : "玻爾茲曼常數",
"CLASSICAL ELECTRON RADIUS" : "經典電子半徑",
"ELEMENTARY CHARGE" : "基本電荷",
"EARTH MASS" : "地球質量",
"EARTH EQUATORIAL RADIUS" : "地球赤道半徑",
"EARTH MEAN ORBITAL VELOCITY" : "地球運動的軌道速度",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "地球自轉角速度",
"FARADAY’S CONSTANT" : "法拉第常數",
"GAS CONSTANT" : "氣體常數",
"MOLAR MASS CONSTANT" : "摩爾質量不變",
"MOLAR VOLUME OF IDEAL GAS" : "理想氣體的摩爾體積",
"NEUTRON MASS" : "中子的質量",
"NEWTONIAN CONSTANT OF GRAVITATION" : "萬有引力常數",
"PLANCK’S CONSTANT" : "普朗克常數",
"PLANCK MASS" : "普朗克質量",
"PROTON MASS" : "質子質量",
"PROTON-ELECTRON MASS RATIO" : "質子 - 電子質量比",
"SPEED OF LIGHT IN VACUUM" : "光在真空中的速度",
"STANDARD ACCELERATION OF GRAVITY" : "標準重力加速度",
"STANDARD ATMOSPHERE" : "標準大氣壓",
"STANDARD REFERENCE SOUND INTENSITY" : "標準參考聲音強度",
"STEFAN-BOLTZMANN CONSTANT" : "斯蒂芬 - 波爾茲曼常數",
"2. GREEK ALPHABET" : "2.希臘字母",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1：希臘字母，C2：名稱，C3：等價的，C4：發音",

"Mechanics" : "力學",
"Thermal physics" : "熱學",
"Optics" : "光學",
"Theory of relativity" : "相對論",

"FREE FALLING" : "自由落體",
"VERTICAL PROJECTILE" : "豎直上拋",
"ANGLED PROJECTILE" : "斜拋",
"HORIZONTAL PROJECTILE" : "平拋",
"SLIDING MOTION" : "滑動",
"ATTRACTIVE FORCE" : "引力",
"Hydraulic press" : "液壓機",
"PRESSURE" : "壓力",
"LINEAR EXPANSION" : "線膨脹",
"VOLUME EXPANSION" : "體積膨脹",
"SOUND SPEED" : "聲速",
"REFRACTION" : "折射",
"PRISM" : "棱鏡",
"LENS" : "透鏡",
"Length contraction" : "長度收縮",
"Time dilation" : "時間膨脹",
"RELATIVISTIC MASS" : "相對質量",

"Height " : "高度",
"Time to touchdown " : "落地時間",
"Touchdown velocity " : "落地時速度",
"Initial velocity " : "初始速度",
"Maximum height " : "最大高度",
"Initial velocity " : "初始速度",
"Angle " : "角",
"Maximum height " : "最大高度",
"Maximum distance " : "最大距離",
"Height " : "高度",
"Initial velocity " : "初始速度",
"Time to touchdown " : "落地時間",
"Touchdown velocity " : "落地時速度",
"Angle of titled plane " : "平面夾角",
"Coefficient of friction " : "摩擦係數",
"Acceleration " : "加速度",
"Mass " : "質量",
"Mass " : "質量",
"Distance " : "距離",
"Attractive force " : "引力",
"Area " : "面積",
"Area " : "面積",
"Force " : "力",
"Force" : "力",
"Force F₂ (or F₁)" : "力F₂（或F₁）",
"Temperature " : "溫度",
"Pressure at 0°C " : "在0℃時的壓力",
"Pressure " : "壓力",
"Original length " : "原始長度",
"Temperature change " : "溫度變化",
"Coefficient of linear expansion " : "線性膨脹係數",
"Change of length " : "長度變化",
"Original volume " : "原始體積",
"Temperature change " : "溫度變化",
"Coefficient of linear expansion " : "線性膨脹係數",
"Change of volume " : "變化量",
"Temperature " : "溫度",
"Sound speed " : "聲速",
"Refractive index " : "折射率",
"Refractive index " : "折射率",
"Angle of incidence " : "入射角",
"Angle of refraction " : "折射角",
"Angle (r or i) " : "角度（r或i）",
"Apex angle " : "頂角",
"Angle of incident " : "入射角",
"Refractive index " : "折射率",
"Angle of emergent ray " : "出射光線的角度",
"Deviation angle " : "偏向角",
"Focal length " : "焦距",
"Object distance " : "物距",
"Image distance " : "像距",
"Image (or object) distance" : "像(或)物距",
"Magnification factor " : "放大係數",
"Speed " : "速度",
"Proper length " : "適當的長度",
"Observed length " : "觀察到的長度",
"Rest mass " : "靜止質量",
"Relativistic mass " : "相對論質量",
"Proper time interval " : "適當的時間間隔",
"Observed time interval " : "觀測時間間隔",
"Calculate" : "0",
"Or input" : "0",
"Calculation Tools" : "計算工具",



	
};