var language={

"1. DYNAMICS" : "1. Dinamikler",
"STRAIGHT LINE MOTION" : "Doğrusal Hareket ",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: mesafe (m), t: zaman (s, saniye), v: hız (m/s), v_a: ortalama hız ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Doğrusal Harekette Sabit İvme",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: ivme, v_o: başlangıç ​​hızı, v: t anındaki hız",
"DISTANCE FUNCTION" : "Mesafe fonksiyonu ",
"x_o: initial distance from origin, x: distance at time t" : "x_o: başlangıca olan ​​mesafe, x: t anındaki mesafe ",
"UNIFORM CIRCULAR MOTION" : "Düzgün Dairesel Hareket ",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: açı (rad), l: yay uzunluğu, R: dairenin yarıçapı, ω: açısal hız (rad/s), t: nesnenin l uzunluğunu katettiği süre ",
"CENTRIPETAL FORCE" : "Merkezcil Kuvvet ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: frekans (Hz), T: Bir rotasyon süresi (s), a: merkezcil ivme, F: merkezcil kuvvet (N, Newton) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Sabit İvme Dairesel Hareket ",
"γ: angular acceleration" : "γ: açısal ivme ",
"ACCELERATION" : "Hızlanma ",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: teğetsel ivme, a_n: normal ivme",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: hızlandırma, P2: düzgün dairesel hareket, P3: yavaşlama",
"FREE FALLING FROM HEIGHT h" : "h yüksekliğinden serbest düşüş ",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: yerçekimsel ivme, v: t anındaki hız, s: t sonrası mesafe, v_h: yere değme anındaki hız , t_h: Yere değmeye kalan zaman",
"VERTICAL PROJECTILE MOTION" : "Dikey Atış Hareketi ",
"h_max: maximum height, v_o: initial velocity" : "h_max: maksimum yükseklik, v_o: ilk hız ",
"Motion equation and velocity equation" : "Hareket Denklemi ve Hız Denklemi ",
"ANGLED PROJECTILE MOTION" : "Açılı Atış Hareketi ",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: hız; x, y: t'ye göre hareket denklemi; H: maksimum yükseklik; L: maksimum mesafe ",
"HORIZONTAL PROJECTILE MOTION" : "Yatay Atış Hareketi ",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: iniş anı zamanı, v_h: iniş anındaki hız ",
"SLIDING MOTION ON AN INCLINED PLANE" : "Eğik Düzlemde Kayma Hareketi ",
"μ: coefficient of friction" : "μ: sürtünme katsayısı ",
"Fiction coefficient of some materials" : "Bazı malzemelerin sürtünme katsayıları ",
"2. FORCES" : "2. Kuvvetleri ",
"ATTRACTIVE FORCE" : "Çekim kuvveti ",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: 2 cismin kütlesi; r: 2 cisim arasındaki mesafe; G: yerçekimi sabiti ",
"GRAVITATIONAL FORCE" : "Yerçekimi kuvveti ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: Dünya kütlesi, m: cismin kütlesi, R: Dünya yarıçapı, h: cismin yüksekliği",
"GRAVITATIONAL ACCELERATION" : "Yerçekimi ivmesi ",
"At a height h above the nominal surface of the earth" : "Dünyanın nominal yüzeyinden h yüksekliğinde ",
"Near the sea level" : "Deniz seviyesine yakın ",
"FORCE OF GRAVITY" : "Yerçekimi kuvveti ",
"Force of gravity on earth, a special case of Gravitational force" : "Yeryüzünde yerçekimi kuvveti, Yerçekimi kuvvetinin özel bir hali ",
"NEWTON'S FIRST LAW" : "Newton'un birinci yasası ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: cisim üzerinde etki eden kuvvetler, v: cismin hızı, a: cismin ivmesi ",
"NEWTON'S SECOND LAW" : "Newton'un ikinci yasası ",
"m: object's mass (kg)" : "m: nesnenin kütlesi (kg) ",
"NEWTON'S THIRD LAW" : "Newton'un üçüncü yasası ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Lineer elastisite - Hooke kanunu ",
"k: spring constant (N/m), x: displacement (m)" : "k: yay sabiti (N/m), x: yerdeğiştirme (m) ",
"A mass suspended by a spring" : "Bir yaya asılmış bir kitle ",
"FORCE OF FRICTION" : "Sürtünme kuvveti ",
"μ: coefficient of friction, N: normal force" : "μ: sürtünme katsayısı, N: normal kuvvet ",
"3. STATICS" : "3. Statik ",
"MOMENT OF A FORCE" : "Bir kuvvetin momenti ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: uygulanan kuvvet (N), d:, moment kolu (Kuvvetin uygulama hattına ekseninden dik mesafe) ",
"MOMENT APPLICATION" : "MOMENT UYGULAMASI",
"MOMENT OF INERTIA" : "Atalet momenti ",
"Rod of length l" : "Uzunluğunda Çubuk l",
"Thin circular hoop/ Thin cylindrical shell" : "İnce dairesel çember/İnce silindirik kabuk ",
"Solid disk/ Solid cylinder" : "Katı Disk/Katı silindir ",
"Solid ball" : "Katı Top ",
"Hollow sphere" : "İçi boş küre ",
"ANGULAR MOMENTUM" : "Açısal Momentum",
"I: moment of inertia, ω: angular velocity" : "I: atalet momenti, ω: açısal hız ",
"PLANE MOTION OF A RIGID BODY" : "RİJİD CİSMİN DÜZ HAREKETİ ",
"γ: angular acceleration, M: moment of a force" : "γ: açısal ivme, M: Bir kuvvetin momenti ",

"4. CONSERVATION LAWS" : "4. Korunum Kanunları ",
"MOMENTUM OF FORCE" : "Kuvvet momenti ",
"LAW OF CONSERVATION OF MOMENTUM" : "Momentumun korunumu ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: nesne 1 ve 2'nin başlangıç ​​hızları; v₁', v₂': nesne 1 ve 2'nin son hızları ",
"PLASTIC COLLISION" : "İnelastik Çarpışma ",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': darbeden sonra iki gövde sistemi (m₁ + m₂) hızı ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Tek boyutlu elastik çarpışma ",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': m₁ ve m₂ darbe sonrası hızları ",
"5. WORK AND ENERGY" : "5. İş ve Enerji ",
"WORK" : "İş",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: Bir kuvvet (J) tarafından yapılan iş, F: bir mesafe s için nesneyi hareket ettiren kuvvet, α: F ve hareket yönü arasındaki açı",
"EXAMPLES" : "Örnekler ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: yerçekiminin hareketi, h: yükseklik değişimi; W_ms: Sürtünme kuvvetinin hareketi; W: Bir yayın hareketi ",
"POWER" : "Güç ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: güç (watt, W), t: W işi için gereken zaman (s) ",
"KINETIC ENERGY" : "Kinetik Enerji ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Bir büyük döner cismin kinetik enerjisi ",
"WORK-ENERGY PRINCIPLE" : "İş-enerji prensibi ",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: değişiklikten önce ve sonra nesnenin hızları ",
"POTENTIAL ENERGY" : "Potansiyel Enerji ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: yerçekimsel potansiyel enerji (J), m: cismin kütlesi (kg) ",
"CONSERVATION OF MECHANICAL ENERGY" : "Mekanik enerjinin korunumu ",
"CONSERVATION OF ENERGY" : "Enerjinin Korunumu ",
"6. MECHANICS OF FLUIDS" : "6. Akışkanlar Mekaniği ",
"DENSITY" : "Yoğunluk ",
"m: mass of a volume V" : "m: bir V hacmnini kütlesi ",
"PRESSURE" : "Basınç ",
"F: force applied on area of A" : "F: kuvvet A alanı üzerine uygulanan güç",
"PRESSURE OF LIQUIDS" : "Akışkanların Basıncı ",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: özgül ağırlık (N/m³), p_o: serbest yüzeyde hava basıncı (N/m²), p: üzerindeki sıvının yarattığı basınç, p_B: derinlik h noktasındaki toplam basınç",
"PASCAL’S PRINCIPLE" : "Pascal Prensibi ",
"p_s: pressure on the surface" : "p_s: yüzeydeki baskı ",
"APPLICATION" : "Uygulama ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: küçük ve büyük silindir alanı; F₁, F₂: uygulanan ve yukarı doğru kuvvetler ",
"ARCHIMEDES’ PRINCIPLE" : "Arşimed Prensibi ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: sıvının özgül ağırlığı (N/m³), V: nesnenin hacmi, F_b: kaldırma kuvveti, batmazlık boyansı",
"FLOW RATE" : "debi ",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: kesit alanı (m²), v: akış hızı (m/s), Q: debisi (m³/s) ",

"1. ELECTROSTATICS" : "1. Elektrostatik ",
"COULOMB’S LAW" : "Coulomb Yasası ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: uygulanan kuvvetlerin büyüklüğü (C), ε: relatif geçirgenlik (vakum ortamında ε = 1), r: kuvvetler arasındaki mesafe (m) ",
"ELECTRIC FIELDS" : "Elektrik Alanları ",
"E: electric field strength (N/C)" : "E: elektrik alan şiddeti (N/C) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Elektrik alanlar için süperpozisyon prensibi ",
"In case of 2 electric fields" : "2 elektrik alanı durumu ",
"WORK OF ELECTRIC FORCE" : "Elektrik gücünün işi",
"ELECTRIC POTENTIAL DIFFERENCE" : "Elektrik potansiyel farkı ",
"RELATION BETWEEN E AND U" : "E ve U arasındaki ilişki ",
"CAPACITANCE" : "Kapasitans ",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: kapasitans (F), Q: toplam elektrik yükü (C), U: elektrik potansiyeli (V) ",
"CAPACITOR" : "Kondansatör ",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: Elektrod levhaların alanı (m²), d: elektrodların arasındaki mesafe (m), ε: relatif geçirgenlik (F/m)",
"CAPACITANCES IN SERIES" : "Seri kapasitans ",
"CAPACITANCES IN PARALLEL" : "Paralel kapasitans ",
"ELECTRIC FIELD ENERGY" : "Elektrik alanı enerjisi ",
"ENERGY OF CAPACITOR" : "Kondansatörün enerjisi",
"V=A.d: volume between two electrode plates" : "V = A.d: iki elektrod levha arasındaki hacim ",
"2. DIRECT CURRENT" : "2. Doğru Akım ",
"ELECTRIC CURRENT" : "Elektrik Akımı ",
"I: current (A), q: charge (C), t: time" : "I: akım (A), q: yük (C), t: zaman ",
"OHM’S LAW" : "Ohm Kanunu ",
"U: electric potential difference between the ends of the resistor R" : "U: direnç uçları arasında elektrik potansiyeli farkı R",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Bir akım tarafından oluşturulan iş (Joule yasası) ",
"ELECTRICAL POWER" : "Elektrik gücü ",
"RESISTANCE" : "Direnç ",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: malzemenin direnci (Ωm), l: uzunluk (m), kesit alanı (m²) ",
"SERIES CIRCUITS" : "Seri Devreler ",
"PARALLEL CIRCUITS" : "Paralel Devreler ",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Direnç tarafından üretilen iş veya ısı enerjisi ",
"POWER CONSUMPTION OF A RESISTOR" : "Direncin güç tüketimi ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Bir elektrik jeneratörünün akım sağlayan elektromotor kuvveti ",
"W: work of force (J), q: charge (C)" : "W: kuvvetin çalışması (J), q: yük (C) ",
"GENERATORS IN SERIES" : "Seri Jeneratörler ",
"r: internal resistance of the generator" : "r: jeneratörün iç direnci ",
"GENERATORS IN PARALLEL" : "Paralel Jeneratörler ",
"GENERATORS IN SERIES-PARALLEL" : "Seri-paralel jeneratörler ",
"WORK AND POWER OF GENERATOR" : "Çalışma ve jeneratör gücü ",
"H: Efficiency of generator" : "H: Jeneratör Randımanı ",
"3. MAGNETISM" : "3. Manyetizma ",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Açık yüzeyde geçen manyetik akım (S) ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: manyetik alanın büyüklüğü (T, tesla), α: B ile yüzeye dik çizgi S arasındaki açı",
"MAGNETIC FORCES ON MOVING CHARGES" : "Hareketli akımlar arasındaki Manyetik Kuvvetler ",
"v: velocity of the charge (m/s)" : "v: akım hızı (m/s) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "Akım taşıyan bir tel üzerindeki kuvvet ",
"I: current (A), l: length of the wire (m)" : "I: akım (A), l: telin uzunluğu (m) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "2 paralel akım taşıyan tel arasındaki kuvvet",
"r: distance between two wires (m)" : "r: iki tel arasındaki mesafe (m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Uzun bir akım-yüklü telin manyetik alanı ",
"r: perpendicular distance from the center of the wire (m)" : "r: telin merkezine olan dikine mesafe (m) ",
"MAGNETIC FIELD OF A LOOP" : "Döngünün Manyetik Alanı ",
"n: number of turns per unit length of solenoid (turns/m)" : "n: solenoitin (iletken tel sarım) birim uzunluk başına sarma sayısı (devir/m) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "İndüklenen elektromotor kuvveti - Faraday Yasası ",
"N: numbers of turns per loop (turns/m)" : "N: döngü başına sarma sayısı (devir/m) ",
"INDUCTANCE" : "İndüktans ",
"ELECTRIC ENERGY" : "Elektrik enerjisi ",
"MAGNETIC ENERGY" : "Manyetik enerji ",
"ELECTRIC-MAGNETIC ENERGY" : "Elektrik-manyetik enerji ",
"4. ALTERNATING CURRENT" : "4. Alternatif Akım ",
"BASIC PARAMETERS" : "Temel parametreler ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: anlık akım (A), I_o: maksimum anlık akım (A), T: dalga periyodu, f: frekans, λ: dalga boyu, c: ışık hızı ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Efektif Akım ve Gerilim ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Sadece Direnç R İçeren Alternatif Akım Ohm Yasası ",
"CONTAINING ONLY INDUCTOR L" : "Sadece indüktör L içeren ",
"Z_L: inductive reactance" : "Z_L: indüktif reaktans ",
"CONTAINING ONLY CAPACITOR C" : "Sadece kondansatör C içeren ",
"Z_C: capacitive reactance" : "Z_C: kapasitif reaktans ",
"CONTAINING R, L AND C IN A SERIES" : "Seri halinde R, L ve C içeren ",
"Z: impedance" : "Z: empedans ",
"PHASE ANGLE" : "Gaz açısı ",
"POWER FACTOR" : "Güç faktörü ",
"REAL POWER" : "Gerçek güç ",
"ELECTRICAL RESONANCE" : "Elektrik rezonans ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Transformatör ile Voltaj değiştirme ",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: birincil bobin ve ikincil bobin sarım sayısı; U₁, U₂: primer ve sekonder gerilim; I₁, I₂: birincil ve ikincil akımlar ",

"1. GAS LAWS" : "1. Gaz Kanunları ",
"KELVIN TEMPERATURE" : "Kelvin sıcaklığı",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: Kelvin ölçeğinde sıcaklık, t: Santigrat ölçekli sıcaklık ",
"EQUATION OF STATE" : "Hal Denklemi ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: basınç (P, Pascal), V: hacim (m³), n: gaz mollerinin sayısı (mol), R: evrensel gaz sabiti, T: Gazın (K) Kelvin sıcaklığı, k: Boltzmann sabiti, N: gazın molekül sayısı ",
"IDEAL GAS LAW" : "İdeal gaz kanunu ",
"BOYLE’S LAW FOR PRESSURE" : "Boyle Basınç Kanunu ",
"If the temperature of the gas is constant" : "Gazın sıcaklığı sabit ise ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Gay-Lussac Basınç-Sıcaklık yasası ",
"If the volume on a gas is constant" : "Bir gazın hacmi sabit ise",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: gazın t ısısındaki basıncı, p_o: 0 santigrat derecedeki basınç, γ: hacim sabit olduğundaki faktör",
"Example when t=0 Kelvin" : "t = 0 Kelvin ",
"CHARLES'S LAW OF VOLUMES" : "Hacimlerin Charles Yasası ",
"If the pressure on a gas is constant" : "Bir gaz basıncı sabit ise ",
"2. CHANGES OF STATE AND SHAPE" : "2. Durum ve şekil değişiklikleri ",
"HEAT" : "Isı ",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: Isı yayılan, Q_r: ısı alınan, m: nesnenin toplam kütlesi (kg), c: özgül ısı (J/kg.K), ∆t: sıcaklık değişimi (K) ",
"The specific heats of some materials" : "Bazı malzemelerin özgül ısıları",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Füzyon (donma veya katılaşma) ",
"Heat of fusion of some materials" : "Bazı malzemelerin füzyon ısıları ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: ısı miktarı (J), λ: füzyon ısısı (J/kg), m: kütle (kg) ",
"VAPORIZATION" : "Buharlaşma ",
"L: heat of vaporization" : "L: buharlaşma ısısı ",
"Heat of vaporization of some materials" : "Bazı malzemelerin buharlaşma ısısı",
"LINEAR EXPANSION" : "Lineer genleşme ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: Orijinal uzunluk (m), α: lineer genleşme katsayısı (K⁻¹), ∆t: sıcaklık değişimi ",
"VOLUME EXPANSION" : "Hacim genleşmesi",
"AREA EXPANSION" : "Alan genleşmesi ",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Yoğunluk Değişimi (hacimsel kütle yoğunluğu) ",
"D_o: original density (kg/m³)" : "D_o: orijinal yoğunluk (kg/m³) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Katı nesnenin kesit çapının değişimi ",
"3. THERMODYNAMICS" : "3. Termodinamik ",
"THE FIRST LAW OF THERMODYNAMICS" : "Termodinamiğin Birinci Yasası ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU: iç enerji değişimi, W: sistem tarafından yapılan iş Q: sisteme eklenen veya çıkartılan ısı",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Birinci yasanın ideal gaz kanunlarına uygulanması ",
"- Volume is constant" : "- Hacim sabittir",
"- Pressure is constant, W': work created by gas" : "- Basınç sabittir, W': gazın yarattığı iş",
"- Temperature is constant" : "- Sıcaklık sabittir",
"THE SECOND LAW OF THERMODYNAMICS" : "Termodinamiğin İkinci Yasası ",
"- The efficiency of a cyclic heat engine" : "- Siklik ısı motorunun verimi",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': çalışma döngüsü başına yürütülen iş (J), Q₁: yüksek sıcaklıktan döngü başına emilen ısı (J), Q₂': döngü başına düşük sıcaklığa reddedilen ısı (J) ",
"- Maximum thermal efficiency" : "- Maksimum termal verim",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: yüksek ve düşük sıcaklıklar ",

"1. SIMPLE HARMONIC MOTION" : "1. Basit Harmonik Hareket ",
"SPRING" : "Yay",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: Yay sabiti (N/m), s: yer değiştirme (m), ω: açısal hız (rad/s), T: dönemi, m: cismin kütlesi, A: genlik ",
"SPRINGS IN SERIES" : "Seri yaylar ",
"k: spring constant of the system, T: period of the system" : "k: sistemin yay sabiti, T: Sistemin periyodu ",
"SPRINGS IN PARALLEL" : "Paralel yaylar ",
"SIMPLE PENDULUM" : "Basit sarkaç ",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: açısal hız (rad/s), T: periyod, α_o: genlik açısı, A: genlik, l: sarkacın uzunluğu ",
"MOTION EQUATIONS" : "Hareket denklemleri ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: yer değiştirme, α: açı, v: hız, T: çubuk üzerindeki güç ",
"ENERGY" : "Enerji ",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: potansiyel enerji, E_k: kinetik enerji, E: mekanik enerji ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Sıcaklık değişikliğinin ardından periyod değişikliği ",
"α: coefficient of linear expansion of the rod" : "α: çubuğun doğrusal genleşme katsayısı ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Yüksekliği değişikliğinin ardından periyod değişikliği ",
"h: height of pendulum, R: Earth's radius" : "h: sarkacın yüksekliği, R: Dünya'nın yarıçapı ",
"PENDULUM" : "Sarkaç ",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: atalet momenti, ω: açısal hız, m: bob kütlesi, d:OG, T: periyod",
"2. PERIODIC MOTION" : "2. Periyodik hareketler ",
"WAVELENGTH" : "Dalgaboyu ",
"FUNCTION OF WAVE AT SOME POINTS" : "Bazı noktalarda dalga fonksiyonu ",
"WAVE INTERFERENCE" : "Dalga enterferensi ",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 dalga kaynağının aynı faza sahip olması; M: rastgele bir nokta ",
"3. SOUND WAVES" : "3. Ses Dalgaları ",
"SOUND SPEED" : "Ses hızı ",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): sıcaklık (Santigrad) t ortamında ses hızı ",
"SOUND INTENSITY " : "Ses şiddeti ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: Ses enerjisi (J), P: ses gücü (W), A: Bir kürenin (m²) yüzey alanı, t: zaman (s) ",
"SOUND INTENSITY LEVEL" : "Ses şiddeti düzeyi ",
"I_o: the standard reference sound intensity" : "I_o: standart referans ses yoğunluğu ",
"THE DOPPLER EFFECT" : "Doppler Etkisi ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: gözlemcinin relatif hızı; v_S: kaynağın relatif hızı; v: bu ortamda ses hızı; f_S, f_O: kaynak ve gözlemcinin ses frekansı ",
"SOUND SPEED IN GASES" : "Gazlarda Ses Hızı ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: ses hızı (m/s), R: evrensel gaz sabiti, T: mutlak sıcaklık (K), M: moleküler gaz kütlesi (kg/mol), γ: adyabatik sabiti ",
"Example in air" : "Hava örneği ",

"1. GEOMETRIC OPTICS" : "1. Geometrik Optik ",
"LAWS OF REFLECTION" : "Yansıma Kanunları ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: gelen ışın, IR: yansıyan ışın, i: geliş açısı, i': yansıma açısı ",
"REFRACTIVE INDEX" : "Kırılma indeksi ",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: a ortamının kırılma indeksi, v: a ortamında ışık hızı, c: vakumda ışık hızı (m/s) ",
"LAW OF REFRACTION" : "Kırılma Kanunu ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: ortam 1'in kırılma indeksi, n₂: ortam 2'nin kırılma indeksi, i: çarpma açısı, r: kırılma açısı, n₂₁: kırılma mutlak endeksi ",
"If medium 1 is vacuum" : "Ortam 1 ​​vakum ise ",
"TOTAL REFLECTION PHENOMENON" : "Toplam yansıma fenomeni",
"There is no refracted ray if" : "Hiçbir kırılan ışın yoktur eğer... ",
"PRISM" : "Prizma ",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: tepe açısı, D: sapma açısı, i₁: geliş açısı, i₂: çıkan ışın açısı ",
"- Condition to have refractive ray" : "- Refraktif ışın olması durumu",
"- When angle of incidence is minimum" : "- Geliş açısı az ise",
"THIN LENS" : "İnce Lens ",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: odak uzaklığı (yakınsak lens f&gt;0; uzaksak lens f&lt;0), d: lens merkezine nesne mesafesi, d': lens merkezinden görüntü mesafesi ",
"MAGNIFICATION FACTOR" : "Büyütme faktörü ",
"h_I: image height, h_O: object height" : "h_I: Görüntü yüksekliği, h_O: nesne yüksekliği ",
"POWER OF THE LENS" : "Lensin gücü ",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: lens materyalinin refraktif indeksi, R₁: ışık kaynağına en yakın olan lens yüzeyinin eğrilik yarıçapı, R₂: ışık kaynağından en uzak lens yüzeyinin eğrilik yarıçapı ",
"2. QUANTUM OF LIGHT" : "2. Işık Kuantumu ",
"PHOTON ENERGY" : "Foton enerjisi ",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: Planck sabiti, f: frekans (Hz), λ: dalga boyu (m), c: ışık hızı ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Fotoelektrik bir etkiye sahip olma durumu ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: yayılan ışığın dalga boyu,  λ_o: fotoelektrik limiti, W: emilen iş (J)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Einstein'ın fotoelektrik etkisi denklemi ",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: fotoelektron kütlesi (kg), v_o: fotoelektronun maksimum hızı (m/s) ",

"1. THEORY OF RELATIVITY" : "1. İzafiyet Teorisi",
"MASS–ENERGY EQUIVALENCE" : "Kütle-enerji denkliği ",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: kütle (kg), E: nesnenin enerjisi (J), c: ışık hızı (m/s)",
"LENGTH CONTRACTION" : "Uzunluk daralması ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: Nesnenin gerçek uzunluğu, l: bir gözlemci tarafından gözlemlenen v hızındaki uzunluk",
"RELATIVISTIC MASS" : "İzafi kütle",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: duruk kütle, m: cismin v hızı ile hareket ederkenki izafi kütlesi",
"TIME DILATION" : "Zaman genişlemesi ",
"2. ATOMIC NUCLEUS" : "2. Atom çekirdeği ",
"NUCLEAR MAKEUP" : "Nükleer yapı ",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: proton sayısı, N: nötron sayısı, A: kütle numarası ",
"NUCLEAR REACTION" : "Nükleer reaksiyon ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: Nükleer reaksiyon enerji verir",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: Nükleer reaksiyon enerji emer",
"RADIOACTIVE DECAY" : "Radyoaktif bozunma ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: başlangıçaktif madde ​​miktarı, N: t süresi sonunda bozunmamış kalan miktar, ΔN: bozunan madde miktarı, m_o: başlangıç kütlesi, m: kalan kütle, λ: bozunma sabiti, t:zaman, T:yarı ömrü",
"Half life of some elements" : "Bazı elementlerin yarı ömrü ",
"AMOUNT OF RADIOACTIVITY" : "Radyoaktivite miktarı ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: başlangıç radyoaktivite ​​miktarı, H: t anındaki radyoaktivite miktarı",
"1. CONSTANTS" : "1. Sabitler ",
"ALPHA PARTICLE MASS" : "Alfa parçacığının kütlesi ",
"ATOMIC MASS CONSTANT" : "atomik kütle sabiti ",
"ATOMIC UNIT OF ENERGY" : "atomik enerji birimi ",
"ATOMIC UNIT OF FORCE" : "kuvvet atom birimi ",
"ATOMIC UNIT OF LENGTH" : "atomik uzunluk birimi ",
"ATOMIC UNIT OF MASS" : "atomik kütle birimi ",
"AVOGADRO'S CONSTANT" : "Avogadro sabiti ",
"BOHR RADIUS" : "Bohr yarıçapı ",
"BOLTZMANN CONSTANT" : "Boltzmann sabiti ",
"CLASSICAL ELECTRON RADIUS" : "klasik elektron yarıçapı ",
"ELEMENTARY CHARGE" : "elemanter yük",
"EARTH MASS" : "dünya kütlesi ",
"EARTH EQUATORIAL RADIUS" : "dünya ekvatorel yarıçapı ",
"EARTH MEAN ORBITAL VELOCITY" : "dünyanın ortalam yörünge hızı ",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Dünyanın dönme açısal hızı ",
"FARADAY’S CONSTANT" : "Faraday sabiti ",
"GAS CONSTANT" : "gaz sabiti ",
"MOLAR MASS CONSTANT" : "molar kütle sabiti ",
"MOLAR VOLUME OF IDEAL GAS" : "İdeal gazın molar hacmi ",
"NEUTRON MASS" : "nötron kütlesi ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Newton kütleçekim sabiti ",
"PLANCK’S CONSTANT" : "Planck sabiti ",
"PLANCK MASS" : "Planck kütlesi",
"PROTON MASS" : "proton kütlesi ",
"PROTON-ELECTRON MASS RATIO" : "Proton-elektron kütle oranı ",
"SPEED OF LIGHT IN VACUUM" : "vakumda ışık hızı ",
"STANDARD ACCELERATION OF GRAVITY" : "standart yerçekimi ivmesi",
"STANDARD ATMOSPHERE" : "standart atmosfer ",
"STANDARD REFERENCE SOUND INTENSITY" : "Standart referans ses şiddeti",
"STEFAN-BOLTZMANN CONSTANT" : "Stefan-Boltzmann sabiti ",
"2. GREEK ALPHABET" : "2. Yunan alfabesi ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: Yunan harfi, C2: Adı, C3: Eşdeğer, C4: Konuşunca çıkan ses ",

"Mechanics" : "Mekanik",
"Thermal physics" : "Termal Fizik ",
"Optics" : "Optik ",
"Theory of relativity" : "İzafiyet teorisi ",

"FREE FALLING" : "Serbest düşüş ",
"VERTICAL PROJECTILE" : "Dikey mermi ",
"ANGLED PROJECTILE" : "Açılı mermi ",
"HORIZONTAL PROJECTILE" : "Yatay mermi ",
"SLIDING MOTION" : "Kayan hareket ",
"ATTRACTIVE FORCE" : "Çekim kuvveti ",
"Hydraulic press" : "Hidrolik pres ",
"PRESSURE" : "Basınç ",
"LINEAR EXPANSION" : "Lineer genleşme ",
"VOLUME EXPANSION" : "Hacim genleşmesi",
"SOUND SPEED" : "Ses hızı ",
"REFRACTION" : "Kırılma ",
"PRISM" : "Prizma ",
"LENS" : "Lens ",
"Length contraction" : "Uzunluk daralması ",
"Time dilation" : "Zaman genişlemesi ",
"RELATIVISTIC MASS" : "İzafi kütle",

"Height " : "Yükseklik ",
"Time to touchdown " : "Yere değme süresi",
"Touchdown velocity " : "Yere değme hızı",
"Initial velocity " : "Başlangıç ​​hızı ",
"Maximum height " : "Maksimum yükseklik ",
"Initial velocity " : "Başlangıç ​​hızı ",
"Angle " : "Açı ",
"Maximum height " : "Maksimum yükseklik ",
"Maximum distance " : "Maksimum mesafe ",
"Height " : "Yükseklik ",
"Initial velocity " : "Başlangıç ​​hızı ",
"Time to touchdown " : "Yere değme süresi",
"Touchdown velocity " : "Yere değme hızı",
"Angle of titled plane " : "Başlıklı düzlem açısı",
"Coefficient of friction " : "Sürtünme katsayısı ",
"Acceleration " : "Hızlanma ",
"Mass " : "Kütle",
"Mass " : "Kütle",
"Distance " : "Uzaklık ",
"Attractive force " : "Çekim kuvveti ",
"Area " : "Alan ",
"Area " : "Alan ",
"Force " : "Kuvvet ",
"Force" : "Kuvvet ",
"Force F₂ (or F₁)" : "F₂ kuvveti (veya F₁) ",
"Temperature " : "Sıcaklık ",
"Pressure at 0°C " : "0°C'de basınç ",
"Pressure " : "Basınç ",
"Original length " : "Orijinal uzunluk",
"Temperature change " : "Isı değişimi ",
"Coefficient of linear expansion " : "Lineer genleşme katsayısı ",
"Change of length " : "Uzunluk değişikliği",
"Original volume " : "Orijinal hacim ",
"Temperature change " : "Isı değişimi ",
"Coefficient of linear expansion " : "Lineer genleşme katsayısı ",
"Change of volume " : "Hacim değişimi ",
"Temperature " : "Sıcaklık ",
"Sound speed " : "Ses hızı",
"Refractive index " : "Kırılma indeksi ",
"Refractive index " : "Kırılma indeksi ",
"Angle of incidence " : "Geliş açısı ",
"Angle of refraction " : "Kırılma açısı ",
"Angle (r or i) " : "Açı (r ya da i) ",
"Apex angle " : "Tepe açısı ",
"Angle of incident " : "Olayın Açısı ",
"Refractive index " : "Kırılma indeksi ",
"Angle of emergent ray " : "Çıkan ışın açısı ",
"Deviation angle " : "Sapma açısı ",
"Focal length " : "Odak uzaklığı ",
"Object distance " : "Nesne mesafesi ",
"Image distance " : "Görüntü mesafesi ",
"Image (or object) distance" : "Görüntü (veya nesne) mesafesi ",
"Magnification factor " : "Büyütme faktörü ",
"Speed " : "Hız ",
"Proper length " : "Uygun uzunluk ",
"Observed length " : "Gözlenen uzunluk",
"Rest mass " : "Duruk kitle ",
"Relativistic mass " : "İzafi kütle ",
"Proper time interval " : "Uygun zaman aralığı ",
"Observed time interval " : "Gözlemlenen zaman aralığı ",
"Calculate" : "Hesapla ",
"Or input" : "Giriş ",
"Calculation Tools" : "Hesap Araçları ",



	
};