var language={


"1. DYNAMICS" : "1. Dynamik ",
"STRAIGHT LINE MOTION" : "Geradlinige Bewegung ",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: Abstand (m), t: Zeit (s, sekunde), v: Geschwindigkeit (m/s), v_a: Durchschnittsgeschwindigkeit ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Konstante Beschleunigung geradlinige Bewegung ",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: Beschleunigung, v_o: Anfangsgeschwindigkeit, v: Geschwindigkeit zum Zeitpunkt t ",
"DISTANCE FUNCTION" : "Abstandsfunktion ",
"x_o: initial distance from origin, x: distance at time t" : "x_o: Anfangsabstand vom Ursprung, x: Abstand zum Zeitpunkt t ",
"UNIFORM CIRCULAR MOTION" : "Gleichförmige Kreisbewegung ",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: Winkel (rad), l: Länge des Bogens, R: Radius des Kreises, ω: Winkelgeschwindigkeit (rad/s), t: Zeit der das Objekt eine Länge von l bewegt ",
"CENTRIPETAL FORCE" : "Zentripetalkraft ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: Frequenz (Hz), T: die Zeit für eine Umdrehung (s), a: Zentripetalbeschleunigung, F: Zentripetalkraft (N, Newton) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Konstante Beschleunigung Kreisbewegung ",
"γ: angular acceleration" : "γ: Winkelbeschleunigung ",
"ACCELERATION" : "Beschleunigung ",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: tangentiale Beschleunigung, a_n: Normalbeschleunigung ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: Beschleunigung, P2: gleichförmige Kreisbewegung, P3: Verlangsamung ",
"FREE FALLING FROM HEIGHT h" : "Freien Fall aus der Höhe h ",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: Erdbeschleunigung, v: Geschwindigkeit bei t, s: Abstand nach t, v_h: Geschwindigkeit, wenn den Boden berühren, t_h: Zeit bis zum Aufsetzen ",
"VERTICAL PROJECTILE MOTION" : "Vertikale Wurfbewegung ",
"h_max: maximum height, v_o: initial velocity" : "h_max: maximale Höhe, v_o: Anfangsgeschwindigkeit ",
"Motion equation and velocity equation" : "Bewegungsgleichung und Geschwindigkeitsgleichung ",
"ANGLED PROJECTILE MOTION" : "Abgewinkelten Wurfbewegung ",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: Geschwindigkeit; x, y: Bewegungsgleichung von t; H: maximale Höhe; L: maximale Entfernung ",
"HORIZONTAL PROJECTILE MOTION" : "Horizontale Wurfbewegung ",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: Zeit zu landen, v_h: Geschwindigkeit beim Aufsetzen ",
"SLIDING MOTION ON AN INCLINED PLANE" : "Gleitende Bewegung auf einer schiefen Ebene ",
"μ: coefficient of friction" : "μ: Reibungskoeffizient ",
"Fiction coefficient of some materials" : "Fiction Koeffizienten einiger Materialien ",
"2. FORCES" : "2. Kraften",
"ATTRACTIVE FORCE" : "Anziehungskraft ",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: Masse von 2 Objekten; r: Abstand zwischen 2 Objekten; G: Gravitationskonstante ",
"GRAVITATIONAL FORCE" : "Schwerkraft ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: Erdmasse, m: Masse des Objekts, R: Erdradius, h: Höhe des Objekts ",
"GRAVITATIONAL ACCELERATION" : "Erdbeschleunigung ",
"At a height h above the nominal surface of the earth" : "In einer Höhe h über der nominale Erdoberfläche ",
"Near the sea level" : "In der Nähe der Meeresspiegel ",
"FORCE OF GRAVITY" : "Schwerkraft ",
"Force of gravity on earth, a special case of Gravitational force" : "Schwerkraft der Erde, ein besonderer Fall der Schwerkraft ",
"NEWTON'S FIRST LAW" : "Das erste Newton Gesetz ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: Kräfte, die auf das Objekt handeln, v: Geschwindigkeit des Objekts, a: Beschleunigung des Objekts ",
"NEWTON'S SECOND LAW" : "Das zweite Newton Gesetz ",
"m: object's mass (kg)" : "m: Masse des Objekts (kg) ",
"NEWTON'S THIRD LAW" : "Newton drittes Gesetz ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Lineare Elastizität - Hooke-Gesetz ",
"k: spring constant (N/m), x: displacement (m)" : "k: Federkonstante (N/m), x: Verschiebung (m) ",
"A mass suspended by a spring" : "Eine Masse von einer Feder aufgehängt ",
"FORCE OF FRICTION" : "Kraft der Reibung ",
"μ: coefficient of friction, N: normal force" : "μ: Reibungskoeffizient, N: Normalkraft ",
"3. STATICS" : "3. Statik ",
"MOMENT OF A FORCE" : "Moment einer Kraft ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: die angewandte Kraft (N), d: Hebelarm (der senkrechte Abstand von der Achse zu der Wirkungslinie der Kraft) ",
"MOMENT APPLICATION" : "MOMENT ANWENDUNG ",
"MOMENT OF INERTIA" : "Trägheitsmoment ",
"Rod of length l" : "Stab der Länge l ",
"Thin circular hoop/ Thin cylindrical shell" : "Dünne kreisförmige Reifen/Thin Zylinderschale ",
"Solid disk/ Solid cylinder" : "Festplatte/Vollzylinder ",
"Solid ball" : "Vollkugel ",
"Hollow sphere" : "Hohlkugel ",
"ANGULAR MOMENTUM" : "Drehimpuls ",
"I: moment of inertia, ω: angular velocity" : "I: Trägheitsmoment, ω: Winkelgeschwindigkeit ",
"PLANE MOTION OF A RIGID BODY" : "Ebene Bewegung eines starren Körpers ",
"γ: angular acceleration, M: moment of a force" : "γ: Winkelbeschleunigung, M: Moment einer Kraft ",

"4. CONSERVATION LAWS" : "4. Erhaltungssätze ",
"MOMENTUM OF FORCE" : "Dynamik der Gewalt ",
"LAW OF CONSERVATION OF MOMENTUM" : "Gesetz der Impulserhaltung ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: Anfangsgeschwindigkeiten von Objekten 1 und 2; v₁', v₂': Endgeschwindigkeiten von Objekt 1 und 2 ",
"PLASTIC COLLISION" : "Kunststoff-Kollision ",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': Geschwindigkeit der beiden Körpersystem (m₁ + m₂) nach dem Aufprall ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Eindimensionalen elastischen Stoß ",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': Geschwindigkeiten von m₁ und m₂ nach dem Aufprall ",
"5. WORK AND ENERGY" : "5. Arbeit und Energie ",
"WORK" : "Arbeit ",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: Arbeit durch eine Kraft (J) getan, F: Kraft zu bewegen ein Objekt für eine Strecke s, α: Winkel zwischen F und Bewegungsrichtung ",
"EXAMPLES" : "Beispiele ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: Arbeit durch die Schwerkraft, h: die Änderung in der Höhe; W_ms: Arbeit der Reibungskraft ist; W: Arbeit durch eine Feder ",
"POWER" : "Macht ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: Leistung (watt, W), t: Zeitpunkt der Durchführung der Arbeit W (s) ",
"KINETIC ENERGY" : "kinetische Energie ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Kinetische Energie eines massiven Drehkörper ",
"WORK-ENERGY PRINCIPLE" : "Work-Energieprinzip ",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: Geschwindigkeit des Gegenstandes vor und nach der Änderung ",
"POTENTIAL ENERGY" : "potenzielle Energie ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: potentielle Energie (J), m: Masse des Objekts (kg) ",
"CONSERVATION OF MECHANICAL ENERGY" : "Erhaltung der mechanischen Energie ",
"CONSERVATION OF ENERGY" : "Erhaltung der Energie ",
"6. MECHANICS OF FLUIDS" : "6. Mechanik der Flüssigkeiten ",
"DENSITY" : "Dichte ",
"m: mass of a volume V" : "m: Masse eines Volumens V ",
"PRESSURE" : "Druck ",
"F: force applied on area of A" : "F: Kraft auf einer Fläche von A angewendet ",
"PRESSURE OF LIQUIDS" : "Druck von Flüssigkeiten ",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: spezifisches Gewicht (N/m³), p_o: Luftdruck an der freien Oberfläche (N/m²), p: Druck durch das Gewicht von oben Flüssigkeit, p_B: Gesamtdruck in der Tiefe h ",
"PASCAL’S PRINCIPLE" : "Pascal-Prinzip ",
"p_s: pressure on the surface" : "p_s: Druck auf die Oberfläche ",
"APPLICATION" : "Anwendung ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: Bereich der kleinen und großen Zylinder; F₁, F₂: aufgetragen und nach oben gerichteten Kräfte ",
"ARCHIMEDES’ PRINCIPLE" : "Archimedes-Prinzip ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: Dichte der Flüssigkeit (N/m³), V: Volumen des Objekts, F_b: Auftriebskraft ",
"FLOW RATE" : "Durchflussrate ",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: Querschnittsfläche (m²), v: Strömungsgeschwindigkeit (m/s), Q: Durchfluss (m³/s) ",

"1. ELECTROSTATICS" : "1. Elektrostatik ",
"COULOMB’S LAW" : "Coulomb-Gesetz ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: Größe der Ladungen (C), ε: Dielektrizitätszahl (im Vakuum ε = 1), r: Abstand zwischen den Ladungen (m) ",
"ELECTRIC FIELDS" : "elektrische Felder ",
"E: electric field strength (N/C)" : "E: elektrische Feldstärke (N/C) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Das Prinzip der Überlagerung für elektrische Felder ",
"In case of 2 electric fields" : "Bei 2 elektrische Felder ",
"WORK OF ELECTRIC FORCE" : "Arbeit der elektrischen Kraft ",
"ELECTRIC POTENTIAL DIFFERENCE" : "Elektrische Potentialdifferenz ",
"RELATION BETWEEN E AND U" : "Beziehung zwischen E und U ",
"CAPACITANCE" : "Kapazität ",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: Kapazität (F), Q: gesamte elektrische Ladung (C), U: elektrische Potential (V) ",
"CAPACITOR" : "Kondensator ",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: Fläche der einzelnen Elektrodenplatte (m²), d: Abstand zwischen den Elektroden (m), ε: Dielektrizitätszahl (F/m) ",
"CAPACITANCES IN SERIES" : "Kapazitäten in Serie ",
"CAPACITANCES IN PARALLEL" : "parallel Kapazitäten",
"ELECTRIC FIELD ENERGY" : "Elektrische Feldenergie ",
"ENERGY OF CAPACITOR" : "Energie des Kondensators ",
"V=A.d: volume between two electrode plates" : "V = A.d: Volumen zwischen zwei Elektrodenplatten ",
"2. DIRECT CURRENT" : "2. Gleichstrom ",
"ELECTRIC CURRENT" : "elektrischer Strom ",
"I: current (A), q: charge (C), t: time" : "I: Strom (A), q: Ladung (C), t: Zeit ",
"OHM’S LAW" : "Ohm Gesetz ",
"U: electric potential difference between the ends of the resistor R" : "U: elektrische Potentialdifferenz zwischen den Enden des Widerstands R ",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Werk von einem Strom (Joule-Gesetz) ",
"ELECTRICAL POWER" : "elektrische Leistung ",
"RESISTANCE" : "Widerstand ",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: Widerstand des Materials (Ωm), l: Länge (m), A: Querschnittsfläche (m²) ",
"SERIES CIRCUITS" : "Serienschaltungen ",
"PARALLEL CIRCUITS" : "Parallelschaltungen ",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Arbeit oder Wärmeenergie durch einen Widerstand erzeugt ",
"POWER CONSUMPTION OF A RESISTOR" : "Stromverbrauch eines Widerstands ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Elektromotorische Kraft eines elektrischen Generators ",
"W: work of force (J), q: charge (C)" : "W: Arbeit der Kraft (J), q: Ladung (C) ",
"GENERATORS IN SERIES" : "Generatoren in Reihe ",
"r: internal resistance of the generator" : "r: Innenwiderstand des Generators ",
"GENERATORS IN PARALLEL" : "parallel Generatoren",
"GENERATORS IN SERIES-PARALLEL" : "Generatoren in Reihenparallel ",
"WORK AND POWER OF GENERATOR" : "Arbeit und Leistung des Generators ",
"H: Efficiency of generator" : "H: Effizienz der Generator ",
"3. MAGNETISM" : "3. Magnetismus ",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Magnetflusses durch die offene Oberfläche S ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: Stärke des Magnetfeldes (T, Tesla), α: Winkel zwischen B und senkrechten Linie zur Oberfläche S ",
"MAGNETIC FORCES ON MOVING CHARGES" : "Magnetische Kräfte auf bewegte Ladungen ",
"v: velocity of the charge (m/s)" : "v: Geschwindigkeit der Ladung (m/s) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "Kraft auf einen stromdurchflossenen Draht ",
"I: current (A), l: length of the wire (m)" : "I: Strom (A), l: Länge des Drahtes (m) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Kraft zwischen 2 parallelen Stromdrähten ",
"r: distance between two wires (m)" : "r: Abstand zwischen zwei Drähten (m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Magnetfeld eines langen Strom-Ladedraht ",
"r: perpendicular distance from the center of the wire (m)" : "r: senkrechter Abstand von der Mitte des Drahtes (m) ",
"MAGNETIC FIELD OF A LOOP" : "Magnetfeld einer Schleife ",
"n: number of turns per unit length of solenoid (turns/m)" : "n: Anzahl der Windungen pro Längeneinheit der Magnetspule (Umdrehungen/m) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Induzierte elektromotorische Kraft – Faraday Gesetz ",
"N: numbers of turns per loop (turns/m)" : "N: Anzahl der Windungen pro Schleife (Umdrehungen/m) ",
"INDUCTANCE" : "Induktivität ",
"ELECTRIC ENERGY" : "elektrische Energie ",
"MAGNETIC ENERGY" : "magnetische Energie ",
"ELECTRIC-MAGNETIC ENERGY" : "Elektro-magnetische Energie ",
"4. ALTERNATING CURRENT" : "4. Wechselstrom ",
"BASIC PARAMETERS" : "Grundparameters",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: Momentanstrom (A), I_o: maximale Momentanstrom (A), T: Periode der Welle, f: Frequenz, λ: Wellenlänge, c: Lichtgeschwindigkeit ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Effektiven Strom und Spannung ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Ohm Gesetz der Wechselstromwiderstand, die nur R ",
"CONTAINING ONLY INDUCTOR L" : "Die nur Induktivität L ",
"Z_L: inductive reactance" : "Z_L: induktive Reaktanz ",
"CONTAINING ONLY CAPACITOR C" : "Die nur der Kondensator C ",
"Z_C: capacitive reactance" : "Z_C: kapazitive Reaktanz ",
"CONTAINING R, L AND C IN A SERIES" : "Die R, L und C in einer Reihe ",
"Z: impedance" : "Z: Impedanz ",
"PHASE ANGLE" : "Phasenwinkel ",
"POWER FACTOR" : "Leistungsfaktor ",
"REAL POWER" : "Wirkleistung ",
"ELECTRICAL RESONANCE" : "Elektrische Resonanz ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Ändern Spannung mit Transformers ",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: Anzahl der Windungen in der Primärspule und Sekundärspule; U₁, U₂: primäre und sekundäre Spannung; I₁, I₂: primäre und sekundäre Ströme ",

"1. GAS LAWS" : "1. Gasgesetze ",
"KELVIN TEMPERATURE" : "Kelvin Temperatur ",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: Temperatur in Kelvin-Skala, t: Temperatur in Celsius-Skala ",
"EQUATION OF STATE" : "Zustandsgleichung ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: Druck (P, Pascal), V: Volumen (m³), n: Anzahl der Mole des Gases (mol), R: Gaskonstante, T: Kelvin Temperatur des Gases (K), k: Boltzmann-Konstante, N: Anzahl der Moleküle in der Gas ",
"IDEAL GAS LAW" : "Idealen Gasgesetz ",
"BOYLE’S LAW FOR PRESSURE" : "Boyle Gesetz für Druck ",
"If the temperature of the gas is constant" : "Wenn die Temperatur des Gases konstant ist ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Gay-Lussac Gesetz von Druck-Temperatur-",
"If the volume on a gas is constant" : "Wenn die Lautstärke auf einem Gas konstant ist ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: Druck des Gases bei der Temperatur t, p_o: Druck bei 0 Grad Celsius, γ: Faktor, wenn Volumen konstant ist ",
"Example when t=0 Kelvin" : "Beispielsweise bei t = 0 Kelvin ",
"CHARLES'S LAW OF VOLUMES" : "Charles Gesetz von Volumes ",
"If the pressure on a gas is constant" : "Wenn der Druck auf die Gaskonstante ist, ",
"2. CHANGES OF STATE AND SHAPE" : "2. Änderungen der staatlichen und Form ",
"HEAT" : "Wärme ",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: Wärme gesendet, Q_r: Wärme empfangen, m: Objekt Gesamtmasse (kg), c: spezifische Wärme (J/kg · K), ∆t: Änderung der Temperatur (K) ",
"The specific heats of some materials" : "Die spezifischen Wärmen einiger Materialien ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Fusion (Einfrieren oder Verfestigung) ",
"Heat of fusion of some materials" : "Schmelzwärme von einigen Materialien ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: Wärmemenge (J), λ: Schmelzwärme (J/kg), m: Masse (kg) ",
"VAPORIZATION" : "Verdampfung ",
"L: heat of vaporization" : "L: Verdampfungswärme ",
"Heat of vaporization of some materials" : "Verdampfungswärme von einigen Materialien ",
"LINEAR EXPANSION" : "Längenausdehnungs ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: ursprüngliche Länge (m), α: der lineare Ausdehnungskoeffizient (K⁻¹), ∆t: Temperaturänderung ",
"VOLUME EXPANSION" : "Volumenausdehnung ",
"AREA EXPANSION" : "Flächenausdehnung ",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Änderung der Dichte (Volumenmassendichte) ",
"D_o: original density (kg/m³)" : "D_o: ursprüngliche Dichte (kg/m³) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Änderung des Durchmessers des Querschnitts eines festen ",
"3. THERMODYNAMICS" : "3. Thermodynamik ",
"THE FIRST LAW OF THERMODYNAMICS" : "Das erste Gesetz der Thermodynamik ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "∆U: Änderung der inneren Energie, W: Arbeit durch das System, Q: Wärme in das oder aus dem System hinzugefügt ",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Anwendung des ersten Gesetzes zur idealen Gasgesetze ",
"- Volume is constant" : "- Volume ist konstant",
"- Pressure is constant, W': work created by gas" : "- Der Druck ist konstant, W': Werk von Gas ",
"- Temperature is constant" : "- Temperatur ist konstant",
"THE SECOND LAW OF THERMODYNAMICS" : "Der zweite Gesetz der Thermodynamik ",
"- The efficiency of a cyclic heat engine" : "- die Effizienz einer zyklischen Wärmekraftmaschine",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': durchgeführten Arbeiten pro Zyklus (J), Q₁: pro Zyklus aus der höheren Temperatur (J), Q₂' aufgenommene Wärme': Wärme pro Zyklus auf die niedrigere Temperatur abgelehnt (J) ",
"- Maximum thermal efficiency" : "- Maximale Wärme-effizienz",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: Höhere und niedrigere Temperaturen ",

"1. SIMPLE HARMONIC MOTION" : "1. Einfache harmonische Bewegung ",
"SPRING" : "Frühling ",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: Federkonstante (N/m), s: Verschiebung (m), ω: Winkelgeschwindigkeit (rad/s), T: Zeit, m: Masse des Objekts, A: Amplitude ",
"SPRINGS IN SERIES" : "Federn in Serie ",
"k: spring constant of the system, T: period of the system" : "k: Federkonstante des Systems, T: Zeit des Systems ",
"SPRINGS IN PARALLEL" : "Federn parallel ",
"SIMPLE PENDULUM" : "einfaches Pendel ",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: Winkelgeschwindigkeit (rad/s), T: Zeit, α_o: Winkel, in Amplitude, A: Amplitude, l: Länge des Pendels ",
"MOTION EQUATIONS" : "Bewegungsgleichungen ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: Verschiebung, α: Winkel, v: Geschwindigkeit, T: Stärke auf der Stange ",
"ENERGY" : "Energie ",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: potentielle Energie, E_k: kinetische Energie, E: mechanische Energie ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Wechsel der Zeit nach der Änderung der Temperatur ",
"α: coefficient of linear expansion of the rod" : "α: der lineare Ausdehnungskoeffizient des Stab ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Wechsel der Zeit nach der Änderung der Höhe ",
"h: height of pendulum, R: Earth's radius" : "h: Höhe des Pendels, R: Radius der Erde ",
"PENDULUM" : "Pendel ",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: Trägheitsmoment, ω: Winkelgeschwindigkeit, m: Masse von bob, d: OG, T: Zeit ",
"2. PERIODIC MOTION" : "2. Regelmäßige Bewegung ",
"WAVELENGTH" : "Wellenlänge ",
"FUNCTION OF WAVE AT SOME POINTS" : "Funktion der Welle an einigen Punkten ",
"WAVE INTERFERENCE" : "Interferenz ",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 Quellen der Welle mit derselben Phase; M: ein zufälliger Punkt ",
"3. SOUND WAVES" : "3. Schallwellen ",
"SOUND SPEED" : "Schallgeschwindigkeit ",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): Schallgeschwindigkeit in Umgebung mit Temperatur t (Celsius) ",
"SOUND INTENSITY " : "Schallintensität ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: Schallenergie (J), P: Schallleistung (W), A: Die Oberfläche einer Kugel (m²), t: Zeit (s) ",
"SOUND INTENSITY LEVEL" : "Schalldruckpegel ",
"I_o: the standard reference sound intensity" : "I_o: der Standard-Referenz-Schallintensität ",
"THE DOPPLER EFFECT" : "Der Dopplereffekt ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: die Relativgeschwindigkeit des Beobachters; v_S: die Relativgeschwindigkeit der Quelle; v: die Schallgeschwindigkeit in diesem Medium; f_S, f_O: Schallfrequenz der Quelle und Beobachter ",
"SOUND SPEED IN GASES" : "Schallgeschwindigkeit in Gasen ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: Schallgeschwindigkeit (m/s), R: allgemeine Gaskonstante, T: absolute Temperatur (K), M: Molekularmasse von Gas (kg/mol), γ: adiabatische Konstante ",
"Example in air" : "Beispiel in der Luft ",

"1. GEOMETRIC OPTICS" : "1. Geometrische Optik ",
"LAWS OF REFLECTION" : "Gesetze der Reflexion ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: einfallenden Strahl, IR: reflektierten Strahl, i: Einfallswinkel, i': Reflexionswinkel ",
"REFRACTIVE INDEX" : "Brechungsindex ",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: Brechungsindex des Mediums ein, v: Geschwindigkeit des Lichts in einem Medium, c: Lichtgeschwindigkeit im Vakuum (m/s) ",
"LAW OF REFRACTION" : "Brechungsgesetz ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: Brechungsindex des Mediums 1, n₂: Brechungsindex des Mediums 2, i: Einfallswinkel, r: Brechungswinkel, n₂₁: absolute Brechungsindex ",
"If medium 1 is vacuum" : "Wenn Medium 1 ist vakuum ",
"TOTAL REFLECTION PHENOMENON" : "Totalreflexion Phänomen ",
"There is no refracted ray if" : "Es gibt keine gebrochene Strahl, wenn ",
"PRISM" : "Prisma ",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: Scheitelwinkel, D: Abweichungswinkel, i₁: Einfallswinkel, i₂: Winkel emergent ray ",
"- Condition to have refractive ray" : "- Kondition, um Brechungsstrahl zu haben",
"- When angle of incidence is minimum" : "- Wenn der Einfallswinkel minimal ist",
"THIN LENS" : "dünne Linsen",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: Brennweite (konvergierenden len f&gt;0; divergier len f&lt;0), d: Objektabstand von der Objektivmitte, d': Bildabstand von der Objektivmitte ",
"MAGNIFICATION FACTOR" : "Vergrößerungsfaktor ",
"h_I: image height, h_O: object height" : "h_I: Bildhöhe, h_O: Objekthöhe ",
"POWER OF THE LENS" : "Kraft der Linse ",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: Brechungsindex des Linsenmaterials, R₁: Radius der Krümmung der Oberfläche len am nächsten an der Lichtquelle, R₂: Radius der Krümmung der Oberfläche am weitesten len von der Lichtquelle ",
"2. QUANTUM OF LIGHT" : "2. Ein Quantum Licht ",
"PHOTON ENERGY" : "Photonenergie ",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: Planck-Konstante, f: Frequenz (Hz), λ: Wellenlänge (m), c: Lichtgeschwindigkeit ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Zustand des photoelektrischen Effekts haben ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: Wellenlänge des blitzendes Licht, λ_o: photoelektrische Grenze, W: gestrahlt Arbeit (J)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Einstein-Gleichung über photoelektrischen Effekt ",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: Masse der Photoelektronen (kg), v_o: maximale Geschwindigkeit der Photoelektron (m/s) ",

"1. THEORY OF RELATIVITY" : "1. Theorie der Relativität ",
"MASS–ENERGY EQUIVALENCE" : "Masse-Energie-Equivalenz ",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: Masse (kg), E: Energie des Objekts (J), c: Lichtgeschwindigkeit (m/s)",
"LENGTH CONTRACTION" : "Längenkontraktion ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: natürliche Länge des Objekts, l: von einem Beobachter beobachtet Länge bewegt sich mit der Geschwindigkeit v ",
"RELATIVISTIC MASS" : "relativistische Masse ",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: Ruhemasse, m: relativistische Masse des Objekts bei der Bewegung mit der Geschwindigkeit v ",
"TIME DILATION" : "Zeitdilatation ",
"2. ATOMIC NUCLEUS" : "2. Atomkern ",
"NUCLEAR MAKEUP" : "Kern Make-up ",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: Anzahl der Protonen, N: Anzahl der Neutronen, A: Massenzahl, ",
"NUCLEAR REACTION" : "Kernreaktion ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: Kernreaktion wird Energie frei",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: Kernreaktion absorbiert Energie",
"RADIOACTIVE DECAY" : "Radioaktiver Zerfall ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: Anfangsmenge an Wirkstoff, N: Menge, die immer noch und ist noch nicht nach einer Zeit t verfallen, ∆N: Anzahl der verfallenen Substanz, m_o: Anfangsmasse, m: Masse der übrigen, λ: Zerfallskonstante, t: Zeit, T: Halbwertszeit ",
"Half life of some elements" : "Halbwertszeit von einigen Elementen ",
"AMOUNT OF RADIOACTIVITY" : "Menge der Radioaktivität ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: Anfangs Menge an Radioaktivität, H: Menge der Radioaktivität zum Zeitpunkt t ",
"1. CONSTANTS" : "1. Konstanten ",
"ALPHA PARTICLE MASS" : "Alpha-Partikeln Masse ",
"ATOMIC MASS CONSTANT" : "Atommasse konstant ",
"ATOMIC UNIT OF ENERGY" : "Atomenergieeinheit ",
"ATOMIC UNIT OF FORCE" : "Atomkrafteinheit ",
"ATOMIC UNIT OF LENGTH" : "Atomlängeneinheit ",
"ATOMIC UNIT OF MASS" : "Atommasseneinheit ",
"AVOGADRO'S CONSTANT" : "Avogadro-Konstante ",
"BOHR RADIUS" : "Bohr-Radius ",
"BOLTZMANN CONSTANT" : "Boltzmann-Konstante ",
"CLASSICAL ELECTRON RADIUS" : "klassische Elektronenradius ",
"ELEMENTARY CHARGE" : "Elementarladung ",
"EARTH MASS" : "Erdmasse ",
"EARTH EQUATORIAL RADIUS" : "Erde Äquatorradius ",
"EARTH MEAN ORBITAL VELOCITY" : "Erde bedeuten Umlaufgeschwindigkeit ",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Erde Drehwinkelgeschwindigkeit ",
"FARADAY’S CONSTANT" : "Faraday-Konstante ",
"GAS CONSTANT" : "Gaskonstante ",
"MOLAR MASS CONSTANT" : "Molmasse konstant ",
"MOLAR VOLUME OF IDEAL GAS" : "Molvolumen des idealen Gas ",
"NEUTRON MASS" : "Neutronenmasse ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Newton Gravitationskonstante ",
"PLANCK’S CONSTANT" : "Planck-Konstante ",
"PLANCK MASS" : "Planck-Masse ",
"PROTON MASS" : "Protonenmasse ",
"PROTON-ELECTRON MASS RATIO" : "Proton-Elektron-Massenverhältnis ",
"SPEED OF LIGHT IN VACUUM" : "Lichtgeschwindigkeit im Vakuum ",
"STANDARD ACCELERATION OF GRAVITY" : "Erdbeschleunigung ",
"STANDARD ATMOSPHERE" : "Standardatmosphäre ",
"STANDARD REFERENCE SOUND INTENSITY" : "Standard-Referenzschallintensität ",
"STEFAN-BOLTZMANN CONSTANT" : "Stefan-Boltzmann-Konstante ",
"2. GREEK ALPHABET" : "2. griechische Alphabet ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: griechische Buchstabe, C2: Name, C3: Entspricht, C4: Sound, wenn gesprochen ",

"Mechanics" : "Mechanik ",
"Thermal physics" : "Thermophysik ",
"Optics" : "Optik ",
"Theory of relativity" : "Relativitätstheorie ",

"FREE FALLING" : "Freien Fall ",
"VERTICAL PROJECTILE" : "Vertikale Projektil ",
"ANGLED PROJECTILE" : "Abgewinkelten Projektil ",
"HORIZONTAL PROJECTILE" : "Horizontal Projektil ",
"SLIDING MOTION" : "Schiebebewegung ",
"ATTRACTIVE FORCE" : "Anziehungskraft ",
"Hydraulic press" : "Hydraulische Presse ",
"PRESSURE" : "Druck ",
"LINEAR EXPANSION" : "Längenausdehnungs ",
"VOLUME EXPANSION" : "Volumenausdehnung ",
"SOUND SPEED" : "Schallgeschwindigkeit ",
"REFRACTION" : "Brechung ",
"PRISM" : "Prisma ",
"LENS" : "Objektiv ",
"Length contraction" : "Längenkontraktion ",
"Time dilation" : "Zeitdilatation ",
"RELATIVISTIC MASS" : "relativistische Masse ",

"Height " : "Höhe ",
"Time to touchdown " : "Zeit bis zum Aufsetzen ",
"Touchdown velocity " : "Touchdown-Geschwindigkeit ",
"Initial velocity " : "Anfangsgeschwindigkeit ",
"Maximum height " : "Maximale Höhe ",
"Initial velocity " : "Anfangsgeschwindigkeit ",
"Angle " : "Winkel ",
"Maximum height " : "Maximale Höhe ",
"Maximum distance " : "Maximaler Abstand ",
"Height " : "Höhe ",
"Initial velocity " : "Anfangsgeschwindigkeit ",
"Time to touchdown " : "Zeit bis zum Aufsetzen ",
"Touchdown velocity " : "Touchdown-Geschwindigkeit ",
"Angle of titled plane " : "Winkel mit dem Titel Flugzeug ",
"Coefficient of friction " : "Reibungskoeffizient ",
"Acceleration " : "Beschleunigung ",
"Mass " : "Masse ",
"Mass " : "Masse ",
"Distance " : "Abstand ",
"Attractive force " : "Anziehungskraft ",
"Area " : "Bereich ",
"Area " : "Bereich ",
"Force " : "Kraft ",
"Force" : "Kraft ",
"Force F₂ (or F₁)" : "Kraft F₂ (oder F₁) ",
"Temperature " : "Temperatur ",
"Pressure at 0°C " : "Druck bei 0°C ",
"Pressure " : "Druck ",
"Original length " : "Originallänge ",
"Temperature change " : "Temperaturänderung ",
"Coefficient of linear expansion " : "Der lineare Ausdehnungskoeffizient ",
"Change of length " : "Längenänderung ",
"Original volume " : "Ursprünglichen Volumens ",
"Temperature change " : "Temperaturänderung ",
"Coefficient of linear expansion " : "Der lineare Ausdehnungskoeffizient ",
"Change of volume " : "Volumenänderung ",
"Temperature " : "Temperatur ",
"Sound speed " : "Schallgeschwindigkeit ",
"Refractive index " : "Brechungsindex ",
"Refractive index " : "Brechungsindex ",
"Angle of incidence " : "Einfallswinkel ",
"Angle of refraction " : "Brechungswinkel ",
"Angle (r or i) " : "Winkel (r oder i) ",
"Apex angle " : "Öffnungswinkel ",
"Angle of incident " : "Winkel des einfallenden ",
"Refractive index " : "Brechungsindex ",
"Angle of emergent ray " : "Winkel von emergenten ray ",
"Deviation angle " : "Abweichungswinkel ",
"Focal length " : "Brennweite ",
"Object distance " : "Objektabstand ",
"Image distance " : "Bildweite ",
"Image (or object) distance" : "Bild (oder Objekt) Abstand ",
"Magnification factor " : "Vergrößerungsfaktor ",
"Speed " : "Geschwindigkeit ",
"Proper length " : "Richtige Länge ",
"Observed length " : "Beobachteten Länge ",
"Rest mass " : "Ruhemasse ",
"Relativistic mass " : "Relativistische Masse ",
"Proper time interval " : "Richtigen Zeitintervall ",
"Observed time interval " : "Beobachteten Zeitintervall ",
"Calculate" : "Berechnen ",
"Or input" : "Oder Eingabe ",
"Calculation Tools" : "Berechnungstools ",


	
};