var language={

"1. DYNAMICS" : "1. डायनेमिक्स",
"STRAIGHT LINE MOTION" : "सीधी रेखा मोशन",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: दूरी (m, मीटर), t: समय (s, सेकण्ड), v: वेग (m/s, मीटर/सेकण्ड), v_a: औसत वेग",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "निरंतर त्वरण सीधी रेखा मोशन",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: त्वरण, v_o: प्रारंभिक वेग, v: समय टी में वेग",
"DISTANCE FUNCTION" : "दूरी समारोह",
"x_o: initial distance from origin, x: distance at time t" : "x_o: मूल से प्रारंभिक दूरी, एक्स: दूरी समय टी में",
"UNIFORM CIRCULAR MOTION" : "एकसमान वृत्तीय गति",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: कोण (rad, रेड), l: चाप की लंबाई, R: वृत्त की त्रिज्या, ω: कोणीय वेग (रेड/एस), t: समय वस्तु l की लंबाई चालें",
"CENTRIPETAL FORCE" : "सेंट्ररपेटल फ़ोर्स",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "F: आवृत्ति (Hz, हर्ट्ज), T: एक रोटेशन (s, सेकण्ड) के लिए अवधि, a: केन्द्राभिमुख त्वरण, F: केन्द्राभिमुख बल (N, न्यूटन)",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "लगातार त्वरण परिपत्र गति",
"γ: angular acceleration" : "γ: कोणीय त्वरण",
"ACCELERATION" : "त्वरण",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: स्पर्शरेखा त्वरण, a_n: सामान्य त्वरण",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1:गति बढ़ाना, P2: वर्दी परिपत्र गति, P3: धीमा",
"FREE FALLING FROM HEIGHT h" : "ऊंचाई ज से मुफ्त गिरना",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: गुरुत्वाकर्षण त्वरण, v: t में वेग, s: दूरी t समय के बाद, v_h : वेग जमीन, छू जब: t_h उतरना के लिए समय",
"VERTICAL PROJECTILE MOTION" : "ऊपर फेंकने की क्रिया",
"h_max: maximum height, v_o: initial velocity" : "h_max: अधिकतम ऊंचाई, v_o: प्रारंभिक वेग",
"Motion equation and velocity equation" : "मोशन समीकरण और वेग समीकरण",
"ANGLED PROJECTILE MOTION" : "कोणीय फेंकने प्रस्ताव",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: वेग; x, y: टी द्वारा प्रस्ताव समीकरण; H: अधिकतम ऊंचाई; L: अधिकतम दूरी",
"HORIZONTAL PROJECTILE MOTION" : "क्षैतिज फेंकने की क्रिया",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: जमीन को छूने का समय, v_h: जमीन को छूने का वेग ",
"SLIDING MOTION ON AN INCLINED PLANE" : "झुका हुआ सतह पर रपट मोशन ",
"μ: coefficient of friction" : "μ: घर्षण के गुणांक",
"Fiction coefficient of some materials" : "कुछ सामग्री के घर्षण गुणांक",
"2. FORCES" : "2. बलों",
"ATTRACTIVE FORCE" : "आकर्षक बल",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: 2 वस्तुओं की बड़े पैमाने पर; r: दो वस्तुओं के बीच की दूरी; G: गुरुत्वाकर्षण स्थिरांक",
"GRAVITATIONAL FORCE" : "गुरुत्वाकर्षण बल",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: पृथ्वी जन, m: वस्तु के द्रव्यमान, R: पृथ्वी की त्रिज्या, h: वस्तु की ऊंचाई",
"GRAVITATIONAL ACCELERATION" : "गुरुत्वीय त्वरण",
"At a height h above the nominal surface of the earth" : "पृथ्वी की नाममात्र की सतह से ऊपर h ऊंचाई पर",
"Near the sea level" : "समुद्र स्तर के पास",
"FORCE OF GRAVITY" : "गुरुत्वाकर्षण का बल",
"Force of gravity on earth, a special case of Gravitational force" : "पृथ्वी पर गुरुत्वाकर्षण बल, गुरुत्वाकर्षण बल के एक विशेष मामला",
"NEWTON'S FIRST LAW" : "न्यूटन के पहले कानून",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: बलों वस्तु पर अभिनय, v: वस्तु का वेग, a: वस्तु के त्वरण",
"NEWTON'S SECOND LAW" : "न्यूटन के दूसरे कानून",
"m: object's mass (kg)" : "m: वस्तु का द्रव्यमान (kg, किलो)",
"NEWTON'S THIRD LAW" : "न्यूटन के तीसरे नियम",
"LINEAR ELASTICITY - HOOKE'S LAW" : "रैखिक लोच - हूक के नियम",
"k: spring constant (N/m), x: displacement (m)" : "k: वसंत निरंतर (N/m, न्यूटन/मी), x: विस्थापन (m, मीटर)",
"A mass suspended by a spring" : "एक स्प्रिंग से निलंबित एक मास",
"FORCE OF FRICTION" : "घर्षण बल",
"μ: coefficient of friction, N: normal force" : "μ: घर्षण के गुणांक: N सीधा बल",
"3. STATICS" : "3. स्टैटिक्स",
"MOMENT OF A FORCE" : "एक बल के क्षण",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: (न्यूटन) लागू बल, d: पल बांह (बल की कार्रवाई की लाइन के लिए धुरी से सीधा दूरी)",
"MOMENT APPLICATION" : "पल आवेदन",
"MOMENT OF INERTIA" : "निष्क्रियता के पल",
"Rod of length l" : "लंबाई एल के रॉड",
"Thin circular hoop/ Thin cylindrical shell" : "पतला परिपत्र घेरा/पतला बेलनाकार खोल",
"Solid disk/ Solid cylinder" : "ठोस डिस्क/ठोस सिलेंडर",
"Solid ball" : "ठोस गेंद",
"Hollow sphere" : "खोखला गोला",
"ANGULAR MOMENTUM" : "कोनेदार गति",
"I: moment of inertia, ω: angular velocity" : "I: जड़ता के छन, ω: कोणीय वेग",
"PLANE MOTION OF A RIGID BODY" : "एक कठोर शरीर के विमान गति",
"γ: angular acceleration, M: moment of a force" : "γ: कोणीय त्वरण, M: एक शक्ति का क्षण",

"4. CONSERVATION LAWS" : "4. संरक्षण कानून",
"MOMENTUM OF FORCE" : "बल की गतिमात्रा",
"LAW OF CONSERVATION OF MOMENTUM" : "गतिमात्रा के संरक्षण के कानून",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: वस्तुओं 1 और 2 के प्रारंभिक वेग; v₁', v₂': वस्तु 1 और 2 के अंतिम वेग",
"PLASTIC COLLISION" : "प्लास्टिक टक्कर",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': प्रभाव के बाद दो शरीर प्रणाली के वेग (m₁ + m₂)",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "एक आयामी लोचदार टक्कर",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': प्रभाव के बाद m₁ और m₂ का वेग",
"5. WORK AND ENERGY" : "5. कार्य और ऊर्जा",
"WORK" : "काम",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: एक बल (जे) द्वारा किए गए कार्य, F: बल एक वस्तु को स्थानांतरित करना के लिए, α: कोण F और संचलन की दिशा के बीच",
"EXAMPLES" : "उदाहरण",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: गंभीरता से काम करते हैं, h: ऊंचाई में परिवर्तन; W_ms: घर्षण के बल का काम; W: एक स्प्रिंग से काम",
"POWER" : "शक्ति",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: शक्ति (वाट, W), t: काम डब्ल्यू आयोजित करने का समय (s)",
"KINETIC ENERGY" : "गतिज ऊर्जा",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "एक बड़े पैमाने पर घूर्णन शरीर की गतिज ऊर्जा",
"WORK-ENERGY PRINCIPLE" : "कार्य-ऊर्जा सिद्धांत",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: पहले और परिवर्तन के बाद वस्तु की गति",
"POTENTIAL ENERGY" : "संभावित ऊर्जा",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: गुरुत्वाकर्षण संभावित ऊर्जा (J), m: वस्तु के द्रव्यमान (kg, किलो)",
"CONSERVATION OF MECHANICAL ENERGY" : "यांत्रिक ऊर्जा का संरक्षण",
"CONSERVATION OF ENERGY" : "ऊर्जा संरक्षण",
"6. MECHANICS OF FLUIDS" : "6. तरल पदार्थ की मैकेनिक्स",
"DENSITY" : "घनत्व",
"m: mass of a volume V" : "m: आद्यतन मात्रा V के द्रव्यमान",
"PRESSURE" : "दबाव",
"F: force applied on area of A" : "F: बल के क्षेत्र पर लागू होता है",
"PRESSURE OF LIQUIDS" : "तरल पदार्थ का दबाव",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: विशिष्ट गुरुत्व (न्यूटन/घन मीटर), p_o: मुक्त सतह पर हवा के दबाव (न्यूटन/वर्ग मीटर), p: उपरोक्त तरल के वजन से बनाया दबाव, p_B गहराई h में कुल दबाव:",
"PASCAL’S PRINCIPLE" : "पास्कल के सिद्धांत",
"p_s: pressure on the surface" : "p_s: सतह पर दबाव",
"APPLICATION" : "प्रयोग",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: छोटे और बड़े सिलेंडरों के क्षेत्र; F₁, F₂: आवेदन किया है और ऊपर की ओर बलों",
"ARCHIMEDES’ PRINCIPLE" : "आर्किमिडीज के सिद्धांत",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: तरल के विशिष्ट गुरुत्व (N/m³, न्यूटन/घन मीटर), V: वस्तु की मात्रा, F_b: प्रसन्नचित्त बल",
"FLOW RATE" : "प्रवाह दर",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: पार के अनुभागीय क्षेत्र (m², वर्ग मीटर), v: प्रवाह वेग (m/s, मीटर/सेकंड), Q: प्रवाह दर (m³/s, घन मीटर/सेकंड)",

"1. ELECTROSTATICS" : "1. स्थिरवैद्युतिकी",
"COULOMB’S LAW" : "कूलॉम-नियम",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: आरोपों का आकार (C, सी), ε: आपेक्षिक विद्युतशीलता (निर्वात ε = 1 में), r: आरोपों के बीच की दूरी (m, मीटर)",
"ELECTRIC FIELDS" : "बिजली क्षेत्र",
"E: electric field strength (N/C)" : "ई: बिजली के क्षेत्र शक्ति (N/C, न्यूटन/ सी)",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "बिजली क्षेत्र के लिए सुपरस्थिति के सिद्धांत",
"In case of 2 electric fields" : "दो बिजली क्षेत्र के मामले में",
"WORK OF ELECTRIC FORCE" : "बिजली बल का कार्य",
"ELECTRIC POTENTIAL DIFFERENCE" : "बिजली क्षमता का अंतर",
"RELATION BETWEEN E AND U" : "E और U के बीच संबंध",
"CAPACITANCE" : "समाई",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: समाई (F, एफ), Q: कुल बिजली का आरोप (C, सी), U: बिजली क्षमता (V, वी)",
"CAPACITOR" : "संधारित्र",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "d: इलेक्ट्रोड के बीच की दूरी (m, मीटर), ε: आपेक्षिक विद्युतशीलता (F/m, एफ/एम), A: प्रत्येक इलेक्ट्रोड प्लेट क्षेत्रफल (m², वर्ग मीटर)",
"CAPACITANCES IN SERIES" : "श्रृंखला में समाई",
"CAPACITANCES IN PARALLEL" : "समानांतर में समाई",
"ELECTRIC FIELD ENERGY" : "बिजली के क्षेत्र में ऊर्जा",
"ENERGY OF CAPACITOR" : "संधारित्र की ऊर्जा",
"V=A.d: volume between two electrode plates" : "V= A.d: दो इलेक्ट्रोड प्लेटों के बीच मात्रा",
"2. DIRECT CURRENT" : "2. डायरेक्ट करंट",
"ELECTRIC CURRENT" : "विद्युत प्रवाह",
"I: current (A), q: charge (C), t: time" : "I: विद्युत धारा (A, ए), q: प्रभारी (C, सी), t: समय",
"OHM’S LAW" : "ओम कानून",
"U: electric potential difference between the ends of the resistor R" : "U: रोकनेवाला R के सिरों के बीच बिजली के संभावित अंतर",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "एक मौजूदा द्वारा बनाई गई कार्य (जूल के नियम)",
"ELECTRICAL POWER" : "विद्युत शक्ति",
"RESISTANCE" : "प्रतिरोध",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ:सामग्री के प्रतिरोधकता पार (Ωm, ओम मीटर), l: लंबाई (मीटर), A: एल के प्रतिरोधकता पार, A:अनुभाग क्षेत्र (वर्ग मीटर)",
"SERIES CIRCUITS" : "सीरीज सर्किट",
"PARALLEL CIRCUITS" : "समानांतर सर्किट",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "एक अवरोध द्वारा उत्पादित कार्य या गर्मी ऊर्जा",
"POWER CONSUMPTION OF A RESISTOR" : "एक अवरोध की बिजली की खपत",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "एक विद्युत जनरेटर का इलेक्ट्रोमोटिव बल",
"W: work of force (J), q: charge (C)" : "W: सेना का काम (J, जे), q: प्रभारी (C, सी)",
"GENERATORS IN SERIES" : "श्रृंखला में जेनरेटर",
"r: internal resistance of the generator" : "r: जनरेटर की आंतरिक विरोध",
"GENERATORS IN PARALLEL" : "समानांतर में जेनरेटर",
"GENERATORS IN SERIES-PARALLEL" : "श्रृंखला समानांतर में जेनरेटर",
"WORK AND POWER OF GENERATOR" : "कार्य और जनरेटर की बिजली",
"H: Efficiency of generator" : "H: जनरेटर की क्षमता",
"3. MAGNETISM" : "3. चुंबकत्व",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "खुले सतह S के माध्यम से चुंबकीय प्रवाह",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: चुंबकीय क्षेत्र की भयावहता (T, टेस्ला), α: कोण की सतह के लिए बी और सीधा लाइन के बीच",
"MAGNETIC FORCES ON MOVING CHARGES" : "बढ़ते प्रभार पर चुंबकीय बलों",
"v: velocity of the charge (m/s)" : "v: प्रभारी के वेग (m/s, मीटर/सेकंड)",
"FORCE ON A CURRENT-CARRYING WIRE" : "एक वर्तमान-पेट वायर पर बल",
"I: current (A), l: length of the wire (m)" : "I: वर्तमान (A, ए), l: तार की लंबाई (मीटर)",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "सेना के बीच दो समानांतर वर्तमान-ले जाने के तार",
"r: distance between two wires (m)" : "r: दो तारों के बीच की दूरी (मीटर)",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "एक लंबे समय के वर्तमान प्रभारी तार के चुंबकीय क्षेत्र",
"r: perpendicular distance from the center of the wire (m)" : "r: तार के केन्द्र से दूरी सीधा (मीटर)",
"MAGNETIC FIELD OF A LOOP" : "एक लूप के चुंबकीय क्षेत्र",
"n: number of turns per unit length of solenoid (turns/m)" : "n: परिनालिका की इकाई लंबाई के अनुसार बदल जाता है की संख्या (बदल जाता है/मी)",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "प्रेरित इलेक्ट्रोमोटिव बल - फैराडे का कानून",
"N: numbers of turns per loop (turns/m)" : "N: पाश प्रति बदल जाता है की संख्या (बदल जाता है/मी)",
"INDUCTANCE" : "अधिष्ठापन",
"ELECTRIC ENERGY" : "विद्युत ऊर्जा",
"MAGNETIC ENERGY" : "चुंबकीय ऊर्जा",
"ELECTRIC-MAGNETIC ENERGY" : "इलेक्ट्रिक-चुंबकीय ऊर्जा",
"4. ALTERNATING CURRENT" : "4. बारी वर्तमान",
"BASIC PARAMETERS" : "बुनियादी मानकों",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: तात्कालिक वर्तमान (ए), I_o: अधिकतम तात्कालिक वर्तमान (ए), T: लहर, f की अवधि: आवृत्ति, λ: तरंगदैर्ध्य, c: प्रकाश की गति",
"EFFECTIVE CURRENT AND VOLTAGE" : "प्रभावी वर्तमान और वोल्टेज",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "केवल प्रतिरोध आर युक्त एसी चालू की ओम कानून",
"CONTAINING ONLY INDUCTOR L" : "केवल प्रारंभ करनेवाला L युक्त",
"Z_L: inductive reactance" : "Z_L: आगमनात्मक मुक़ाबला",
"CONTAINING ONLY CAPACITOR C" : "युक्त केवल संधारित्र C",
"Z_C: capacitive reactance" : "Z_C: कैपेसिटिव मुक़ाबला",
"CONTAINING R, L AND C IN A SERIES" : "एक श्रृंखला में R, L और C युक्त",
"Z: impedance" : "Z: प्रतिबाधा",
"PHASE ANGLE" : "अवस्था कोण",
"POWER FACTOR" : "ऊर्जा घटक",
"REAL POWER" : "असली शक्ति",
"ELECTRICAL RESONANCE" : "विद्युत गूंज",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "ट्रांसफॉर्मर के साथ वोल्टेज बदलने से",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: प्राथमिक कुंडल और माध्यमिक कुंडल में घुमावों की संख्या; U₁, U₂: प्राथमिक और माध्यमिक वोल्टेज; I₁, I₂: प्राथमिक और माध्यमिक धाराओं",

"1. GAS LAWS" : "1. गैस कानूनों",
"KELVIN TEMPERATURE" : "केल्विन तापमान",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: केल्विन पैमाने पर में तापमान, t: सेल्सियस पैमाने में तापमान",
"EQUATION OF STATE" : "स्थिति के समीकरण",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: दबाव (P, पास्कल), V: मात्रा (घन मीटर), n: गैस (मोल) के मोल्स की संख्या, अनुसंधान, R: यूनिवर्सल गैस निरंतर, T: गैस के केल्विन तापमान, k: बोल्ट्जमान के निरंतर, N: गैस में अणुओं की संख्या",
"IDEAL GAS LAW" : "आदर्श गैस कानून",
"BOYLE’S LAW FOR PRESSURE" : "दबाव के लिए बॉयल के नियम",
"If the temperature of the gas is constant" : "गैस का तापमान स्थिर है, तो",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "दबाव तापमान के Gay-Lussac का कानून",
"If the volume on a gas is constant" : "एक गैस पर मात्रा स्थिर है, तो",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: तापमान टी में गैस के दबाव, p_o: 0 सेल्सियस पर दबाव, γ: कारक मात्रा दबाव स्थिर है जब",
"Example when t=0 Kelvin" : "t = 0 केल्विन, उदाहरण",
"CHARLES'S LAW OF VOLUMES" : "संस्करणों के चार्ल्स का कानून",
"If the pressure on a gas is constant" : "एक गैस पर दबाव स्थिर है तो",
"2. CHANGES OF STATE AND SHAPE" : "2. राज्य और आकार परिवर्तन",
"HEAT" : "गर्मी",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: गर्मी उत्सर्जित, Q_r: गर्मी प्राप्त किया, m: वस्तु के कुल द्रव्यमान (किलो), C: विशिष्ट गर्मी (J/kg.K), Δt: तापमान में परिवर्तन (K)",
"The specific heats of some materials" : "कुछ सामग्री के विशिष्ट तपता",
"FUSION (FREEZING OR SOLIDIFICATION)" : "फ्यूजन (ठंड या दृढ़ीभवन)",
"Heat of fusion of some materials" : "कुछ सामग्री के विलय की गर्मी",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: गर्मी की मात्रा (जे), λ: संलयन की गर्मी (ज/किग्रा), m: द्रव्यमान (किलो)",
"VAPORIZATION" : "वाष्पीकरण",
"L: heat of vaporization" : "L: वाष्पीकरण की गर्मी",
"Heat of vaporization of some materials" : "कुछ सामग्री का वाष्पीकरण की गर्मी",
"LINEAR EXPANSION" : "रैखिक विस्तार",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: मूल लंबाई (एम), α: रैखिक विस्तार के गुणांक (K⁻¹), Δt: तापमान में परिवर्तन",
"VOLUME EXPANSION" : "मात्रा विस्तार",
"AREA EXPANSION" : "क्षेत्र विस्तार",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "घनत्व के बदले (बड़ा जन घनत्व)",
"D_o: original density (kg/m³)" : "D_o: मूल घनत्व (किलो/घन मीटर)",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "एक ठोस के पार अनुभाग के व्यास का परिवर्तन",
"3. THERMODYNAMICS" : "3. ऊष्मप्रवैगिकी",
"THE FIRST LAW OF THERMODYNAMICS" : "ऊष्मप्रवैगिकी के पहले कानून",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU: आंतरिक ऊर्जा में बदलने के लिए, W: सिस्टम द्वारा किए गए कार्य, Q: गर्मी में या सिस्टम से बाहर जोड़ा",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "आदर्श गैस कानूनों के पहले कानून के आवेदन",
"- Volume is constant" : "- माप स्थिर है",
"- Pressure is constant, W': work created by gas" : "- दबाव निरंतर है, W': गैस के द्वारा बनाई गई काम",
"- Temperature is constant" : "- तापमान स्थिर है",
"THE SECOND LAW OF THERMODYNAMICS" : "ऊष्मप्रवैगिकी के दूसरे कानून",
"- The efficiency of a cyclic heat engine" : "- एक चक्रीय गर्मी इंजन की क्षमता",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': काम चक्र (जे) के अनुसार किया जाता, Q₁: उच्च तापमान (जे) से प्रति चक्र अवशोषित गर्मी, Q₂': कम तापमान के प्रति चक्र को अस्वीकार कर दिया गर्मी (जे)",
"- Maximum thermal efficiency" : "- अधिकतम थर्मल दक्षता",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: उच्च और निम्न तापमान",

"1. SIMPLE HARMONIC MOTION" : "1. सरल आवर्त गति",
"SPRING" : "वसंत",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: वसंत निरंतर (N/m, एन/मी), s: विस्थापन (एम), ω: कोणीय वेग (रेड/एस), T: अवधि, m: वस्तु के द्रव्यमान, A: आयाम",
"SPRINGS IN SERIES" : "श्रृंखला में स्प्रिंग्स",
"k: spring constant of the system, T: period of the system" : "k: प्रणाली के वसंत निरंतर, T: सिस्टम की अवधि",
"SPRINGS IN PARALLEL" : "समानांतर में स्प्रिंग्स",
"SIMPLE PENDULUM" : "सरल लोलक",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: कोणीय वेग (रेड/एस), T: अवधि, α_o: आयाम पर कोण, A: आयाम, l: पेंडुलम की लंबाई",
"MOTION EQUATIONS" : "मोशन समीकरणों",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: विस्थापन, α: कोण, v: वेग, T: रॉड पर ताकत",
"ENERGY" : "शक्ति",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: ऊर्जा क्षमता, E_k: गतिज ऊर्जा, E: मैकेनिक ऊर्जा",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "तापमान के परिवर्तन के बाद की अवधि के बदले",
"α: coefficient of linear expansion of the rod" : "α: छड़ी के रैखिक विस्तार के गुणांक",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "ऊंचाई के परिवर्तन के बाद की अवधि के बदले",
"h: height of pendulum, R: Earth's radius" : "h: पेंडुलम की ऊंचाई, R: पृथ्वी की त्रिज्या",
"PENDULUM" : "लंगर",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: जड़ता के क्षण, ω:कोणीय वेग, m: बॉब की बड़े पैमाने पर, d: OG, T:अवधि",
"2. PERIODIC MOTION" : "2. आवधिक गति",
"WAVELENGTH" : "वेवलेंथ",
"FUNCTION OF WAVE AT SOME POINTS" : "कुछ बिंदुओं पर लहर के फंक्शन",
"WAVE INTERFERENCE" : "वेव हस्तक्षेप",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: लहर के दो सूत्रों का कहना है एक ही चरण होने; M: एक यादृच्छिक बिंदु",
"3. SOUND WAVES" : "3. ध्वनि तरंगों",
"SOUND SPEED" : "ध्वनि की गति",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (एम/एस): तापमान t के साथ वातावरण में ध्वनि की गति (सेल्सियस)",
"SOUND INTENSITY " : "ध्वनि की तीव्रता",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: ध्वनि ऊर्जा (जे), P: ध्वनि शक्ति (W), A: एक क्षेत्र (वर्ग मीटर) की सतह क्षेत्र, t: समय (सेकंड)",
"SOUND INTENSITY LEVEL" : "ध्वनि तीव्रता स्तर",
"I_o: the standard reference sound intensity" : "I_o: मानक संदर्भ ध्वनि तीव्रता",
"THE DOPPLER EFFECT" : "डॉपलर प्रभाव",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: पर्यवेक्षक के सापेक्ष गति; v_S: स्रोत के सापेक्ष गति; v: इस माध्यम में ध्वनि की गति; f_S, f_O: स्रोत और प्रेक्षक की ध्वनि आवृत्ति",
"SOUND SPEED IN GASES" : "गैसों में ध्वनि की गति",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v:ध्वनिकी गति, R: यूनिवर्सल गैस निरंतर, T: पूर्ण तापमान (के), M: गैस की आणविक द्रव्यमान (किलो/मोल), γ: ऐडियाबैटिक लगातार ",
"Example in air" : "हवा में उदाहरण",

"1. GEOMETRIC OPTICS" : "1. ज्यामितीय प्रकाशिकी",
"LAWS OF REFLECTION" : "परावर्तन के नियमों",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: घटना रे, IR: परिलक्षित रे, i: घटना के कोण, i': प्रतिबिंब के कोण",
"REFRACTIVE INDEX" : "अपवर्तनांक",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: का अपवर्तनांक एक मध्यम, v: एक माध्यम में प्रकाश की गति, c: शून्य में प्रकाश की गति (एम/एस)",
"LAW OF REFRACTION" : "अपवर्तन के कानून",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: मध्यम 1 का अपवर्तनांक, n₂ मध्यम 2 का अपवर्तनांक, i: संयोग के कोण, r:अपवर्तनके कोण, n₂₁: अपवर्तन के निरपेक्ष सूचकांक ",
"If medium 1 is vacuum" : "मध्यम 1 निर्वात है तो",
"TOTAL REFLECTION PHENOMENON" : "कुल प्रतिबिंब घटना",
"There is no refracted ray if" : "कोई अपवर्तित किरण अगर नहीं है",
"PRISM" : "प्रिज्म",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: सुप्रीम कोण, D: विचलन कोण, i₁: घटना के कोण, i₂: आकस्मिक रे के कोण",
"- Condition to have refractive ray" : "- दशा अपवर्तक रे के लिए है",
"- When angle of incidence is minimum" : "- घटना के कोण न्यूनतम है जब",
"THIN LENS" : "पतला लेंस",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: फोकल लम्बाई (अभिसारी लेंस f&gt;0; अपसारी लेंस f&lt;0), d: लेंस केंद्र से वस्तु की दूरी, d': लेंस केंद्र से छवि दूरी",
"MAGNIFICATION FACTOR" : "आवर्धन कारक",
"h_I: image height, h_O: object height" : "h_I: छवि ऊंचाई, h_O: वस्तु ऊंचाई",
"POWER OF THE LENS" : "लेंस की पावर",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: लेंस सामग्री का अपवर्तनांक, R₁: प्रकाश स्रोत के लिए निकटतम लेन सतह की वक्रता त्रिज्या, R₂: प्रकाश स्रोत से लेन सतह सब से अधिक दूर की वक्रता त्रिज्या",
"2. QUANTUM OF LIGHT" : "2. प्रकाश का क्वांटम",
"PHOTON ENERGY" : "फोटॉन ऊर्जा",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: प्लैंक स्थिरांक, f: आवृत्ति (हर्ट्ज), λ: तरंगदैर्ध्य (मीटर), c: प्रकाश की गति",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "हालत विद्युतप्रकाशीय प्रभाव है करने के लिए",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: चमकना प्रकाश की तरंग दैर्ध्य, λ_o: विद्युतप्रकाशीय सीमा, W: उत्सर्जित काम (जे)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : " विद्युतप्रकाशीय प्रभाव के बारे में आइंस्टीन के समीकरण",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: प्रकाश-इलेक्ट्रॉन (किलो), के द्रव्यमान, v_o:प्रकाश-इलेक्ट्रॉन की अधिकतम गति (मीटर/सेकंड)",

"1. THEORY OF RELATIVITY" : "सापेक्षता के थ्योरी",
"MASS–ENERGY EQUIVALENCE" : "जन ऊर्जा तुल्यता",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: द्रव्यमान (kg, किलो), E: वस्तु की ऊर्जा (J, जे), C: प्रकाश की गति (m/s, मीटर/सेकंड)",
"LENGTH CONTRACTION" : "लंबाई संकुचन",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: वस्तु की वास्तविक लंबाई, l: स्पीड v के साथ आगे बढ़ एक पर्यवेक्षक द्वारा मनाया लंबाई",
"RELATIVISTIC MASS" : "आपेक्षिकीय द्रव्यमान",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: बाकी जन, m: वस्तु का आपेक्षिकीय बड़े पैमाने पर गति v के साथ घूम रहा है जब",
"TIME DILATION" : "समय फैलाव",
"2. ATOMIC NUCLEUS" : "2. परमाणु नाभिक",
"NUCLEAR MAKEUP" : "परमाणु श्रृंगार",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: प्रोटॉनों की संख्या, N: न्यूट्रॉन की संख्या, A: जन संख्या",
"NUCLEAR REACTION" : "परमाणु प्रतिक्रिया",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: परमाणु प्रतिक्रिया ऊर्जा रिलीज",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: परमाणु प्रतिक्रिया ऊर्जा अवशोषित",
"RADIOACTIVE DECAY" : "रेडियोधर्मी क्षय",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: सक्रिय पदार्थ की आरंभिक राशि, N: है कि मात्रा अभी भी बनी हुई है और अभी तक एक समय t के बाद सड़ा हुआ नहीं, m_o:  प्रारंभिक जन, m:  शेष की बड़े पैमाने पर, λ: क्षय निरंतर, ΔN: सड़ा हुआ पदार्थ की राशि, t: समय, T: आधा जीवन",
"Half life of some elements" : "कुछ तत्वों के आधा जीवन",
"AMOUNT OF RADIOACTIVITY" : "रेडियोधर्मिता की राशि",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: रेडियोधर्मिता की आरंभिक राशि, H: रेडियोधर्मिता की राशि समय t में",
"1. CONSTANTS" : "1. स्थिरांक",
"ALPHA PARTICLE MASS" : "अल्फा कण द्रव्यमान",
"ATOMIC MASS CONSTANT" : "परमाणु भार निरंतर",
"ATOMIC UNIT OF ENERGY" : "ऊर्जा के परमाणु इकाई",
"ATOMIC UNIT OF FORCE" : "बल की परमाणु इकाई",
"ATOMIC UNIT OF LENGTH" : "लंबाई की परमाणु इकाई",
"ATOMIC UNIT OF MASS" : "बड़े पैमाने पर की परमाणु इकाई",
"AVOGADRO'S CONSTANT" : "एवोगेड्रो की निरंतर",
"BOHR RADIUS" : "बोर त्रिज्या",
"BOLTZMANN CONSTANT" : "बोल्ट्जमान निरंतर",
"CLASSICAL ELECTRON RADIUS" : "शास्त्रीय इलेक्ट्रॉन त्रिज्या",
"ELEMENTARY CHARGE" : "प्राथमिक आरोप",
"EARTH MASS" : "पृथ्वी द्रव्यमान",
"EARTH EQUATORIAL RADIUS" : "पृथ्वी इक्वेटोरियल त्रिज्या",
"EARTH MEAN ORBITAL VELOCITY" : "पृथ्वी कक्षीय वेग मतलब",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "पृथ्वी घूर्णी कोणीय वेग",
"FARADAY’S CONSTANT" : "फैराडे के निरंतर",
"GAS CONSTANT" : "गैस निरंतर",
"MOLAR MASS CONSTANT" : "दाढ़ जन के निरंतर",
"MOLAR VOLUME OF IDEAL GAS" : "आदर्श गैस की दाढ़ मात्रा",
"NEUTRON MASS" : "न्यूट्रॉन द्रव्यमान",
"NEWTONIAN CONSTANT OF GRAVITATION" : "गुरुत्वाकर्षण न्यूटन का निरंतर",
"PLANCK’S CONSTANT" : "प्लैंक निरंतर",
"PLANCK MASS" : "प्लैंक द्रव्यमान",
"PROTON MASS" : "प्रोटॉन द्रव्यमान",
"PROTON-ELECTRON MASS RATIO" : "प्रोटॉन इलेक्ट्रॉन द्रव्यमान अनुपात",
"SPEED OF LIGHT IN VACUUM" : "शून्य में प्रकाश की गति",
"STANDARD ACCELERATION OF GRAVITY" : "गुरुत्वाकर्षण के मानक त्वरण",
"STANDARD ATMOSPHERE" : "मानक माहौल",
"STANDARD REFERENCE SOUND INTENSITY" : "मानक संदर्भ ध्वनि तीव्रता",
"STEFAN-BOLTZMANN CONSTANT" : "स्टीफन-बोल्ट्जमान निरंतर",
"2. GREEK ALPHABET" : "2. ग्रीक वर्णमाला",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: ग्रीक अक्षर, C2: नाम, C3: बराबर, C4: ध्वनि जब बात",

"Mechanics" : "मैकेनिक्स",
"Thermal physics" : "थर्मल भौतिकी",
"Optics" : "प्रकाशिकी",
"Theory of relativity" : "सापेक्षता का सिद्धांत",

"FREE FALLING" : "बेरोक गिरावट",
"VERTICAL PROJECTILE" : "कार्यक्षेत्र फेंकने",
"ANGLED PROJECTILE" : "कोणीय फेंकने",
"HORIZONTAL PROJECTILE" : "क्षैतिज फेंकने",
"SLIDING MOTION" : "स्लाइडिंग प्रस्ताव",
"ATTRACTIVE FORCE" : "आकर्षक बल",
"Hydraulic press" : "हाइड्रॉलिक प्रेस",
"PRESSURE" : "दबाव",
"LINEAR EXPANSION" : "रैखिक विस्तार",
"VOLUME EXPANSION" : "मात्रा विस्तार",
"SOUND SPEED" : "ध्वनि की गति",
"REFRACTION" : "अपवर्तन",
"PRISM" : "प्रिज्म",
"LENS" : "लेंस",
"Length contraction" : "लंबाई संकुचन",
"Time dilation" : "समय फैलाव",
"RELATIVISTIC MASS" : "आपेक्षिकीय द्रव्यमान",

"Height " : "ऊंचाई",
"Time to touchdown " : "टाइम अवतरण के लिए",
"Touchdown velocity " : "उतर जाना का वेग",
"Initial velocity " : "प्रारंभिक वेग",
"Maximum height " : "ज्यादा से ज्यादा ऊंचाई",
"Initial velocity " : "प्रारंभिक वेग",
"Angle " : "कोण",
"Maximum height " : "ज्यादा से ज्यादा ऊंचाई",
"Maximum distance " : "अधिकतम दूरी",
"Height " : "ऊंचाई",
"Initial velocity " : "प्रारंभिक वेग",
"Time to touchdown " : "टाइम अवतरण के लिए",
"Touchdown velocity " : "उतर जाना का वेग",
"Angle of tilted plane " : "शीर्षक विमान का कोण",
"Coefficient of friction " : "घर्षण के गुणांक",
"Acceleration " : "त्वरण",
"Mass " : "सामूहिक",
"Mass " : "सामूहिक",
"Distance " : "दूरी",
"Attractive force " : "आकर्षक बल",
"Area " : "क्षेत्र",
"Area " : "क्षेत्र",
"Force " : "बल",
"Force" : "बल",
"Force F₂ (or F₁)" : "सेना F₂ (या F₁)",
"Temperature " : "तापमान",
"Pressure at 0°C " : "0 डिग्री सेल्सियस पर दबाव",
"Pressure " : "दबाव",
"Original length " : "मूल लंबाई",
"Temperature change " : "तापमान परिवर्तन",
"Coefficient of linear expansion " : "रेखीय विस्तार के गुणांक",
"Change of length " : "लंबाई के बदले",
"Original volume " : "मूल मात्रा",
"Temperature change " : "तापमान परिवर्तन",
"Coefficient of linear expansion " : "रेखीय विस्तार के गुणांक",
"Change of volume " : "मात्रा के बदले",
"Temperature " : "तापमान",
"Sound speed " : "ध्वनि की गति",
"Refractive index " : "अपवर्तनांक",
"Refractive index " : "अपवर्तनांक",
"Angle of incidence " : "घटना का कोण",
"Angle of refraction " : "अपवर्तन कोण",
"Angle (r or i) " : "कोण (आर या मैं)",
"Apex angle " : "एपेक्स कोण",
"Angle of incident " : "घटना के कोण",
"Refractive index " : "अपवर्तनांक",
"Angle of emergent ray " : "आकस्मिक रे के कोण",
"Deviation angle " : "विचलन कोण",
"Focal length " : "फोकल लम्बाई",
"Object distance " : "वस्तु की दूरी",
"Image distance " : "छवि की दूरी",
"Image (or object) distance" : "छवि (या वस्तु) दूरी",
"Magnification factor " : "आवर्धन कारक",
"Speed " : "गति",
"Proper length " : "उचित लंबाई",
"Observed length " : "मनाया लंबाई",
"Rest mass " : "बाकी बड़े पैमाने पर",
"Relativistic mass " : "आपेक्षिकीय द्रव्यमान",
"Proper time interval " : "उचित समय अंतराल",
"Observed time interval " : "मनाया समय अंतराल",
"Calculate" : "गणना",
"Or input" : "या इनपुट",
"Calculation Tools" : "गणना उपकरण",
	
};