var language={

"1. DYNAMICS" : "1. دینامیک",
"STRAIGHT LINE MOTION" : "حرکت بر روی خط مستقیم",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s(m):مسافت , t(s):زمان , v(m/s):سرعت , v_a:سرعت متوسط",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "حرکت با شتاب ثابت بر روی خط مستقیم",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a(m/s²):شتاب , v_o(m/s):سرعت اولیه , v:سرعت در زمان t",
"DISTANCE FUNCTION" : "محاسبه مسافت طی شده در حرکت با شتاب ثابت",
"x_o: initial distance from origin, x: distance at time t" : "x_o: فاصله از مبدا اولیه، x: فاصله در زمان t",
"UNIFORM CIRCULAR MOTION" : "حرکت دایره ای یکنواخت",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ(rad):زاویه , l:طول قوس, R:شعاع دایره , ω(rad/s):سرعت زاویه ای , t:مدت زمانیکه شی طول قوس را طی می کند",
"CENTRIPETAL FORCE" : "نیروی جانب مرکز",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f(Hz):فرکانس , T(s):زمان تناوب , a:شتاب جانب مرکز, F:نیروی جانب مرکز (N)",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "حرکت دایره ای با شتاب ثابت",
"γ: angular acceleration" : "γ: شتاب زاویه ای ",
"ACCELERATION" : "شتاب",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: شتاب مماسی، a_n: شتاب طبیعی",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1:حرکت با شتاب افزاینده, P2:حرکت دایره ای یکنواخت, P3:حرکت با شتاب کاهنده",
"FREE FALLING FROM HEIGHT h" : "سقوط آزاد از ارتفاع h",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g:شتاب جاذبه زمین, v:سرعت در زمان t, s:مسافت طی شده پس از زمان t, v_h:سرعت در زمان برخورد شی با زمین, t_h:زمان برخورد شی با زمین پس از رهاشدن",
"VERTICAL PROJECTILE MOTION" : "حرکت پرتابه عمودی",
"h_max: maximum height, v_o: initial velocity" : "h_max: حداکثر ارتفاع، v_o: سرعت اولیه",
"Motion equation and velocity equation" : "معادله حرکت و معادله سرعت",
"ANGLED PROJECTILE MOTION" : "حرکت پرتابه زاویه دار",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x , v_y:سرعت, x , y :معادلات حرکت برحسب زمان, H :بیشینه ارتفاع, L :بیشینه فاصله",
"HORIZONTAL PROJECTILE MOTION" : "حرکت پرتابه افقی",
"t_h: time when touchdown, v_h: velocity when touchdown" : "v_h:سرعت در زمان برخورد شی با زمین ,t_h:زمان برخورد شی با زمین پس از رهاشدن",
"SLIDING MOTION ON AN INCLINED PLANE" : "حرکت بر روی سطح شیب دار",
"μ: coefficient of friction" : "μ: ضریب اصطکاک",
"Fiction coefficient of some materials" : "ضریب اصطکاک برخی مواد",
"2. FORCES" : "2. نیروها",
"ATTRACTIVE FORCE" : "نیروی جاذبه",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁، m₂: جرم دو شئ ؛ r: فاصله بین دو شیئ؛ G: ثابت گرانشی",
"GRAVITATIONAL FORCE" : "نیروی گرانش",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M:جرم زمین, m:جرم جسم, R:شعاع زمین , h:ارتفاع جسم از سطح زمین",
"GRAVITATIONAL ACCELERATION" : "شتاب گرانشی",
"At a height h above the nominal surface of the earth" : "در ارتفاع h بالای سطح اسمی از زمین",
"Near the sea level" : "در نزدیکی سطح دریا",
"FORCE OF GRAVITY" : "نیروی جاذبه",
"Force of gravity on earth, a special case of Gravitational force" : "نیروی جاذبه بر روی زمین، یک مورد خاص از نیروی گرانشی",
"NEWTON'S FIRST LAW" : "قانون اول نیوتون",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: نیروهای وارد بر جسم، v: سرعت جسم،: شتاب جسم",
"NEWTON'S SECOND LAW" : "قانون دوم نیوتن",
"m: object's mass (kg)" : "m: جرم جسم (کیلوگرم)",
"NEWTON'S THIRD LAW" : "قانون سوم نیوتن",
"LINEAR ELASTICITY - HOOKE'S LAW" : "کشش خطی - قانون هوک",
"k: spring constant (N/m), x: displacement (m)" : "k: ثابت فنر (N/m)، x: جابجایی (متر)",
"A mass suspended by a spring" : "جرم معلق توسط یک فنر",
"FORCE OF FRICTION" : "نیروی اصطکاک",
"μ: coefficient of friction, N: normal force" : "μ: ضریب اصطکاک، N: نیروی نرمال",
"3. STATICS" : "3. آمار",
"MOMENT OF A FORCE" : "گشتاور نیرو",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: نیروی اعمال شده (N)،d:بازوی گشتاور   (فاصله عمود از محور به خط عمل نیرو)",
"MOMENT APPLICATION" : "کاربرد گشتاور",
"MOMENT OF INERTIA" : "گشتاور اینرسی",
"Rod of length l" : "میله به طول l",
"Thin circular hoop/ Thin cylindrical shell" : "حلقه نازک دایره /  پوسته استوانه ای نازک",
"Solid disk/ Solid cylinder" : "دیسک حالت جامد / سیلندر جامد ",
"Solid ball" : "توپ جامد",
"Hollow sphere" : "حوزه توخالی",
"ANGULAR MOMENTUM" : "حرکت زاویه ای",
"I: moment of inertia, ω: angular velocity" : "I: گشتاور اینرسی، ω: سرعت زاویه ای",
"PLANE MOTION OF A RIGID BODY" : "حرکت صفحه ای جسم صلب",
"γ: angular acceleration, M: moment of a force" : "γ: شتاب زاویه ای، M: گشتاور نیرو",

"4. CONSERVATION LAWS" : "4. قوانین بقاء ",
"MOMENTUM OF FORCE" : "اندازه حرکت نیرو",
"LAW OF CONSERVATION OF MOMENTUM" : "قانون بقای اندازه حرکت (پایستگی تکانه)",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁، v₂: سرعت اولیه اشیاء 1 و 2؛ v₁'، v₂': سرعت نهایی جسم 1 و 2",
"PLASTIC COLLISION" : "برخورد پلاستیک",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': سرعت سیستم دو جسم (m₁ + m₂) پس از ضربه",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "برخورد الاستیک یک بعدی",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁'، v₂':  پس از ضربه  m₁ و m₂ سرعت",
"5. WORK AND ENERGY" : "5. کار و انرژی",
"WORK" : "کار",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: کار انجام شده توسط یک نیرو(J)،   F : نیروی حرکت یک شی در طی یک مسافت (s) ، α: زاویه بین F و جهت حرکت ",
"EXAMPLES" : "مثالها",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: کار توسط نیروی جاذبه، h: تغییر در ارتفاع. W_ms: کار نیروی اصطکاک ؛               W: کارانجام شده توسط قدرت فنر",
"POWER" : "توان",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: توان (وات، W)، t: زمان انجام کار W (s)",
"KINETIC ENERGY" : "انرژی جنبشی",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "انرژی جنبشی یک جسم دوار عظیم",
"WORK-ENERGY PRINCIPLE" : "اصل کار انرژی",
"v₁, v₂: speeds of object before and after the change" : "v₁، v₂: سرعت جسم قبل و بعد از تغییر",
"POTENTIAL ENERGY" : "انرژی پتانسیل",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: انرژی پتانسیل گرانشی (J)، m: جرم جسم (کیلوگرم)",
"CONSERVATION OF MECHANICAL ENERGY" : "حفاظت از انرژی مکانیکی",
"CONSERVATION OF ENERGY" : "حفاظت از انرژی",
"6. MECHANICS OF FLUIDS" : "6. مکانیک سیالات",
"DENSITY" : "تراکم",
"m: mass of a volume V" : "m: جرم حجم V",
"PRESSURE" : "فشار",
"F: force applied on area of A" : "F: A نیروی اعمال شده در منطقه  ",
"PRESSURE OF LIQUIDS" : "فشار مایعات",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d : وزن مخصوص ( متر مکعب/ N )،p_o: فشار هوا در سطح آزاد ( متر مربع /N)،  p: فشار ایجاد شده توسط وزن مایع بالا،p_B: فشار کل در عمق h",
"PASCAL’S PRINCIPLE" : "اصل پاسکال",
"p_s: pressure on the surface" : "p_s: فشار بر روی سطح",
"APPLICATION" : "کاربرد",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁، A₂: مساحت استوانه کوچک و بزرگ؛ F₁، F₂: نیروهای اعمال شده و به سمت بالا",
"ARCHIMEDES’ PRINCIPLE" : "اصل ارشمیدس ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: وزن مخصوص مایع (N / متر مکعب)، V: حجم جسم، F_b: نیروی شناور",
"FLOW RATE" : "آهنگ شارش (دبی)",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: سطح مقطع (متر مربع)، v: سرعت جریان (m/s)  Q، i: دبی (متر مکعب /s)",

"1. ELECTROSTATICS" : "1. الکترواستاتیک",
"COULOMB’S LAW" : "قانون کولن",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: اندازه بارهای الکتریکی (C)، ε: گذردهی نسبی (در خلاء ε = 1)،  r : فاصله میان بارهای الکتریکی   (متر)                             ",
"ELECTRIC FIELDS" : "میدان های الکتریکی",
"E: electric field strength (N/C)" : "E: قدرت میدان الکتریکی (N/C)",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "اصل انطباق برای میدانهای الکتریکی",
"In case of 2 electric fields" : "درصورت وجود دو میدان الکتریکی",
"WORK OF ELECTRIC FORCE" : "کار نیروی برق",
"ELECTRIC POTENTIAL DIFFERENCE" : "اختلاف پتانسیل الکتریکی",
"RELATION BETWEEN E AND U" : "ارتباط E و U",
"CAPACITANCE" : "ظرفیت خازنی",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: خازن (F)، Q: کل بار الکتریکی (C)، U: پتانسیل الکتریکی (V)",
"CAPACITOR" : "خازن",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: مساحت هر صفحه الکترود (متر مربع)، d: فاصله بین دو الکترود (m)، ε: گذردهی نسبی (F/m)",
"CAPACITANCES IN SERIES" : "خازن به صورت سری",
"CAPACITANCES IN PARALLEL" : "خازن به صورت موازی",
"ELECTRIC FIELD ENERGY" : "انرژی میدان الکتریکی",
"ENERGY OF CAPACITOR" : "انرژی خازن",
"V=A.d: volume between two electrode plates" : "V = A.d: حجم بین دو صفحه الکترود",
"2. DIRECT CURRENT" : "2. جریان مستقیم",
"ELECTRIC CURRENT" : "جریان الکتریکی",
"I: current (A), q: charge (C), t: time" : "I: جریان (A)،q:بار الکتریکی   (C)، t: زمان",
"OHM’S LAW" : "قانون اهم",
"U: electric potential difference between the ends of the resistor R" : "U: اختلاف پتانسیل الکتریکی بین دو سر مقاومت R",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "کار ایجاد شده توسط یک جریان (قانون ژول )",
"ELECTRICAL POWER" : "قدرت برق",
"RESISTANCE" : "مقاومت",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: مقاومت مواد (Ωm)، l: طول (متر)، A: مساحت سطح مقطع (متر مربع)",
"SERIES CIRCUITS" : "مدارهای سری",
"PARALLEL CIRCUITS" : "مدارهای موازی",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : " کار و یا انرژی گرمایی تولید شده توسط یک مقاومت",
"POWER CONSUMPTION OF A RESISTOR" : "مصرف برق یک مقاومت",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "نیروی الکتریکی یک ژنراتور الکتریکی",
"W: work of force (J), q: charge (C)" : "W: کار نیرو (J)،q:  بار الکتریکی  (C)",
"GENERATORS IN SERIES" : "ژنراتورهای سری",
"r: internal resistance of the generator" : "r: مقاومت داخلی در ژنراتور",
"GENERATORS IN PARALLEL" : "ژنراتور موازی",
"GENERATORS IN SERIES-PARALLEL" : "ژنراتور های سری-موازی",
"WORK AND POWER OF GENERATOR" : "کار و قدرت ژنراتور",
"H: Efficiency of generator" : "H: بهره وری از ژنراتور",
"3. MAGNETISM" : "3. مغناطیس",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "شار مغناطیسی از طریق سطح باز S",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: یکای قدرت میدان مغناطیسی (T، تسلا)،    α:  S  و خط عمود بر سطح  B زاویه بین  ",
"MAGNETIC FORCES ON MOVING CHARGES" : "نیروهای مغناطیسی بر بارهای الکتریکی متحرک",
"v: velocity of the charge (m/s)" : "v: سرعت بار الکتریکی (m/s)",
"FORCE ON A CURRENT-CARRYING WIRE" : "نیرو در سیم حامل جریان",
"I: current (A), l: length of the wire (m)" : "I: جریان (A)، l: طول سیم (m)",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "نیروی بین دو سیم حامل جریان موازی",
"r: distance between two wires (m)" : "r: فاصله بین دو سیم حامل جریان (m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "میدان مغناطیسی یک سیم دراز حامل جریان ",
"r: perpendicular distance from the center of the wire (m)" : "r: فاصله عمود از مرکز سیم (m)",
"MAGNETIC FIELD OF A LOOP" : "میدان مغناطیسی از یک حلقه",
"n: number of turns per unit length of solenoid (turns/m)" : "n: تعداد دور در واحد طول سولنئید  (نوبت /m)",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "نیروی محرکه الکتریکی القایی - قانون فاراده",
"N: numbers of turns per loop (turns/m)" : "N: تعداد دور در حلقه (نوبت /m)",
"INDUCTANCE" : "اندوکتانس",
"ELECTRIC ENERGY" : "انرژی الکتریکی یا برق",
"MAGNETIC ENERGY" : "انرژی مغناطیسی",
"ELECTRIC-MAGNETIC ENERGY" : "انرژی الکترومغناطیسی",
"4. ALTERNATING CURRENT" : "4. جریان متناوب",
"BASIC PARAMETERS" : "پارامترهای اساسی",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "من: جریان لحظه ای (A)، I_o: حداکثر جریان لحظه ای (A)، T: دوره موج، F: فرکانس، λ: طول موج، c: سرعت نور",
"EFFECTIVE CURRENT AND VOLTAGE" : "جریان موثر و ولتاژ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "قانون اهم از جریان AC شامل تنها مقاومت R",
"CONTAINING ONLY INDUCTOR L" : " شامل تنها القاگر L",
"Z_L: inductive reactance" : "Z_L: راکتانس القائی",
"CONTAINING ONLY CAPACITOR C" : " شامل تنها خازن C",
"Z_C: capacitive reactance" : "Z_C: خازنی راکتانس",
"CONTAINING R, L AND C IN A SERIES" : "شامل R، L و C به صورت سری",
"Z: impedance" : "Z: امپدانس",
"PHASE ANGLE" : " زاویه فاز",
"POWER FACTOR" : "ضریب قدرت",
"REAL POWER" : "توان واقعی",
"ELECTRICAL RESONANCE" : "رزونانس برق",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "تغییر ولتاژ با ترانسفورماتور",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁، N₂: تعداد دور در سیم پیچ اولیه و سیم پیچ ثانویه. U₁، U₂:  ولتاژ اولیه و ثانویه    . I₁، I₂: جریان اولیه و ثانویه",

"1. GAS LAWS" : "1. قوانین گاز",
"KELVIN TEMPERATURE" : "دمای کلوین",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: درجه حرارت در مقیاس کلوین، t: درجه حرارت در مقیاس سلسیوس",
"EQUATION OF STATE" : "معادله حالت",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: فشار (P، پاسکال)، V: حجم (متر مکعب)، n: تعداد مول های گاز (مول)،                     R: ثابت جهانی گاز ، T: درجه حرارت کلوین از گاز (K)، k: ثابت بولتزمن ،N: تعداد مولکولها در گاز",
"IDEAL GAS LAW" : "قانون گاز آرمانی",
"BOYLE’S LAW FOR PRESSURE" : "قانون بویل برای فشار",
"If the temperature of the gas is constant" : "اگر دمای گاز ثابت است",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "قانون گیلوساک درمورد دما و فشار   ",
"If the volume on a gas is constant" : "اگر حجم در یک گاز ثابت است",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: t فشار گاز در دمای ، p_o: فشار در 0 سانتیگراد، γ: عامل وقتی حجم ثابت باشد",
"Example when t=0 Kelvin" : "به عنوان مثال زمانی که t=0 کلوین باشد.",
"CHARLES'S LAW OF VOLUMES" : "قانون شارل در مورد حجم",
"If the pressure on a gas is constant" : "اگر فشار در یک گاز ثابت است",
"2. CHANGES OF STATE AND SHAPE" : "2. تغییر حالت و شکل",
"HEAT" : "حرارت-گرما",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: حرارت ساطع شده، Q_r: حرارت دریافت، m:  (کیلوگرم)جرم کل جسم    c: (J / kg.K) گرمای ویژه    ∆t:   (K)  تغییر در دما",
"The specific heats of some materials" : "حرارت خاص برخی از مواد",
"FUSION (FREEZING OR SOLIDIFICATION)" : "هم جوشی (انجماد)",
"Heat of fusion of some materials" : "گرمای هم جوشی برخی از مواد",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: مقدار حرارت (J)، λ: گرمای همجوشی (J / کیلوگرم)، m: جرم (کیلوگرم)",
"VAPORIZATION" : "تبخیر",
"L: heat of vaporization" : "L: گرمای تبخیر",
"Heat of vaporization of some materials" : "گرمای تبخیر برخی از مواد",
"LINEAR EXPANSION" : "گسترش خطی",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: طول اولیه (M)، α: ضریب انبساط خطی (K⁻¹) مبنای: تغییر در درجه حرارت",
"VOLUME EXPANSION" : "گسترش حجم",
"AREA EXPANSION" : "گسترش سطح",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "تغییر تراکم (چگالی حجمی)",
"D_o: original density (kg/m³)" : "D_o: تراکم اصلی (کیلوگرم / متر مکعب)",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "تغییر قطر سطح مقطع یک جامد",
"3. THERMODYNAMICS" : "3. ترمودینامیک",
"THE FIRST LAW OF THERMODYNAMICS" : "قانون اول ترمودینامیک",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU: تغییر در انرژی داخلی، W: کار انجام شده توسط سیستم،                                        Q: گرمای اضافه شده به داخل یا خارج سیستم",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "کاربرد قانون اول در برابر قوانین آرمانی گاز ",
"- Volume is constant" : "- حجم ثابت است",
"- Pressure is constant, W': work created by gas" : "-    فشار ثابت است، W': کار ایجاد شده توسط گاز",
"- Temperature is constant" : "- درجه حرارت ثابت است",
"THE SECOND LAW OF THERMODYNAMICS" : "قانون دوم ترمودینامیک",
"- The efficiency of a cyclic heat engine" : "- بهره وری از یک موتور گرمایی چرخه ای",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': (J) کار انجام شده در هر چرخه ،  Q₁:حرارت جذب شده در هر چرخه از درجه حرارت بالاتر، Q₂': حرارت رد شده در هر چرخه به درجه حرارت پایین تر (J)",
"- Maximum thermal efficiency" : "- حداکثر راندمان حرارتی",
"T₁, T₂: higher and lower temperatures" : "T₁، T₂: درجه حرارت بالا و پایین",

"1. SIMPLE HARMONIC MOTION" : "حرکت هماهنگ ساده               ",
"SPRING" : "فنر",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: ثابت فنر (N/m)، s: جابجایی (m)، ω: سرعت زاویه ای (راد /s)، T: دوره، m: جرم جسم، A: دامنه",
"SPRINGS IN SERIES" : "فنرها به صورت سری",
"k: spring constant of the system, T: period of the system" : "ثابت فنر سیستم، T:: k دوره سیستم",
"SPRINGS IN PARALLEL" : "فنرها به صورت موازی",
"SIMPLE PENDULUM" : "آونگ ساده",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: سرعت زاویه ای (راد /s)، T: دوره، α_o: زاویه در دامنه، A: دامنه، l: طول آونگ",
"MOTION EQUATIONS" : "معادلات حرکت",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: جابجایی، α: زاویه، v: سرعت، T: قدرت روی میله",
"ENERGY" : "انرژی",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: انرژی پتانسیل، E_k: انرژی جنبشی، E: انرژی مکانیک",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "تغییر تناوب پس از تغییر درجه حرارت",
"α: coefficient of linear expansion of the rod" : "α: ضریب انبساط خطی میله",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "تغییر تناوب پس از تغییر ارتفاع",
"h: height of pendulum, R: Earth's radius" : "h:ارتفاع آونگ، R :شعاع زمین",
"PENDULUM" : "پاندول",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: زمان اینرسی، ω: سرعت زاویه ای، m: جرم باب، d: OG، T:تناوب",
"2. PERIODIC MOTION" : "2. حرکت تناوبی",
"WAVELENGTH" : "طول موج",
"FUNCTION OF WAVE AT SOME POINTS" : "تابع موج  در برخی از نقاط",
"WAVE INTERFERENCE" : "تداخل امواج",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁، S₂:  دو منبع موج هم فاز. M: یک نقطه تصادفی",
"3. SOUND WAVES" : "3. امواج صوتی",
"SOUND SPEED" : "سرعت صوت",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): سرعت صوت در محیط با دما یt (سانتیگراد)",
"SOUND INTENSITY " : "شدت صدا",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: انرژی صوتی (J)، P: قدرت صدا (W)، A: مساحت سطح یک کره (متر مربع)، t: زمان (s)",
"SOUND INTENSITY LEVEL" : "سطح شدت صدا",
"I_o: the standard reference sound intensity" : "I_o: شدت صدا با مرجع استاندارد",
"THE DOPPLER EFFECT" : "اثر دوپلر",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: سرعت نسبی ناظر. v_S: سرعت نسبی منبع. v: سرعت صوت در این محیط. f_S، f_O: فرکانس صدا از منبع و ناظر",
"SOUND SPEED IN GASES" : "سرعت صوت در گازها",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: سرعت صوت (m/s)، R: ثابت جهانی گاز ، T: درجه حرارت مطلق (K)، M: جرم مولکولی گاز (کیلوگرم / مول)، γ: ثابت آدیاباتیک",
"Example in air" : " مثال در هوا",

"1. GEOMETRIC OPTICS" : "1. اپتیک هندسی",
"LAWS OF REFLECTION" : "قوانین بازتاب",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: پرتو تابش، IR:پرتو بازتابش ، i: زاویه تابش، i':زاویه بازتاب",
"REFRACTIVE INDEX" : "ضریب شکست",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: ضریب شکست محیط، v: سرعت نور در یک محیط، c: سرعت نور در خلاء (m/s)",
"LAW OF REFRACTION" : "قانون شکست نور",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: ضریب شکست محیط 1، n₂: ضریب شکست محیط 2، من: زاویه تابش، r: زاویه انکسار، n₂₁: شاخص مطلق شکست",
"If medium 1 is vacuum" : "اگر محیط 1 خلاء است",
"TOTAL REFLECTION PHENOMENON" : "پدیده بازتابش کلی",
"There is no refracted ray if" : "هیچ اشعه شکست نور وجود ندارد اگر",
"PRISM" : "منشور",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: زاویه راس، D: زاویه انحراف، i₁: زاویه تابش، i₂: زاویه خروج پرتو نور",
"- Condition to have refractive ray" : "- وضعیت داشتن اشعه شکست",
"- When angle of incidence is minimum" : "- هنگامی که زاویه تابش حداقل است",
"THIN LENS" : "لنز نازک",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: فاصله کانونی (همگرا لن f&gt; 0؛ واگرا لن f&lt;0)، d: فاصله جسم از مرکز لنز،   d': فاصله  تصویراز مرکز  لنز",
"MAGNIFICATION FACTOR" : "عامل بزرگ نمایی",
"h_I: image height, h_O: object height" : "h_I: ارتفاع تصویر، h_O: ارتفاع شی",
"POWER OF THE LENS" : "قدرت لنز",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: ضریب شکست مواد لنز، R₁: شعاع انحنا در سطح لن نزدیک به منبع نور، R₂: شعاع انحنا در دورترین سطح لن از منبع نور",
"2. QUANTUM OF LIGHT" : "2. کوانتومی نور",
"PHOTON ENERGY" : "انرژی فوتون",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: ثابت پلانک:، f:  فرکانس (Hz)، λ: طول موج (m)، c: سرعت نور",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "شرایط داشتن اثر فوتوالکتریک",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: طول موج نور رخشان، λ_o: حد فوتوالکتریک، W: ساطع کار (J)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "معادلات اینشتین در مورد اثر فوتوالکتریک",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: جرم فوتوالکترون (کیلوگرم)، v_o: حداکثر سرعت فوتوالکترون (m/s)",

"1. THEORY OF RELATIVITY" : "1. نظریه نسبیت",
"MASS–ENERGY EQUIVALENCE" : "هم ارزی جرم و انرژی",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: جرم (کیلوگرم)، E: انرژی جسم (J)، c: سرعت نور (m/s)",
"LENGTH CONTRACTION" : "انقباض طول",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: طول واقعی جسم، l: طول مشاهده شده توسط یک ناظر در حال حرکت با سرعت v",
"RELATIVISTIC MASS" : "جرم نسبیتی",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: توده استراحت، m: جرم نسبیتی از جسم در حال حرکت با سرعت v",
"TIME DILATION" : "اتساع زمان",
"2. ATOMIC NUCLEUS" : "2. هسته اتمی",
"NUCLEAR MAKEUP" : "آرایش هسته ای",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: تعداد پروتون ها، N: تعداد نوترون ها، A: عدد جرمی",
"NUCLEAR REACTION" : "واکنش های هسته ای",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: واکنش های هسته ای انرژی آزاد می کند",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: واکنش های هسته ای انرژی جذب می کند",
"RADIOACTIVE DECAY" : "تجزیه رادیواکتیو",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: مقدار اولیه ماده فعال، N: مقدار که هنوز باقی مانده است و هنوز پس از یک زمان t فاسد نمی،   ΔN: مقدار ماده تجزیه شده، m_o: توده اولیه، m: جرم باقی مانده، λ ثابت تجزیه، t: زمان،    T: نیمه عمر",
"Half life of some elements" : "نیمه عمر بعضی از عناصر",
"AMOUNT OF RADIOACTIVITY" : "میزان رادیواکتیویته",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: مقدار اولیه رادیواکتیویته، H: مقدار رادیواکتیویته در زمان t",
"1. CONSTANTS" : "1. ثوابت",
"ALPHA PARTICLE MASS" : "جرم ذرات آلفا",
"ATOMIC MASS CONSTANT" : "ثابت جرم اتمی",
"ATOMIC UNIT OF ENERGY" : "واحد اتمی انرژی",
"ATOMIC UNIT OF FORCE" : "واحد اتمی نیرو ",
"ATOMIC UNIT OF LENGTH" : "واحد اتمی طول",
"ATOMIC UNIT OF MASS" : "واحد اتمی جرم",
"AVOGADRO'S CONSTANT" : "ثابت آووگادرو",
"BOHR RADIUS" : "شعاع بور",
"BOLTZMANN CONSTANT" : "ثابت بولتزمن",
"CLASSICAL ELECTRON RADIUS" : "شعاع الکترونی کلاسیک",
"ELEMENTARY CHARGE" : "شارژ ابتدایی",
"EARTH MASS" : "جرم زمین",
"EARTH EQUATORIAL RADIUS" : " شعاع استوایی زمین",
"EARTH MEAN ORBITAL VELOCITY" : " سرعت متوسط مداری زمین",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "سرعت زاویه ای چرخشی زمین",
"FARADAY’S CONSTANT" : "ثابت فارادی",
"GAS CONSTANT" : "ثابت گاز",
"MOLAR MASS CONSTANT" : "ثابت جرم مولی",
"MOLAR VOLUME OF IDEAL GAS" : "حجم مولی گاز ایده آل",
"NEUTRON MASS" : "جرم نوترون",
"NEWTONIAN CONSTANT OF GRAVITATION" : "ثابت گرانش نیوتنی",
"PLANCK’S CONSTANT" : "ثابت پلانک",
"PLANCK MASS" : "جرم پلانک",
"PROTON MASS" : "جرم پروتون",
"PROTON-ELECTRON MASS RATIO" : "نسبت جرم پروتون الکترونی",
"SPEED OF LIGHT IN VACUUM" : "سرعت نور در خلاء",
"STANDARD ACCELERATION OF GRAVITY" : "شتاب استاندارد ثقل ",
"STANDARD ATMOSPHERE" : "جو استاندارد",
"STANDARD REFERENCE SOUND INTENSITY" : " مرجع استاندارد شدت صوت",
"STEFAN-BOLTZMANN CONSTANT" : "ثابت استفان-بولتزمن",
"2. GREEK ALPHABET" : "2. الفبای یونانی",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: حرف یونانی، C2: نام، C3: معادل، C4: صدا در هنگام صحبت",

"Mechanics" : "مکانیک",
"Thermal physics" : "فیزیک حرارتی",
"Optics" : "اپتیک",
"Theory of relativity" : "نظریه نسبیت",

"FREE FALLING" : "سقوط آزاد",
"VERTICAL PROJECTILE" : "پرتابه عمودی",
"ANGLED PROJECTILE" : "پرتابه زاویه دار",
"HORIZONTAL PROJECTILE" : "پرتابه افقی",
"SLIDING MOTION" : "حرکت بر روی سطح شیب دار",
"ATTRACTIVE FORCE" : "نیروی جاذبه",
"Hydraulic press" : "فشار هیدرولیکی",
"PRESSURE" : "فشار",
"LINEAR EXPANSION" : "گسترش خطی",
"VOLUME EXPANSION" : "گسترش حجم",
"SOUND SPEED" : "سرعت صوت",
"REFRACTION" : "شکست نور",
"PRISM" : "منشور",
"LENS" : "عدسی",
"Length contraction" : "انقباض طول",
"Time dilation" : "اتساع زمان",
"RELATIVISTIC MASS" : "جرم نسبیتی",

"Height " : "ارتفاع",
"Time to touchdown " : "مدت زمان برخورد شی با زمین پس از رها شدن",
"Touchdown velocity " : "سرعت شی هنگام برخورد به زمین",
"Initial velocity " : "سرعت اولیه",
"Maximum height " : "حداکثر ارتفاع",
"Initial velocity " : "سرعت اولیه",
"Angle " : "زاویه",
"Maximum height " : "حداکثر ارتفاع",
"Maximum distance " : "حداکثر فاصله",
"Height " : "ارتفاع",
"Initial velocity " : "سرعت اولیه",
"Time to touchdown " : "مدت زمان برخورد شی با زمین پس از رها شدن",
"Touchdown velocity " : "سرعت شی هنگام برخورد به زمین",
"Angle of tilted plane " : "زاویه سطح شیب دار",
"Coefficient of friction " : "ضریب اصطکاک",
"Acceleration " : "شتاب",
"Mass " : "جرم",
"Mass " : "جرم",
"Distance " : "فاصله",
"Attractive force " : "نیروی گرانش",
"Area " : "مساحت",
"Area " : "مساحت",
"Force " : "نیرو",
"Force" : "نیرو",
"Force F₂ (or F₁)" : "نیروی F₂ (یا F₁)",
"Temperature " : "درجه حرارت",
"Pressure at 0°C " : "فشار در دمای صفر",
"Pressure " : "فشار",
"Original length " : "طول اولیه",
"Temperature change " : "تغییر دما",
"Coefficient of linear expansion " : "ضریب انبساط خطی",
"Change of length " : "تغییر طول",
"Original volume " : "حجم اولیه",
"Temperature change " : "تغییر دما",
"Coefficient of linear expansion " : "ضریب انبساط خطی",
"Change of volume " : "تغییر حجم",
"Temperature " : "درجه حرارت",
"Sound speed " : "سرعت صوت",
"Refractive index " : "ضریب شکست",
"Refractive index " : "ضریب شکست",
"Angle of incidence " : "زاویه تابش",
"Angle of refraction " : "زاویه شکست",
"Angle (r or i) " : "زاویه ( r یا i )",
"Apex angle " : "زاویه راس",
"Angle of incident " : "زاویه تابش",
"Refractive index " : "ضریب شکست",
"Angle of emergent ray " : "زاویه خروج پرتو نور",
"Deviation angle " : "زاویه انحراف",
"Focal length " : "فاصله کانونی",
"Object distance " : "فاصله شی",
"Image distance " : "فاصله تصویر",
"Image (or object) distance" : "فاصله تصویر ( یا شی ) از عدسی",
"Magnification factor " : "ضریب بزرگنمایی",
"Speed " : "سرعت",
"Proper length " : "طول مبنا",
"Observed length " : "طول مشاهده شده",
"Rest mass " : "جرم اولیه",
"Relativistic mass " : "جرم نسبیتی",
"Proper time interval " : "گذشت زمان در حالت سکون",
"Observed time interval " : "گذشت زمان در حال حرکت",
"Calculate" : "محاسبه",
"Or input" : "یا وارد کنید",
"Calculation Tools" : "ابزار محاسباتی",

	
};