var language={

"1. DYNAMICS" : "1. Dinâmica",
"STRAIGHT LINE MOTION" : "Movimento Retilíneo",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: distância (m), t: tempo (s, segundo), v: velocidade (m/s), v_a: velocidade média ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Movimento Retilíneo Uniformemente Acelerado",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: aceleração, v_o: velocidade inicial, v: velocidade no tempo t ",
"DISTANCE FUNCTION" : "Função distância",
"x_o: initial distance from origin, x: distance at time t" : "x_o: distância inicial à origem, x: distância no tempo t ",
"UNIFORM CIRCULAR MOTION" : "Movimento Circular Uniforme ",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: ângulo (rad), l: comprimento do arco, R: raio do círculo, ω: velocidade angular (rad/s), t: tempo que o objeto requer para percorrer o comprimento l ",
"CENTRIPETAL FORCE" : "Força centrípeta ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: frequência (Hz), T: período de uma rotação (s), a: aceleração centrípeta, F: força centrípeta (N, Newton) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Movimento Circular Uniformemente Acelerado",
"γ: angular acceleration" : "γ: aceleração angular ",
"ACCELERATION" : "Aceleração",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: aceleração tangencial, a_n: aceleração normal ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: a acelerar, P2: movimento circular uniforme, P3: a abrandar ",
"FREE FALLING FROM HEIGHT h" : "Queda livre de uma altura h ",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: aceleração da gravidade, v: velocidade em t, s: distância após t, v_h: velocidade ao tocar o chão, t_h: instante de aterragem ",
"VERTICAL PROJECTILE MOTION" : "Movimento vertical de um projétil",
"h_max: maximum height, v_o: initial velocity" : "h_max: altura máxima, v_o: velocidade inicial ",
"Motion equation and velocity equation" : "Equação do movimento e equação da velocidade ",
"ANGLED PROJECTILE MOTION" : "Movimento angular de um projétil",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: velocidade; x, y: equação de movimento em função de t; H: altura máxima; L: distância máxima ",
"HORIZONTAL PROJECTILE MOTION" : "Movimento horizontal de um projétil",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: instante de aterragem, v_h: velocidade aquando da aterragem ",
"SLIDING MOTION ON AN INCLINED PLANE" : "Movimento de deslize num plano inclinado",
"μ: coefficient of friction" : "μ: coeficiente de atrito ",
"Fiction coefficient of some materials" : "Coeficiente de atrito de alguns materiais ",
"2. FORCES" : "2. Forças ",
"ATTRACTIVE FORCE" : "Força atrativa ",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: massa de 2 objetos; r: distância entre dois objetos; G: constante gravitacional ",
"GRAVITATIONAL FORCE" : "Força gravitacional ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: massa da Terra, m: massa do objeto, R: raio da Terra, h: altura do objeto ",
"GRAVITATIONAL ACCELERATION" : "Aceleração gravitacional ",
"At a height h above the nominal surface of the earth" : "A uma altura h acima da superfície da terra ",
"Near the sea level" : "Perto do nível do mar ",
"FORCE OF GRAVITY" : "Força da gravidade ",
"Force of gravity on earth, a special case of Gravitational force" : "Força da gravidade na Terra, um caso especial da força gravitacional ",
"NEWTON'S FIRST LAW" : "Primeira lei de Newton ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: forças que agem sobre o objeto, v: velocidade do objeto, a: a aceleração do objeto ",
"NEWTON'S SECOND LAW" : "Segunda lei de Newton ",
"m: object's mass (kg)" : "m: massa do objeto (kg) ",
"NEWTON'S THIRD LAW" : "Terceira lei de Newton ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Elasticidade Linear - A lei de Hooke ",
"k: spring constant (N/m), x: displacement (m)" : "k: constante de elasticidade da mola (N/m), x: deslocamento (m) ",
"A mass suspended by a spring" : "A massa suspensa por uma mola ",
"FORCE OF FRICTION" : "Força de atrito ",
"μ: coefficient of friction, N: normal force" : "μ: coeficiente de atrito, N: força normal ",
"3. STATICS" : "3. Estática ",
"MOMENT OF A FORCE" : "Momento de uma força ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: a força aplicada (N), d: braço de momento (a distância perpendicular do eixo à linha de ação da força) ",
"MOMENT APPLICATION" : "MOMENTO DE APLICAÇÃO ",
"MOMENT OF INERTIA" : "Momento de inércia ",
"Rod of length l" : "Vara de comprimento l ",
"Thin circular hoop/ Thin cylindrical shell" : "Aro circular fino/casca cilíndrica fina ",
"Solid disk/ Solid cylinder" : "Disco sólido/cilindro sólido ",
"Solid ball" : "Bola sólida",
"Hollow sphere" : "Esfera oca",
"ANGULAR MOMENTUM" : "Momento angular",
"I: moment of inertia, ω: angular velocity" : "I: momento de inércia, ω: velocidade angular ",
"PLANE MOTION OF A RIGID BODY" : "Movimento plano de um corpo rígido ",
"γ: angular acceleration, M: moment of a force" : "γ: aceleração angular, M: momento de uma força ",

"4. CONSERVATION LAWS" : "4. Leis de conservação ",
"MOMENTUM OF FORCE" : "Momento da força ",
"LAW OF CONSERVATION OF MOMENTUM" : "Lei da conservação do momento ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: velocidades iniciais dos objetos 1 e 2; v₁', v₂': velocidades finais dos objetos 1 e 2 ",
"PLASTIC COLLISION" : "Colisão inelástica",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': velocidade do sistema composto por dois corpos (m₁ + m₂) após impacto ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Colisão elástica unidimensional ",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': velocidades de m₁ e m₂ após o impacto ",
"5. WORK AND ENERGY" : "5. Trabalho e energia ",
"WORK" : "Trabalho ",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: trabalho realizado por uma força (J), F: Força que atua sobre um objeto ao longo de uma distância s, α: ângulo entre F e direção do movimento ",
"EXAMPLES" : "Exemplos ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: trabalho da gravidade, h: a mudança de altura; W_ms: trabalho da força de atrito; W: trabalho de uma mola ",
"POWER" : "Potência",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: Potência (watt, W), t: tempo de realização do trabalho W (s) ",
"KINETIC ENERGY" : "Energia cinética ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Energia cinética de um corpo maciço em rotação",
"WORK-ENERGY PRINCIPLE" : "Princípio do trabalho-energia ",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: velocidades de um objeto antes e depois da mudança ",
"POTENTIAL ENERGY" : "Energia Potencial ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: energia potencial gravítica (J), m: massa de objecto (kg) ",
"CONSERVATION OF MECHANICAL ENERGY" : "Conservação da Energia Mecânica ",
"CONSERVATION OF ENERGY" : "Conservação de Energia ",
"6. MECHANICS OF FLUIDS" : "6. Mecânica de fluidos ",
"DENSITY" : "Densidade ",
"m: mass of a volume V" : "m: massa de um volume V ",
"PRESSURE" : "Pressão ",
"F: force applied on area of A" : "F: força aplicada numa área A ",
"PRESSURE OF LIQUIDS" : "Pressão dos Líquidos ",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: densidade relativa (N/m³), p_o: pressão do ar na superfície livre (N/m²), p: pressão criada pelo peso do líquido acima, p_B: pressão total à profundidade h ",
"PASCAL’S PRINCIPLE" : "Princípio de Pascal ",
"p_s: pressure on the surface" : "p_s: pressão sobre a superfície ",
"APPLICATION" : "Aplicação ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: área dos cilindros pequeno e grande; F₁, F₂: forças aplicadas com direção para cima ",
"ARCHIMEDES’ PRINCIPLE" : "Princípio de Arquimedes ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: densidade relativa do líquido (N/m³), V: volume de objeto, F_b: força de impulsão ",
"FLOW RATE" : "Fluxo volumétrico",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: área da secção transversal (m²), v: velocidade de fluxo (m/s), Q: caudal (m³/s) ",

"1. ELECTROSTATICS" : "1. Eletrostática ",
"COULOMB’S LAW" : "Lei de Coulomb ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: intensidade das cargas (C), ε: permissividade relativa (em vácuo ε = 1), r: distância entre as cargas (m) ",
"ELECTRIC FIELDS" : "Campos Elétricos ",
"E: electric field strength (N/C)" : "E: intensidade do campo elétrico (N/C) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "O princípio da sobreposição dos campos elétricos ",
"In case of 2 electric fields" : "No caso de existirem dois campos eléctricos ",
"WORK OF ELECTRIC FORCE" : "Trabalho de força elétrica ",
"ELECTRIC POTENTIAL DIFFERENCE" : "Diferença de potencial elétrico ",
"RELATION BETWEEN E AND U" : "Relação entre E e U ",
"CAPACITANCE" : "Capacidade elétrica",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: capacidade elétrica (F), Q: carga elétrica total (C), U: potencial elétrico (V) ",
"CAPACITOR" : "Capacitor (Condensador)",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: área de cada placa do eletrodo (m²), d: distância entre os eletrodos (m), ε: permissividade relativa (F/m) ",
"CAPACITANCES IN SERIES" : "Capacitâncias em série ",
"CAPACITANCES IN PARALLEL" : "Capacitâncias em paralelo ",
"ELECTRIC FIELD ENERGY" : "Energia do campo elétrico ",
"ENERGY OF CAPACITOR" : "Energia do capacitor (condensador)",
"V=A.d: volume between two electrode plates" : "V = A.d: volume entre duas placas de eletrodos ",
"2. DIRECT CURRENT" : "2 Corrente Contínua ",
"ELECTRIC CURRENT" : "Corrente elétrica ",
"I: current (A), q: charge (C), t: time" : "I: intensidade da corrente (A), q: carga (C), t: tempo ",
"OHM’S LAW" : "Lei de Ohm ",
"U: electric potential difference between the ends of the resistor R" : "U: diferença de potencial eléctrico entre as extremidades da resistência R ",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Trabalho criado por uma corrente (Lei de Joule) ",
"ELECTRICAL POWER" : "Potência Elétrica",
"RESISTANCE" : "Resistência ",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: resistividade do material (Ωm), l: comprimento (m), A: área da secção transversal (m²) ",
"SERIES CIRCUITS" : "Circuitos em Série",
"PARALLEL CIRCUITS" : "Circuitos Paralelos",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Trabalho ou energia térmica produzida por uma resistência ",
"POWER CONSUMPTION OF A RESISTOR" : "O consumo de energia de uma resistência",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Força eletromotriz de um gerador elétrico ",
"W: work of force (J), q: charge (C)" : "W: trabalho de força (J), q: carga (C) ",
"GENERATORS IN SERIES" : "Geradores em série ",
"r: internal resistance of the generator" : "r: a resistência interna do gerador ",
"GENERATORS IN PARALLEL" : "Geradores em paralelo ",
"GENERATORS IN SERIES-PARALLEL" : "Geradores em série-paralelo ",
"WORK AND POWER OF GENERATOR" : "Trabalho e potência de gerador ",
"H: Efficiency of generator" : "H: Eficiência do gerador ",
"3. MAGNETISM" : "3. Magnetismo ",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "O fluxo magnético através da superfície aberta S ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: intensidade do campo magnético (T, tesla), α: ângulo entre B e a linha perpendicular à superfície S ",
"MAGNETIC FORCES ON MOVING CHARGES" : "Forças magnéticas sobre cargas em movimento ",
"v: velocity of the charge (m/s)" : "v: velocidade da carga (m/s) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "Força sobre um fio com corrente ",
"I: current (A), l: length of the wire (m)" : "I: corrente (A), l: comprimento do fio (m) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Força entre dois fios condutores de corrente paralelas ",
"r: distance between two wires (m)" : "r: distância entre dois fios (m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "O campo magnético de um fio longo de corrente de carga ",
"r: perpendicular distance from the center of the wire (m)" : "r: distância perpendicular a partir do centro do fio (m) ",
"MAGNETIC FIELD OF A LOOP" : "Campo Magnético de uma espira",
"n: number of turns per unit length of solenoid (turns/m)" : "n: número de voltas por unidade de comprimento do solenóide (voltas/m) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Força eletromotriz induzida - Lei de Faraday ",
"N: numbers of turns per loop (turns/m)" : "N: número de voltas por loop (voltas/m) ",
"INDUCTANCE" : "Indutância ",
"ELECTRIC ENERGY" : "Energia elétrica ",
"MAGNETIC ENERGY" : "Energia magnética ",
"ELECTRIC-MAGNETIC ENERGY" : "Energia eletromagnética ",
"4. ALTERNATING CURRENT" : "4. Corrente Alternada ",
"BASIC PARAMETERS" : "Parâmetros básicos ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: corrente instantânea (A), I_o: corrente instantânea máxima (A), T: período da onda, f: frequência, λ: comprimento de onda, c: velocidade da luz ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Corrente eficaz e Tensão ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "A lei de Ohm de Corrente AC Contendo Apenas Resistência R ",
"CONTAINING ONLY INDUCTOR L" : "Contendo apenas o indutor L ",
"Z_L: inductive reactance" : "Z_L: reatância indutiva ",
"CONTAINING ONLY CAPACITOR C" : "Contendo apenas o capacitor C ",
"Z_C: capacitive reactance" : "Z_C: reatância capacitiva ",
"CONTAINING R, L AND C IN A SERIES" : "Contendo, R, L e C em série ",
"Z: impedance" : "Z: impedância ",
"PHASE ANGLE" : "Ângulo de fase ",
"POWER FACTOR" : "Fator de potência ",
"REAL POWER" : "O poder real ",
"ELECTRICAL RESONANCE" : "Ressonância elétrica ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Mudando tensão com transformadores ",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: número de voltas da bobina primária e bobina secundária; U₁, U₂: tensões primária e secundária; I₁, I₂: correntes primária e secundária",

"1. GAS LAWS" : "1. Leis dos Gases ",
"KELVIN TEMPERATURE" : "Temperatura Kelvin ",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: temperatura na escala Kelvin, t: temperatura na escala Celsius ",
"EQUATION OF STATE" : "Equação de Estado ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: pressão (P, Pascal), V: Volume (m³), n: número de moles do gás (mol), R: constante universal do gás, T: temperatura Kelvin do gás (K), k: constante de Boltzmann, N: número de moléculas do gás ",
"IDEAL GAS LAW" : "Lei dos gases ideais",
"BOYLE’S LAW FOR PRESSURE" : "Lei de Boyle para a pressão ",
"If the temperature of the gas is constant" : "Se a temperatura do gás é constante ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Lei de de pressão e temperatura de Gay-Lussac",
"If the volume on a gas is constant" : "Se o volume do gás é constante ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: pressão do gás à temperatura t, p_o: pressão a 0 Celsius, γ: fator quando o volume é constante ",
"Example when t=0 Kelvin" : "Exemplo quando t = 0 Kelvin",
"CHARLES'S LAW OF VOLUMES" : "Lei de Charles",
"If the pressure on a gas is constant" : "Se a pressão no gás é constante ",
"2. CHANGES OF STATE AND SHAPE" : "2. Mudanças de Estado e de forma ",
"HEAT" : "Capacidade Térmica Mássica",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: calor emitido, Q_r: calor recebido, m: massa total do objeto (kg), c: capacidade térmica mássica (J/kg.K),  ∆t: mudança de temperatura (K) ",
"The specific heats of some materials" : "As capacidades térmicas específicas de alguns materiais ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Fusão (congelamento ou solidificação) ",
"Heat of fusion of some materials" : "A entalpia de fusão de alguns materiais ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: quantidade de calor (J), λ: calor de fusão (J/kg), m: de massa (kg) ",
"VAPORIZATION" : "Vaporização ",
"L: heat of vaporization" : "L: entalpia de vaporização ",
"Heat of vaporization of some materials" : "A entalpia de vaporização de alguns materiais ",
"LINEAR EXPANSION" : "Expansão linear ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: comprimento original (m), α: coeficiente de expansão linear (K⁻¹), ∆t: mudança de temperatura ",
"VOLUME EXPANSION" : "A expansão de volume ",
"AREA EXPANSION" : "A expansão da área ",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Mudança de densidade (densidade de massa volumétrica) ",
"D_o: original density (kg/m³)" : "D_o: densidade original (kg/m³) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Mudança de diâmetro da secção transversal de um sólido ",
"3. THERMODYNAMICS" : "3. Termodinâmica ",
"THE FIRST LAW OF THERMODYNAMICS" : "A Primeira Lei da Termodinâmica ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "∆U: variação da energia interna, W: trabalho realizado pelo sistema, Q: calor adicionado para dentro ou fora do sistema ",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Aplicação da Primeira Lei à lei dos gases ideais ",
"- Volume is constant" : "- O Volume é constante",
"- Pressure is constant, W': work created by gas" : "- A pressão é constante, W': trabalho realizado pelo gás ",
"- Temperature is constant" : "- A temperatura é constante",
"THE SECOND LAW OF THERMODYNAMICS" : "A Segunda Lei da Termodinâmica ",
"- The efficiency of a cyclic heat engine" : "- A eficiência de um motor térmico cíclico",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': o trabalho realizado por ciclo (J), Q₁: calor absorvido por ciclo a partir da temperatura mais elevada (J), Q₂': calor rejeitado por ciclo para a temperatura mais baixa (J) ",
"- Maximum thermal efficiency" : "- Eficiência térmica máxima",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: temperaturas mais elevadas e mais baixas ",

"1. SIMPLE HARMONIC MOTION" : "1. Movimento Harmónico Simples ",
"SPRING" : "Mola",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: constante da mola (N/m), s: deslocamento (m), ω: velocidade angular (rad/s), T: período, m: massa do objeto, A: amplitude ",
"SPRINGS IN SERIES" : "Molas em série ",
"k: spring constant of the system, T: period of the system" : "k: constante da mola do sistema, T: período do sistema ",
"SPRINGS IN PARALLEL" : "Molas em paralelo ",
"SIMPLE PENDULUM" : "Pêndulo simples ",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: velocidade angular (rad/s), T: período, α_o: ângulo em amplitude, A: amplitude, l: comprimento do pêndulo ",
"MOTION EQUATIONS" : "Equações de movimento ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: deslocamento, α: ângulo, v: velocidade, T: força na haste ",
"ENERGY" : "Energia",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: energia potencial, E_k: energia cinética, E: energia mecânica ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Mudança de período posterior à mudança da temperatura ",
"α: coefficient of linear expansion of the rod" : "α: coeficiente de expansão linear da haste ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Mudança de período após a mudança de altura ",
"h: height of pendulum, R: Earth's radius" : "h: altura do pêndulo, R: raio da Terra ",
"PENDULUM" : "Pêndulo",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: momento de inércia, ω: velocidade angular, m: massa colocada no pêndulo, d: OG, T: período ",
"2. PERIODIC MOTION" : "2 Movimento periódico ",
"WAVELENGTH" : "Comprimento de Onda",
"FUNCTION OF WAVE AT SOME POINTS" : "Função de onda em alguns pontos ",
"WAVE INTERFERENCE" : "Interferência de ondas ",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 fontes de onda com mesma fase; M: um ponto aleatório ",
"3. SOUND WAVES" : "3. Ondas de Som",
"SOUND SPEED" : "Velocidade do som",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): velocidade do som em ambiente com temperatura t (Celsius) ",
"SOUND INTENSITY " : "Intensidade sonora ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: a energia sonora (J), P: potência sonora (W), A: a área da superfície de uma esfera (m²), t: tempo (s) ",
"SOUND INTENSITY LEVEL" : "Nível de intensidade sonora ",
"I_o: the standard reference sound intensity" : "I_o: a intensidade do som de referência padrão ",
"THE DOPPLER EFFECT" : "O Efeito Doppler ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: a velocidade relativa do observador; v_S: a velocidade relativa da fonte; v: velocidade do som neste meio; f_S, f_O: frequência de som da fonte e observador ",
"SOUND SPEED IN GASES" : "Velocidade do som em gases ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: velocidade do som (m/s), R: constante universal dos gases, T: temperatura absoluta (K), M: massa molecular do gás (kg/mol), γ: constante adiabática ",
"Example in air" : "Exemplo em ar ",

"1. GEOMETRIC OPTICS" : "1. Ótica Geométrica ",
"LAWS OF REFLECTION" : "Leis da reflexão ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: raio incidente, IR: raio refletido, i: ângulo de incidência, i': ângulo de reflexão ",
"REFRACTIVE INDEX" : "índice de refração ",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: índice de refração do meio, v: velocidade da luz num meio, c: velocidade da luz no vácuo (m/s) ",
"LAW OF REFRACTION" : "Lei da Refração ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: índice de refração do meio 1, n₂: índice de refração do meio 2, i: ângulo de incidência, r: ângulo de refração, n₂₁: índice absoluto de refração ",
"If medium 1 is vacuum" : "Se o meio 1 é o vácuo",
"TOTAL REFLECTION PHENOMENON" : "Fenómeno de reflexão total ",
"There is no refracted ray if" : "Não há raio refratado se",
"PRISM" : "Prisma",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: ângulo de ápice, D: ângulo de desvio, i₁: ângulo de incidência, i₂: ângulo do raio emergente ",
"- Condition to have refractive ray" : "- Condições para que haja raios de refracção",
"- When angle of incidence is minimum" : "- Quando o ângulo de incidência é mínimo",
"THIN LENS" : "Lente fina ",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: distância focal (convergentes se f&gt;0; divergentes se f&lt;0), d: objeto distância do centro da lente, d': distância da imagem ao centro da lente ",
"MAGNIFICATION FACTOR" : "Fator de ampliação",
"h_I: image height, h_O: object height" : "h_I: altura da imagem, h_O: a altura do objeto ",
"POWER OF THE LENS" : "Potência da lente ",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: índice de refracção do material da lente, R₁: raio de curvatura da superfície da lente mais próxima da fonte de luz, R₂: raio de curvatura da superfície mais distante lente a partir da fonte de luz ",
"2. QUANTUM OF LIGHT" : "2. Quântica da luz ",
"PHOTON ENERGY" : "Energia do Fotão",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: Constante de Planck, f: frequência (Hz), λ: comprimento de onda (m), c: velocidade da luz ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Condições para que haja efeito fotoelétrico ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: comprimento de onda da luz incidente, λ_o: limite fotoelétrico, W: trabalho emitido (J) ",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "A equação de Einstein sobre o efeito fotoelétrico ",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: massa de fotoeletrões (kg), v_o: velocidade máxima de fotoeletrões (m/s) ",

"1. THEORY OF RELATIVITY" : "1 Teoria da Relatividade ",
"MASS–ENERGY EQUIVALENCE" : "Equivalência massa-energia ",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: massa (kg), E: energia de objeto (J), c: velocidade da luz (m/s)",
"LENGTH CONTRACTION" : "Contração do comprimento ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: comprimento real do objeto, l: comprimento observado por um observador movendo-se com velocidade v ",
"RELATIVISTIC MASS" : "Massa relativística",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: massa de repouso, m: massa relativística de um objeto que se move com velocidade v ",
"TIME DILATION" : "Dilatação do tempo ",
"2. ATOMIC NUCLEUS" : "2. Núcleo atómico ",
"NUCLEAR MAKEUP" : "Constituição Nuclear",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: número de protões, N: número de neutrões, A: número de massa ",
"NUCLEAR REACTION" : "Reação nuclear ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt; m_o: a reação nuclear libera energia",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: a reacção nuclear absorve energia",
"RADIOACTIVE DECAY" : "Decaimento Radioativo",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: quantidade inicial de substância activa, N: quantidade que permanece e ainda não decaiu, passado um tempo t, ΔN: quantidade de substância decaída, m_o: massa inicial, m: massa restante, λ: constante de decaimento, t: tempo, T: meia-vida ",
"Half life of some elements" : "A meia-vida de alguns elementos ",
"AMOUNT OF RADIOACTIVITY" : "Quantidade de radioactividade ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: quantidade inicial de radioatividade, H: quantidade de radioactividade no tempo t ",
"1. CONSTANTS" : "1. Constantes ",
"ALPHA PARTICLE MASS" : "massa de partículas alfa ",
"ATOMIC MASS CONSTANT" : "constante de massa atómica ",
"ATOMIC UNIT OF ENERGY" : "unidade atómica de energia ",
"ATOMIC UNIT OF FORCE" : "unidade atómica de força ",
"ATOMIC UNIT OF LENGTH" : "unidade atómica de comprimento ",
"ATOMIC UNIT OF MASS" : "unidade atómica de massa ",
"AVOGADRO'S CONSTANT" : "constante de Avogadro ",
"BOHR RADIUS" : "raio de Bohr ",
"BOLTZMANN CONSTANT" : "constante de Boltzmann ",
"CLASSICAL ELECTRON RADIUS" : "raio clássico do eletrão",
"ELEMENTARY CHARGE" : "carga elementar",
"EARTH MASS" : "massa da Terra",
"EARTH EQUATORIAL RADIUS" : "raio equatorial da Terra",
"EARTH MEAN ORBITAL VELOCITY" : "velocidade orbital média da Terra",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "velocidade de rotação angular da Terra",
"FARADAY’S CONSTANT" : "constante de Faraday ",
"GAS CONSTANT" : "constante do gás ",
"MOLAR MASS CONSTANT" : "massa molar constante ",
"MOLAR VOLUME OF IDEAL GAS" : "o volume molar do gás ideal ",
"NEUTRON MASS" : "massa do neutrão",
"NEWTONIAN CONSTANT OF GRAVITATION" : "constante gravitacional de Newton",
"PLANCK’S CONSTANT" : "constante de Planck ",
"PLANCK MASS" : "massa de Planck ",
"PROTON MASS" : "massa do protão",
"PROTON-ELECTRON MASS RATIO" : "relação de massa protão-eletrão",
"SPEED OF LIGHT IN VACUUM" : "velocidade da luz no vácuo ",
"STANDARD ACCELERATION OF GRAVITY" : "aceleração normal da gravidade ",
"STANDARD ATMOSPHERE" : "atmosfera padrão ",
"STANDARD REFERENCE SOUND INTENSITY" : "Referência padrão da intensidade de som ",
"STEFAN-BOLTZMANN CONSTANT" : "constante de Stefan-Boltzmann ",
"2. GREEK ALPHABET" : "2. Alfabeto grego ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: letra grega, C2: Nome, C3: Equivalente, C4: O som quando se fala ",

"Mechanics" : "Mecânica",
"Thermal physics" : "Física térmica ",
"Optics" : "Ótica ",
"Theory of relativity" : "Teoria da Relatividade ",

"FREE FALLING" : "Queda livre",
"VERTICAL PROJECTILE" : "Projétil vertical ",
"ANGLED PROJECTILE" : "Projétil lançado obliquamente",
"HORIZONTAL PROJECTILE" : "Projétil horizontal ",
"SLIDING MOTION" : "Movimento de deslizamento",
"ATTRACTIVE FORCE" : "Força atrativa ",
"Hydraulic press" : "Prensa hidráulica ",
"PRESSURE" : "Pressão ",
"LINEAR EXPANSION" : "Expansão linear ",
"VOLUME EXPANSION" : "A expansão de volume ",
"SOUND SPEED" : "Velocidade do som",
"REFRACTION" : "Refração ",
"PRISM" : "Prisma",
"LENS" : "Lente",
"Length contraction" : "Contração do comprimento ",
"Time dilation" : "Dilatação do tempo ",
"RELATIVISTIC MASS" : "Massa relativística",

"Height " : "Altura ",
"Time to touchdown " : "Tempo de aterragem ",
"Touchdown velocity " : "Velocidade de aterragem",
"Initial velocity " : "Velocidade inicial ",
"Maximum height " : "Altura máxima ",
"Initial velocity " : "Velocidade inicial ",
"Angle " : "Ângulo ",
"Maximum height " : "Altura máxima ",
"Maximum distance " : "Alcance",
"Height " : "Altura ",
"Initial velocity " : "Velocidade inicial ",
"Time to touchdown " : "Tempo de aterragem ",
"Touchdown velocity " : "Velocidade de aterragem",
"Angle of titled plane " : "Ângulo do plano inclinado",
"Coefficient of friction " : "Coeficiente de atrito ",
"Acceleration " : "Aceleração ",
"Mass " : "Massa",
"Mass " : "Massa",
"Distance " : "Distância ",
"Attractive force " : "Força atrativa ",
"Area " : "Área ",
"Area " : "Área ",
"Force " : "Força",
"Force" : "Força",
"Force F₂ (or F₁)" : "Força F₂ (ou F₁) ",
"Temperature " : "temperatura ",
"Pressure at 0°C " : "Pressão a 0°C ",
"Pressure " : "Pressão ",
"Original length " : "Comprimento original ",
"Temperature change " : "Mudança de temperatura ",
"Coefficient of linear expansion " : "Coeficiente de expansão linear ",
"Change of length " : "Mudança de comprimento ",
"Original volume " : "Volume original ",
"Temperature change " : "Mudança de temperatura ",
"Coefficient of linear expansion " : "Coeficiente de expansão linear ",
"Change of volume " : "Mudança de volume ",
"Temperature " : "temperatura ",
"Sound speed " : "Velocidade do som ",
"Refractive index " : "Índice de refração ",
"Refractive index " : "Índice de refração ",
"Angle of incidence " : "Ângulo de incidência ",
"Angle of refraction " : "Ângulo de refração ",
"Angle (r or i) " : "Ângulo (r ou i) ",
"Apex angle " : "Ângulo de ápice ",
"Angle of incident " : "Ângulo de incidência ",
"Refractive index " : "Índice de refração ",
"Angle of emergent ray " : "Ângulo do raio emergente ",
"Deviation angle " : "Ângulo de desvio ",
"Focal length " : "Distância focal ",
"Object distance " : "Distância do objeto ",
"Image distance " : "Distância da imagem ",
"Image (or object) distance" : "Distância da imagem (ou objeto)",
"Magnification factor " : "Fator de ampliação ",
"Speed " : "Velocidade",
"Proper length " : "Comprimento próprio ",
"Observed length " : "Comprimento observado ",
"Rest mass " : "Massa em repouso",
"Relativistic mass " : "Massa relativística",
"Proper time interval " : "Intervalo de tempo próprio ",
"Observed time interval " : "Intervalo de tempo observado ",
"Calculate" : "Calcular ",
"Or input" : "Ou introduzir",
"Calculation Tools" : "Ferramentas de Cálculo ",



	
};