var language={

"1. DYNAMICS" : "1. Dynamique",
"STRAIGHT LINE MOTION" : "Mouvement rectiligne",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: distance (m), t : temps (s, seconde), v : vitesse (m/s), v_a : vitesse moyenne",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Accélération rectiligne et uniforme",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: accélération, v_o : accélération initiale, v : vitesse au temps t",
"DISTANCE FUNCTION" : "Fonction de distance",
"x_o: initial distance from origin, x: distance at time t" : "x_o : distance depuis l'origine, x : distance au temps t",
"UNIFORM CIRCULAR MOTION" : "Mouvement circulaire uniforme",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: angle (rad), l: longueur de la courbe, R: rayon du cercle, ω: vitesse angulaire (rad/s), t: le temps que l'objet bouge à une longueur de l",
"CENTRIPETAL FORCE" : "Force centripède",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: fréquence (Hz), T : la période d'une rotation (s), a : une accélération centripète, F : force centripède (N, Newton)",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Mouvement d'accélération circulaire constant",
"γ: angular acceleration" : "γ: accélération angulaire",
"ACCELERATION" : "Accélération",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t : accélération tangentielle, a_n : accélération normale",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1 : augmentation de la vitesse, P2 : mouvement circulaire uniforme, P3 : diminution de la vitesse",
"FREE FALLING FROM HEIGHT h" : "Chute libre depuis la hauteur h",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: accélération gravitationnelle, v : vitesse au temps t, s : distance après t, v_h : vitesse lors du toucher du sol, t_h : temps pour atteindre de sol",
"VERTICAL PROJECTILE MOTION" : "Mouvement vertical d'un projectile",
"h_max: maximum height, v_o: initial velocity" : "h_max:hauteur maximale, v_o:vitesse initiale",
"Motion equation and velocity equation" : "Equation et vitesse du mouvement",
"ANGLED PROJECTILE MOTION" : "Mouvement angulaire projeté",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y : vitesse ; x,y : équation de mouvement au temps t ; H : hauteur maximale ; L : distance maximale",
"HORIZONTAL PROJECTILE MOTION" : "Mouvement horizontal du projectile",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h : temps au moment du toucher au sol, v_h : vitesse lors du toucher au sol",
"SLIDING MOTION ON AN INCLINED PLANE" : "Mouvement de glissement d'un avion incliné",
"μ: coefficient of friction" : "μ:coefficient de friction",
"Fiction coefficient of some materials" : "Coefficient de friction de certain matériaux",
"2. FORCES" : "2. Forces",
"ATTRACTIVE FORCE" : "Force d'attraction",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁,m₂ : masse de 2 objet ; r : distance entre deux objets ; G : constante gravitationnelle",
"GRAVITATIONAL FORCE" : "Force gravitationnelle",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: masse de la terre, m : masse de l'objet, R : rayon terrestre, h : hauteur de l'objet",
"GRAVITATIONAL ACCELERATION" : "Accélération gravitationnelle",
"At a height h above the nominal surface of the earth" : "A une hauteur h au-dessus du niveau de la terre",
"Near the sea level" : "Proche du niveau de la mère",
"FORCE OF GRAVITY" : "force de gravité",
"Force of gravity on earth, a special case of Gravitational force" : "Force de gravité sur terre, un cas spécifique de la force de gravitation",
"NEWTON'S FIRST LAW" : "Première loi de Newton",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: les forces agissant sur l'objet, v : vitesse de l'objet, a : accélération de l'objet",
"NEWTON'S SECOND LAW" : "Deuxième loi de Newton",
"m: object's mass (kg)" : "m: masse de l'objet (kg)",
"NEWTON'S THIRD LAW" : "Troisième loi de Newton",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Elasticité linéaire – Loi de Hooke",
"k: spring constant (N/m), x: displacement (m)" : "k: constante de ressort (N/m), x : déplacement (m)",
"A mass suspended by a spring" : "Une masse suspendue par un ressort",
"FORCE OF FRICTION" : "Force de friction",
"μ: coefficient of friction, N: normal force" : "μ:coefficient de friction, N : force normale",
"3. STATICS" : "3. Statiques",
"MOMENT OF A FORCE" : "Moment de la force",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: la force appliquée (N), d : bras de levier (la distance perpendiculaire de l'axe à la ligne d'action de la force)",
"MOMENT APPLICATION" : "Moment d'application",
"MOMENT OF INERTIA" : "Moment d'inertie",
"Rod of length l" : "Tige de longueur I",
"Thin circular hoop/ Thin cylindrical shell" : "cercle circulaire fin/coquille fine cylindrique",
"Solid disk/ Solid cylinder" : "Disque solide/Cylindre solide",
"Solid ball" : "Balle solide",
"Hollow sphere" : "Sphère creuse",
"ANGULAR MOMENTUM" : "Moment angulaire",
"I: moment of inertia, ω: angular velocity" : "I: moment d'inertie, ω : vitesse angulaire",
"PLANE MOTION OF A RIGID BODY" : "Mouvement plane d'un corps rigide",
"γ: angular acceleration, M: moment of a force" : "γ: accélération angulaire, M : moment de la force",

"4. CONSERVATION LAWS" : "4. Les lois de conservation",
"MOMENTUM OF FORCE" : "Moment de la force",
"LAW OF CONSERVATION OF MOMENTUM" : "Loi du moment de conservation",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂ : vitesse initiale des objets 1 et 2 ; v₁', v₂' : vitesses finales des objets 1 et 2",
"PLASTIC COLLISION" : "Collision plastique",
"v': velocity of the two body system (m₁+m₂) after impact" : "v' : vitesse de deux système de corps (m₁+m₂) après impact",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Collision élastique uni-dimensionnelle",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': vitesses de m₁ et m₂ après impact",
"5. WORK AND ENERGY" : "5. Travail et énergie",
"WORK" : "Travail",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W:travail effectué par une force (J), F : force de mouvement d'un objet pour une distance s, α : angle entre F et un mouvement directionnel",
"EXAMPLES" : "Exemples",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p : travail par la gravité, h : changement de hauteur ; W_ms : travail d'une force de friction ; W : travail d'un ressort",
"POWER" : "Energie",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: puissance (watt, W), t : temps de conduite d'un travail W (s)",
"KINETIC ENERGY" : "Energie cinétique",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Energie cinétique d'un corps massif en rotation",
"WORK-ENERGY PRINCIPLE" : "Principe travail-énergie",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂ : vitesses des objets avant et après le changement",
"POTENTIAL ENERGY" : "Energie potentielle",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p : énergie potentielle de gravitation (J), m : masse de l'objet (kg)",
"CONSERVATION OF MECHANICAL ENERGY" : "Energie mécanique de conservation",
"CONSERVATION OF ENERGY" : "Conservation de l'énergie",
"6. MECHANICS OF FLUIDS" : "6. Mécanique des fluides",
"DENSITY" : "Densité",
"m: mass of a volume V" : "m: masse d'un volume V",
"PRESSURE" : "Pression",
"F: force applied on area of A" : "F: force appliquée à une zone de A",
"PRESSURE OF LIQUIDS" : "Pression des liquides",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: gravité spécifique (N/m³), p_o : pression d'air dans une surface libre (N/m²), p : pression créée par le poid d'un liquide, p_B : pression totale de profondeur h",
"PASCAL’S PRINCIPLE" : "Principe de Pascal",
"p_s: pressure on the surface" : "p_s : pression sur la surface",
"APPLICATION" : "Application",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁,A₂ : zone de petits et grands cylindres ; F₁, F₂ : forces appliquées et forces remontantes",
"ARCHIMEDES’ PRINCIPLE" : "Principe d'Archimède",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: gravité spécifique d'un liquide (N/m³), V : volume d'un objet, F_b : force de flottabilité",
"FLOW RATE" : "Taux de débit",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: zone inter-sectionnelle (m²), v : vitesse du débit (m/s), Q : taux de débit (m³/s)",

"1. ELECTROSTATICS" : "1. Electrostatiques",
"COULOMB’S LAW" : "Loi de Coulomb",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: taille des charges (C); ɛ: permittivité relative (dans le vide ɛ=1); r: distance entre les charges (m)",
"ELECTRIC FIELDS" : "Champs électriques",
"E: electric field strength (N/C)" : "E: puissance du champs électrique (N/C)",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Principe de superposition des champs électriques",
"In case of 2 electric fields" : "Dans le cas de 2 champs électriques",
"WORK OF ELECTRIC FORCE" : "Travail de la force électrique",
"ELECTRIC POTENTIAL DIFFERENCE" : "Différence de potentiel électrique",
"RELATION BETWEEN E AND U" : "Relation entre E et U",
"CAPACITANCE" : "Capacité",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: résistance (F), Q : charge électrique totale (C), U : Potentiel électrique (V)",
"CAPACITOR" : "Capaciteur",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: zone de chaque électrode plate (m²), d : distance entre les électrodes (m), ε : permutativité relative",
"CAPACITANCES IN SERIES" : "Résistances en séries",
"CAPACITANCES IN PARALLEL" : "Résistances parallèles",
"ELECTRIC FIELD ENERGY" : "Energie du champs électrique",
"ENERGY OF CAPACITOR" : "Energie de la résistance",
"V=A.d: volume between two electrode plates" : "V=A.d : volume entre deux électrodes",
"2. DIRECT CURRENT" : "2. Courant Direct",
"ELECTRIC CURRENT" : "Courant électrique",
"I: current (A), q: charge (C), t: time" : "I: intensité (A), q : charge (C), t : temps",
"OHM’S LAW" : "Loi d'Ohm",
"U: electric potential difference between the ends of the resistor R" : "U: différence de potentiel électrique entre les fins de résistance R",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Travail créé par un courant (loi de Joule)",
"ELECTRICAL POWER" : "Puissance électrique",
"RESISTANCE" : "Résistance ",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: résistance des matériaux (Ωm), l : longueur (m), A : zone de section croisée (m²)",
"SERIES CIRCUITS" : "Circuits en séries",
"PARALLEL CIRCUITS" : "Circuits parallèles",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Travail ou énergie de chaleur produite par une résistance",
"POWER CONSUMPTION OF A RESISTOR" : "Consommation électrique d'une résistance",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Force électromotrice d'un générateur électrique",
"W: work of force (J), q: charge (C)" : "W: travail de force (J), q : charge (C)",
"GENERATORS IN SERIES" : "Générateurs en séries",
"r: internal resistance of the generator" : "r: résistance interne du générateur",
"GENERATORS IN PARALLEL" : "Générateurs en parallèle",
"GENERATORS IN SERIES-PARALLEL" : "Générateurs en séries-parallèles",
"WORK AND POWER OF GENERATOR" : "Travail et puissance du générateur",
"H: Efficiency of generator" : "H: efficience du générateur",
"3. MAGNETISM" : "3. Magnétisme",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Flux magnétique au travers d'une surface ouverte S",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: magnitude du champs magnétique (T, tesla), α : angle entre B et la ligne perpendiculaire à la surface S",
"MAGNETIC FORCES ON MOVING CHARGES" : "Forces magnétiques sur les charges en mouvements",
"v: velocity of the charge (m/s)" : "v: vitesse de la charge (m/s)",
"FORCE ON A CURRENT-CARRYING WIRE" : "Force sur un fil transportant le courant",
"I: current (A), l: length of the wire (m)" : "I: intensité (A), l: longueur du fil (m)",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Force entre 2 fils parallèles transportant du courant",
"r: distance between two wires (m)" : "r: distance entre deux fils (m)",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Champs magnétique d'un long fil chargé de courant",
"r: perpendicular distance from the center of the wire (m)" : "r: distance perpendiculaire de la distance du centre du fil (m)",
"MAGNETIC FIELD OF A LOOP" : "Champs magnétique d'un circuit",
"n: number of turns per unit length of solenoid (turns/m)" : "n: nombre de tours par unité de longueur d'un solénoïde (tours/m)",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Force électromotrice induite – Loi de Faraday",
"N: numbers of turns per loop (turns/m)" : "N: nombre de tours par circuit (tours/m)",
"INDUCTANCE" : "Induction",
"ELECTRIC ENERGY" : "Energie électrique",
"MAGNETIC ENERGY" : "Energie magnétique",
"ELECTRIC-MAGNETIC ENERGY" : "Energie électro-magnétique",
"4. ALTERNATING CURRENT" : "4. Courant alternatif",
"BASIC PARAMETERS" : "Paramètres de base",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: courant instantané (A); I_o: courant maximum instantané (A); T: période de l'onde; f: fréquence; λ: longueur d'onde; c: vitesse de la lumière ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Courant effectif et voltage",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Loi d'Ohm du courant AC contenant uniquement une résistance R",
"CONTAINING ONLY INDUCTOR L" : "Inducteur contenant seulement L",
"Z_L: inductive reactance" : "Z_L : réactivité induite",
"CONTAINING ONLY CAPACITOR C" : "Capaciteur contenant seulement C",
"Z_C: capacitive reactance" : "Z_C : réactivité capacitaire",
"CONTAINING R, L AND C IN A SERIES" : "Contenance R, L et C en série",
"Z: impedance" : "Z: impédance",
"PHASE ANGLE" : "Phase angulaire",
"POWER FACTOR" : "Facteur puissance",
"REAL POWER" : "Puissance réelle",
"ELECTRICAL RESONANCE" : "Résonance électrique",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Voltage changeant avec transformateurs",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂ : nombre de tours dans la bobine primaire et secondaire ; U₁, U₂ : voltage primaire et secondaire ; I₁, I₂ : courants primaire et secondaire",

"1. GAS LAWS" : "1. Lois des gaz",
"KELVIN TEMPERATURE" : "Températeur Kelvin",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: température suivant l'échelle de Kelvin; t: température suivant l'échelle Celsius",
"EQUATION OF STATE" : "Equation d'état",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: pression (P, Pascal), V : volume (m³), n : nombre de moles dans le gaz (mole), R : constante universelle du gaz (K), T: température suivant l'échelle de Kelvin (K), k : constante de Boltzmann, N : nombre de molécules dans le gaz",
"IDEAL GAS LAW" : "Loi du gaz idéal",
"BOYLE’S LAW FOR PRESSURE" : "Loi de Boyle sur la pression",
"If the temperature of the gas is constant" : "si la température du gaz est constante",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Loi de Gay-Lussac sur la pression-température",
"If the volume on a gas is constant" : "Si le volume du gaz est constant",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: pression du gaz à température t, p_o : pression à 0 Celsius, γ : facteur lorsque le volume est constant",
"Example when t=0 Kelvin" : "Exemple lorsque t=0 Kelvin",
"CHARLES'S LAW OF VOLUMES" : "Loi de Charles sur les volumes",
"If the pressure on a gas is constant" : "Si la pression sur un gaz est constante",
"2. CHANGES OF STATE AND SHAPE" : "2. Changements d'état et forme",
"HEAT" : "Chaleur",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e : Chaleur émise, Q_r : chaleur reçue, m : masse totale d'un objet (kg), c : chaleur spécifique (J/kg.K), Δt : changement dans la température (K)",
"The specific heats of some materials" : "Les chaleurs spécifiques de certains matériaux",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Fusion (congélation ou solidification)",
"Heat of fusion of some materials" : "Chaleur de fusion de certains matériaux",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: quantité de chaleur (J), λ : chaleur de fusion (J/kg), m : masse (kg)",
"VAPORIZATION" : "Vaporisation",
"L: heat of vaporization" : "L: chaleur de vaporisation",
"Heat of vaporization of some materials" : "Chaleur de vaporisation de certain matériaux",
"LINEAR EXPANSION" : "Expansion linéaire",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o : longueur originale (m), α : coefficient linéaire d'expansion (K⁻¹), Δt : changement de température",
"VOLUME EXPANSION" : "Volume d'expansion",
"AREA EXPANSION" : "Zone d'expansion",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Changement de densité (masse de densité volumétrique)",
"D_o: original density (kg/m³)" : "D_o : densité originale (kg/m³)",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Changement de diamètre de la section  droite d'un solide",
"3. THERMODYNAMICS" : "3. Thermodynamique",
"THE FIRST LAW OF THERMODYNAMICS" : "Première loi de la thermodynamique",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU : changement d'énergie interne, W : travail fait par le système, Q : chaleur ajoutée dans ou hors du système",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Application de la première loi aux lois des gaz idéaux",
"- Volume is constant" : "- Volume est constant",
"- Pressure is constant, W': work created by gas" : "- Pression est constante, W': travail créé par un gaz",
"- Temperature is constant" : "- Température est constante",
"THE SECOND LAW OF THERMODYNAMICS" : "La seconde loi de la thermodynamique",
"- The efficiency of a cyclic heat engine" : "- L'efficience d'un moteur à chaleur cyclique",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W' : travail effectué par cycle (J), Q₁ : chaleur absorbée par cycle de température plus élevée (J), Q₂' : chaleur rejetée par cycle à la température plus basse (J)",
"- Maximum thermal efficiency" : "- Efficience thermique maximale",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂ : températures hautes et basses",

"1. SIMPLE HARMONIC MOTION" : "1. Mouvement harmonique simple",
"SPRING" : "Ressort",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: élasticité constante (N/m), s : déplacement (m), ω : vitesse angulaire (rad/s), T : période, m : masse de l'objet, A : amplitude",
"SPRINGS IN SERIES" : "Ressorts en séries",
"k: spring constant of the system, T: period of the system" : "k: élasticité constante du système, T : période du système",
"SPRINGS IN PARALLEL" : "Ressorts en parallèle",
"SIMPLE PENDULUM" : "Pendule simple",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: vitesse angulaire (rad/s), T : période, α_o : angle d'amplitude, A : amplitude, l : longueur du pendule",
"MOTION EQUATIONS" : "Equations de mouvement",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: déplacement, α : angle, v : vitesse, T : force sur la tige",
"ENERGY" : "Energie",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p : énergie potentielle, E_k : énergie cinétique, E : énergie mécanique",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Changement de période suivant le changement de température",
"α: coefficient of linear expansion of the rod" : "α: coefficient d'expansion linéaire de la tige",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Changement de période suivant un changement de la hauteur",
"h: height of pendulum, R: Earth's radius" : "h: hauteur du pendule, R : rayon de la terre",
"PENDULUM" : "Pendule  ",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: moment d'inertie, ω : vitesse angulaire, masse d'un bob, d : OG, T : période",
"2. PERIODIC MOTION" : "2. Mouvement périodique",
"WAVELENGTH" : "Longueur d'onde",
"FUNCTION OF WAVE AT SOME POINTS" : "Fonction d'onde à un point",
"WAVE INTERFERENCE" : "Interférence ondulaire",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂ : 2 sources d'onde ayant la même phase, M : un point quelconque",
"3. SOUND WAVES" : "3. Ondes sonores",
"SOUND SPEED" : "Vitesse du son",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s) : vitesse du son dans un environnement à une température t",
"SOUND INTENSITY " : "Intensité sonore",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: énergie sonore (J), P : puissance du son (W), A : zone de la surface de la sphère (m²), t : temps (s)",
"SOUND INTENSITY LEVEL" : "Niveau d'intensité sonore",
"I_o: the standard reference sound intensity" : "I_o : l'intensité de référence standard du son",
"THE DOPPLER EFFECT" : "L'effet Doppler",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O : la vitesse relative de l'observateur, v_S : la vitesse relative de la source ; v : la vitesse du son dans ce moyen ; f_S, f_O : fréquence du son à la source et observateur",
"SOUND SPEED IN GASES" : "Vitesse du son dans les gaz",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: vitesse du son (m/s), R : constante universelle du gaz, T: température suivant l'échelle de Kelvin (K), M : masse moléculaire du gaz (kg/mole), γ : constante adiabatique",
"Example in air" : "Exemple dans l'air",

"1. GEOMETRIC OPTICS" : "1. Optiques géométriques",
"LAWS OF REFLECTION" : "Lois de la réflection",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI : rayon incident, IR : rayon réfléchit, i : angle d'incidence, i' : angle de réflexion",
"REFRACTIVE INDEX" : "Indice de réfraction",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: indice de réfraction dans le milieu, v : vitesse de la lumière dans le milieu, c : vitesse de la lumière dans le vide (m/s)",
"LAW OF REFRACTION" : "Loi de la réfraction",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁ : indice de réfraction du milieu 1,  n₂ : indice de réfraction du milieu 2, i : angle d'incidence, r : angle de réfraction, n₂₁ : indice absolu de réfraction",
"If medium 1 is vacuum" : "Si le milieu 1 est vide",
"TOTAL REFLECTION PHENOMENON" : "Phénomène total de rélexion",
"There is no refracted ray if" : "Il n'y a pas de rayon réfracté si",
"PRISM" : "Prisme",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: angle au sommet, D: angle de déviation, i₁ : angle d'incident, i₂ : angle de rayon émergeant",
"- Condition to have refractive ray" : "- Condition pour avoir un rayon réfracté",
"- When angle of incidence is minimum" : "- Lorsque l'angle d'incidence est au minimum",
"THIN LENS" : "Lentilles fines",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: longueur focale (lentille convergeante f&gt;0 ; lentille divergeante f&lt;0), d : distance de l'objet du centre des lentilles, d' : distance de l'image du centre des lentilles",
"MAGNIFICATION FACTOR" : "Facteur d'agrandissement",
"h_I: image height, h_O: object height" : "h_I : hauteur d'image, h_O : hauteur d'objet",
"POWER OF THE LENS" : "Puissance des lentilles",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: indice de réfraction des lentilles, R₁ : rayon de courbature de la surface de la lentille la plus proche à la source de lumière, R₂ : rayon de courbature de la surface de la lentille la plus éloignée de la source de lumière",
"2. QUANTUM OF LIGHT" : "2. Quanta de lumière",
"PHOTON ENERGY" : "Photon d'énergie",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: constante de Planck, f : fréquence (Hz), λ : longueur d'onde (m), c : vitesse de la lumière",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Condition pour avoir un effet photoélectrique",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: longueur d'onde de la lumière scintillante, λ_o : limite photoélectrique, W : travail émis (J)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Equation d'Einstein à propos de l'effet photoélectrique",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: masse d'un photon (kg), v_o : vitesse maximale d'un photon (m/s)",

"1. THEORY OF RELATIVITY" : "1. Théorie de la relativité",
"MASS–ENERGY EQUIVALENCE" : "Equivalence masse-énergie",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: masse (kg), E : énergie de l'objet (J), c : vitesse de la lumière (m/s)",
"LENGTH CONTRACTION" : "Contraction de la longueur",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o : longueur réelle de l'objet, l : longueur observée par un observateur en mouvement avec une vitesse v.",
"RELATIVISTIC MASS" : "Masse relative",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o : masse au repos, m : masse relative d'un objet en mouvement avec une vitesse v",
"TIME DILATION" : "Dilatation du temps",
"2. ATOMIC NUCLEUS" : "2. Nucléon atomique",
"NUCLEAR MAKEUP" : "Maquillage nucléaire",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: nombre de protons, N : nombre de neutrons, A : numéro de masse",
"NUCLEAR REACTION" : "Réaction nucléaire",
"- m&lt;m_o: nuclear reaction releases energy" : "-m&lt;m_o: énergie libérée dans la réaction nucléaire",
"- m&gt;m_o: nuclear reaction absorbs energy" : "-m&gt;m_o: réaction nucléaire absorbant l'énergie",
"RADIOACTIVE DECAY" : "Désintégration radioactive",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o : quantité initiale de substance active, N : quantité restante et n'ayant pas été désintégrée après un temps t, ΔN : quantité de substance désintégrée, m_o : masse initiale, m : masse restante, λ : constante de désintégration, t : temps, T: demi-vie",
"Half life of some elements" : "Demi-vie des éléments",
"AMOUNT OF RADIOACTIVITY" : "Quantité de radioactivité",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o : quantité initiale de radioactivité, H : quantité de radioactivité à un temps t",
"1. CONSTANTS" : "1. Constantes",
"ALPHA PARTICLE MASS" : "Masse de particules alpha",
"ATOMIC MASS CONSTANT" : "Constante de masse atomique",
"ATOMIC UNIT OF ENERGY" : "Unité d'énergie atomique",
"ATOMIC UNIT OF FORCE" : "Unité de force atomique",
"ATOMIC UNIT OF LENGTH" : "Unité de longueur atomique",
"ATOMIC UNIT OF MASS" : "Unité de masse atomique",
"AVOGADRO'S CONSTANT" : "Constante d'Avogadro",
"BOHR RADIUS" : "Rayon de Bohr",
"BOLTZMANN CONSTANT" : "Constante de Boltzmann",
"CLASSICAL ELECTRON RADIUS" : "Rayon classique d'électron",
"ELEMENTARY CHARGE" : "Charge élémentaire",
"EARTH MASS" : "Masse de la terre",
"EARTH EQUATORIAL RADIUS" : "Rayons équatorial de la terre",
"EARTH MEAN ORBITAL VELOCITY" : "Vitesse orbitale principale de la terre",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Vitesse angulaire rotationnelle de la terre",
"FARADAY’S CONSTANT" : "Constante de Faraday",
"GAS CONSTANT" : "Constante de gaz",
"MOLAR MASS CONSTANT" : "Constante de masse molaire",
"MOLAR VOLUME OF IDEAL GAS" : "Volume molaire de gaz idéal",
"NEUTRON MASS" : "Masse neutronique",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Constante de gravitation de Newton",
"PLANCK’S CONSTANT" : "Constante de Planck",
"PLANCK MASS" : "Masse de Planch",
"PROTON MASS" : "Masse de proton",
"PROTON-ELECTRON MASS RATIO" : "Ratio de masse proton-électron",
"SPEED OF LIGHT IN VACUUM" : "Vitesse de la lumière dans le vide",
"STANDARD ACCELERATION OF GRAVITY" : "Accélération standard de la gravité",
"STANDARD ATMOSPHERE" : "Atmosphère standard",
"STANDARD REFERENCE SOUND INTENSITY" : "Intensité sonore standard de référence",
"STEFAN-BOLTZMANN CONSTANT" : "Constante de Stefan-Boltzmann",
"2. GREEK ALPHABET" : "2. Alphabet Grec",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1 : lettre grecque, C2 : nom, C3 : équivalent, C4 : son lorsque parlé",

"Mechanics" : "Mécanique",
"Thermal physics" : "Thermodynamique",
"Optics" : "Optique",
"Theory of relativity" : "Théorie de la relativité",

"FREE FALLING" : "Chute libre",
"VERTICAL PROJECTILE" : "Projectile vertical",
"ANGLED PROJECTILE" : "Projectile angulaire",
"HORIZONTAL PROJECTILE" : "Projectile horizontal",
"SLIDING MOTION" : "Mouvement de glissement",
"ATTRACTIVE FORCE" : "Force d'attraction",
"Hydraulic press" : "Presse hydraulique",
"PRESSURE" : "Pression",
"LINEAR EXPANSION" : "Expansion linéaire",
"VOLUME EXPANSION" : "Volume d'expansion",
"SOUND SPEED" : "Vitesse du son",
"REFRACTION" : "Réfraction",
"PRISM" : "Prisme",
"LENS" : "Lentilles",
"Length contraction" : "Contraction de la longueur",
"Time dilation" : "Dilatation du temps",
"RELATIVISTIC MASS" : "Masse relative",

"Height " : "Hauteur",
"Time to touchdown " : "Durée jusqu'au sol",
"Touchdown velocity " : "Vitesse jusqu'au sol",
"Initial velocity " : "Vélocité initiale",
"Maximum height " : "Hauteur maximale",
"Initial velocity " : "Vélocité initiale",
"Angle " : "Angle",
"Maximum height " : "Hauteur maximale",
"Maximum distance " : "Distance maximale",
"Height " : "Hauteur",
"Initial velocity " : "Vélocité initiale",
"Time to touchdown " : "Durée jusqu'au sol",
"Touchdown velocity " : "Vitesse jusqu'au sol",
"Angle of titled plane " : "Angle de plan intitulé",
"Coefficient of friction " : "Coefficient de friction",
"Acceleration " : "Accélération  ",
"Mass " : "Masse  ",
"Mass " : "Masse  ",
"Distance " : "Distance  ",
"Attractive force " : "Force d'attraction",
"Area " : "Zone  ",
"Area " : "Zone  ",
"Force " : "Force  ",
"Force" : "Force  ",
"Force F₂ (or F₁)" : "Force F₂ (ou F₁)",
"Temperature " : "Température",
"Pressure at 0°C " : "Pression à 0°C",
"Pressure " : "Pression  ",
"Original length " : "Longueur originale",
"Temperature change " : "Changement de température",
"Coefficient of linear expansion " : "Coefficient d'expansion linéaire",
"Change of length " : "Changement de longueur",
"Original volume " : "Volume original",
"Temperature change " : "Changement de température",
"Coefficient of linear expansion " : "Coefficient d'expansion linéaire",
"Change of volume " : "Changement de volume",
"Temperature " : "Température",
"Sound speed " : "Vitesse du son",
"Refractive index " : "Indice de réfraction",
"Refractive index " : "Indice de réfraction",
"Angle of incidence " : "Angle d'incidence",
"Angle of refraction " : "Angle de réfraction",
"Angle (r or i) " : "Angle (r ou i)",
"Apex angle " : "Angle au sommet",
"Angle of incident " : "Angle d'incidence",
"Refractive index " : "Indice de réfraction",
"Angle of emergent ray " : "Angle de rayon émergeant",
"Deviation angle " : "Angle de déviation",
"Focal length " : "Longueur focale",
"Object distance " : "Distance de l'objet",
"Image distance " : "Distance de l'image",
"Image (or object) distance" : "Distance ou image de l'objet",
"Magnification factor " : "Facteur d'agrandissement",
"Speed " : "Vitesse du son",
"Proper length " : "Longueur propre",
"Observed length " : "Longueur observée",
"Rest mass " : "Masse restante",
"Relativistic mass " : "Masse relative",
"Proper time interval " : "Intervalle propre de temps",
"Observed time interval " : "Intervalle observé de temps",
"Calculate" : "Calculer",
"Or input" : "Ou entrée",
"Calculation Tools" : "Outils de calcul",



	
};