var language={


"1. DYNAMICS" : "1. Dinamica",
"STRAIGHT LINE MOTION" : "Moto rettilineo",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: distanza (m), t: tempo (s, secondo), v: Velocità (m/s), v_a: velocità media",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Moto rettilineo uniformemente accelerato",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: accelerazione, v_o: velocità iniziale, v: velocità al tempo t",
"DISTANCE FUNCTION" : "Funzione di distanza",
"xₒ: initial distance from origin, x: distance at time t" : "x_o: distanza iniziale dall'origine, x: distanza al tempo t",
"UNIFORM CIRCULAR MOTION" : "Moto circolare uniforme",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: angolo (rad), l: lunghezza dell'arco, R: raggio del cerchio, ω: velocità angolare (rad/s), t: tempo in cui l'oggetto si sposta di una lunghezza l",
"CENTRIPETAL FORCE" : "Forza centripeta",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: frequenza (Hz), T: il periodo di una rotazione (s), a: accelerazione centripeta, F: forza centripeta (N, Newton)",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Moto circolare uniformemente accelerato",
"γ: angular acceleration" : "γ: accelerazione angolare",
"ACCELERATION" : "Accelerazione",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: accelerazione tangenziale, a_n: accelerazione normale",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: accelerare, P2: moto circolare uniforme, P3: decelerando",
"FREE FALLING FROM HEIGHT h" : "Caduta libera da un'altezza h",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: accelerazione di gravità, v: velocità all'istante t, s: distanza dopo t, v_h: la velocità quando si tocca il suolo, t_h: tempo all'atterraggio",
"VERTICAL PROJECTILE MOTION" : "Moto del proiettile Verticale",
"h_max: maximum height, v_o: initial velocity" : "h_max: altezza massima, v_o: velocità iniziale",
"Motion equation and velocity equation" : "Equazione del moto e Equazione di velocità",
"ANGLED PROJECTILE MOTION" : "Moto parabolico del proiettile ",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: velocità; x, y: equazione del moto per t; H: altezza massima; L: distanza massima",
"HORIZONTAL PROJECTILE MOTION" : "Moto del proiettile Orizzontale",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: tempo in cui tocca terra, v_h: velocità quando tocca terra",
"SLIDING MOTION ON AN INCLINED PLANE" : "Moto di scorrimento su di un piano inclinato",
"μ: coefficient of friction" : "μ: coefficiente di attrito",
"Fiction coefficient of some materials" : "Coefficiente di attrito di alcuni materiali",
"2. FORCES" : "2. Forze",
"ATTRACTIVE FORCE" : "Forza attrattiva",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: massa dei 2 oggetti; r: distanza tra i 2 oggetti; G: costante gravitazionale",
"GRAVITATIONAL FORCE" : "Forza gravitazionale",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: massa della Terra, m: massa dell'oggetto, R: raggio terrestre, h: altezza dell'oggetto",
"GRAVITATIONAL ACCELERATION" : "Accelerazione di gravità",
"At a height h above the nominal surface of the earth" : "Ad un'altezza h sopra la superficie nominale della terra",
"Near the sea level" : "Vicino al livello del mare",
"FORCE OF GRAVITY" : "Forza di gravità",
"Force of gravity on earth, a special case of Gravitational force" : "Forza di gravità sulla terra, un caso particolare di forza gravitazionale",
"NEWTON'S FIRST LAW" : "Prima legge di Newton",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: forze agenti sull'oggetto, v: velocità dell'oggetto, a: accelerazione dell'oggetto",
"NEWTON'S SECOND LAW" : "Seconda legge di Newton",
"m: object's mass (kg)" : "m: la massa dell'oggetto (kg)",
"NEWTON'S THIRD LAW" : "Terza legge di Newton",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Elasticità lineare - legge di Hooke",
"k: spring constant (N/m), x: displacement (m)" : "k: costante della molla (N/m), x: spostamento (m)",
"A mass suspended by a spring" : "Una massa sospesa attaccata ad una molla",
"FORCE OF FRICTION" : "Forza di attrito",
"μ: coefficient of friction, N: normal force" : "μ: coefficiente di attrito, N: forza normale",
"3. STATICS" : "3. Statica",
"MOMENT OF A FORCE" : "Momento di una forza",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: forza applicata (N), d: braccio del momento (la distanza perpendicolare dall'asse alla linea di azione della forza)",
"MOMENT APPLICATION" : "MOMENTO DI APPLICAZIONE",
"MOMENT OF INERTIA" : "Momento d'inerzia",
"Rod of length l" : "Asta di lunghezza l",
"Thin circular hoop/ Thin cylindrical shell" : "Anello sottile/mantello cilindrico sottile",
"Solid disk/ Solid cylinder" : "Disco solido/cilindro solido",
"Solid ball" : "Sfera solida",
"Hollow sphere" : "Sfera cava",
"ANGULAR MOMENTUM" : "Momento angolare",
"I: moment of inertia, ω: angular velocity" : "I: momento d'inerzia, ω: velocità angolare",
"PLANE MOTION OF A RIGID BODY" : "MOTO PIANO DI UN CORPO RIGIDO",
"γ: angular acceleration, M: moment of a force" : "γ: accelerazione angolare, M: momento di una forza",

"4. CONSERVATION LAWS" : "4. Leggi di conservazione",
"MOMENTUM OF FORCE" : "Momento di forza",
"LAW OF CONSERVATION OF MOMENTUM" : "La legge di conservazione del momento",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: velocità iniziali degli oggetti 1 e 2; v₁', v₂': velocità finali degli oggetti 1 e 2",
"PLASTIC COLLISION" : "Urto totalmente anaelastico",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': velocità del sistema di due corpi (m₁ + m₂) dopo l'impatto",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Urto elastico monodimensionale",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': velocità di m₁ e m₂ dopo l'impatto",
"5. WORK AND ENERGY" : "5. Lavoro ed energia",
"WORK" : "Lavoro",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: il lavoro svolto da una forza (J), F: forza per spostare un oggetto di una distanza s, α: angolo tra F e la direzione del movimento",
"EXAMPLES" : "Esempi",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: lavoro della forza di gravità, h: la variazione di altezza; W_ms: opera della forza di attrito; W: lavoro di una molla",
"POWER" : "Energia",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: Potenza (Watt, W), t: tempo per avere un lavoro W (s)",
"KINETIC ENERGY" : "Energia cinetica",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Energia cinetica di un corpo massiccio rotante",
"WORK-ENERGY PRINCIPLE" : "Principio di lavoro-energia",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: velocità di oggetti prima e dopo il cambiamento",
"POTENTIAL ENERGY" : "Energia potenziale",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: energia potenziale gravitazionale (J), m: la massa dell'oggetto (kg)",
"CONSERVATION OF MECHANICAL ENERGY" : "Conservazione dell'energia meccanica",
"CONSERVATION OF ENERGY" : "Conservazione dell'Energia",
"6. MECHANICS OF FLUIDS" : "6. Meccanica dei fluidi",
"DENSITY" : "Densità",
"m: mass of a volume V" : "m: massa di un volume V",
"PRESSURE" : "Pressione",
"F: force applied on area of A" : "F: forza applicata sulla superficie di A",
"PRESSURE OF LIQUIDS" : "Pressione idrostatica",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: peso specifico (N/m), p_o: pressione dell'aria sulla superficie libera (N/m), p: pressione creata dal peso di liquido sopra, p_B: pressione totale alla profondità h",
"PASCAL’S PRINCIPLE" : "Principio di Pascal",
"p_s: pressure on the surface" : "p_s: pressione sulla superficie",
"APPLICATION" : "Applicazione",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: area del piccolo e del grande cilindro; F₁, F₂: forze applicate e verso l'alto",
"ARCHIMEDES’ PRINCIPLE" : "Principio di Archimede'",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: peso specifico del liquido (N/m³), ​​V: volume dell'oggetto, F_b: spinta di Archimede",
"FLOW RATE" : "Portata",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: sezione trasversale (m²), v: velocità del flusso (m/s), D: portata (m³/s)",

"1. ELECTROSTATICS" : "1. Elettrostatica",
"COULOMB’S LAW" : "La legge di Coulomb",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: carica (C), ε: costante dielettrica relativa (nel vuoto ε = 1), r: distanza tra le cariche (m)",
"ELECTRIC FIELDS" : "Campi elettrici",
"E: electric field strength (N/C)" : "E: intensità di campo elettrico (N/C)",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Il principio di sovrapposizione per campi elettrici",
"In case of 2 electric fields" : "In caso di 2 campi elettrici",
"WORK OF ELECTRIC FORCE" : "Lavoro della forza elettrica",
"ELECTRIC POTENTIAL DIFFERENCE" : "Differenza di potenziale elettrico",
"RELATION BETWEEN E AND U" : "Relazione tra E e U",
"CAPACITANCE" : "Capacità",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: capacità (F), Q: la carica elettrica totale (C), U: potenziale elettrico (V)",
"CAPACITOR" : "Condensatore",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: area di ogni piastra elettrodica (mq), d: distanza tra gli elettrodi (m), ε: permittività relativa (F/m)",
"CAPACITANCES IN SERIES" : "Capacità in serie",
"CAPACITANCES IN PARALLEL" : "Capacità in parallelo",
"ELECTRIC FIELD ENERGY" : "Energia di campo elettrico",
"ENERGY OF CAPACITOR" : "Energia del condensatore",
"V=A.d: volume between two electrode plates" : "V = A.d: volume tra due piastre di elettrodi",
"2. DIRECT CURRENT" : "2. corrente continua",
"ELECTRIC CURRENT" : "Corrente elettrica",
"I: current (A), q: charge (C), t: time" : "I: corrente (A), q: carica (C), t: tempo",
"OHM’S LAW" : "Legge di Ohm",
"U: electric potential difference between the ends of the resistor R" : "U: differenza di potenziale elettrico fra le estremità del resistore R",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Lavoro generato da una corrente (legge di Joule)",
"ELECTRICAL POWER" : "Elettricità",
"RESISTANCE" : "Resistenza",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: resistività del materiale (Ωm), l: lunghezza (m), A: area della sezione trasversale (mq)",
"SERIES CIRCUITS" : "Circuiti in serie",
"PARALLEL CIRCUITS" : "Circuiti in parallelo",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Lavoro o energia termica prodotta da un resistore",
"POWER CONSUMPTION OF A RESISTOR" : "Il consumo di energia di un resistore",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Forza elettromotrice di un generatore elettrico",
"W: work of force (J), q: charge (C)" : "W: lavoro della forza (J), q: carica (C)",
"GENERATORS IN SERIES" : "Generatori in serie",
"r: internal resistance of the generator" : "r: resistenza interna del generatore",
"GENERATORS IN PARALLEL" : "Generatori in parallelo",
"GENERATORS IN SERIES-PARALLEL" : "Generatori in serie-parallelo",
"WORK AND POWER OF GENERATOR" : "Lavoro e potenza del generatore",
"H: Efficiency of generator" : "H: Efficienza del generatore",
"3. MAGNETISM" : "3. Magnetismo",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Flusso del campo magnetico attraverso la superficie S aperta",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: intensità del campo magnetico (T, tesla), α: angolo tra B e perpendicolare alla superficie S",
"MAGNETIC FORCES ON MOVING CHARGES" : "Forze magnetiche sulle cariche in movimento",
"v: velocity of the charge (m/s)" : "v: velocità della carica (m/s)",
"FORCE ON A CURRENT-CARRYING WIRE" : "Forza su un filo percorso da corrente",
"I: current (A), l: length of the wire (m)" : "I: corrente (A), l: lunghezza del filo (m)",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Forza tra 2 fili percorsi da corrente paralleli",
"r: distance between two wires (m)" : "r: distanza tra due fili (m)",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Campo magnetico di un lungo filo carico di corrente",
"r: perpendicular distance from the center of the wire (m)" : "r: distanza perpendicolare dal centro del filo (m)",
"MAGNETIC FIELD OF A LOOP" : "Campo magnetico di un anello ",
"n: number of turns per unit length of solenoid (turns/m)" : "n: numero di spire per unità di lunghezza del magnete (giri/m)",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Forza elettromotrice indotta - legge di Faraday",
"N: numbers of turns per loop (turns/m)" : "N: numero di giri per anello (giri/m)",
"INDUCTANCE" : "Induttanza",
"ELECTRIC ENERGY" : "Energia elettrica",
"MAGNETIC ENERGY" : "Energia magnetica",
"ELECTRIC-MAGNETIC ENERGY" : "Energia elettromagnetica",
"4. ALTERNATING CURRENT" : "4. Corrente alternata",
"BASIC PARAMETERS" : "Parametri di base",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "I: corrente istantanea (A), I_o: massima corrente istantanea (A), T: periodo dell'onda, f: frequenza, λ: lunghezza d'onda, c: velocità della luce",
"EFFECTIVE CURRENT AND VOLTAGE" : "Tensione e corrente efficace ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Legge di Ohm per Corrente AC contenente Solo la Resistenza R",
"CONTAINING ONLY INDUCTOR L" : "Contenente solo induttore L",
"Z_L: inductive reactance" : "Z_L: reattanza induttiva",
"CONTAINING ONLY CAPACITOR C" : "Contenente solo condensatore C",
"Z_C: capacitive reactance" : "Z_C: reattanza capacitiva",
"CONTAINING R, L AND C IN A SERIES" : "Contenenti R, L e C in una serie",
"Z: impedance" : "Z: impedenza",
"PHASE ANGLE" : "Angolo di fase",
"POWER FACTOR" : "Fattore di potenza",
"REAL POWER" : "Potenza reale",
"ELECTRICAL RESONANCE" : "Risonanza elettrica",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Cambiare tensione con trasformatori",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: numero di spire nella bobina primaria e bobina secondaria; U₁, U₂: tensione a primario e secondario; I₁, I₂: le correnti a primario e a secondario",

"1. GAS LAWS" : "1. Leggi dei gas",
"KELVIN TEMPERATURE" : "Temperatura kelvin",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: temperatura in gradi Kelvin, t: temperatura nella scala Celsius",
"EQUATION OF STATE" : "Equazione di Stato",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: pressione (P, Pascal), V: Volume (m³), n: numero di moli di gas (mol), R: costante universale gas, T: temperatura Kelvin del gas (K), k: costante di Boltzmann, N: numero di molecole nel gas",
"IDEAL GAS LAW" : "Legge per i gas ideali",
"BOYLE’S LAW FOR PRESSURE" : "Legge di Boyle per la pressione",
"If the temperature of the gas is constant" : "Se la temperatura del gas è costante",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Legge di Gay-Lussac di pressione-temperatura",
"If the volume on a gas is constant" : "Se il volume di un gas è costante",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: pressione del gas a temperatura t, p_o: pressione a 0 gradi Celsius, γ: Fattore quando il volume è costante",
"Example when t=0 Kelvin" : "Esempio quando t=0 Kelvin",
"CHARLES'S LAW OF VOLUMES" : "La legge di Charles dei volumi",
"If the pressure on a gas is constant" : "Se la pressione in un gas è costante",
"2. CHANGES OF STATE AND SHAPE" : "2. Variazioni di Stato e di forma",
"HEAT" : "Calore",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: calore emesso, Q_r: calore ricevuto, m: massa totale dell'oggetto (kg), c: calore specifico (J/kg.K), ∆t: cambiamento di temperatura (K)",
"The specific heats of some materials" : "I calori specifici di alcuni materiali",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Fusione (congelamento o solidificazione)",
"Heat of fusion of some materials" : "Calore di fusione di alcuni materiali",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: quantità di calore (J), λ: calore di fusione (J/kg), m: massa (kg)",
"VAPORIZATION" : "Vaporizzazione",
"L: heat of vaporization" : "L: calore di vaporizzazione",
"Heat of vaporization of some materials" : "Calore di vaporizzazione di alcuni materiali",
"LINEAR EXPANSION" : "Dilatazione lineare",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: lunghezza originale (m), α: coefficiente di dilatazione lineare (K⁻¹), ∆t: variazione di temperatura",
"VOLUME EXPANSION" : "Espansione del volume",
"AREA EXPANSION" : "Espansione dell'area",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Variazione di densità (densità di massa volumica)",
"D_o: original density (kg/m³)" : "D_o: densità originale (kg/m³)",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Modifica del diametro della sezione trasversale di un solido",
"3. THERMODYNAMICS" : "3. Termodinamica",
"THE FIRST LAW OF THERMODYNAMICS" : "La Prima Legge della Termodinamica",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU: variazione di energia interna, W: lavoro svolto dal sistema, Q: il calore aggiunto dentro o fuori del sistema",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Applicazione della prima legge per le leggi dei gas perfetti",
"- Volume is constant" : "- Il volume è costante",
"- Pressure is constant, W': work created by gas" : "- La pressione è costante,  W': lavoro generato dal gas",
"- Temperature is constant" : "- La temperatura è costante",
"THE SECOND LAW OF THERMODYNAMICS" : "La seconda legge della termodinamica",
"- The efficiency of a cyclic heat engine" : "- L'efficienza di una macchina termica ciclica",

"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': lavoro svolto per ciclo (J), Q₁: calore assorbito per ciclo dalla temperatura più alta (J), Q₂': il calore ceduto per ciclo alla temperatura più bassa (J)",
"- Maximum thermal efficiency" : "- Massima efficienza termica",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: alta e bassa temperatura",

"1. SIMPLE HARMONIC MOTION" : "1. Moto armonico semplice",
"SPRING" : "Molla",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: costante della molla (N/m), s: spostamento (m), ω: velocità angolare (rad/s), T: Periodo, m: massa dell'oggetto, A: ampiezza",
"SPRINGS IN SERIES" : "Molle in serie",
"k: spring constant of the system, T: period of the system" : "k: costante della molla del sistema, T: periodo del sistema",
"SPRINGS IN PARALLEL" : "Molle in parallelo",
"SIMPLE PENDULUM" : "Pendolo semplice",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: velocità angolare (rad/s), T: periodo α_o: angolo in ampiezza, A: l'ampiezza, l: lunghezza del pendolo",
"MOTION EQUATIONS" : "Equazioni del moto",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: spostamento, α: angolo, v: velocità, T: forza sull'asta",
"ENERGY" : "Energia",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: energia potenziale, E_k: energia cinetica, E: energia meccanica",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Variazione del periodo successiva alla variazione della temperatura",
"α: coefficient of linear expansion of the rod" : "α: coefficiente di dilatazione lineare dell'asta",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Variazione del periodo successiva al cambiamento dell'altezza",
"h: height of pendulum, R: Earth's radius" : "h: altezza del pendolo, R: Raggio della Terra",
"PENDULUM" : "Pendolo",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: momento di inerzia, ω: velocità angolare, m: massa di bob, d: OG, T: periodo",
"2. PERIODIC MOTION" : "2. moto periodico",
"WAVELENGTH" : "Lunghezza d'onda",
"FUNCTION OF WAVE AT SOME POINTS" : "Funzione d'onda in alcuni punti",
"WAVE INTERFERENCE" : "Interferenze d'onda",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 sorgenti d'onda aventi stessa fase; M: un punto casuale",
"3. SOUND WAVES" : "3. Onde sonore",
"SOUND SPEED" : "Velocità del suono",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): velocità del suono in ambiente con temperatura t (Celsius)",
"SOUND INTENSITY " : "Intensità sonora",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: energia sonora (J), P: potenza sonora (W), A: la superficie di una sfera (m²), t: tempo (s)",
"SOUND INTENSITY LEVEL" : "Livello di intensità sonora",
"I_o: the standard reference sound intensity" : "I_o: l'intensità del suono di riferimento standard",
"THE DOPPLER EFFECT" : "L'effetto Doppler",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: la velocità relativa dell'osservatore; v_S: la velocità relativa della sorgente; v: la velocità del suono in questo mezzo; f_S, f_O: frequenza del suono della sorgente e dell'osservatore",
"SOUND SPEED IN GASES" : "Velocità suono nei gas",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: velocità del suono (m/s), R: costante universale dei gas, T: temperatura assoluta (K), M: massa molecolare del gas (kg/mol), γ: costante adiabatica",
"Example in air" : "Esempio in aria",

"1. GEOMETRIC OPTICS" : "1. Ottica geometrica",
"LAWS OF REFLECTION" : "Leggi della riflessione",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: raggio incidente, IR: raggio riflesso, i: angolo di incidenza, i': angolo di riflessione",
"REFRACTIVE INDEX" : "Indice di rifrazione",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: indice di rifrazione del mezzo, v: velocità della luce in un mezzo, c: velocità della luce nel vuoto (m/s)",
"LAW OF REFRACTION" : "Legge di rifrazione",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: indice di rifrazione del mezzo 1, n₂: indice di rifrazione del mezzo 2, i: angolo di incidenza, r: angolo di rifrazione, n₂₁: indice di rifrazione assoluto",
"If medium 1 is vacuum" : "Se il mezzo 1 è vuoto",
"TOTAL REFLECTION PHENOMENON" : "Fenomeno della riflessione totale",
"There is no refracted ray if" : "Non c'è raggio rifratto se",
"PRISM" : "Prisma",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: angolo di vertice, D: angolo di deviazione, i₁: angolo di incidenza, i₂: angolo del raggio emergente",
"- Condition to have refractive ray" : "- Condizione per avere raggio di rifrazione",
"- When angle of incidence is minimum" : "- Quando l'angolo di incidenza è minimo",
"THIN LENS" : "Lente sottile",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: lunghezza focale (lente convergente f&gt;0; lente divergente f&lt;0), d: distanza dell'oggetto dal centro della lente, d':  distanza dell'immagine dal centro della lente",
"MAGNIFICATION FACTOR" : "Fattore di ingrandimento",
"h_I: image height, h_O: object height" : "h_I: altezza dell'immagine, h_O: altezza dell'oggetto",
"POWER OF THE LENS" : "Potenza della lente",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: indice di rifrazione del materiale della lente, R₁: raggio di curvatura della superficie della lente più vicina alla sorgente di luce, R₂: raggio di curvatura della superficie della lente più lontana dalla sorgente luminosa",
"2. QUANTUM OF LIGHT" : "2. Quantum di luce",
"PHOTON ENERGY" : "L'energia fotonica",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: costante di Planck, f: frequenza (Hz), λ: lunghezza d'onda (m), c: velocità della luce",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Condizioni per avere l'effetto fotoelettrico",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: lunghezza d'onda della luce , λ_o: limite fotoelettrico, W: lavoro emesso (J)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Equazione di Einstein su effetto fotoelettrico",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: massa del fotoelettrone (kg), v_o: velocità massima del fotoelettrone (m/s)",

"1. THEORY OF RELATIVITY" : "1. Teoria della relatività",
"MASS–ENERGY EQUIVALENCE" : "Equivalenza massa-energia",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: massa (kg), E: energia dell'oggetto (J), c: velocità della luce (m/s)",
"LENGTH CONTRACTION" : "Lunghezza della contrazione",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: lunghezza reale dell'oggetto, l: lunghezza osservata da un osservatore che si muove con velocità v",
"RELATIVISTIC MASS" : "Massa relativistica",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: massa a riposo, m: la massa relativistica dell'oggetto quando si muove con velocità v",
"TIME DILATION" : "Dilatazione del tempo",
"2. ATOMIC NUCLEUS" : "2. nucleo atomico",
"NUCLEAR MAKEUP" : "Composizione Nucleare",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: numero di protoni, N: numero di neutroni, A: numero di massa",
"NUCLEAR REACTION" : "Reazione nucleare",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: reazione nucleare rilascia energia",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: reazione nucleare assorbe energia",
"RADIOACTIVE DECAY" : "Decadimento radioattivo",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: importo iniziale di sostanza attiva, N: quantità che rimane ancora e non è ancora decaduta dopo un tempo t, ΔN: quantità di sostanza decaduta, m_o: massa iniziale, m: massa rimasta, λ: costante di decadimento, t: tempo, T: tempo di dimezzamento",
"Half life of some elements" : "Dimezzamento di alcuni elementi",
"AMOUNT OF RADIOACTIVITY" : "Quantità di radioattività",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: importo iniziale di radioattività, H: quantità di radioattività al tempo t",
"1. CONSTANTS" : "1. Costanti",
"ALPHA PARTICLE MASS" : "massa della particella alfa",
"ATOMIC MASS CONSTANT" : "costante di massa atomica",
"ATOMIC UNIT OF ENERGY" : "unità atomica di energia",
"ATOMIC UNIT OF FORCE" : "unità atomica di forza",
"ATOMIC UNIT OF LENGTH" : "unità atomica di lunghezza",
"ATOMIC UNIT OF MASS" : "unità atomica di massa",
"AVOGADRO'S CONSTANT" : "Costante di Avogadro",
"BOHR RADIUS" : "Raggio di Bohr",
"BOLTZMANN CONSTANT" : "Costante di Boltzmann",
"CLASSICAL ELECTRON RADIUS" : "raggio classico dell'elettrone",
"ELEMENTARY CHARGE" : "carica elementare",
"EARTH MASS" : "massa della terra",
"EARTH EQUATORIAL RADIUS" : "raggio equatoriale della terra",
"EARTH MEAN ORBITAL VELOCITY" : "velocità orbitale della terra",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Velocità angolare di rotazione della Terra",
"FARADAY’S CONSTANT" : "Costante di Faraday",
"GAS CONSTANT" : "costante dei gas",
"MOLAR MASS CONSTANT" : "costante di massa molare",
"MOLAR VOLUME OF IDEAL GAS" : "volume molare del gas ideale",
"NEUTRON MASS" : "massa del neutrone",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Costante di gravitazione newtoniana",
"PLANCK’S CONSTANT" : "La costante di Planck",
"PLANCK MASS" : "Massa di Planck",
"PROTON MASS" : "massa del protone",
"PROTON-ELECTRON MASS RATIO" : "rapporto massa del protone-elettrone",
"SPEED OF LIGHT IN VACUUM" : "velocità della luce nel vuoto",
"STANDARD ACCELERATION OF GRAVITY" : "accelerazione standard di gravità",
"STANDARD ATMOSPHERE" : "atmosfera standard",
"STANDARD REFERENCE SOUND INTENSITY" : "Standard di riferimento di intensità sonora",
"STEFAN-BOLTZMANN CONSTANT" : "Costante di Stefan-Boltzmann",
"2. GREEK ALPHABET" : "2. alfabeto greco",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: lettera greca, C2: Nome, C3: Equivalente, C4: Suono quando gli si parla",

"Mechanics" : "Meccanica",
"Thermal physics" : "Fisica termica",
"Optics" : "Ottica",
"Theory of relativity" : "Teoria della relatività",

"FREE FALLING" : "Caduta libera",
"VERTICAL PROJECTILE" : "Proiettile Verticale",
"ANGLED PROJECTILE" : "Proiettile ad angolo",
"HORIZONTAL PROJECTILE" : "Proiettile Orizzontale",
"SLIDING MOTION" : "Scorrimento",
"ATTRACTIVE FORCE" : "Forza attrattiva",
"Hydraulic press" : "Pressa idraulica",
"PRESSURE" : "Pressione",
"LINEAR EXPANSION" : "Dilatazione lineare",
"VOLUME EXPANSION" : "Espansione del volume",
"SOUND SPEED" : "Velocità del suono",
"REFRACTION" : "Rifrazione",
"PRISM" : "Prisma",
"LENS" : "Lente",
"Length contraction" : "Lunghezza della contrazione",
"Time dilation" : "Dilatazione del tempo",
"RELATIVISTIC MASS" : "Massa relativistica",

"Height " : "Altezza",
"Time to touchdown " : "Tempo per toccare terra",
"Touchdown velocity " : "Velocità quando tocca terra",
"Initial velocity " : "Velocità iniziale",
"Maximum height " : "Altezza massima",
"Initial velocity " : "Velocità iniziale",
"Angle " : "Angolo",
"Maximum height " : "Altezza massima",
"Maximum distance " : "Distanza massima",
"Height " : "Altezza",
"Initial velocity " : "Velocità iniziale",
"Time to touchdown " : "Tempo per toccare terra",
"Touchdown velocity " : "Velocità quando tocca terra",
"Angle of tilted plane " : "Angolo del piano inclinato",
"Coefficient of friction " : "Coefficiente d'attrito",
"Acceleration " : "Accelerazione",
"Mass " : "Massa",
"Mass " : "Massa",
"Distance " : "Distanza",
"Attractive force " : "Forza attrattiva",
"Area " : "Area",
"Area " : "Area",
"Force " : "Forza",
"Force" : "Forza",
"Force F₂ (or F₁)" : "Forza F₂ (o F₁)",
"Temperature " : "Temperatura",
"Pressure at 0°C " : "Pressione a 0°C",
"Pressure " : "Pressione",
"Original length " : "Lunghezza originale",
"Temperature change " : "Variazione di temperatura",
"Coefficient of linear expansion " : "Coefficiente di espansione lineare",
"Change of length " : "Variazione di lunghezza",
"Original volume " : "Volume originale",
"Temperature change " : "Variazione di temperatura",
"Coefficient of linear expansion " : "Coefficiente di espansione lineare",
"Change of volume " : "Variazione di volume",
"Temperature " : "Temperatura",
"Sound speed " : "Velocità del suono",
"Refractive index " : "Indice di rifrazione",
"Refractive index " : "Indice di rifrazione",
"Angle of incidence " : "Angolo di incidenza",
"Angle of refraction " : "Angolo di rifrazione",
"Angle (r or i) " : "Angle (r o i)",
"Apex angle " : "Angolo all'apice",
"Angle of incident " : "Angolo di incidente",
"Refractive index " : "Indice di rifrazione",
"Angle of emergent ray " : "Angolo del raggio emergente",
"Deviation angle " : "Angolo di deviazione",
"Focal length " : "Lunghezza focale",
"Object distance " : "Distanza dell'oggetto",
"Image distance " : "Distanza dell'Immagine",
"Image (or object) distance" : "Distanza dell'immagine (o oggetto) ",
"Magnification factor " : "Fattore di ingrandimento",
"Speed " : "Velocità",
"Proper length " : "Lunghezza propria",
"Observed length " : "Lunghezza osservata",
"Rest mass " : "Massa a riposo",
"Relativistic mass " : "Massa relativistica",
"Proper time interval " : "Intervallo di tempo proprio",
"Observed time interval " : "Intervallo di tempo osservato",
"Calculate" : "Calcolare",
"Or input" : "Or input",
"Calculation Tools" : "Strumenti di calcolo",
	
};