var language={

"1. DYNAMICS" : "1. Dinámica ",
"STRAIGHT LINE MOTION" : "Movimiento en Línea Recta ",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: distancia (m), t: tiempo (s, segundo), v: velocidad (m/s), v_a: velocidad media ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Aceleración Constante de un Movimiento en Línea Recta",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: aceleración, v_o: velocidad inicial, v: velocidad en el instante t ",
"DISTANCE FUNCTION" : "Función de Distancia ",
"x_o: initial distance from origin, x: distance at time t" : "x_o: distancia inicial de origen, x: distancia en el tiempo t ",
"UNIFORM CIRCULAR MOTION" : "Movimiento Circular Uniforme ",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: ángulo (rad), l: longitud del arco, R: radio del círculo, ω: velocidad angular (rad/s), t: tiempo en que el objeto se mueve a una longitud de l ",
"CENTRIPETAL FORCE" : "Fuerza Centrípeta ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: frecuencia (Hz), T: el período para una rotación (s), a: aceleración centrípeta, F: fuerza centrípeta (N, Newton) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Aceleración constante de un movimiento circular ",
"γ: angular acceleration" : "γ: aceleración angular ",
"ACCELERATION" : "Aceleración ",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: aceleración tangencial, a_n: aceleración normal ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: acelerar, P2: movimiento circular uniforme, P3: desaceleración ",
"FREE FALLING FROM HEIGHT h" : "Caída libre desde una altura h ",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: aceleración de la gravedad, v: velocidad en t, s: distancia después de t, v_h: velocidad al tocar el suelo, t_h: la hora de la toma de contacto ",
"VERTICAL PROJECTILE MOTION" : "Movimiento Vertical de proyectiles",
"h_max: maximum height, v_o: initial velocity" : "h_max: altura máxima, v_o: velocidad inicial ",
"Motion equation and velocity equation" : "Ecuación de movimiento y ecuación de velocidad ",
"ANGLED PROJECTILE MOTION" : "Movimiento de proyectiles en ángulo ",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: velocidad; x, y: ecuación de movimiento de t; H: altura máxima; L: distancia máxima ",
"HORIZONTAL PROJECTILE MOTION" : "Movimiento Horizontal de proyectiles ",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: momento en el momento del aterrizaje, v_h: velocidad al momento de contacto",
"SLIDING MOTION ON AN INCLINED PLANE" : "Movimiento de Deslizamiento sobre un Plano Inclinado ",
"μ: coefficient of friction" : "μ: coeficiente de fricción ",
"Fiction coefficient of some materials" : "Coeficiente de ficción de algunos materiales ",
"2. FORCES" : "2. Fuerzas ",
"ATTRACTIVE FORCE" : "Fuerza de Atracción ",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: masa de 2 objetos; r: distancia entre 2 objetos; G: constante gravitacional ",
"GRAVITATIONAL FORCE" : "Fuerza gravitacional ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: masa de la Tierra, m: masa de objeto, R: radio de la Tierra, h: altura del objeto ",
"GRAVITATIONAL ACCELERATION" : "Aceleración de la gravedad ",
"At a height h above the nominal surface of the earth" : "A una altura h por encima de la superficie nominal de la tierra ",
"Near the sea level" : "Cerca del nivel del mar ",
"FORCE OF GRAVITY" : "Fuerza de gravedad ",
"Force of gravity on earth, a special case of Gravitational force" : "Fuerza de gravedad en la tierra, un caso especial de la fuerza gravitacional ",
"NEWTON'S FIRST LAW" : "Primera Ley de Newton ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: fuerzas que actúan sobre el objeto, v: velocidad del objeto, a: aceleración del objeto ",
"NEWTON'S SECOND LAW" : "La segunda ley de Newton ",
"m: object's mass (kg)" : "m: masa del objeto (kg) ",
"NEWTON'S THIRD LAW" : "La tercera ley de Newton ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Elasticidad lineal - la ley de Hooke: restauración de una fuerza de reacción",
"k: spring constant (N/m), x: displacement (m)" : "k: constante del resorte (N/m), x: desplazamiento (m) ",
"A mass suspended by a spring" : "Una masa suspendida por un resorte ",
"FORCE OF FRICTION" : "Fuerza de fricción ",
"μ: coefficient of friction, N: normal force" : "μ: coeficiente de fricción, N: fuerza normal ",
"3. STATICS" : "3. Estática ",
"MOMENT OF A FORCE" : "Momento de una fuerza ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: la fuerza aplicada (N), d: brazo de momento (la distancia perpendicular desde el eje a la línea de acción de la fuerza) ",
"MOMENT APPLICATION" : "APLICACIÓN DEL MOMENTO ",
"MOMENT OF INERTIA" : "Momento de inercia ",
"Rod of length l" : "Varilla de longitud l ",
"Thin circular hoop/ Thin cylindrical shell" : "Aro delgado circular/ Cubierta cilíndrica delgado ",
"Solid disk/ Solid cylinder" : "Disco Sólido/ Cilindro Sólido ",
"Solid ball" : "Bola Sólida ",
"Hollow sphere" : "Esfera Hueca ",
"ANGULAR MOMENTUM" : "Momento Angular ",
"I: moment of inertia, ω: angular velocity" : "I: momento de inercia, ω: velocidad angular ",
"PLANE MOTION OF A RIGID BODY" : "MOVIMIENTO PLANO DE UN CUERPO RIGIDO",
"γ: angular acceleration, M: moment of a force" : "γ: aceleración angular, M: momento de una fuerza ",

"4. CONSERVATION LAWS" : "4. Leyes de conservación ",
"MOMENTUM OF FORCE" : "Momentum de la fuerza ",
"LAW OF CONSERVATION OF MOMENTUM" : "Ley de conservación del momento ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: velocidades iniciales de los objetos 1 y 2; v₁', v₂': velocidades finales de objeto 1 y 2 ",
"PLASTIC COLLISION" : "Colisión Plástica ",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': velocidad del sistema de dos cuerpos (m₁ + m₂) después del impacto ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Colisión elástica unidimensional ",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': velocidades de m₁ y m₂ después del impacto ",
"5. WORK AND ENERGY" : "5. Trabajo y energía ",
"WORK" : "Trabajo ",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: trabajo realizado por una fuerza (J), F: fuerza al mover un objeto de una distancia s, α: ángulo entre F y la dirección del movimiento ",
"EXAMPLES" : "Ejemplos ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: trabajo por gravedad, h: cambio de altura; W_ms: trabajo de la fuerza de fricción; W: trabajo por resorte ",
"POWER" : "Potencia ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: Potencia (vatio, W), t: tiempo de conducción de los trabajos W (s) ",
"KINETIC ENERGY" : "La energía cinética ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Energía cinética de un cuerpo en rotación masiva ",
"WORK-ENERGY PRINCIPLE" : "Principio del trabajo-energía ",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: velocidades del objeto antes y después del cambio ",
"POTENTIAL ENERGY" : "Energía potencial ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: energía potencial gravitatoria (J), m: masa de objeto (kg) ",
"CONSERVATION OF MECHANICAL ENERGY" : "Conservación de la energía mecánica ",
"CONSERVATION OF ENERGY" : "Conservación de la Energía ",
"6. MECHANICS OF FLUIDS" : "6. Mecánica de fluidos ",
"DENSITY" : "Densidad ",
"m: mass of a volume V" : "m: masa de un volumen V ",
"PRESSURE" : "Presión ",
"F: force applied on area of A" : "F: fuerza aplicada al área de A ",
"PRESSURE OF LIQUIDS" : "Presión de líquidos ",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: gravedad específica (N/m³), p_o: presión de aire sobre superficie libre (N/m²), p: presión creada por el peso del líquido encima, p_B: presión total a la profundidad h ",
"PASCAL’S PRINCIPLE" : "Principio de Pascal ",
"p_s: pressure on the surface" : "p_s: presión sobre la superficie ",
"APPLICATION" : "Aplicación ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: área de cilindros pequeños y grandes; F₁, F₂: fuerzas aplicadas y al alza ",
"ARCHIMEDES’ PRINCIPLE" : "Principio de Arquímedes ",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: peso específico del líquido (N/m³), V: volumen del objeto, F_b: fuerza de flotación ",
"FLOW RATE" : "Caudal ",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: área transversal (m²), v: velocidad del flujo (m/s), Q: caudal (m³/s) ",

"1. ELECTROSTATICS" : "1. Electrostática ",
"COULOMB’S LAW" : "Ley de Coulomb ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: tamaño de cargas (C), ε: permitividad relativa (en vacío ε = 1), r: distancia entre las cargas (m) ",
"ELECTRIC FIELDS" : "Campos Eléctricos ",
"E: electric field strength (N/C)" : "E: intensidad de campo eléctrico (N/C) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "El principio de superposición para campos eléctricos ",
"In case of 2 electric fields" : "En el caso de 2 campos eléctricos  ",
"WORK OF ELECTRIC FORCE" : "Trabajo de fuerza eléctrica ",
"ELECTRIC POTENTIAL DIFFERENCE" : "Diferencia de potencial eléctrico ",
"RELATION BETWEEN E AND U" : "Relación entre E y U ",
"CAPACITANCE" : "Capacitancia ",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: capacitancia (F), Q: carga eléctrica total (C), U: potencial eléctrico (V) ",
"CAPACITOR" : "Capacitador o Condensador",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: área de cada placa de electrodos (m²), d: distancia entre los electrodos (m), ε: permitividad relativa (F/m) ",
"CAPACITANCES IN SERIES" : "Capacitancias en serie ",
"CAPACITANCES IN PARALLEL" : "Capacitancias en paralelo ",
"ELECTRIC FIELD ENERGY" : "Energía del campo eléctrico ",
"ENERGY OF CAPACITOR" : "Energía del condensador o capacitador",
"V=A.d: volume between two electrode plates" : "V = A.d: volumen entre dos placas de eléctrodos ",
"2. DIRECT CURRENT" : "2. Corriente Directa ",
"ELECTRIC CURRENT" : "Corriente eléctrica ",
"I: current (A), q: charge (C), t: time" : "I: Corriente (A), q: carga (C), t: tiempo ",
"OHM’S LAW" : "Ley de Ohm ",
"U: electric potential difference between the ends of the resistor R" : "U: diferencia de potencial eléctrico entre los extremos de la resistencia R ",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Trabajo creado por una corriente (Ley de Joule) ",
"ELECTRICAL POWER" : "La energía eléctrica ",
"RESISTANCE" : "Resistencia ",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: resistividad del material (Ωm), l: longitud (m), A: área de sección transversal (m²) ",
"SERIES CIRCUITS" : "Circuitos en serie ",
"PARALLEL CIRCUITS" : "Circuitos en paralelo ",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Trabajo o energía térmica producida por una resistencia ",
"POWER CONSUMPTION OF A RESISTOR" : "Consumo de energía de una resistencia ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Fuerza electromotriz de un generador eléctrico ",
"W: work of force (J), q: charge (C)" : "W: el trabajo de la fuerza (J), q: carga (C) ",
"GENERATORS IN SERIES" : "Generadores en serie ",
"r: internal resistance of the generator" : "r: resistencia interna del generador ",
"GENERATORS IN PARALLEL" : "Generadores en paralelo ",
"GENERATORS IN SERIES-PARALLEL" : "Generadores en serie-paralelo ",
"WORK AND POWER OF GENERATOR" : "Trabajo y potencia de generador ",
"H: Efficiency of generator" : "H: Eficiencia del generador ",
"3. MAGNETISM" : "3. Magnetismo ",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Flujo magnético a través de la superficie abierta S ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: magnitud del campo magnético (T, tesla), α: ángulo entre B y la línea perpendicular a la superficie S ",
"MAGNETIC FORCES ON MOVING CHARGES" : "Fuerzas magnéticas sobre cargas en movimiento ",
"v: velocity of the charge (m/s)" : "v: velocidad de la carga (m/s) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "Fuerza sobre un cable portador de corriente ",
"I: current (A), l: length of the wire (m)" : "I: Corriente (A), l: longitud del cable (m) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Fuerza entre 2 cables conductores de corriente paralelos ",
"r: distance between two wires (m)" : "r: distancia entre dos cables (m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Campo magnético de un cable largo portador de corriente",
"r: perpendicular distance from the center of the wire (m)" : "r: distancia perpendicular desde el centro del cable (m) ",
"MAGNETIC FIELD OF A LOOP" : "El campo magnético de un Loop (Bucle)",
"n: number of turns per unit length of solenoid (turns/m)" : "n: número de vueltas por unidad de longitud de solenoide (vueltas/m) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Fuerza electromotriz inducida - Ley de Faraday ",
"N: numbers of turns per loop (turns/m)" : "N: número de vueltas por loop o bucle (vueltas/m) ",
"INDUCTANCE" : "Inductancia ",
"ELECTRIC ENERGY" : "Energía Eléctrica ",
"MAGNETIC ENERGY" : "La energía magnética ",
"ELECTRIC-MAGNETIC ENERGY" : "Energía eléctromagnética ",
"4. ALTERNATING CURRENT" : "4. Corriente Alterna ",
"BASIC PARAMETERS" : "Parámetros Básicos ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: corriente instantánea (A), I_o: máxima corriente instantánea (A), T: periodo de la ola, f: frecuencia, λ: longitud de onda, c: velocidad de la luz ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Corriente Efectiva y Voltaje ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Ley de Ohm de corriente CA que contiene sólo la resistencia R ",
"CONTAINING ONLY INDUCTOR L" : "Conteniendo sólo inductor L ",
"Z_L: inductive reactance" : "Z_L: reactancia inductiva ",
"CONTAINING ONLY CAPACITOR C" : "Conteniendo solo el condensador C ",
"Z_C: capacitive reactance" : "Z_C: reactancia capacitiva ",
"CONTAINING R, L AND C IN A SERIES" : "Que contiene R, L y C en una serie ",
"Z: impedance" : "Z: impedancia ",
"PHASE ANGLE" : "El ángulo de fase ",
"POWER FACTOR" : "Factor de potencia ",
"REAL POWER" : "El poder real ",
"ELECTRICAL RESONANCE" : "Resonancia eléctrica ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Cambio de tensión con transformadores ",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: número de vueltas en la bobina primaria y la bobina secundaria; U₁, U₂: tensión o voltaje primario y secundario; I₁, I₂: corrientes primarias y secundarias ",

"1. GAS LAWS" : "1. Leyes de Gases ",
"KELVIN TEMPERATURE" : "Temperatura Kelvin ",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: temperatura en escala Kelvin, t: temperatura en escala Celsius ",
"EQUATION OF STATE" : "Ecuación de Estado ",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: presión (P, Pascal), V: volumen (m³), n: número de moles del gas (mol), R: constante universal de gas, T: temperatura Kelvin del gas (K), k: constante de Boltzmann, N: número de moléculas en el gas ",
"IDEAL GAS LAW" : "Ley de los gases ideales ",
"BOYLE’S LAW FOR PRESSURE" : "Ley de Boyle para la presión ",
"If the temperature of the gas is constant" : "Si la temperatura del gas es constante ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "La ley de Gay-Lussac de Presión-Temperatura ",
"If the volume on a gas is constant" : "Si el volumen de un gas es constante ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: presión de gas a temperatura t, p_o: presión a 0 grados Celsius, γ: Factor cuando el volumen es constante ",
"Example when t=0 Kelvin" : "Ejemplo cuando t = 0 Kelvin ",
"CHARLES'S LAW OF VOLUMES" : "La ley de Charles de volúmenes ",
"If the pressure on a gas is constant" : " ",
"2. CHANGES OF STATE AND SHAPE" : "2. Cambios de Estado y de forma ",
"HEAT" : "Calor ",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: Calor emitido, Q_r: Calor recibido, m: Masa total del objeto (kg), c: Calor específico (J/kg.K), ∆t: Cambio en la temperatura (K) ",
"The specific heats of some materials" : "Calores específicos de algunos materiales ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Fusión (congelación o solidificación) ",
"Heat of fusion of some materials" : "Calor de fusión de algunos materiales ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: cantidad de calor (J), λ: calor de fusión (J/kg), m: masa (kg) ",
"VAPORIZATION" : "La vaporización ",
"L: heat of vaporization" : "L: calor de vaporización ",
"Heat of vaporization of some materials" : "Calor de vaporización de algunos materiales ",
"LINEAR EXPANSION" : "Expansión lineal ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: longitud original (m), α: coeficiente de expansión lineal (K⁻¹), ∆t: cambio en la temperatura ",
"VOLUME EXPANSION" : "Expansión de volumen ",
"AREA EXPANSION" : "Expansión del área ",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Cambio de densidad (densidad de masa volumétrica) ",
"D_o: original density (kg/m³)" : "D_o: densidad original (kg/m³) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Cambio de diámetro de la sección transversal de un sólido ",
"3. THERMODYNAMICS" : "3. Termodinámica ",
"THE FIRST LAW OF THERMODYNAMICS" : "La Primera Ley de la Termodinámica ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "∆U: el cambio en la energía interna, W: trabajo realizado por el sistema, Q: calor añadido dentro o fuera del sistema ",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Aplicación de la primera ley de leyes de los gases ideales ",
"- Volume is constant" : "- El volumen es constante",
"- Pressure is constant, W': work created by gas" : "- La presión es constante, W': trabajo generado por un gas",
"- Temperature is constant" : "- La temperatura es constante",
"THE SECOND LAW OF THERMODYNAMICS" : "La Segunda Ley de la Termodinámica ",
"- The efficiency of a cyclic heat engine" : "- La eficiencia de un motor térmico cíclico",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': trabajo realizado por ciclo (J), Q₁: calor absorbido por el ciclo de la temperatura más alta (J), Q₂': calor rechazado por ciclo a la temperatura más baja (J) ",
"- Maximum thermal efficiency" : "- Eficiencia térmica máxima",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: temperaturas superiores e inferiores ",

"1. SIMPLE HARMONIC MOTION" : "1. Movimiento Armónico Simple ",
"SPRING" : "Resorte",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: constante del resorte (N/m), s: desplazamiento (m), ω: velocidad angular (rad/s), T: periodo, m: masa del objeto, A: amplitud ",
"SPRINGS IN SERIES" : "Resortes en serie ",
"k: spring constant of the system, T: period of the system" : "k: constante de resorte del sistema, T: período del sistema ",
"SPRINGS IN PARALLEL" : "Resortes en paralelo ",
"SIMPLE PENDULUM" : "Péndulo simple ",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: velocidad angular (rad/s), T: periodo, α_o: ángulo en amplitud, A: amplitud, l: longitud del péndulo ",
"MOTION EQUATIONS" : "Ecuaciones de movimiento ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: desplazamiento, α: ángulo, v: velocidad, T: fuerza sobre la varilla ",
"ENERGY" : "Energía ",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: energía potencial, E_k: energía cinética, E: energía mecánica ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Cambio del período que siguió al cambio de la temperatura ",
"α: coefficient of linear expansion of the rod" : "α: coeficiente de expansión lineal de la varilla ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Cambio del período que siguió al cambio de la altura ",
"h: height of pendulum, R: Earth's radius" : "h: altura del péndulo, R: radio de la Tierra ",
"PENDULUM" : "Péndulo",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: momento de inercia, ω: velocidad angular, m: masa de la sacudida, d: OG, T: período ",
"2. PERIODIC MOTION" : "2. Movimiento periódico ",
"WAVELENGTH" : "Longitud de onda ",
"FUNCTION OF WAVE AT SOME POINTS" : "Función de onda en algunos puntos ",
"WAVE INTERFERENCE" : "interferencia de onda ",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 fuentes de onda que tienen la misma fase; M: un punto al azar ",
"3. SOUND WAVES" : "3. Ondas de sonido ",
"SOUND SPEED" : "Velocidad del sonido ",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): velocidad del sonido en el medio ambiente con temperatura t (Celsius) ",
"SOUND INTENSITY " : "Intensidad del sonido ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: energía sonora (J), P: potencia sonora (W), A:  área de la superficie de una esfera (m²), t: tiempo (s) ",
"SOUND INTENSITY LEVEL" : "Nivel de intensidad de sonido ",
"I_o: the standard reference sound intensity" : "I_o: Intensidad de sonido estándar de referencia  ",
"THE DOPPLER EFFECT" : "El efecto Doppler ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: la velocidad relativa del observador; v_S: la velocidad relativa de la fuente; v: la velocidad del sonido en este medio; f_S, f_O: la frecuencia del sonido de la fuente y el observador ",
"SOUND SPEED IN GASES" : "Velocidad del sonido en gases ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: velocidad del sonido (m/s), R: constante universal de los gases, T: temperatura absoluta (K), M: masa molecular de gas (kg/mol), γ: constante adiabática ",
"Example in air" : "Ejemplo en el aire ",

"1. GEOMETRIC OPTICS" : "1. Óptica Geométrica ",
"LAWS OF REFLECTION" : "Leyes de la reflexión ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: rayo incidente, IR: rayo reflejado, i: ángulo de incidencia, i': ángulo de reflexión ",
"REFRACTIVE INDEX" : "Índice de refracción ",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: Índice de refracción del medio, v: velocidad de la luz en un medio, c: velocidad de la luz en el vacío (m/s) ",
"LAW OF REFRACTION" : "Ley de Refracción ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: Índice de refracción del medio 1, n₂: Índice de refracción del medio 2, i: Ángulo de incidencia, r: Ángulo de refracción, n₂₁: Índice absoluto de refracción ",
"If medium 1 is vacuum" : "Si el medio 1 es vacío",
"TOTAL REFLECTION PHENOMENON" : "Fenómeno de reflexión total ",
"There is no refracted ray if" : "No hay rayo refractado si ",
"PRISM" : "Prisma ",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: ángulo en el vértice, D: ángulo de desviación, i₁: ángulo de incidencia, i₂: ángulo del rayo emergente  o rayo de dirección desviada",
"- Condition to have refractive ray" : "- Condición para tener rayos de refracción",
"- When angle of incidence is minimum" : "- Cuando el ángulo de incidencia es mínimo",
"THIN LENS" : "Lente Delgado",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: distancia focal (convergiendo en lente f&gt;0; divergentes en lente f&lt;0), d: distancia del objeto desde el centro del objetivo, d': distancia de la imagen desde el centro del objetivo ",
"MAGNIFICATION FACTOR" : "Factor de magnificación ",
"h_I: image height, h_O: object height" : "h_I: altura de la imagen, h_O: altura del objeto ",
"POWER OF THE LENS" : "Potencia de la lente ",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: índice de refracción del material del lente, R₁: radio de curvatura de la superficie del lente más cercano a la fuente de luz, R₂: radio de curvatura de la superficie más alejada del lente de la fuente de luz ",
"2. QUANTUM OF LIGHT" : "2. Quantum de la luz ",
"PHOTON ENERGY" : "Energía fotónica ",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: constante de Planck, f: frecuencia (Hz), λ: longitud de onda (m), c: velocidad de la luz ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Condición para el Efecto Fotoeléctrico ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: longitud de onda de la luz resplandeciente, λ_o: límite fotoeléctrico, W: trabajo generado (J) ",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Ecuación de Einstein sobre el efecto fotoeléctrico ",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: masa de fotoelectrones (kg), v_o: velocidad máxima de fotoelectrones (m/s) ",

"1. THEORY OF RELATIVITY" : "1. Teoría de la relatividad ",
"MASS–ENERGY EQUIVALENCE" : "Equivalencia masa-energía ",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: masa (kg), E: energía del objeto (J), c: velocidad de la luz (m/s)",
"LENGTH CONTRACTION" : "Longitud de Contracción",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: Longitud real del objeto, l: longitud observada por un observador que se mueve a una velocidad v ",
"RELATIVISTIC MASS" : "Masa relativista ",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: masa en reposo, m: masa relativista del objeto cuando se mueve con velocidad v ",
"TIME DILATION" : "La dilatación del tiempo ",
"2. ATOMIC NUCLEUS" : "2. Núcleo atómico ",
"NUCLEAR MAKEUP" : "Composición Nuclear ",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: Número de protones, N: Número de neutrones, A: Número de masa ",
"NUCLEAR REACTION" : "Reacción Nuclear ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: reacción nuclear libera energía",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: reacción absorbe La energía nuclear",
"RADIOACTIVE DECAY" : "Desintegración radiactiva ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: cantidad inicial de sustancia activa, N: cantidad que aún se mantiene y aún no ha decaído después de un tiempo t, ∆N: cantidad de sustancia en descomposición, m_o: masa inicial, m: masa que permanece, λ: constante de desintegración, t: tiempo, T: período de semidesintegración ",
"Half life of some elements" : "Periodos de semidesintegración de algunos radionucleidos",
"AMOUNT OF RADIOACTIVITY" : "Cantidad de radiactividad ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: cantidad inicial de radiactividad, H: cantidad de radiactividad en el tiempo t ",
"1. CONSTANTS" : "1. Constantes ",
"ALPHA PARTICLE MASS" : "masa de partículas alfa ",
"ATOMIC MASS CONSTANT" : "constante de masa atómica ",
"ATOMIC UNIT OF ENERGY" : "unidad atómica de energía ",
"ATOMIC UNIT OF FORCE" : "unidad atómica de la fuerza ",
"ATOMIC UNIT OF LENGTH" : "unidad atómica de longitud ",
"ATOMIC UNIT OF MASS" : "unidad atómica de masa ",
"AVOGADRO'S CONSTANT" : "Constante de Avogadro ",
"BOHR RADIUS" : "Radio de Bohr ",
"BOLTZMANN CONSTANT" : "Constante de Boltzmann ",
"CLASSICAL ELECTRON RADIUS" : "Radio clásico del electrón ",
"ELEMENTARY CHARGE" : "Carga elemental ",
"EARTH MASS" : "Masa de la tierra ",
"EARTH EQUATORIAL RADIUS" : "Radio ecuatorial de la tierra ",
"EARTH MEAN ORBITAL VELOCITY" : "Velocidad orbital media de la tierra ",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Velocidad angular de rotación de la tierra ",
"FARADAY’S CONSTANT" : "Constante de Faraday ",
"GAS CONSTANT" : "Constante de los gases ",
"MOLAR MASS CONSTANT" : "Constante de masa molar ",
"MOLAR VOLUME OF IDEAL GAS" : "Volumen molar del gas ideal ",
"NEUTRON MASS" : "Masa del neutrón ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Constante de Newton de gravitación ",
"PLANCK’S CONSTANT" : "Constante de Planck ",
"PLANCK MASS" : "Masa de Planck ",
"PROTON MASS" : "Masa del protón ",
"PROTON-ELECTRON MASS RATIO" : "Relación de masa protón-electrón ",
"SPEED OF LIGHT IN VACUUM" : "Velocidad de la luz en el vacío ",
"STANDARD ACCELERATION OF GRAVITY" : "Aceleración normal de la gravedad ",
"STANDARD ATMOSPHERE" : "Atmósfera estándar ",
"STANDARD REFERENCE SOUND INTENSITY" : "Referencia Estandar de Intensidad de sonido  ",
"STEFAN-BOLTZMANN CONSTANT" : "Constante de Stefan-Boltzmann",
"2. GREEK ALPHABET" : "2. Alfabeto griego ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: letra griega, C2: Nombre, C3: Equivalente, C4: Sonido cuando se pronuncia",

"Mechanics" : "Mecánica ",
"Thermal physics" : "Física Térmica ",
"Optics" : "Óptica ",
"Theory of relativity" : "Teoría de la relatividad ",

"FREE FALLING" : "Caída libre ",
"VERTICAL PROJECTILE" : "Proyectil Vertical ",
"ANGLED PROJECTILE" : "Proyectil en ángulo ",
"HORIZONTAL PROJECTILE" : "Proyectil Horizontal ",
"SLIDING MOTION" : "Movimiento de deslizamiento ",
"ATTRACTIVE FORCE" : "Fuerza de Atracción ",
"Hydraulic press" : "Prensa hidráulica ",
"PRESSURE" : "Presión ",
"LINEAR EXPANSION" : "Expansión lineal ",
"VOLUME EXPANSION" : "Expansión de volumen ",
"SOUND SPEED" : "Velocidad del sonido ",
"REFRACTION" : "Refracción ",
"PRISM" : "Prisma ",
"LENS" : "Lente ",
"Length contraction" : "Longitud de Contracción",
"Time dilation" : "La dilatación del tiempo ",
"RELATIVISTIC MASS" : "Masa relativista ",

"Height " : "Altura ",
"Time to touchdown " : "Hora de toma de contacto ",
"Touchdown velocity " : "Velocidad de contacto",
"Initial velocity " : "Velocidad inicial ",
"Maximum height " : "Altura máxima ",
"Initial velocity " : "Velocidad inicial ",
"Angle " : "Ángulo ",
"Maximum height " : "Altura máxima ",
"Maximum distance " : "Distancia máxima ",
"Height " : "Altura ",
"Initial velocity " : "Velocidad inicial ",
"Time to touchdown " : "Hora de toma de contacto ",
"Touchdown velocity " : "Velocidad de contacto",
"Angle of titled plane " : "Ángulo de plano inclinado",
"Coefficient of friction " : "Coeficiente de fricción ",
"Acceleration " : "Aceleración ",
"Mass " : "Masa",
"Mass " : "Masa",
"Distance " : "Distancia ",
"Attractive force " : "Fuerza de atracción ",
"Area " : "Area ",
"Area " : "Area ",
"Force " : "Fuerza ",
"Force" : "Fuerza ",
"Force F₂ (or F₁)" : "Fuerza F₂ (o F₁) ",
"Temperature " : "Temperatura ",
"Pressure at 0°C " : "Presión a 0°C ",
"Pressure " : "Presión ",
"Original length " : "Longitud original ",
"Temperature change " : "Cambio de temperatura ",
"Coefficient of linear expansion " : "Coeficiente de dilatación lineal ",
"Change of length " : "Cambio de la longitud ",
"Original volume " : "Volumen original ",
"Temperature change " : "Cambio de temperatura ",
"Coefficient of linear expansion " : "Coeficiente de dilatación lineal ",
"Change of volume " : "Cambio de volumen ",
"Temperature " : "Temperatura ",
"Sound speed " : "Velocidad del sonido ",
"Refractive index " : "Índice de refracción ",
"Refractive index " : "Índice de refracción ",
"Angle of incidence " : "Ángulo de incidencia ",
"Angle of refraction " : "Ángulo de refracción ",
"Angle (r or i) " : "Ángulo (r o i) ",
"Apex angle " : "Ángulo de vértice ",
"Angle of incident " : "Ángulo de incidencia ",
"Refractive index " : "Índice de refracción ",
"Angle of emergent ray " : "Ángulo de rayo emergente ",
"Deviation angle " : "Ángulo de desviación ",
"Focal length " : "Longitud focal ",
"Object distance " : "Distancia al objeto ",
"Image distance " : "Distancia a la imagen ",
"Image (or object) distance" : "Distancia a la imagen (u objeto)",
"Magnification factor " : "Factor de magnificación ",
"Speed " : "Velocidad ",
"Proper length " : "Longitud adecuada ",
"Observed length " : "Longitud observada ",
"Rest mass " : "Masa en reposo ",
"Relativistic mass " : "Masa relativista ",
"Proper time interval " : "Intervalo de tiempo propio ",
"Observed time interval " : "Intervalo de tiempo observado ",
"Calculate" : "Calcular ",
"Or input" : "O ingresar data",
"Calculation Tools" : "Herramientas de cálculo ",

	
};