var language={


"1. DYNAMICS" : "1. Dinamika ",
"STRAIGHT LINE MOTION" : "Gerak Garis Lurus ",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: jarak (m), t: waktu (s, detik), v: kecepatan (m/s), v_a: kecepatan rata-rata ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Percepatan Konstan  Gerak  Garis Lurus",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: percepatan, v_o: kecepatan awal, v: kecepatan pada saat t ",
"DISTANCE FUNCTION" : "Fungsi jarak ",
"x_o: initial distance from origin, x: distance at time t" : "x_o: jarak awal dari asal, x: jarak pada waktu t ",
"UNIFORM CIRCULAR MOTION" : "Gerak Melingkar Seragam",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: sudut (rad), l: panjang busur, R: jari-jari lingkaran, ω: kecepatan sudut (rad/s), t: waktu objek bergerak panjang l ",
"CENTRIPETAL FORCE" : "Gaya sentripetal ",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: frekuensi (Hz), T: periode untuk satu putaran (s), a: percepatan sentripetal, F: gaya sentripetal (N, Newton) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "Percepatan konstan gerak melingkar ",
"γ: angular acceleration" : "γ: percepatan sudut ",
"ACCELERATION" : "Percepatan ",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: percepatan tangensial, a_n: percepatan yang normal ",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: mempercepat, P2: gerakan melingkar seragam , P3: melambat ",
"FREE FALLING FROM HEIGHT h" : "Jatuh bebas dari ketinggian h ",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: percepatan gravitasi, v: kecepatan pada t, s: jarak setelah t, v_h: kecepatan saat menyentuh tanah, t_h: waktu untuk sampai",
"VERTICAL PROJECTILE MOTION" : "Gerak peluru Vertikal ",
"h_max: maximum height, v_o: initial velocity" : "h_max: ketinggian maksimum, v_o: kecepatan awal ",
"Motion equation and velocity equation" : "Persamaan gerak dan persamaan kecepatan ",
"ANGLED PROJECTILE MOTION" : "Gerak lekukan peluru",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: kecepatan; x, y: persamaan gerak dengan t; H: tinggi maksimal; L: jarak maksimum ",
"HORIZONTAL PROJECTILE MOTION" : "Gerak peluru Horizontal ",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: waktu saat mendarat, v_h: kecepatan ketika mendarat",
"SLIDING MOTION ON AN INCLINED PLANE" : "Pergeseran Gerak pada bidang miring ",
"μ: coefficient of friction" : "μ: koefisien gesekan ",
"Fiction coefficient of some materials" : "Koefisien Fiksi dari beberapa bahan ",
"2. FORCES" : "2. Gaya",
"ATTRACTIVE FORCE" : "Gaya tarik",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: massa benda 2; r: jarak antara 2 obyek; G: konstanta gravitasi ",
"GRAVITATIONAL FORCE" : "Gaya gravitasi ",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: massa Bumi, m: massa benda, R: jari-jari Bumi, h: tinggi benda ",
"GRAVITATIONAL ACCELERATION" : "Percepatan gravitasi ",
"At a height h above the nominal surface of the earth" : "Pada ketinggian  h  di atas permukaan nominal bumi ",
"Near the sea level" : "Dekat permukaan laut ",
"FORCE OF GRAVITY" : "Gaya gravitasi ",
"Force of gravity on earth, a special case of Gravitational force" : "Gaya gravitasi di bumi, kasus khusus dari kekuatan gravitasi ",
"NEWTON'S FIRST LAW" : "Hukum pertama Newton ",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F: gaya yang bekerja pada objek, v: kecepatan objek, a: percepatan benda ",
"NEWTON'S SECOND LAW" : "Hukum kedua Newton ",
"m: object's mass (kg)" : "m: massa benda (kg) ",
"NEWTON'S THIRD LAW" : "Hukum ketiga Newton ",
"LINEAR ELASTICITY - HOOKE'S LAW" : "Elastisitas Linear - hukum Hooke ",
"k: spring constant (N/m), x: displacement (m)" : "k: konstanta pegas (N/m), x: perpindahan (m) ",
"A mass suspended by a spring" : "Massa ditangguhkan oleh pegas ",
"FORCE OF FRICTION" : "Gaya gesekan ",
"μ: coefficient of friction, N: normal force" : "μ: koefisienn gesekan, N: gaya normal ",
"3. STATICS" : "3. Statika ",
"MOMENT OF A FORCE" : "Momen gaya ",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: gaya yang diterapkan (N), d: saat lengan (jarak tegak lurus dari sumbu ke garis aksi gaya) ",
"MOMENT APPLICATION" : "APLIKASI MOMEN",
"MOMENT OF INERTIA" : "Momen inersia ",
"Rod of length l" : "Panjang batang l ",
"Thin circular hoop/ Thin cylindrical shell" : "Lingkaran tipis melingkar/Rangka silinder tipis ",
"Solid disk/ Solid cylinder" : "Cakram Padat /silinder Padat ",
"Solid ball" : "Bola Padat ",
"Hollow sphere" : "Bola berongga ",
"ANGULAR MOMENTUM" : "Momentum sudut ",
"I: moment of inertia, ω: angular velocity" : "I: momen inersia, ω: kecepatan sudut ",
"PLANE MOTION OF A RIGID BODY" : "BIDANG GERAK DARI BADAN KAKU ",
"γ: angular acceleration, M: moment of a force" : "γ: percepatan sudut, M: momen gaya ",

"4. CONSERVATION LAWS" : "4. Hukum Konservasi ",
"MOMENTUM OF FORCE" : "Momentum gaya",
"LAW OF CONSERVATION OF MOMENTUM" : "Hukum kekekalan dari momentum ",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: kecepatan awal benda 1 dan 2; v₁', v₂': kecepatan akhir benda 1 dan 2 ",
"PLASTIC COLLISION" : "Tumbukan Plastik ",
"v': velocity of the two body system (m₁+m₂) after impact" : "v': kecepatan sistem dua badan (m₁ + m₂) setelah dampak ",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "Tumbukan elastis satu dimensi ",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁', v₂': kecepatan dari m₁ dan m₂ setelah dampak ",
"5. WORK AND ENERGY" : "5. Kerja dan energi ",
"WORK" : "Kerja",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: kerja yang dilakukan oleh gaya (J), F: gaya memindahkan objek untuk sebuah s jarak, α: sudut antara F dan arah gerakan ",
"EXAMPLES" : "Contoh ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: bekerja dengan gravitasi, h: perubahan tinggi; W_ms: kerja gaya gesek ; W: kerja dengan pegas ",
"POWER" : "Daya ",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: daya (W), t: waktu melakukan pekerjaan A (s) ",
"KINETIC ENERGY" : "Energi kinetik ",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Energi kinetik dari tubuh berputar besar ",
"WORK-ENERGY PRINCIPLE" : "Prinsip kerja-energi ",
"v₁, v₂: speeds of object before and after the change" : "v₁, v₂: kecepatan benda sebelum dan sesudah perubahan ",
"POTENTIAL ENERGY" : "Energi Potensial ",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: energi potensial gravitasi (J), m: massa benda (kg) ",
"CONSERVATION OF MECHANICAL ENERGY" : "Konservasi energi mekanik ",
"CONSERVATION OF ENERGY" : "Konservasi Energi ",
"6. MECHANICS OF FLUIDS" : "6. Mekanika cairan ",
"DENSITY" : "Kepadatan ",
"m: mass of a volume V" : "m: massa volume V ",
"PRESSURE" : "Tekanan ",
"F: force applied on area of A" : "F: gaya yang diterapkan pada daerah A ",
"PRESSURE OF LIQUIDS" : "Tekanan Cairan ",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: berat jenis (N/m³), p_o: tekanan udara di permukaan bebas (N/m²), p: tekanan yang diciptakan oleh berat cairan di atas, p_B: tekanan total pada kedalaman h ",
"PASCAL’S PRINCIPLE" : "Prinsip Pascal ",
"p_s: pressure on the surface" : "p_s: tekanan pada permukaan ",
"APPLICATION" : "Aplikasi ",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: Area silinder kecil dan besar; F₁, F₂: Gaya diterapkan dan ke atas ",
"ARCHIMEDES’ PRINCIPLE" : "Prinsip Archimedes'",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: berat jenis cairan (N/m³), V: volume benda, F_b: gaya apung ",
"FLOW RATE" : "Laju aliran",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: luas penampang (m²), v: kecepatan aliran (m/s), Q: laju aliran (m³/s) ",

"1. ELECTROSTATICS" : "1. Elektrostatik ",
"COULOMB’S LAW" : "Hukum Coulomb ",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: ukuran muatan (C), ε: permitivitas relatif (dalam ruang hampa ε = 1), r: jarak antara muatan (m) ",
"ELECTRIC FIELDS" : "Medan listrik ",
"E: electric field strength (N/C)" : "E: kekuatan medan listrik (N/C) ",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Prinsip superposisi untuk medan listrik ",
"In case of 2 electric fields" : "Dalam kasus 2 medan listrik ",
"WORK OF ELECTRIC FORCE" : "Kerja kekuatan listrik ",
"ELECTRIC POTENTIAL DIFFERENCE" : "Perbedaan potensial listrik ",
"RELATION BETWEEN E AND U" : "Hubungan antara E dan U ",
"CAPACITANCE" : "Kapasitansi ",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: kapasitansi (F), Q: muatan listrik keseluruhan (C), U: potensial listrik (V) ",
"CAPACITOR" : "Kapasitor",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: luas setiap lempeng elektroda (m²), d: jarak antara elektroda (m), ε: permitivitas relatif (F/m) ",
"CAPACITANCES IN SERIES" : "Kapasitansi dalam rangkaian",
"CAPACITANCES IN PARALLEL" : "Kapasitansi secara paralel ",
"ELECTRIC FIELD ENERGY" : "Energi medan listrik ",
"ENERGY OF CAPACITOR" : "Energi kapasitor ",
"V=A.d: volume between two electrode plates" : "V = A.d: volume antara dua pelat elektroda ",
"2. DIRECT CURRENT" : "2. Arus langsung",
"ELECTRIC CURRENT" : "Arus Listrik ",
"I: current (A), q: charge (C), t: time" : "I: arus (A), q charge (C), t: waktu ",
"OHM’S LAW" : "Hukum Ohm ",
"U: electric potential difference between the ends of the resistor R" : "U: perbedaan potensial listrik antara ujung-ujung resistor R ",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Pekerjaan yang diciptakan oleh arus (Hukum Joule) ",
"ELECTRICAL POWER" : "Daya listrik ",
"RESISTANCE" : "Daya tahan",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: resistivitas material (Ωm), l: panjang (m), A: area penampang (m²) ",
"SERIES CIRCUITS" : "Rangkaian Sirkuit ",
"PARALLEL CIRCUITS" : "Sirkuit paralel ",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Pekerjaan atau energi panas yang dihasilkan oleh resistor ",
"POWER CONSUMPTION OF A RESISTOR" : "Konsumsi daya dari resistor ",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Gaya gerak listrik dari sebuah generator listrik ",
"W: work of force (J), q: charge (C)" : "W: kerja gaya (J), q: muatan (C) ",
"GENERATORS IN SERIES" : "Generator dalam rangkaian",
"r: internal resistance of the generator" : "r: resistansi internal dari generator ",
"GENERATORS IN PARALLEL" : "Generator secara paralel ",
"GENERATORS IN SERIES-PARALLEL" : "Generator di rangkaian paralel ",
"WORK AND POWER OF GENERATOR" : "Kerja dan daya generator ",
"H: Efficiency of generator" : "H: Efisiensi generator ",
"3. MAGNETISM" : "3. Magnetis",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Fluks magnetik melalui permukaan yang terbuka S ",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: besarnya medan magnet (T, tesla), α: sudut antara B dan garis tegak lurus ke permukaan S ",
"MAGNETIC FORCES ON MOVING CHARGES" : "Daya magnetik pada Perpindahan muatan",
"v: velocity of the charge (m/s)" : "v: kecepatan muatan (m/s) ",
"FORCE ON A CURRENT-CARRYING WIRE" : "Gaya pada kawat pembawa arus",
"I: current (A), l: length of the wire (m)" : "I: arus (A), l: panjang kawat (m) ",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Gaya antara 2 kabel pembawa arus paralel ",
"r: distance between two wires (m)" : "r: jarak antara dua kawat (m) ",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Medan magnet dari kawat panjang pembawa arus",
"r: perpendicular distance from the center of the wire (m)" : "r: jarak tegak lurus dari pusat kawat (m) ",
"MAGNETIC FIELD OF A LOOP" : "Medan Magnet dari putaran",
"n: number of turns per unit length of solenoid (turns/m)" : "n: jumlah putaran per satuan panjang solenoid (putaran/m) ",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Gaya gerak listrik terinduksi - Hukum Faraday ",
"N: numbers of turns per loop (turns/m)" : "N: jumlah belokan per putaran (putaran/m) ",
"INDUCTANCE" : "Induksi ",
"ELECTRIC ENERGY" : "Energi listrik ",
"MAGNETIC ENERGY" : "Energi magnetik ",
"ELECTRIC-MAGNETIC ENERGY" : "Energi listrik-magnet ",
"4. ALTERNATING CURRENT" : "4. Arus pengganti",
"BASIC PARAMETERS" : "Parameter dasar ",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: arus sesaat (A), I_o:  arus sesaat maksimum(A), T: periode gelombang, f: frekuensi, λ: panjang gelombang, c: kecepatan cahaya ",
"EFFECTIVE CURRENT AND VOLTAGE" : "Arus dan Tegangan Efektif ",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Hukum Ohm dari Arus AC Mengandung Hanya Resisten R ",
"CONTAINING ONLY INDUCTOR L" : "Hanya Mengandung induktor L ",
"Z_L: inductive reactance" : "Z_L: reaktansi induktif ",
"CONTAINING ONLY CAPACITOR C" : "Hanya Mengandung  kapasitor C ",
"Z_C: capacitive reactance" : "Z_C: reaktansi kapasitif ",
"CONTAINING R, L AND C IN A SERIES" : "Mengandung R, L dan C dalam seri ",
"Z: impedance" : "Z: impedansi ",
"PHASE ANGLE" : "Sudut fase ",
"POWER FACTOR" : "Faktor daya ",
"REAL POWER" : "Daya sebenarnya",
"ELECTRICAL RESONANCE" : "Resonansi listrik ",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Mengubah Tegangan dengan Pengubah bentuk",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: jumlah putaran dalam kumparan primer dan kumparan sekunder; U₁, U₂: tegangan primer dan sekunder ; I₁, I₂: arus primer dan sekunder ",

"1. GAS LAWS" : "1. Hukum Gas ",
"KELVIN TEMPERATURE" : "Suhu Kelvin ",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: suhu dalam skala Kelvin, t: suhu dalam skala Celcius ",
"EQUATION OF STATE" : "Persamaan keadaan",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: tekanan (P, Pascal), V: volume (m³), n: jumlah mol gas (mol), R: tetapan gas universal, T: suhu Kelvin dari gas (K), k: konstanta Boltzmann, N: jumlah molekul dalam gas ",
"IDEAL GAS LAW" : "Hukum gas ideal ",
"BOYLE’S LAW FOR PRESSURE" : "Hukum Boyle untuk Tekanan ",
"If the temperature of the gas is constant" : "Jika suhu gas konstan ",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "- Hukum Gay Lussac mengenai Tekanan-Temperatur",
"If the volume on a gas is constant" : "Jika volume gas adalah konstan ",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: tekanan gas pada suhu t, p_o: tekanan pada 0 Celcius, γ: faktor ketika volume konstan ",
"Example when t=0 Kelvin" : "Contoh ketika t = 0 Kelvin ",
"CHARLES'S LAW OF VOLUMES" : "Hukum  volume Charles",
"If the pressure on a gas is constant" : "Jika tekanan gas adalah konstan ",
"2. CHANGES OF STATE AND SHAPE" : "2. Perubahan Keadaan dan bentuk ",
"HEAT" : "Panas ",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: Panas yang dipancarkan, Q_r: panas yang diterima, m:  massa benda total (kg), c: panas spesifik (J/kg.K), At: perubahan suhu (K) ",
"The specific heats of some materials" : "Pemanasan spesifik dari beberapa bahan ",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Fusi (pembekuan atau pemadatan) ",
"Heat of fusion of some materials" : "Panas fusi dari beberapa bahan ",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: kuantitas panas (J), λ: panas fusi (J/kg), m: massa (kg) ",
"VAPORIZATION" : "Penguapan ",
"L: heat of vaporization" : "L: panas penguapan ",
"Heat of vaporization of some materials" : "Panas penguapan dari beberapa bahan ",
"LINEAR EXPANSION" : "Ekspansi linear ",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: panjang asli (m), α: koefisien ekspansi linear (K⁻¹), ∆t: perubahan suhu ",
"VOLUME EXPANSION" : "Ekspansi Volume ",
"AREA EXPANSION" : "Perluasan area",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Perubahan densitas (kerapatan massa volumetrik) ",
"D_o: original density (kg/m³)" : "D_o: kepadatan asli (kg/m³) ",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Perubahan diameter penampang padat",
"3. THERMODYNAMICS" : "3. Termodinamika ",
"THE FIRST LAW OF THERMODYNAMICS" : "Hukum Pertama Termodinamika ",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "ΔU: perubahan energi internal, W: kerja yang dilakukan oleh sistem, Q: panas yang ditambahkan ke dalam atau keluar dari sistem ",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "Penerapan hukum pertama hukum gas ideal ",
"- Volume is constant" : "- Volume konstan",
"- Pressure is constant, W': work created by gas" : "- Tekanan konstan W kerja yang diciptakan oleh gas",
"- Temperature is constant" : "- Suhu konstan",
"THE SECOND LAW OF THERMODYNAMICS" : "Hukum Kedua Termodinamika ",
"- The efficiency of a cyclic heat engine" : "- Efisiensi mesin panas tersiklus",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W': pekerjaan yang dilakukan per siklus (J), Q₁: panas yang diserap per siklus dari suhu tinggi (J), Q₂': panas yang dibuang per siklus dengan suhu rendah (J) ",
"- Maximum thermal efficiency" : "- Efisiensi termal maksimum",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: suhu yang lebih tinggi dan lebih rendah ",

"1. SIMPLE HARMONIC MOTION" : "1. Gerak  Harmonik Sederhana",
"SPRING" : "Lonjakan",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: konstanta lonjakan (N/m), s: perpindahan (m), ω: kecepatan sudut (rad/s), T: periode, m: massa benda, A: amplitudo ",
"SPRINGS IN SERIES" : "Lonjakan di rangkaian",
"k: spring constant of the system, T: period of the system" : "k: konstanta lonjakan dari sistem, T: periode sistem ",
"SPRINGS IN PARALLEL" : "Lonjakan secara paralel ",
"SIMPLE PENDULUM" : "Pendulum  Sederhana",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: kecepatan sudut (rad/s), T: periode, α_o: sudut di amplitudo, A: amplitudo, l: panjang pendulum ",
"MOTION EQUATIONS" : "Persamaan gerak ",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: perpindahan, α: sudut, v: kecepatan, T: kekuatan pada batang ",
"ENERGY" : "Energi ",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: energi potensial, E_k: energi kinetik, E: energi mekanik ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Perubahan periode setelah perubahan suhu ",
"α: coefficient of linear expansion of the rod" : "α:Koefisien ekspansi linear pada batang ",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Perubahan periode setelah perubahan ketinggian ",
"h: height of pendulum, R: Earth's radius" : "h: tinggi pendulum, R:radius Bumi ",
"PENDULUM" : "Pendulum ",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "I: momen inersia, ω: kecepatan sudut, m: massa bob, d: OG, T: periode ",
"2. PERIODIC MOTION" : "2. Gerak periodik ",
"WAVELENGTH" : "Panjang gelombang ",
"FUNCTION OF WAVE AT SOME POINTS" : "Fungsi gelombang di beberapa titik ",
"WAVE INTERFERENCE" : "Interferensi gelombang ",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 sumber gelombang memiliki fase yang sama; M: titik acak ",
"3. SOUND WAVES" : "3. Gelombang Suara",
"SOUND SPEED" : "Kecepatan suara ",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): kecepatan suara dalam lingkungan dengan suhu t (Celcius) ",
"SOUND INTENSITY " : "Intensitas bunyi ",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: energi suara (J), P: kekuatan suara (W), A: luas permukaan bola (m²), t: waktu (s) ",
"SOUND INTENSITY LEVEL" : "Tingkat intensitas suara ",
"I_o: the standard reference sound intensity" : "I_o: intensitas suara acuan standar ",
"THE DOPPLER EFFECT" : "Efek Doppler ",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: kecepatan relatif pengamat; v_S: kecepatan relatif dari sumber; v: kecepatan suara dalam medium ini; f_S, f_O: frekuensi suara dari sumber dan pengamat ",
"SOUND SPEED IN GASES" : "Kecepatan Suara di Gas ",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: kecepatan suara (m/s), R: konstanta gas universal, T: suhu mutlak (K), M: massa molekul gas (kg/mol), γ: konstanta adiabatik ",
"Example in air" : "Contoh di udara ",

"1. GEOMETRIC OPTICS" : "1. Optik Geometris ",
"LAWS OF REFLECTION" : "Hukum Refleksi ",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: insiden ray, IR: tercermin ray, i: sudut datang, i': sudut refleksi ",
"REFRACTIVE INDEX" : "Indeks bias ",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: indeks bias medium, v: kecepatan cahaya dalam medium, c: kecepatan cahaya dalam ruang hampa (m/s) ",
"LAW OF REFRACTION" : "Hukum Refraksi ",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: indeks bias medium 1, n₂: indeks bias medium 2, i: sudut datang, r: sudut bias, n₂₁: Indeks bias absolut ",
"If medium 1 is vacuum" : "Jika media 1 adalah vakum ",
"TOTAL REFLECTION PHENOMENON" : "Jumlah fenomena refleksi ",
"There is no refracted ray if" : "Tidak ada sinar dibiaskan jika ",
"PRISM" : "Prisma",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: sudut apex, D: sudut deviasi, i₁: sudut datang, i₂: sudut sinar muncul ",
"- Condition to have refractive ray" : "- Kondisi muatan untuk memiliki sinar bias",
"- When angle of incidence is minimum" : "- Bila sudut datang adalah minimum",
"THIN LENS" : "Lensa tipis",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: panjang fokus (konvergen len f&gt;0; divergen len f&lt;0), d: jarak benda dari pusat lensa, d' : jarak bayangan dari pusat lensa ",
"MAGNIFICATION FACTOR" : "Faktor pembesaran ",
"h_I: image height, h_O: object height" : "h_I: tinggi bayangan, h_O: tinggi benda ",
"POWER OF THE LENS" : "Kekuatan lensa ",

"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: indeks bias bahan lensa, R₁: jari-jari kelengkungan permukaan len paling dekat dengan sumber cahaya, R₂: jari-jari kelengkungan permukaan terjauh len dari sumber cahaya ",
"2. QUANTUM OF LIGHT" : "2. Quantum cahaya ",
"PHOTON ENERGY" : "Energi foton ",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: konstanta Planck, f: frekuensi (Hz), λ: panjang gelombang (m), c: kecepatan cahaya ",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Kondisi muatan untuk memiliki efek fotolistrik ",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: panjang gelombang cahaya bersinar, λ_o: batas fotolistrik, W: kerja dipancarkan (J) ",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Persamaan Einstein tentang efek fotolistrik ",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: massa fotoelektron (kg), v_o: kecepatan maksimum fotoelektron (m/s) ",

"1. THEORY OF RELATIVITY" : "1. Teori relativitas ",
"MASS–ENERGY EQUIVALENCE" : "Massa-energi kesetaraan ",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: massa (kg), E: energi benda (J), c: kecepatan cahaya (m/s) ",
"LENGTH CONTRACTION" : "Panjang kontraksi ",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: panjang obyek sebenarnya , l: panjang diamati oleh seorang pengamat yang bergerak dengan kecepatan v ",
"RELATIVISTIC MASS" : "Massa relativistik ",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: massa diam, m: massa relativistik benda ketika bergerak dengan kecepatan v ",
"TIME DILATION" : "Dilatasi waktu ",
"2. ATOMIC NUCLEUS" : "2. Inti atom ",
"NUCLEAR MAKEUP" : "Nuklir terdiri dari",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: jumlah proton, N: jumlah neutron, A: nomor massa ",
"NUCLEAR REACTION" : "Reaksi nuklir ",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: reaksi nuklir melepaskan energi",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: reaksi nuklir menyerap energi",
"RADIOACTIVE DECAY" : "Peluruhan radioaktif ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: jumlah awal zat aktif, N: jumlah yang masih tetap dan belum membusuk setelah t waktu, ΔN: jumlah zat membusuk, m_o: massa awal, m: massa yang tersisa, λ: konstanta peluruhan, t: waktu, T: waktu paruh",
"Half life of some elements" : "Separuh kehidupan dari beberapa elemen ",
"AMOUNT OF RADIOACTIVITY" : "Jumlah radioaktivitas ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: jumlah awal radioaktivitas, H: jumlah radioaktivitas pada waktu t ",
"1. CONSTANTS" : "1. Konstanta ",
"ALPHA PARTICLE MASS" : "Massa partikel alpha ",
"ATOMIC MASS CONSTANT" : "Massa atom konstan ",
"ATOMIC UNIT OF ENERGY" : "Unit atom energi ",
"ATOMIC UNIT OF FORCE" : "Unit atom gaya ",
"ATOMIC UNIT OF LENGTH" : "Unit atom panjang ",
"ATOMIC UNIT OF MASS" : "Unit atom massa ",
"AVOGADRO'S CONSTANT" : "Avogadro Konstan",
"BOHR RADIUS" : "Radius Bohr ",
"BOLTZMANN CONSTANT" : "Konstanta Boltzmann ",
"CLASSICAL ELECTRON RADIUS" : "Radius elektron klasik ",
"ELEMENTARY CHARGE" : "Muatan elementer ",
"EARTH MASS" : "Massa bumi ",
"EARTH EQUATORIAL RADIUS" : "Radius khatulistiwa bumi",
"EARTH MEAN ORBITAL VELOCITY" : "Kecepatan rata-rata orbital bumi",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Kecepatan  rotasi  sudut Bumi",
"FARADAY’S CONSTANT" : "Konstana Faraday ",
"GAS CONSTANT" : "Konstanta gas ",
"MOLAR MASS CONSTANT" : "Konstanta massa molar ",
"MOLAR VOLUME OF IDEAL GAS" : "Volume molar gas ideal ",
"NEUTRON MASS" : "Massa neutron ",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Konstanta Newtonian gravitasi ",
"PLANCK’S CONSTANT" : "Konstanta Planck ",
"PLANCK MASS" : "Massa Planck ",
"PROTON MASS" : "Massa proton ",
"PROTON-ELECTRON MASS RATIO" : "Rasio massa proton-elektron ",
"SPEED OF LIGHT IN VACUUM" : "Kecepatan cahaya dalam ruang hampa ",
"STANDARD ACCELERATION OF GRAVITY" : "Percepatan  standar gravitasi",
"STANDARD ATMOSPHERE" : "Atmosfir standar ",
"STANDARD REFERENCE SOUND INTENSITY" : "Acuan standar  Intensitas bunyi",
"STEFAN-BOLTZMANN CONSTANT" : "Konstanta Stefan-Boltzmann ",
"2. GREEK ALPHABET" : "2. Alfabet Yunani ",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: huruf Yunani, C2: Nama, C3: Setara, C4: Suara ketika berbicara ",

"Mechanics" : "Mekanika ",
"Thermal physics" : "Fisika Thermal ",
"Optics" : "Optik ",
"Theory of relativity" : "Teori relativitas ",

"FREE FALLING" : "Jatuh Bebas ",
"VERTICAL PROJECTILE" : "Proyektil Vertikal ",
"ANGLED PROJECTILE" : "Proyektil Lekukan ",
"HORIZONTAL PROJECTILE" : "Proyektil Horizontal ",
"SLIDING MOTION" : "Gerakan Geser ",
"ATTRACTIVE FORCE" : "Gaya tarik",
"Hydraulic press" : "Tekanan Hidrolik ",
"PRESSURE" : "Tekanan ",
"LINEAR EXPANSION" : "Ekspansi linear ",
"VOLUME EXPANSION" : "Ekspansi Volume ",
"SOUND SPEED" : "Kecepatan suara ",
"REFRACTION" : "Refraksi ",
"PRISM" : "Prisma",
"LENS" : "Lensa",
"Length contraction" : "Panjang kontraksi ",
"Time dilation" : "Dilatasi waktu ",
"RELATIVISTIC MASS" : "Massa relativistik ",

"Height " : "Tinggi ",
"Time to touchdown " : "Waktu untuk sampai ",
"Touchdown velocity " : "Kecepatan sampai",
"Initial velocity " : "Kecepatan awal ",
"Maximum height " : "Tinggi maksimum ",
"Initial velocity " : "Kecepatan awal ",
"Angle " : "Sudut",
"Maximum height " : "Tinggi maksimum ",
"Maximum distance " : "Jarak maksimum ",
"Height " : "Tinggi ",
"Initial velocity " : "Kecepatan awal ",
"Time to touchdown " : "Waktu untuk sampai ",
"Touchdown velocity " : "Kecepatan sampai",
"Angle of tilted plane " : "Sudut kemiringan bidang",
"Coefficient of friction " : "Koefisien gesekan ",
"Acceleration " : "Percepatan ",
"Mass " : "Massa ",
"Mass " : "Massa ",
"Distance " : "Jarak ",
"Attractive force " : "Kekuatan menarik ",
"Area " : "Area ",
"Area " : "Area ",
"Force " : "Gaya",
"Force" : "Gaya",
"Force F₂ (or F₁)" : "Gaya F₂ (atau F₁) ",
"Temperature " : "Suhu ",
"Pressure at 0°C " : "Tekanan pada 0°C ",
"Pressure " : "Tekanan ",
"Original length " : "Panjang asli ",
"Temperature change " : "Perubahan suhu ",
"Coefficient of linear expansion " : "Koefisien ekspansi linear ",
"Change of length " : "Perubahan panjang ",
"Original volume " : "Volume asli ",
"Temperature change " : "Perubahan suhu ",
"Coefficient of linear expansion " : "Koefisien ekspansi linear ",
"Change of volume " : "Perubahan volume ",
"Temperature " : "Suhu ",
"Sound speed " : "Kecepatan suara ",
"Refractive index " : "Indeks bias ",
"Refractive index " : "Indeks bias ",
"Angle of incidence " : "Sudut datang ",
"Angle of refraction " : "Sudut bias ",
"Angle (r or i) " : "Sudut (r atau i) ",
"Apex angle " : "Sudut Apex ",
"Angle of incident " : "Sudut insiden ",
"Refractive index " : "Indeks bias ",
"Angle of emergent ray " : "Sudut sinar muncul ",
"Deviation angle " : "Sudut deviasi ",
"Focal length " : "Panjang fokus ",
"Object distance " : "Jarak obyek",
"Image distance " : "Jarak gambar ",
"Image (or object) distance" : "Gambar (atau objek) jarak ",
"Magnification factor " : "Faktor pembesaran ",
"Speed " : "Kecepatan ",
"Proper length " : "Panjang yang tepat ",
"Observed length " : "Panjang teramati ",
"Rest mass " : "Massa diam ",
"Relativistic mass " : "Massa relativistik ",
"Proper time interval " : "Interval waktu yang tepat ",
"Observed time interval " : "Interval waktu Teramati ",
"Calculate" : "Hitung ",
"Or input" : "Atau masukan ",
"Calculation Tools" : "Alat perhitungan ",



	
};