var language={

	
"1. DYNAMICS" : "1. Chuyển động học",
"STRAIGHT LINE MOTION" : "Chuyển động thẳng",
"s: distance (m), t: time (s, second), v: velocity (m/s), v_a: average velocity" : "s: quãng đường (m), t: thời gian (s, giây), v: vận tốc (m/s), v_a: vận tốc trung bình ",
"CONSTANT ACCELERATION STRAIGHT LINE MOTION" : "Chuyển động thẳng biến đổi đều",
"a: acceleration, v_o: initial velocity, v: velocity at time t" : "a: Gia tốc, v_o: vận tốc ban đầu, v: vận tốc tại thời điểm t",
"DISTANCE FUNCTION" : "Phương trình tọa độ",
"x_o: initial distance from origin, x: distance at time t" : "x_o: vị trí ban đầu, x: vị trí tại thời điểm t ",
"UNIFORM CIRCULAR MOTION" : "Chuyển động tròn đều",
"φ: angle (rad), l: length of arc, R: radius of circle, ω: angular velocity (rad/s), t: time the object moves a length of l" : "φ: góc quay (rad), l: độ dài cung tròn, R: bán kính đường tròn, ω: vận tốc góc (rad/s), t: thời gian quay được cung tròn l",
"CENTRIPETAL FORCE" : "Lực hướng tâm",
"f: frequency (Hz), T:  the period for one rotation (s), a: centripetal acceleration, F: centripetal force (N, Newton)" : "f: tần số (Hz), T: chu kỳ quay hết 1 vòng tròn (s), a: gia tốc hướng tâm, F: lực hướng tâm (N, Newton) ",
"CONSTANT ACCELERATION CIRCULAR MOTION" : "CHUYỂN ĐỘNG TRÒN BIẾN ĐỔI ĐỀU ",
"γ: angular acceleration" : "γ: Gia tốc góc",
"ACCELERATION" : "Gia tốc",
"a_t: tangential acceleration, a_n: normal acceleration" : "a_t: Gia tốc tiếp tuyến, a_n: Gia tốc pháp tuyến",
"P1: speeding up, P2: uniform circular motion, P3: slowing down" : "P1: nhanh dần đều, P2: chuyển động tròn đều, P3: chậm dần đều",
"FREE FALLING FROM HEIGHT h" : "RƠI TỰ DO Ở ĐỘ CAO h",
"g: gravitational acceleration, v: velocity at t, s: distance after t, v_h: velocity when touching the ground, t_h: time to touchdown" : "g: gia tốc trọng trường, v: vận tốc đạt được tại thời điểm t, s: quãng đường đi được sau thời gian t, v_h: vận tốc lúc chạm đất, t_h: thời gian lúc chạm đất.",
"VERTICAL PROJECTILE MOTION" : "NÉM THẲNG ĐỨNG LÊN TRÊN",
"h_max: maximum height, v_o: initial velocity" : "h_max: Độ cao lớn nhất vật đạt được, v_o: vận tốc ban đầu",
"Motion equation and velocity equation" : "Phương trình chuyển động và phương trình vận tốc",
"ANGLED PROJECTILE MOTION" : "Ném xiên",
"v_x, v_y: velocity; x, y: motion equation by t; H: maximum height; L: maximum distance" : "v_x, v_y: vận tốc; x, y: Phương trình chuyển động theo thời gian t; H: Độ cao cực đại; L: Tầm bay xa ",
"HORIZONTAL PROJECTILE MOTION" : "Ném ngang",
"t_h: time when touchdown, v_h: velocity when touchdown" : "t_h: Thời gian chạm đất, v_h: Vận tốc khi chạm đất",
"SLIDING MOTION ON AN INCLINED PLANE" : "VẬT CHUYỂN ĐỘNG TRÊN MẶT PHẲNG NGHIÊNG",
"μ: coefficient of friction" : "μ: HỆ SỐ MA SÁT",
"Fiction coefficient of some materials" : "Hệ số ma sát của một số chất",
"2. FORCES" : "2. CÁC LOẠI LỰC",
"ATTRACTIVE FORCE" : "LỰC HẤP DẪN",
"m₁, m₂: mass of 2 objects; r: distance between 2 objects; G: gravitational constant" : "m₁, m₂: khối lượng các vật; r: khoảng cách giữa hai vật; G: hằng số hấp dẫn",
"GRAVITATIONAL FORCE" : "LỰC HẤP DẪN CỦA TRÁI ĐẤT",
"M: Earth mass, m: mass of object, R: Earth radius, h: object's height" : "M: khối lượng Trái Đất, m: khối lượng của vật, R: bán kính Trái Đất, h: độ cao so với mặt đất",
"GRAVITATIONAL ACCELERATION" : "Gia tốc trọng trường",
"At a height h above the nominal surface of the earth" : "Ở độ cao h so với mặt đất",
"Near the sea level" : "Vật ở mặt đất",
"FORCE OF GRAVITY" : "TRỌNG LỰC",
"Force of gravity on earth, a special case of Gravitational force" : "Trọng lực là trường hợp riêng của lực hấp dẫn",
"NEWTON'S FIRST LAW" : "Định luật I Niu-tơn",
"F: forces acting on the object, v: velocity of the object, a: acceleration of the object" : "F là ngoại lực tác dụng lên vật (N), v là vận tốc của vật, a là gia tốc của vật",
"NEWTON'S SECOND LAW" : "Định luật II Niu-tơn",
"m: object's mass (kg)" : "m là khối lượng của vật (kg)",
"NEWTON'S THIRD LAW" : "Định luật III Niu-tơn",
"LINEAR ELASTICITY - HOOKE'S LAW" : "LỰC ĐÀN HỒI CỦA LÒ XO - Định luật Húc",
"k: spring constant (N/m), x: displacement (m)" : "k: độ cứng của lò xo (N/m), x: độ dãn của lò xo (m)",
"A mass suspended by a spring" : "Nếu lực đàn hồi do trọng lực",
"FORCE OF FRICTION" : "LỰC MA SÁT",
"μ: coefficient of friction, N: normal force" : "μ: Hệ số ma sát, N: áp lực",
"3. STATICS" : "3. TĨNH HỌC VẬT RẮN",
"MOMENT OF A FORCE" : "MOMEN LỰC",
"F: the force applied (N), d: moment arm (the perpendicular distance from the axis to the line of action of the force)" : "F: lực tác dụng vào vật (N), d: cánh tay đòn của lực (m)",
"MOMENT APPLICATION" : "QUY TẮC MOMEN LỰC",
"MOMENT OF INERTIA" : "MOMEN QUÁN TÍNH CỦA VẬT RẮN ĐỒNG CHẤT",
"Rod of length l" : "THANH MẢNH CHIỀU DÀI l",
"Thin circular hoop/ Thin cylindrical shell" : "VÀNH TRÒN/HÌNH TRỤ RỖNG",
"Solid disk/ Solid cylinder" : "ĐĨA TRÒN/HÌNH TRỤ ĐẶC",
"Solid ball" : "QUẢ CẦU ĐẶC",
"Hollow sphere" : "Quả cầu rỗng",
"ANGULAR MOMENTUM" : "MOMEN ĐỘNG LƯỢNG",
"I: moment of inertia, ω: angular velocity" : "I: momen quán tính, ω: tốc độ góc",
"PLANE MOTION OF A RIGID BODY" : "PHƯƠNG TRÌNH ĐỘNG LỰC HỌC",
"γ: angular acceleration, M: moment of a force" : "γ: gia tốc góc, M: momen lực",

"4. CONSERVATION LAWS" : "4. CÁC ĐỊNH LUẬT BẢO TOÀN",
"MOMENTUM OF FORCE" : "ĐỘNG LƯỢNG",
"LAW OF CONSERVATION OF MOMENTUM" : "ĐỊNH LUẬT BẢO TOÀN ĐỘNG LƯỢNG",
"v₁, v₂: initial velocities of objects 1 and 2; v₁', v₂': final velocities of object 1 and 2" : "v₁, v₂: vận tốc ban đầu của vật 1 và 2; v₁', v₂': vận tốc sau va chạm của vật ",
"PLASTIC COLLISION" : "Va chạm mềm",
"v': velocity of the two body system (m₁+m₂) after impact" : "v’: Vận tốc của hệ (m₁ + m₂) sau va chạm",
"ONE-DIMENSIONAL ELASTIC COLLISION" : "VA CHẠM ĐÀN HỒI TRỰC DIỆN",
"v₁’, v₂’: velocities of m₁ and m₂ after impact" : "v₁’ và v₂’: Vận tốc của m₁ và m₂ sau va chạm",
"5. WORK AND ENERGY" : "5. Công và năng lượng",
"WORK" : "Công",
"W: work done by a force (J), F: force move a object for a distance s, α: angle between F and movement direction" : "W: Công sinh ra (J), F: lực đẩy quãng đường s, α: góc hợp bởi hướng của lực và hướng chuyển động, ",
"EXAMPLES" : "Ví dụ",
"W_p: work by gravity, h: the change in height; W_ms: work of friction's force; W: work by a spring" : "W_p: Công của trọng lực, h: hiệu độ cao giữa điểm đầu và cuối; W_ms: công của lực ma sát; W: công của lực đàn hồi.",
"POWER" : "Công suất",
"P: power (watt, W), t: time of conducting the work W (s)" : "P: Công suất (watt, W), t: Thời gian thực hiện công W (s)",
"KINETIC ENERGY" : "Động năng",
"KINETIC ENERGY OF A MASSIVE ROTATING BODY" : "Động năng của vật rắn quay quanh 1 trục cố định",
"WORK-ENERGY PRINCIPLE" : "Định lý động năng",
"v₁, v₂: speeds of object before and after the change" : "v₁ và v₂: Vận tốc của vật trước và sau thay đổi",
"POTENTIAL ENERGY" : "Thế năng",
"E_p: gravitational potential energy (J), m: mass of object (kg)" : "E_p: thế năng hấp dẫn (J), m: khối lượng của vật",
"CONSERVATION OF MECHANICAL ENERGY" : "Định luật bảo toàn cơ năng",
"CONSERVATION OF ENERGY" : "Định luật bảo toàn năng lượng",
"6. MECHANICS OF FLUIDS" : "6. Cơ chất lỏng",
"DENSITY" : "Khối lượng riêng",
"m: mass of a volume V" : "m: khối lượng của một khối thể tích V",
"PRESSURE" : "Áp suất",
"F: force applied on area of A" : "F: lực tác động trên diện tích A",
"PRESSURE OF LIQUIDS" : "Áp suất chất lỏng",
"d: specific gravity (N/m³), p_o: air pressure at the free surface (N/m²), p: pressure created by the weight of liquid above, p_B: total pressure at the depth h" : "d: trọng lượng riêng của chất lỏng (N/m³), p_o: áp suất khí quyển tại mặt thoáng (N/m²), p: áp suất của cột chất lỏng có độ cao h, p_B: Áp suất tĩnh của chất lỏng ở độ sâu h",
"PASCAL’S PRINCIPLE" : "NGUYÊN LÍ PASCAL",
"p_s: pressure on the surface" : "p_s: áp suất ngoài",
"APPLICATION" : "Áp dụng",
"A₁, A₂: area of small and large cylinders; F₁, F₂: applied and upward forces" : "A₁, A₂: diện tích của cột chất lỏng; F₁, F₂: lực tương ứng",
"ARCHIMEDES’ PRINCIPLE" : "Lực đẩy Ác-si-mét",
"d: specific gravity of liquid (N/m³), V: volume of object, F_b: buoyant force" : "d: trọng lượng riêng của chất lỏng (N/m³), V: thể tích phần bị chìm trong  chất lỏng",
"FLOW RATE" : "Lưu lượng chất lỏng",
"A: cross-sectional area (m²), v: flow velocity (m/s), Q: flow rate (m³/s)" : "A: tiết diện (m²), v: vận tốc dòng chảy (m/s), Q: lưu lượng (m³/s)",

"1. ELECTROSTATICS" : "1. Tĩnh học",
"COULOMB’S LAW" : "Định luật Cu-lông",
"q: size of charges (C), ε: relative permittivity (in vacuum ε=1), r: distance between the charges (m)" : "q: điện tích (C), ε: hằng số điện môi (trong chân không ε=1), k: hằng số cu-lông trong không khí, r: khoảng cách giữa 2 điện tích (m)",
"ELECTRIC FIELDS" : "Điện trường",
"E: electric field strength (N/C)" : "E: cường độ điện trường (N/C)",
"THE PRINCIPLE OF SUPERPOSITION FOR ELECTRIC FIELDS" : "Nguyên lý chồng chất điện trường",
"In case of 2 electric fields" : "Xét trường hợp có 2 cường độ điện trường",
"WORK OF ELECTRIC FORCE" : "Công của lực điện trường",
"ELECTRIC POTENTIAL DIFFERENCE" : "Hiệu điện thế",
"RELATION BETWEEN E AND U" : "Liên hệ giữa E và U",
"CAPACITANCE" : "Điện dung",
"C: capacitance (F), Q: total electric charge (C), U: electric potential (V)" : "C: Điện dung (F), Q: điện tích (C), U: hiệu điện thế đặt vào (V)",
"CAPACITOR" : "TỤ ĐIỆN",
"A: area of each electrode plate (m²), d: distance between the electrodes (m), ε: relative permittivity (F/m)" : "A: tiết diện của 2 bản tụ (m²), d: khoảng cách giữa hai bản tụ (m), ε: hằng số điện môi.",
"CAPACITANCES IN SERIES" : "Ghép tụ điện nối tiếp",
"CAPACITANCES IN PARALLEL" : "Chép tụ điện song song",
"ELECTRIC FIELD ENERGY" : "Năng lượng điện trường",
"ENERGY OF CAPACITOR" : "Năng lượng điện trường của tụ điện phẳng",
"V=A.d: volume between two electrode plates" : "V=A.d: thể tích không gian giữa 2 bản tụ",
"2. DIRECT CURRENT" : "2. Dòng điện một chiều",
"ELECTRIC CURRENT" : "Cường độ dòng điện",
"I: current (A), q: charge (C), t: time" : "I: cường độ dòng điện (A), q: điện tích (C), t: thời gian",
"OHM’S LAW" : "Định luật Ôm",
"U: electric potential difference between the ends of the resistor R" : "U: hiệu điện thế đặt vào hai đầu điện trở R",
"WORK CREATED BY A CURRENT (JOULE’S LAW)" : "Công của dòng điện (Điện năng tiêu thụ - Định luật Jun-Lenxơ)",
"ELECTRICAL POWER" : "Công suất của dòng điện",
"RESISTANCE" : "Điện trở",
"ρ: resistivity of the material (Ωm), l: length (m), A: cross-section area (m²)" : "ρ: điện trở suất của chất làm điện trở (Ωm),l:chiều dài của điện trở (m), S: tiết diện của điện trở (m²)",
"SERIES CIRCUITS" : "Điện trở mắc nối tiếp",
"PARALLEL CIRCUITS" : "Điện trở mắc song song",
"WORK OR HEAT ENERGY PRODUCED BY A RESISTOR" : "Điện năng tiêu thụ của điện trở",
"POWER CONSUMPTION OF A RESISTOR" : "Công suất toả nhiệt của điện trở",

"ELECTROMOTIVE FORCE OF AN ELECTRICAL GENERATOR" : "Suất điện động của nguồn điện",
"W: work of force (J), q: charge (C)" : "W: công của lực lạ (J), q: điện tích (C)",
"GENERATORS IN SERIES" : "Bộ nguồn mắc nối tiếp",
"r: internal resistance of the generator" : "r: điện trở trong của bộ nguồn",
"GENERATORS IN PARALLEL" : "Bộ nguồn mắc song song",
"GENERATORS IN SERIES-PARALLEL" : "Bộ nguồn mắc hỗn hợp đối xứng",
"WORK AND POWER OF GENERATOR" : "Công và công suất của nguồn điện",
"H: Efficiency of generator" : "H: Hiệu suất của nguồn điện",
"3. MAGNETISM" : "3. TỪ TRƯỜNG",
"MAGNETIC FLUX THROUGH THE OPEN SURFACE S" : "Từ thông qua diện tích S",
"B: magnitude of the magnetic field (T, tesla), α: angle between B and perpendicular line to surface S" : "B: mật độ từ thông (T, tesla), α: góc hợp bởi B và đường vuông góc với mặt S ",
"MAGNETIC FORCES ON MOVING CHARGES" : "Lực từ lên một điện tích di động - lực Lo-ren-xơ",
"v: velocity of the charge (m/s)" : "v: vận tốc của điện tích (m/s)",
"FORCE ON A CURRENT-CARRYING WIRE" : "Lực tác động lên 1 dây dẫn mang dòng điện",
"I: current (A), l: length of the wire (m)" : "I: cường độ dòng điện (A), l: chiều dài dây dẫn (m)",
"FORCE BETWEEN 2 PARALLEL CURRENT-CARRYING WIRES" : "Lực tương tác giữa hai dây dẫn song song có dòng điện",
"r: distance between two wires (m)" : "r: khoảng cách giữa hai dây dẫn (m)",
"MAGNETIC FIELD OF A LONG CURRENT-CHARGE WIRE" : "Từ trường của dòng điện trong dây dẫn thẳng",
"r: perpendicular distance from the center of the wire (m)" : "r: bán kính tiết diện của dây dẫn thẳng (m)",
"MAGNETIC FIELD OF A LOOP" : "Từ trường trong ống dây dẫn",
"n: number of turns per unit length of solenoid (turns/m)" : "n: số vòng trên mỗi mét chiều dài của ống",
"INDUCED ELECTROMOTIVE FORCE - FARADAY’S LAW" : "Suất điện động cảm ứng trong mạch kín",
"N: numbers of turns per loop (turns/m)" : "N: số vòng dây",
"INDUCTANCE" : "Độ tự cảm của cuộn dây",
"ELECTRIC ENERGY" : "Năng lượng điện trường",
"MAGNETIC ENERGY" : "Năng lượng từ trường",
"ELECTRIC-MAGNETIC ENERGY" : "Năng lượng điện từ",
"4. ALTERNATING CURRENT" : "4. Dòng điện xoay chiều",
"BASIC PARAMETERS" : "Các thông số cơ bản",
"i: instantaneous current (A), I_o: maximum instantaneous current (A), T: period of the wave, f: frequency, λ: wavelength, c: speed of light" : "i: dòng điện tức thời (A), I_o: biên độ (A), T: chu kỳ dòng điện, f: tần số, λ: bước sóng, c: tốc độ ánh sáng",
"EFFECTIVE CURRENT AND VOLTAGE" : "Các giá trị hiệu dụng",
"OHM’S LAW OF AC CURRENT CONTAINING ONLY RESISTANCE R" : "Định luật Ôm với đoạn mạch chỉ chứa R",
"CONTAINING ONLY INDUCTOR L" : "Đoạn mạch chỉ chứa cảm kháng L ",
"Z_L: inductive reactance" : "Z_L: cảm kháng",
"CONTAINING ONLY CAPACITOR C" : "Đoạn mạch chỉ chứa dung kháng C",
"Z_C: capacitive reactance" : "Z_C: dung kháng",
"CONTAINING R, L AND C IN A SERIES" : "Đoạn mạch gồm R, L, C mắc nối tiếp",
"Z: impedance" : "Z: tổng trở",
"PHASE ANGLE" : "Độ lệch pha giữa u và i",
"POWER FACTOR" : "Hệ số công suất",
"REAL POWER" : "Công suất mạch điện",
"ELECTRICAL RESONANCE" : "Hiện tượng cộng hưởng, u và i cùng pha",
"CHANGING VOLTAGE WITH TRANSFORMERS" : "Máy biến áp",
"N₁, N₂: number of turns in the primary coil and secondary coil; U₁, U₂: primary and secondary voltage; I₁, I₂: primary and secondary currents" : "N₁, N₂: số vòng dây của cuộn sơ cấp & thứ cấp; U₁, U₂: hiệu điện thế cuộn sơ cấp & thứ cấp; I₁, I₂: dòng điện ở cuộn sơ cấp & thứ cấp",

"1. GAS LAWS" : "1. Các định luật về khí",
"KELVIN TEMPERATURE" : "Nhiệt độ tuyệt đối",
"T: temperature in Kelvin scale, t: temperature in Celsius scale" : "T: nhiệt độ trong nhiệt giai Kenvin,  t: nhiệt độ trong nhiệt giai Celsius",
"EQUATION OF STATE" : "PHƯƠNG TRÌNH CLA-PÊ-RÔN – MEN-ĐÊ-LÊ-ÉP",
"p: pressure (P, Pascal), V: volume (m³), n: number of moles of the gas(mol), R: universal gas constant, T: Kelvin temperature of the gas (K), k: Boltzmann’s constant, N: number of molecules in the gas" : "p: áp suất (P, Pascal), V: thể tích (m³), n: số các hạt trong khối khí (mol), R: hằng số khí, T: nhiệt độ (K), k: Hằng số Bôn-zơ-man",
"IDEAL GAS LAW" : "Phương trình trạng thái khí lí tưởng",
"BOYLE’S LAW FOR PRESSURE" : "Định luật BÔI-LƠ – MA-RI-ỐT (đẳng nhiệt)",
"If the temperature of the gas is constant" : "Nếu nhiệt độ không đổi",
"GAY-LUSSAC'S LAW OF PRESSURE-TEMPERATURE" : "Định luật SÁC-LƠ (ĐẲNG TÍCH)",
"If the volume on a gas is constant" : "Nếu thể tích không đổi",
"p: pressure of gas at temperature t, p_o: pressure at 0 Celsius, γ: factor when volume is constant" : "p: áp suất chất khí ở nhiệt độ t, p_o: áp suất chất khí ở nhiệt độ 0 Celsius, γ: hệ số tăng áp đẳng tích (đều có chung một giá trị đối với mọi chất khí và ở mọi khoảng nhiệt độ)",
"Example when t=0 Kelvin" : "Ví dụ khi t=0 độ kevin",
"CHARLES'S LAW OF VOLUMES" : "Định luật GAY LUY-XẮC (Đẳng áp)",
"If the pressure on a gas is constant" : "Nếu áp suất không đổi",
"2. CHANGES OF STATE AND SHAPE" : "2. Sự thay đổi trạng thái và hình dạng",
"HEAT" : "Phương trình cân bằng nhiệt",
"Q_e: Heat emitted, Q_r: heat received, m: object's total mass (kg), c: specific heat(J/kg.K), ∆t: change in temperature (K)" : "Q_e: tỏa, Q_r: thu, m: khối lượng của chất (kg), c: nhiệt dung riêng của chất (J/kg.K), ∆t: độ biến thiên nhiệt độ (K)",
"The specific heats of some materials" : "Nhiệt dung riêng của một số chất",
"FUSION (FREEZING OR SOLIDIFICATION)" : "Nhiệt nóng chảy/đông đặc",
"Heat of fusion of some materials" : "Nhiệt nóng chảy (đông đặc) của một số chất",
"Q: quantity of heat (J), λ: heat of fusion (J/kg), m: mass (kg)" : "Q: nhiệt cần cung cấp (J), λ: nhiệt nóng chảy (đông đặc) của chất (J/kg), m: khối lượng chất (kg)",
"VAPORIZATION" : "Hóa hơi",
"L: heat of vaporization" : "L: nhiệt hoá hơi (ngưng tụ) của chất (J/kg)",
"Heat of vaporization of some materials" : "Nhiệt hoá hơi (ngưng tụ) của một số chất",
"LINEAR EXPANSION" : "Sự nở dài",
"l_o: original length (m), α: coefficient of linear expansion (K⁻¹), ∆t: change in temperature" : "l_o: chiều dài ban đầu (m), α: hệ số nở dài của vật rắn (K⁻¹), ∆t: độ biến thiên nhiệt độ ",
"VOLUME EXPANSION" : "Sự nở khối (thể tích)",
"AREA EXPANSION" : "Sự nở tích (diện tích)",
"CHANGE OF DENSITY (VOLUMETRIC MASS DENSITY)" : "Sự thay đổi về khối lượng riêng của vật rắn",
"D_o: original density (kg/m³)" : "D_o: khối lượng riêng ban đầu (kg/m³)",
"CHANGE OF DIAMETER OF THE CROSS SECTION OF A SOLID" : "Sự thay đổi về đường kính tiết diện của vật rắn",
"3. THERMODYNAMICS" : "3. Nhiệt động lực học",
"THE FIRST LAW OF THERMODYNAMICS" : "NGUYÊN LÍ I VỀ NHIỆT ĐỘNG LỰC HỌC",
"∆U: change in internal energy, W: work done by the system, Q: heat added into or out of the system" : "∆U: độ biến thiên nội năng của hệ, W: công (giá trị đại số), Q: nhiệt lượng (giá trị đại số)",
"APPLICATION OF FIRST LAW TO IDEAL GAS LAWS" : "ÁP DỤNG NGUYÊN LÍ I CHO CÁC QUÁ TRÌNH CỦA KHÍ LÍ TƯỞNG",
"- Volume is constant" : "Quá trình đẳng tích",
"- Pressure is constant, W': work created by gas" : "Quá trình đẳng áp, W’: công khí sinh ra",
"- Temperature is constant" : "Quá trình đẳng nhiệt",
"THE SECOND LAW OF THERMODYNAMICS" : "NGUYÊN LÍ II VỀ NHIỆT ĐỘNG LỰC HỌC",
"- The efficiency of a cyclic heat engine" : "Hiệu suất của động cơ nhiệt",
"W′: work carried out per cycle (J), Q₁: heat absorbed per cycle from the higher temperature (J), Q₂’: heat rejected per cycle to the lower temperature (J)" : "W′: công sinh ra cho vật ngoài (J), Q₁: nhiệt lượng nhận từ nguồn nóng (J), Q₂’: nhiệt lượng truyền cho nguồn lạnh (J)",
"- Maximum thermal efficiency" : "Hiệu suất cực đại của máy nhiệt",
"T₁, T₂: higher and lower temperatures" : "T₁, T₂: nhiệt độ nguồn nóng & nguồn lạnh",

"1. SIMPLE HARMONIC MOTION" : "1. Các loại dao đông điều hòa đơn giản",
"SPRING" : "Con lắc lò xo",
"k: spring constant (N/m), s: displacement (m), ω: angular velocity (rad/s), T: period, m: mass of the object, A: amplitude" : "k: độ cứng của lò xo (N/m), s: phương trình dao động (m), ω: Tốc độ góc, T: chu kỳ, m: khối lượng của vật, A: biên độ",
"SPRINGS IN SERIES" : "Ghép lò xo nối tiếp",
"k: spring constant of the system, T: period of the system" : "k: độ cứng của hệ ghép, T: chu kỳ của hệ ghép",
"SPRINGS IN PARALLEL" : "Ghép lò xo song song",
"SIMPLE PENDULUM" : "Con lắc đơn",
"ω: angular velocity (rad/s), T: period, α_o: angle at amplitude, A: amplitude, l: length of pendulum" : "ω: Tốc độ góc, T: chu kỳ, α_o: biên độ góc, A: biên độ, l: chiều dài con lắc",
"MOTION EQUATIONS" : "Phương trình chuyển động",
"s: displacement, α: angle, v: velocity, T: strength on the rod" : "s: Li độ cong, α: Li độ góc, v: tốc độ, T: lực căng dây",
"ENERGY" : "Năng lượng",
"E_p: potential energy, E_k: kinetic energy, E: mechanic energy" : "E_p: Thế năng, E_k: động năng, E: cơ năng",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE TEMPERATURE" : "Sự biến thiên chu kì của con lắc đơn theo nhiệt độ",
"α: coefficient of linear expansion of the rod" : "α: hệ số nở dài của dây treo",
"CHANGE OF PERIOD FOLLOWING THE CHANGE OF THE HEIGHT" : "Sự biến thiên chu kì của con lắc đơn theo độ cao",
"h: height of pendulum, R: Earth's radius" : "h: độ cao con lắc so với mặt đất, R: bán kính Trái Đất",
"PENDULUM" : "Con lắc vật lý",
"I: moment of inertia, ω: angular velocity, m: mass of bob, d: OG, T: period" : "ω: tốc độ góc, I: momen quán tính, m: khối lượng con lắc, d: khoảng cách từ trọng tâm G đến trục quay O (OG), T: chu kỳ",
"2. PERIODIC MOTION" : "2. Dao động",
"WAVELENGTH" : "Bước sóng",
"FUNCTION OF WAVE AT SOME POINTS" : "Phương trình sóng tại điểm",
"WAVE INTERFERENCE" : "Giao thoa sóng",
"S₁, S₂: 2 sources of wave having same phase; M: a random point" : "S₁, S₂: 2 nguồn sóng kết hợp cùng pha; M: 1 điểm bất kì",
"3. SOUND WAVES" : "3. Sóng âm",
"SOUND SPEED" : "Vận tốc âm thanh",
"v (m/s): sound speed in environment with temperature t (Celsius)" : "v (m/s): vận tốc âm thanh ở môi trường có nhiệt độ t (Celsius)",
"SOUND INTENSITY " : "Cường độ âm",
"E: sound energy (J), P: sound power (W), A: the surface area of a sphere (m²), t: time (s)" : "E: năng lượng phát âm (J), P: công suất phát âm (W), A: diện tích mặt cầu (m²), t: thời gian sóng âm truyền (s)",
"SOUND INTENSITY LEVEL" : "Mức cường độ âm",
"I_o: the standard reference sound intensity" : "I_o: mức cường độ âm chuẩn",
"THE DOPPLER EFFECT" : "Hiệu ứng ĐỐP-LE",
"v_O: the relative speed of the observer; v_S: the relative speed of the source; v: the sound speed in this medium; f_S, f_O: sound frequency of the source and observer" : "v_O: tốc độ máy thu; v_S: tốc độ nguồn phát; v: tốc độ truyền âm trong môi trường; f_S, f_O: tần số máy phát và tần số thu được ",
"SOUND SPEED IN GASES" : "Tốc độ âm trong chất khí",
"v: speed of sound (m/s), R: universal gas constant, T: absolute temperature (K), M: molecular mass of gas (kg/mol), γ: adiabatic constant" : "v: vận tốc âm (m/s), R: hằng số khí, T: nhiệt độ tuyệt đối (K), M: trọng lượng hạt (kg/mol),  γ: hằng số",
"Example in air" : "Ví dụ trong không khí",

"1. GEOMETRIC OPTICS" : "1. QUANG HÌNH HỌC",
"LAWS OF REFLECTION" : "Định luật phản xạ ánh sáng",
"SI: incident ray, IR: reflected ray, i: angle of incidence, i': angle of reflection" : "SI: tia tới, IR: tia phản xạ, i: góc tới, i': góc phản xạ",
"REFRACTIVE INDEX" : "Chiết suất",
"n: refractive index of the a medium, v: speed of light in a medium, c: speed of light in vacuum (m/s)" : "n: chiết suất của môi trường, v: vận tốc ánh sáng trong môi trường đó, c: vận tốc ánh sáng trong chân không (m/s)",
"LAW OF REFRACTION" : "Định luật khúc xạ ánh sáng",
"n₁: refractive index of the medium 1,n₂: refractive index of the medium 2, i:  angle of incidence, r: angle of refraction,n₂₁: absolute index of refraction" : "n₁: chiết suất của môi trường tới,n₂: chiết suất của môi trường khúc xạ, i:  góc tới, r: góc khúc xạ,n₂₁: chiết suất tuyệt đối",
"If medium 1 is vacuum" : "Nếu môi trường 1 là chân không ",
"TOTAL REFLECTION PHENOMENON" : "Hiện tượng phản xạ toàn phần",
"There is no refracted ray if" : "Không có tia khúc xạ nếu",
"PRISM" : "Lăng kính",
"A: apex angle, D: deviation angle, i₁: angle of incidence, i₂: angle of emergent ray" : "A: góc chiết quang, D: góc lệch của tia sáng và tia ló ra khỏi lăng kính, i₁: góc tới, i₂: góc ló",
"- Condition to have refractive ray" : "Điều kiện để có tia khúc xạ",
"- When angle of incidence is minimum" : "Khi tia sáng có góc lệch nhỏ nhất ",
"THIN LENS" : "Thấu kính mỏng",
"f: focal length (converging lens f&gt;0; diverging lens f&lt;0), d: object distance from lens center, d′: image distance from lens center" : "f: tiêu cự của thấu kính, (TK hội tụ f&gt;0; TK phân kì f&lt; 0), d: khoảng cách từ vật đến thấu kính, d′: khoảng cách từ ảnh đến thấu kính",
"MAGNIFICATION FACTOR" : "Độ phóng đại",
"h_I: image height, h_O: object height" : "h_I: độ cao của ảnh, h_O: độ cao của vật",
"POWER OF THE LENS" : "Độ tụ",
"n: refractive index of the lens material, R₁: radius of curvature of the lens surface closest to the light source, R₂: radius of curvature of the lens surface farthest from the light source" : "n: chiết suất tỉ đối của vật liệu làm thấu kính đối với môi trường xung quanh, R₁, R₂: bán kính cong của các mặt thấu kính",
"2. QUANTUM OF LIGHT" : "2. Lượng tử ánh sáng",
"PHOTON ENERGY" : "Năng lượng photon",
"h: Planck's constant, f: frequency (Hz), λ: wavelength (m), c: speed of light" : "h: hằng số Planck, f: tần số của ánh sáng chiếu vào (Hz), λ: bước sóng ánh sáng (m), c: vận tốc ánh sáng",
"CONDITION TO HAVE PHOTOELECTRIC EFFECT" : "Điều kiện để có hiện tượng quang điện",
"λ: wavelength of the shinning light , λ_o: photoelectric limit, W: emitted work (J)" : "λ: bước sóng của ánh sáng chiếu vào, λ_o𝑜: giới hạn quang điện, W: công thoát (J)",
"EINSTEIN'S EQUATION ABOUT PHOTOELECTRIC EFFECT" : "Phương trình Anh-stanh về hiện tượng quang điện",
"m: mass of photoelectron (kg), v_o: maximum velocity of photoelectron (m/s)" : "m: khối lượng của electron quang điện (kg), v_o: vận tốc ban đầu cực đại của electron quang điện (m/s)",

"1. THEORY OF RELATIVITY" : "1. Thuyết tương đối",
"MASS–ENERGY EQUIVALENCE" : "Hệ thức ANH-STANH",
"m: mass (kg), E: energy of object (J), c: speed of light (m/s)" : "m: khối lượng của vật (kg), E: năng lượng của vật (J), c: vận tốc ánh sáng (m/s)",
"LENGTH CONTRACTION" : "Sự co độ dài",
"l_o: real length of object, l: length observed by an observer moving with speed v" : "l_o: chiều dài thực của vật, l: chiều dài được quan sát khi vật có vận tốc v",
"RELATIVISTIC MASS" : "Khối lượng tương đối",
"m_o: rest mass, m: relativistic mass of object when moving with speed v" : "m_o: khối lượng thực của vật, m: khối lượng của vật khi có vận tốc v",
"TIME DILATION" : "Sự chậm lại của đồng hồ",
"2. ATOMIC NUCLEUS" : "2. Hạt nhân nguyên tử",
"NUCLEAR MAKEUP" : "Cấu tạo hạt nhân nguyên tử",
"Z: number of protons, N: number of neutrons, A: mass number" : "Z: nguyên tử số (số proton trong hạt nhân), N: số nơtron trong hạt nhân, A: số khối",
"NUCLEAR REACTION" : "Phản ứng hạt nhân",
"- m&lt;m_o: nuclear reaction releases energy" : "- m&lt;m_o: phản ứng toả năng lượng",
"- m&gt;m_o: nuclear reaction absorbs energy" : "- m&gt;m_o: phản ứng thu năng lượng. E_s: năng lượng cần cung cấp",
"RADIOACTIVE DECAY" : "Định luật phóng xạ",
"N_o: initial amount of active substance, N: quantity that still remains and has not yet decayed after a time t, ∆N: amount of decayed substance, m_o: initial mass, m: mass of remaining, λ: decay constant, t: time, T: half-life" : "N_o: số hạt ban đầu, N: số hạt còn lại, ∆N: số hạt phân rã, m_o: khối lượng chất ban đầu, m: khối lượng chất còn lại, λ: hằng số phóng xạ (phân rã), t: thời gian phóng xạ, T: chu kì bán rã",
"Half life of some elements" : "Chu kỳ bán rã của một số chất",
"AMOUNT OF RADIOACTIVITY" : "Độ phóng xạ",
"H_o: initial amount of radioactivity, H: amount of radioactivity at time t" : "H_o: Độ phóng xạ ban đầu, H: Độ phóng xạ tại thời điểm t",
"1. CONSTANTS" : "1. Hằng số",
"ALPHA PARTICLE MASS" : "Khối lượng hạt alpha",
"ATOMIC MASS CONSTANT" : "Hằng số khối lượng nguyên tử",
"ATOMIC UNIT OF ENERGY" : "Đơn vị nguyên tử của năng lượng",
"ATOMIC UNIT OF FORCE" : "Đơn vị nguyên tử của lực",
"ATOMIC UNIT OF LENGTH" : "Đơn vị nguyên tử của chiều dài",
"ATOMIC UNIT OF MASS" : "Đơn vị nguyên tử của khối lượng",
"AVOGADRO'S CONSTANT" : "Hằng số Avogadro",
"BOHR RADIUS" : "Bán kính Bohr",
"BOLTZMANN CONSTANT" : "Hằng số Boltzmann",
"CLASSICAL ELECTRON RADIUS" : "Bán kính điện tử",
"ELEMENTARY CHARGE" : "Điện tích nguyên tố",
"EARTH MASS" : "Khối lượng Trái đất",
"EARTH EQUATORIAL RADIUS" : "Bán kính Trái đất",
"EARTH MEAN ORBITAL VELOCITY" : "Vận tốc quỹ đạo trung bình của Trái đất",
"EARTH ROTATIONAL ANGULAR VELOCITY" : "Vận tốc góc quay của Trái đất",
"FARADAY’S CONSTANT" : "Hằng số Faraday",
"GAS CONSTANT" : "Hằng số khí",
"MOLAR MASS CONSTANT" : "Hằng số phân tử gam",
"MOLAR VOLUME OF IDEAL GAS" : "Thể tích mol của khí lý tưởng",
"NEUTRON MASS" : "Khối lượng hạt nơ tron",
"NEWTONIAN CONSTANT OF GRAVITATION" : "Hằng số hấp dẫn New tơn",
"PLANCK’S CONSTANT" : "Hằng số Planck",
"PLANCK MASS" : "Khối lượng Planck",
"PROTON MASS" : "Khối lượng proton",
"PROTON-ELECTRON MASS RATIO" : "Tỉ số khối lượng proton-điện tử",
"SPEED OF LIGHT IN VACUUM" : "Tốc độ ánh sáng trong chân không",
"STANDARD ACCELERATION OF GRAVITY" : "Gia tốc trọng trường",
"STANDARD ATMOSPHERE" : "Áp suất khí quyển",
"STANDARD REFERENCE SOUND INTENSITY" : "Mức cường độ âm chuẩn",
"STEFAN-BOLTZMANN CONSTANT" : "Hằng số Stefan-Boltzmann",
"2. GREEK ALPHABET" : "2. Các ký tự Hy lạp",
"C1: Greek letter, C2: Name, C3: Equivalent, C4: Sound when spoken" : "C1: ký tự Hy lạp, C2: Tên, C3: Tương đương, C4: Cách đọc",

"Mechanics" : "Cơ học",
"Thermal physics" : "Nhiệt học",
"Optics" : "Quang học",
"Theory of relativity" : "Thuyết tương đối",

"FREE FALLING" : "Rơi tự do",
"VERTICAL PROJECTILE" : "Ném thẳng đứng",
"ANGLED PROJECTILE" : "Ném xiên",
"HORIZONTAL PROJECTILE" : "Ném ngang",
"SLIDING MOTION" : "Gia tốc trượt",
"ATTRACTIVE FORCE" : "LỰC HẤP DẪN",
"Hydraulic press" : "Máy nén thủy lực",
"PRESSURE" : "Áp suất",
"LINEAR EXPANSION" : "Sự nở dài",
"VOLUME EXPANSION" : "Sự nở khối (thể tích)",
"SOUND SPEED" : "Vận tốc âm thanh",
"REFRACTION" : "Khúc xạ ánh sáng",
"PRISM" : "Lăng kính",
"LENS" : "Thấu kính",
"Length contraction" : "Sự co độ dài",
"Time dilation" : "Sự chậm lại của đồng hồ",
"RELATIVISTIC MASS" : "Khối lượng tương đối",

"Height " : "Chiều cao",
"Time to touchdown " : "Thời gian chạm đất",
"Touchdown velocity " : "Vận tốc chạm đất",
"Initial velocity " : "Vận tốc ban đầu",
"Maximum height " : "Độ cao tối đa",
"Initial velocity " : "Vận tốc ban đầu",
"Angle " : "Góc",
"Maximum height " : "Độ cao tối đa",
"Maximum distance " : "Khoảng cách tối đa",
"Height " : "Chiều cao",
"Initial velocity " : "Vận tốc ban đầu",
"Time to touchdown " : "Thời gian chạm đất",
"Touchdown velocity " : "Vận tốc chạm đất",
"Angle of titled plane " : "Góc mặt phẳng",
"Coefficient of friction " : "Hệ số ma sát",
"Acceleration " : "Gia tốc",
"Mass " : "Khối lượng",
"Mass " : "Khối lượng",
"Distance " : "Khoảng cách",
"Attractive force " : "Lực hấp dẫn",
"Area " : "Diện tích",
"Area " : "Diện tích",
"Force " : "Lực",
"Force" : "Lực",
"Force F₂ (or F₁)" : "Lực F₂ (hoặc F₁)",
"Temperature " : "Nhiệt độ",
"Pressure at 0°C " : "Áp suất ở 0°C",
"Pressure " : "Áp suất",
"Original length " : "Độ dài ban đầu",
"Temperature change " : "Sự thay đổi nhiệt độ",
"Coefficient of linear expansion " : "Hệ số nở dài",
"Change of length " : "Sự thay đổi độ dài",
"Original volume " : "Thể tích ban đầu",
"Temperature change " : "Sự thay đổi nhiệt độ",
"Coefficient of linear expansion " : "Hệ số nở dài",
"Change of volume " : "Sự thay đổi thể tích",
"Temperature " : "Nhiệt độ",
"Sound speed " : "Vận tốc âm thanh",
"Refractive index " : "Chiết suất",
"Refractive index " : "Chiết suất",
"Angle of incidence " : "Góc tới",
"Angle of refraction " : "Góc khúc xạ",
"Angle (r or i) " : "Góc (r hoặc i)",
"Apex angle " : "Góc chiết quang",
"Angle of incident " : "Góc tới",
"Refractive index " : "Chiết suất",
"Angle of emergent ray " : "Góc ló",
"Deviation angle " : "Góc lệch",
"Focal length " : "Tiêu cự",
"Object distance " : "Khoảng cách vật",
"Image distance " : "Khoảng cách ảnh",
"Image (or object) distance" : "Khoảng cách ảnh (vật)",
"Magnification factor " : "Độ phóng đại",
"Speed " : "Tốc độ",
"Proper length " : "Độ dài thực",
"Observed length " : "Độ dài quan sát",
"Rest mass " : "Khối lượng thực",
"Relativistic mass " : "Khối lượng tương đối",
"Proper time interval " : "Thời gian thực",
"Observed time interval " : "Thời gian quan sát",
"Calculate" : "0",
"Or input" : "0",
"Calculation Tools" : "Công Cụ Tính Toán",


	
};